- README.md
Markdown badges
- CircleCI build status
- Licence
- PyPI version
See how it looks [here](https://github.com/mlrun/mlrun/tree/markdown-badges#mlrun)
> Markdown badges - CircleCI, License & PyPI version

- README.md
There were only two instances of "MLrun", both in the README file. The internal code comments already used "MLRun".
> [DOC] Product-name capitalization: "MLrun" > "MLRun"

- mlrun/runtimes/sparkjob.py
@yaronha - This is critcal for spark job performance (cuts it from 2-3 minutes to 30 secs)
> Fix sparkjob driver resources

- docs/api.rst
- docs/index.rst
- docs/mlrun.rst
- mlrun/__init__.py
@yaronha please review.
NOTE: Currently, we have similar intro text on the **General** and **mlrun Package** pages (created from duplicate sources at **docs/api.rst** and **mlrun/__init__.py**). I spoke with Miki about eliminating this duplication. I'll discuss this with you f2f. This PR just slightly edits the text in both places in a similar manner. The output looks like this (this is from the mlrun package page; General has a similar intro):
> [DOC REVIEW] Edit RST doc for the auto-generated readthedocs reference [IG-13721]

- mlrun/funcdoc.py
- tests/test_funcdoc.py
> Ignore underscored functions in find_handlers

- mlrun/api/api/endpoints/artifacts.py
- mlrun/api/api/endpoints/functions.py
- mlrun/api/api/endpoints/runs.py
A typo happened in the big refactor of httpd -> FastAPI (https://github.com/mlrun/mlrun/pull/255)
> Fixing labels query param typo

- mlrun/api/api/endpoints/artifacts.py
- mlrun/api/api/endpoints/functions.py
- mlrun/api/api/endpoints/logs.py
- mlrun/api/api/endpoints/pipelines.py
- mlrun/api/api/endpoints/runs.py
- mlrun/api/api/endpoints/submit.py
- mlrun/api/api/endpoints/tags.py
Running the horovod demo caused to this bug https://github.com/tiangolo/fastapi/issues/1475
Looks like the better way t run sync and async code in a path operation (endpoint) is to define the endpoint as async (`async def`) and use `run_in_threadpool` for the sync code
This is the original error logs (not from the minified example):
```
10.200.0.52:43328 - "POST /api/log/cat-and-dog-servers/794107eb9af243e6b59a3d472705d87e?append=yes HTTP/1.1" 500
[2020-05-08 01:44:42 +0000] [130] [ERROR] Exception in ASGI application
File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 385, in run_asgi
File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_heade …
```
> API - Fix endpoints with mix of sync and async code

- mlrun/__main__.py
- mlrun/api/api/api.py
- mlrun/api/api/endpoints/runtimes.py
- mlrun/builder.py
- mlrun/db/httpdb.py
- mlrun/k8s_utils.py
- mlrun/runtimes/__init__.py
- mlrun/runtimes/base.py
- mlrun/runtimes/constants.py
- mlrun/runtimes/daskjob.py
- mlrun/runtimes/kubejob.py
- mlrun/runtimes/mpijob/__init__.py
- mlrun/runtimes/mpijob/abstract.py
- mlrun/runtimes/mpijob/v1.py
- mlrun/runtimes/mpijob/v1alpha1.py
- mlrun/runtimes/pod.py
- mlrun/runtimes/sparkjob.py
1. Added endpoints:
* `GET /runtimes`
* `GET /runtimes/{kind}`
* `DELETE /runtimes`
* `DELETE /runtimes/{kind}`
2. Added `RuntimeHandler` classes that currently exposes `list_resources` and `delete_resources` methods
3. Changed the mlrun cli `clean` command to use the delete runtime endpoints
4. Added support in the mlrun cli `get` command to the get runtime endpoints
> Adding runtimes handlers

- hack/mlrun-all.yaml
- hack/mlrunapi.yaml
- mlrun/api/db/init_db.py
- mlrun/api/db/session.py
- mlrun/api/singletons.py
- mlrun/config.py
* Changing the default DB to be SQLDB
Hacks in order to enable upgrading iguazio 2.8 systems to latest MLRun without touching helm charts or env vars (only replacing images):
* In order to get filedb the `config.httpdb.db_type` value used to be `filerundb`. 
we change this value to be `filedb` so from now on any value except `filedb` will give you SQLDB (so `filerundb` will give SQLDB)
* if the `config.httpdb.dsn` value is `sqlite:///mlrun.sqlite3?check_same_thread=false` (2.8 default) it will be replaced to `sqlite:////mlrun/db/mlrun.db?check_same_thread=false` so that the db file will be under the fuse mount (so will persist pod restarts)
> Change SQLDB to be the default DB

- mlrun/runtimes/base.py
the `_function_uri` function was prioritizing tags over hash key - should be the opposite
The effect was that when you run a job, the function linked to it was linked by tag instead of by hash, unlike hash key, tag is dynamic, so linking by tag may not let you to re-run a job with the exact version of the function is was created with
> Fix hash vs tag prioritization 

- mlrun/config.py
Change the default logs path from `~/.mlrun/logs` to `/mlrun/db/logs` so logs will persist pod restarts (since the volume mount is on `/mlrun/db`
> Fix default logs path

- examples/mlrun_basics.ipynb
- examples/mlrun_dask.ipynb
- examples/mlrun_jobs.ipynb
- mlrun/run.py
- tests/Dockerfile.test-nb
- tests/integration/Dockerfile.test-nb
- tests/integration/test-notebooks.yml
* minimize env vars required for integration test
* add this code snippet wherever `!` is being used in the notebooks so the cell execution (and as an outcome the test) will fail if the command execution failed
```
if _exit_code != 0:
raise RuntimeError()
```
* change `wait_for_pipeline_completion` default `expected_statuses` to be `[ Succeeded ]` (was empty) and other correctness and docs changes for this function
* use `wait_for_pipeline_completion` in the test notebooks so that test will fail when the pipeline fail (and will succeed only after pipeline finished successfully)
> Improve integration tests

- mlrun/api/api/utils.py
- mlrun/api/main.py
there were 2 bugs:
* line 106 in `utils.py` - `resp.to_yaml()` in case of a schedule job `resp` is a dict which doesn't have the `to_yaml` method so it would fail on it - calling `to_yaml` only when relevant
* If the mlrun api pod got restarted, when it comes up, it tries to reschedule the job (it fails after it insert it to the DB), then it fails (for the same reason) but since it's happening on the startup event it fails the app initalization and the pod gets into crash loop - wrapped the rescheduling with try except so it won't fail the app initialization
> Fix scheduled job submission bug

- mlrun/api/schemas/project.py
The field is currently not really in use so shouldn't be mandatory
> Make project's owner field optional

- mlrun/datastore/azure_blob.py
- mlrun/datastore/datastore.py
- requirements.txt
- tests/integration/azure_blob/test-azure-blob.yml
- tests/integration/azure_blob/test.txt
- tests/integration/azure_blob/test_azure_blob.py
Commit has the code needed and unit tests for new functionality.
Data store URLs should begin with az:// for Azure blob files.
> Added support for Azure blobs as an MLRun data store

- .github/workflows/ci.yaml
We have bots pushing commits to branches, these shouldn't trigger CI
From now on - trigger CI on pull requests to reasonable base branches, and on pushes to master only (before release)
> Be selective on CI run

- mlrun/api/api/utils.py
- mlrun/api/utils/scheduler.py
* use run name to for the schedule name (instead of function name)
* move some logic from `submit` to inside the scheduler
> Scheduler fixes

- mlrun/datastore/datastore.py
- tests/test_datastores.py
When this `parseurl` function was called with `'store://Hedi/mlrun-dbd7ef-training_mymodel#a5dc8e34a46240bb9a07cd9deb3609c7'` (which represent an artifact reference) the second value it returns, called `endpoint` (which is later used as the `project` to query the artifact) was equal to `hedi` instead of `Hedi`
this is because the underlying `urllib.parse.urlparse` is lowering the `hostname` (which is used to the endpoint).
Added logic to preserve the hostname/endpoint case
Other then that:
* ordered imports
* changed some weirdly named variables (`p`)
* added test
> Fix url parsing to preserve case

- mlrun/utils/logger.py
- tests/utils/logger/test_logger.py
The difference between the `log` to the `_log` method is exactly the call to `.isEnabledFor` which verifies whether the log message level is above the log level set for the logger (if not it won't be logged)
> Fixing logger to consider log level correctly

- dockerfiles/mlrun-api/requirements.txt
- mlrun/api/main.py
* Bumping FastAPI version to get this bugfix https://github.com/tiangolo/fastapi/pull/1463 related to enums in docs
* Changing docs endpoints so they will more easily accessible in iguazio system
> API docs fixes

- setup.py
there was a typo in `setup.py` - `extra_requires` instead of `extras_require`
now doing `pip install mlrun[api]` is really working
> Fix extra requirements definition

- mlrun/api/api/endpoints/submit.py
This enrichment is needed so when we "render" the `{{run.user}}` in the output path the right user will be used (otherwise we're using the `V3IO_USERNAME` env var which is actually the username under which the MLRun DB is sitting
> Enrich owner on job submission

- dockerfiles/models-gpu/Dockerfile
Building it raised this:
```
Step 17/27 : RUN conda install -n base -c rapidsai -c nvidia     -c anaconda -c conda-forge -c defaults rapids=0.12
---> Running in a4bee57dd883
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working... 
Building graph of deps:   0%|          | 0/3 [00:00<?, ?it/s]
Examining python=3.8:   0%|          | 0/3 [00:00<?, ?it/s]  
Examining …
```
> Pin models-gpu image python version to 3.7

- mlrun/api/api/endpoints/functions.py
We have a problem that a function saved with `versioned=False` is not query-able using its uid (hash-key)
When running/scheduling a function from the UI it uses the uid to identify a function. 
A function that was deployed but never ran last saved with `versioned=False` so it can't be triggered from the UI, doing this as an intermediate fix - we should make it so any function would be queryable by its uid
> Save versioned function at the end of deploy

- mlrun/api/api/endpoints/functions.py
Continuing https://github.com/mlrun/mlrun/pull/386 - currently the way `deploy` works is that by default (can be changed with the `watch` arg) the client "polls" the `/build/status` endpoint, which also does `store_function` each time, so this actually do the last `store_function` in the `deploy` phase, therefore added logic to `store_function` with `versioned=True` when `state == "ready"`
> Save versioned function at the end of deploy - phase 2

- requirements.txt
cause from 7.17 python 3.6 is not supported and models-gpu-legacy image build fail
> Bound ipython version to less than 7.17

- mlrun/api/api/deps.py
- mlrun/api/api/endpoints/artifacts.py
- mlrun/api/api/endpoints/files.py
- mlrun/api/api/endpoints/functions.py
- mlrun/api/api/endpoints/logs.py
- mlrun/api/api/endpoints/pipelines.py
- mlrun/api/api/endpoints/projects.py
- mlrun/api/api/endpoints/runs.py
- mlrun/api/api/endpoints/submit.py
- mlrun/api/api/endpoints/tags.py
- mlrun/api/api/endpoints/workflows.py
- mlrun/api/api/utils.py
- mlrun/api/crud/logs.py
- tests/api/api/test_artifacts.py
- tests/api/api/test_projects.py
- tests/api/api/test_schedules.py
- tests/api/api/test_submit.py
- tests/api/api/test_tags.py
- tests/conftest.py
- tests/integration/test-notebooks.yml
- Converted all uses of `http.HTTPStatus` to `fastapi.status`
- Converted all boolean url params to be actual booleans instead of strings which then get converted using `strtobool`
> Use FastApi facilities instead of older packages

- mlrun/api/api/endpoints/files.py
- mlrun/datastore/base.py
- mlrun/datastore/v3io.py
- mlrun/errors.py
- tests/test_datastores.py
- Added `errors.py` to mlrun.
- The errors are built in a way that they can be used as HTTP errors with a custom `raise_for_status(response)` function, or just regular errors that aren't HTTP.
Used the errors in:
- When using /files or /filestat, if user is unauthorised to access the files in the v3io container, return a 403 status code
> MLRun Errors + v3io access forbidden uses errors

- mlrun/api/api/deps.py
- mlrun/api/api/endpoints/artifacts.py
- mlrun/api/api/endpoints/files.py
- mlrun/api/api/endpoints/functions.py
- mlrun/api/api/endpoints/pipelines.py
- mlrun/api/api/endpoints/runs.py
- mlrun/api/api/endpoints/runtimes.py
- mlrun/api/api/endpoints/schedules.py
- mlrun/api/api/endpoints/submit.py
- mlrun/api/api/endpoints/tags.py
- mlrun/api/api/utils.py
- mlrun/api/crud/logs.py
- mlrun/errors.py
- mlrun/platforms/iguazio.py
- tests/api/api/test_artifacts.py
- tests/api/api/test_projects.py
- tests/api/api/test_schedules.py
- tests/api/api/test_submit.py
- tests/api/api/test_tags.py
- tests/conftest.py
- tests/platforms/test_iguazio.py
- tests/test_datastores.py
In https://github.com/mlrun/mlrun/pull/375 we moved from `http.HTTPStatus` to `fastapi.status` for 2 reasons:
1. I thought we anyway need FastAPI which have the http status codes enums, so why having a special package - `http` for it (more packages, longer package install time)
2. the http status caused for weird error messages in some cases
After some time I understood that:
1. Apparently http is part of the python standard library - so we saved nothing
2. The wrong usage fix is simple - instead of doing `HTTPStatus.NOT_FOUND` we should do `HTTPStatus.NOT_FOUND.value` which would give only the number (404) itself
3. We need the status codes also in the client side and we don't want to make `fastapi` a requirement of the package
bottomline - changing everything back to `http.HTTPStatus` …
> Replace back fastapi status with http status

- mlrun/api/api/endpoints/files.py
- mlrun/api/db/sqldb/db.py
- mlrun/api/main.py
- mlrun/datastore/v3io.py
- mlrun/db/filedb.py
- mlrun/errors.py
- tests/rundb/test_dbs.py
- tests/test_datastores.py
Changes:
* All the status specific errors inherited from `MLRunDataStoreError` although they might be used in a non data store related context, renamed to `HTTPStatusableError` (I'm open to other name suggestions)
* Added the `BadRequestError` and `InvalidArgumentError` to show that it's ok and possible for 2 errors to match the same status code (but only one of them will be used when doing `raise_for_status()`)
* Added usage of [FastAPI's capability to set a global exception handler](https://fastapi.tiangolo.com/tutorial/handling-errors/#install-custom-exception-handlers) so we handle `HTTPStatusableError` in one place
* Removed the `MLRun` prefix for the error classes names, I don't think we need it since it's `mlrun.errors.BaseError`
> Improving errors infrastructure

- mlrun/runtimes/mpijob/abstract.py
- mlrun/runtimes/pod.py
Added easy performance analysis and tuning capabilities to MLRun's MPIJob runtime.
[**Horovod Autotune**](https://horovod.readthedocs.io/en/latest/autotune_include.html)
```
<mpi-function>.with_autotune(log_file_path: str, warmup_samples: int, steps_per_sample: int, bayes_opt_max_samples: int, 
gaussian_process_noise: float)
```
Adds an Autotuner to help optimize Horovod's Parameters for better performence. The autotuner will collect metrics and tune horovod's parameters while running using Bayesian optimiation. This may affect the performence of the run initially but after arriving to the best parameters should increase performence.
Since autotuning imposes a tradeoff between early performence for better performence later on, It's advised to enable it when both: 
- Training should take a …
> Add performance analysis to hvd

- mlrun/api/db/sqldb/db.py
- tests/api/utils/test_scheduler.py
* Fixed to do `datetime.now(timezone.utc)` instead of `datetime.now()` (also in schedules un-related places)
* apparently [sqlalchemy losing timezone information with sqlite](https://stackoverflow.com/questions/6991457/sqlalchemy-losing-timezone-information-with-sqlite) so added a function to add back the timezone after retrieving records from the DB, currently using it only for schedules
> Fix schedules datetime fields formatting

- setup.py
Bug that failed the release to Pypi, root cause is https://github.com/mlrun/mlrun/pull/413
> Fix version parsing

- mlrun/api/db/sqldb/db.py
- mlrun/kfpops.py
- setup.py
- tests/api/utils/test_scheduler.py
- tests/assets/test_kfp_input_file.txt
- tests/conftest.py
- tests/test_kfp.py
* `fp.write(val)` is raising when val is not string, changed to `fp.write(str(val))`
* The exception there was ignored, added log
* refactored the kfp unit tests
> Fix pipelines non-str results logging

- dockerfiles/mlrun-api/requirements.txt
- mlrun/api/main.py
- tests/api/api/test_runs.py
We had a bug in which one of the runs in the DB was this:
[run-with-nan-float.txt](https://github.com/mlrun/mlrun/files/5120876/run-with-nan-float.txt)
you can note that inside the value of the preview key of one of this run's artifacts there is a Nan.
The default response in FastAPI is JSONResponse which uses `json.dumps` to serialize jsons which would fail with this message:
```
INFO:     10.200.0.20:48732 - "GET /api/run/model-deployment-with-streaming-iguazio/dec577c6f1e74aed9e1911c4b6a8bddc HTTP/1.0" 500 Internal Server Error
ERROR:    Exception in ASGI application
File "/usr/local/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 390, in run_asgi
File …
```
> Change API default response to ORJSONResponse

- mlrun/api/api/endpoints/schedules.py
- mlrun/api/db/base.py
- mlrun/api/db/filedb/db.py
- mlrun/api/db/sqldb/db.py
- mlrun/api/utils/scheduler.py
- mlrun/db/httpdb.py
- tests/api/utils/test_scheduler.py
We filter the name in DB using `query.filter(Schedule.name.ilike(f"%{name}%"))` meaning:
1. using `ilike` - ignoring case
2. wrapping with `%` meaning any schedule that the name is a substring of its name will be matched
> Adding option to give name filter in list_schedules

- dev-requirements.txt
- mlrun/api/api/endpoints/schedules.py
- mlrun/api/db/sqldb/db.py
- mlrun/api/utils/scheduler.py
- mlrun/artifacts/manager.py
- mlrun/db/filedb.py
- mlrun/k8s_utils.py
- mlrun/platforms/iguazio.py
- mlrun/runtimes/base.py
- mlrun/runtimes/function.py
- requirements.txt
- tests/system/demos/base.py
- tests/system/demos/horovod/test_horovod.py
- tests/system/demos/sklearn/test_sklearn.py
- tests/system/examples/dask/test_dask.py
- tests/test_kfp.py
In https://github.com/mlrun/mlrun/pull/423 I changed the code to be formatted according to the new black version - `20.8b1` the problem is that from 20.8 black requires `click>=7.1.2`, and we're pinned to `7.0` because of kfp
so bounded black - `black<=19.10b0` and did the needed formatting
> Pin black requirement

- mlrun/utils/helpers.py
- tests/utils/test_helpers.py
hub function directories have underscores instead of hyphens - so if someone request from us this function `hub://some-function` we should look for it in the `some_function` directory
> Fix hub function url resolution

- dockerfiles/models/Dockerfile
- dockerfiles/models/py36/Dockerfile
Got this error trying to build `models-legacy` image:
```
CMake Error at /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
Could NOT find Tensorflow: Found unsuitable version "1.14.0", but required
is at least "1.15.0" (found
-L/opt/conda/lib/python3.6/site-packages/tensorflow;-l:libtensorflow_framework.so.1)
```
full build log here - 
[models-legacy-build-bug.txt](https://github.com/mlrun/mlrun/files/5180435/models-legacy-build-bug.txt)
It happened since in the new horovod version - [0.20.0](https://github.com/horovod/horovod/releases/tag/v0.20.0) - they support only 1.15 and above (https://github.com/horovod/horovod/pull/2169)
So bumped to use tensorflow 1.15 (instead of 1.14) and changed to install with `pip` instead of `conda` like the regular image
> Fix models legacy image

- infile.txt
- tests/assets/test_run_input_file.txt
- tests/test_remote.py
- tests/test_run.py
This is a file that was used for tests, was replaced with test specific file under a proper path like:
`<repo_root>/tests/assets/test_run_input_file.txt`
> Remove root dir infile.txt

- .github/workflows/build.yaml
- .github/workflows/ci.yaml
- Makefile
- automation/version/version_file.py
- dockerfiles/automation/Dockerfile
- setup.py
https://github.com/mlrun/mlrun/pull/437 introduced a new `version_file.py` script that used to create/update the version file.
This script is being run in the `update-version-file` makefile target, which is a dependency of every step that is building something (images/package).
Running this script requires to python3.7 and the `automation/requirements.txt` to be installed, so:
1. we needed to add several setup tests to the CI in several places
2. If you want to clone the repo and build some image you now can't - you need to do the above setup steps
I thought that although it will add some time (building an image and running it >> running python script) it worth moving this script to be ran dockerized when running it the from the `update-version-file` makefile target
I also fixed some …
> Run update-version-file in docker

- mlrun/artifacts/plots.py
- tests/artifacts/test_artifacts.py
When running the [model_server_tester function](https://github.com/mlrun/functions/tree/master/model_server_tester) we noticed that in the UI the `latency` artifact has no name.
The reason for that was that the artifact (which is `ChartArtifact` instance) had no `db_key` field.
It didn't had the field since `db_key` is not in the class's `_dict_fields` attribute, I noticed that this class's dict fields is simply a subset of the base class's dict fields, so I just removed it (and the class will use the base class dict fields)
> Fix chart artifact to have db key

- README.md
- docs/end-to-end-pipeline.rst
- docs/job-submission-and-tracking.md
- docs/load-from-marketplace.md
- examples/load-project.ipynb
- examples/mlrun_basics.ipynb
- examples/mlrun_dask.ipynb
- examples/mlrun_export_import.ipynb
- examples/mlrun_jobs.ipynb
- examples/mlrun_sparkk8s.ipynb
- mlrun/__init__.py
- mlrun/model.py
- mlrun/run.py
- tests/system/examples/basics/test_basics.py
- tests/system/examples/basics/test_db.py
- tests/system/examples/dask/test_dask.py
- tests/system/examples/jobs/test_jobs.py
- tests/test_dask.py
- tests/test_func_to_mod.py
- tests/test_kfp.py
- tests/test_log_serialization.py
- tests/test_remote.py
- tests/test_run.py
- tests/test_run_local.py
* Created `new_task` with `NewTask` code, and now `NewTask` just show deprecation warning and call `new_task`
* Added todo to remove `NewTask` in 0.7.0
* Added docstring to `new_task`
Note:
Used `FutureWarning` and not `DeprecationWarning` mainly because `DeprecationWarning` is ignored by default while `FutureWarning` is not. also It's more "right" - `FutureWarning` is to notify end users while `DeprecationWarning` is for developers.
docs - https://docs.python.org/3/library/warnings.html
> NewTask -> new_task + added docstring

- dockerfiles/models/Dockerfile
- dockerfiles/models/py36/Dockerfile
When building the models and models legacy images this occured when trying to install horovod:
```
-- Could NOT find Mxnet (missing: Mxnet_LIBRARIES) (Required is at least version "1.4.0")
File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'mxnet'
CMake Error at cmake/Modules/FindMxnet.cmake:59 (string):
string no output variable specified
Call Stack (most recent call first):
horovod/mxnet/CMakeLists.txt:12 (find_package)
```
Full log: 
[models-image-bug.txt](https://github.com/mlrun/mlrun/files/5285917/models-image-bug.txt)
So added installation of `mxnet` in the previous step
> Fix models images

- mlrun/run.py
- mlrun/runtimes/funcdoc.py
- mlrun/runtimes/kubejob.py
- tests/runtimes/test_funcdoc.py
This is purposed to fix a bug in which a user updated function params and saved the function but when using the run job X he saw the old params.
The solution is simple, took code that was duplicated in several places, moved it to a function `update_function_entry_points` and added a call to it in `with_code` function.
`with_code` is sitting in `mlrun/runtimes/kubejob.py` and `update_function_entry_points` would have sit in `mlrun/run.py` which itself import the runtimes module which caused an import cycle.
to solve it I moved `update_function_entry_points` and its helpers to `mlrun/funcdoc.py` and moved it to `mlrun/runtimes/funcdoc.py`.
Also moved the `test_funcdoc.pt` under `tests/runtimes` and added docstring to `with_code`
> Update function entry points when updating code

- mlrun/model.py
In https://github.com/mlrun/mlrun/pull/442 I created `new_task` to be instead `NewTask`.
`NewTask` remained but with a deprecation warning that it will be removed in `0.7.0`, the chosen warning class was `FutureWarning` because `DeprecationWarning` is ignored by default while `FutureWarning` is not.
The problem is that our examples and demos use `NewTask` a lot.
If we'll change all of them to `new_task` it will be problematic since users running MLRun <0.5.3 won't have this `new_task` and they'll have to search for the examples relevant to their release which is very inconvient.
On the other hand keeping them as is means that when running them the deprecation warning will be printed which is also not nice (new user running latest version with latest examples getting deprecation warnings) …
> Changing NewTask deprecation plan

- dockerfiles/mlrun-api/Dockerfile
I want to add a liveness probe which will use `ps` to check the whether the main process is running
`procps` is actually `ps`
> Add Installation of procps in mlrun-api 

- mlrun/api/db/sqldb/db.py
- tests/api/db/test_artifacts.py
Theortically it should be `key` not `name` but since it's already `name` in the APIs leaving it as is
> Adding artifact name filter

- README.md
- docs/job-submission-and-tracking.md
- examples/load-project.ipynb
- examples/mlrun_basics.ipynb
- examples/mlrun_dask.ipynb
- examples/mlrun_export_import.ipynb
- examples/mlrun_jobs.ipynb
- examples/mlrun_sparkk8s.ipynb
- mlrun/model.py
Following https://github.com/mlrun/mlrun/pull/452 changed back examples to use `NewTask` and added TODO to change it to `new_task` in 0.7.0
> new_task -> NewTask in examples

- .github/workflows/build.yaml
- .github/workflows/system-tests.yml
- automation/system_test/prepare.py
Terminology:
* test code - This is the code of the tests themselves, today the CI is running `make test-system` which builds a test image out of the local code - which means the test code is the code from the REF of the action (cloned by `- uses: actions/checkout@v2`)
* tested code - This is the code that being tested, practically this is the MLRun version that is being transplanted to the system, after this PR this version of code changes according to the scenario.
3 scenarios I'm trying to address in this PR:
1. we want to run system tests (one time, not periodically) on some branch in upstream which is not `development`, for example - on `0.5.x` before releasing. 
In this scenario both test and tested code should be from `0.5.x`
2. we want make changes in system tests code (test code, …
> Enable to trigger workflows manually

- mlrun/runtimes/function.py
There was a bug in `add_model` function which caused serving functions to fail.
> Fixed serving model bug

- dockerfiles/models-gpu/py36/Dockerfile
A transient failure started occuring pretty often when trying to build the models gpu legacy image in the step that installs horovod (log attached below).
I couldn't identify what exactly is the root cause, but I did notice that when I add `MAKEFLAGS="-j1"` - which means that there will be no concurrency between make executions it doesn't happen anymore.
It does make some sense that the issue is realted to concurrency since it is transient.
[error_log.txt](https://github.com/mlrun/mlrun/files/5373319/error_log.txt)
> Fix models gpu legacy image

- automation/system_test/prepare.py
The `access_token` GET param is now deprecated in Githubs API, and this causes the CI to fail as it cannot download the latest provctl.
> [System Tests]: Changed access_token param to Authorization header

- automation/system_test/prepare.py
The PR with the mistake: https://github.com/mlrun/mlrun/pull/475
> Fix Typo from #475

- dockerfiles/jupyter/Dockerfile
- docs/quick-start.md
- mlrun/api/api/endpoints/workflows.py
- mlrun/run.py
- tests/api/api/test_workflows.py
> Fixing quick start

- automation/system_test/prepare.py
Filter out unstable provctl releases and only get the latest stable release for using in the system test preparer.
> Fix MLRun System Test CI provctl release query

- requirements.txt
So far the dependency was defined as `boto3>=1.9`, recently boto3 1.16 was released, which requires `botocore >=1.19.0`, which requires `urllib3>=1.25.4,<1.26` which conflicting ours `urllib3>=1.24.2, <1.25`
So added upbound for boto3: `boto3>=1.9, <1.16`
This was causing errors such as: 
`botocore 1.19.2 requires urllib3<1.26,>=1.25.4; python_version != "3.4", but you'll have urllib3 1.24.3 which is incompatible.` when installing MLRun
And also caused this error in our CI:
```
ImportError while loading conftest '/mlrun/tests/conftest.py'.
tests/conftest.py:50: in <module>
from mlrun.api.db.sqldb.db import run_time_fmt  # noqa: E402
mlrun/__init__.py:29: in <module>
from .datastore import DataItem
mlrun/datastore/__init__.py:17: in <module>
from .datastore import StoreManager, …
```
> Fix boto3 dependency

- mlrun/run.py
- tests/runtimes/test_run.py
When doing `mlrun.new_function(runtime=runtime)` if runtime had any `args` defined in its `spec` they were missing in the resulting function object, this PR fixes it
> Fix missing args when instantiating function from runtime

- mlrun/api/api/endpoints/logs.py
In https://github.com/mlrun/mlrun/pull/467 I've changed the header name from `pod_status` to `x-mlrun-run-state`
After this PR API will send both headers so it will backwards compatible with <0.5.3 clients
> Add old pod_status header for BC with <0.5.3 clients

- docs/data-management-and-versioning.md
- docs/job-submission-and-tracking.md
- docs/load-from-marketplace.md
- docs/quick-start.md
Added some documentation of dataset usage
Also some minor fixes to the documentation
> [docs] Adding Dataset usage examples

- mlrun/api/db/sqldb/models.py
- mlrun/api/utils/scheduler.py
- mlrun/runtimes/base.py
- tests/api/conftest.py
- tests/api/utils/function.py
- tests/api/utils/test_scheduler.py
In https://github.com/mlrun/mlrun/pull/467 I changed `submit_run` to be `async def` and forgot to add `await` when calling it in the `submit_run_wrapper` of the scheduler which made the scheduler completely broken (runs nothing) - fixed it, and also:
* Unlike all current tests that use `local_function` schedule kind (created for tests), added a test that run a schedule with the real `job` schedule kind which would have caught this breakage.
* Found that the tests were using `start_time` and `end_time` while it should be `start_date` and `end_date` - fixed that which showed that there is a bug - the standard lib `json` is unable to `dumps` and `loads` datetime, changed to use `orjson`
* minor changes to allow running `local` runtime inside the api context
> Fix scheduler not running anything

- dockerfiles/mlrun-api/requirements.txt
- requirements.txt
https://github.com/mlrun/mlrun/pull/490 changed SQLDB to use orjson - therefore needed in general requirements
> Move orjson to general requirements

- mlrun/api/db/base.py
- mlrun/api/db/filedb/db.py
- mlrun/api/db/sqldb/db.py
- mlrun/db/base.py
- mlrun/db/filedb.py
- mlrun/db/sqldb.py
- tests/api/db/test_functions.py
2 bugs:
* tag filter (only, without name) didn't work - was returning only the first function - simply wasn't handled
* unversioned untagged function was returned in list functions (see test)
> Fix list functions bugs

- mlrun/runtimes/__init__.py
> Fix typo in model server initialization

- mlrun/builder.py
This `tini` looks like some left over from the days we had special docker image for dask, not needed anymore, it currently explodes on this when trying to use built dask function image:
```
Error: failed to start container "base": Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"tini\": executable file not found in $PATH": unknown
```
> Fix dask image build

- mlrun/api/api/endpoints/schedules.py
- mlrun/api/utils/scheduler.py
- mlrun/db/httpdb.py
- tests/api/utils/test_scheduler.py
Adding `POST /projects/{project}/schedules/{name}/invoke` endpoint to enable manually one-time invocation of the schedule scheduled object
> Add invoke schedule endpoint

- mlrun/runtimes/base.py
People see a line like this
```
> 2020-10-29 08:36:12,525 [info] starting run scala_emd_no_sc_stop_pwfs uid=ff2e9b5cce574148a2474b24eb55d9a7 -> http://mlrun-api:8080 
``` 
and thinks the link is to MLRun UI
> [SDK] Make starting run log message more clear

- mlrun/render.py
- mlrun/runtimes/function.py
Couldn't find a nice way to condition the color based on the Jupyter theme so used a color that looks ok on both themes
Before:
After:
> [SDK] Change printed items background colors to support Jupyter dark theme

- mlrun/runtimes/function.py
In Nuclio 1.6.0 default service type will be changed to "ClusterIP" so as a preparation we explictly specify nodeport in the spec
> [Nuclio] Specify nodeport service type explicitly

- .github/workflows/ci.yaml
Split the CI Test jobs to save time
> [CI] Split migrations tests to different job

- mlrun/config.py
- mlrun/utils/helpers.py
do not use nest asyncio by default (required for Storey to run, and the Jupyter issue requiering it was fixed a while ago)
> [SDK] Do not use nest asyncio by default

- mlrun/run.py
- tests/runtimes/test_run.py
Before this fix when giving args without command the first argument was parsed as the command, e.g. 
`args=["--memory-limit", "4GB"]` would become `command="--memory-limit"` and `args="4GB"`
> [SDK] - Fix function initialization with args without command

- mlrun/runtimes/daskjob.py
When you do `function.with_limits(mem="4GB")` on dask function, it will automatically add `--memory-limit 4GB` to the args (in addition to setting the memory limit on the pod)
> [Dask] Pass memory limit to dask worker

- mlrun/runtimes/base.py
- mlrun/runtimes/daskjob.py
- tests/api/runtime_handlers/base.py
- tests/api/runtime_handlers/test_daskjob.py
- tests/api/runtime_handlers/test_kubejob.py
- tests/api/runtime_handlers/test_mpijob.py
- tests/api/runtime_handlers/test_sparkjob.py
minor improvements:
* custom `_delete_resources` gets the list of `deleted_resources` instead of duplicating logic and generate it by itself
* resources that are forced deleted will also pass the pre-deletion actions
> [Cleanup] Adding cleanup tests + minor improvements

- dockerfiles/base/Dockerfile
- dockerfiles/jupyter/Dockerfile
- dockerfiles/mlrun-api/Dockerfile
- dockerfiles/mlrun/Dockerfile
- dockerfiles/models-gpu/Dockerfile
- dockerfiles/models-gpu/py36/Dockerfile
- dockerfiles/models/Dockerfile
- dockerfiles/models/py36/Dockerfile
- dockerfiles/test-system/Dockerfile
- dockerfiles/test/Dockerfile
* add `ENV PIP_NO_CACHE_DIR=1` to all images
* add `rm -rf /var/lib/apt/lists/*` (remove apt-get cache) to mlrun-api (already exists in the rest of the images)
* add `RUN conda clean -ayq` (remove conda cache) to models-legacy (already exists in the rest of the images)
Image | Before | After | percentage
--- | --- | --- | ---
`mlrun/mlrun` | `1.61GB` | `1.47GB` | 8.7%
`mlrun/mlrun-api` | `1.16GB` | `996MB` | 14.1%
`mlrun/jupyter` | `3.61GB` | `3.61GB` | 0%
`mlrun/ml-base` | `2.3GB` | `1.9GB` | 17.4%
`mlrun/ml-base` (`-py36` tag) | `2.3GB` | `1.89GB` | 17.8%
`mlrun/ml-models` | `7.91GB` | `7GB` | 11.5%
`mlrun/ml-models` (`-py36` tag) | `7.98GB` | `7.3GB` | 8.5%
`mlrun/ml-models-gpu` | `23.5GB` | `22.8GB` | 3%
`mlrun/ml-models-gpu` (`-py36` tag) | `21.2GB` | `20.6GB` | 2.8%
> [Build] Optimize images size by removing redundant caches

- tests/system/demos/horovod/test_horovod.py
The test fails cause the mpi worker getting OOM killed, skipping for now
we need to cut the train data size
> [Tests] Skip horovod demo system test

- mlrun/api/db/base.py
- mlrun/api/db/filedb/db.py
- mlrun/api/db/sqldb/db.py
- mlrun/api/db/sqldb/models.py
- mlrun/api/migrations/tests/test_migrations.py
- mlrun/api/migrations/versions/1c954f8cb32d_schedule_last_run_uri.py
- mlrun/api/schemas/schedule.py
- mlrun/api/utils/scheduler.py
- mlrun/db/httpdb.py
- mlrun/model.py
- tests/api/utils/test_scheduler.py
Added a text field in Schedule called `last_run_uri` which contains a uri representing the last run of that schedule.
The uri is built as such:
`<project>@<run_uid>#<iteration>[:<tag>]`
For example:
1. For `project = 'default'; run_uid = '1234abcd'; iteration = 2; tag = None` :
The uri is `default@1234abcd#2`
2. For `project = 'myproj'; run_uid = '9876zyxw'; iteration = 5; tag = 'mytag'` :
The uri is `myproj@9876zyxw#5:mytag `
> [Scheduling] Populate last run uri in schedule

- mlrun/api/api/endpoints/schedules.py
- mlrun/api/schemas/schedule.py
- mlrun/api/utils/scheduler.py
- mlrun/db/httpdb.py
- tests/api/utils/test_scheduler.py
Include last run dict in output schema for get and list schedules, if `include_last_run` flag is used
> [Scheduling] Include last run on get and list

- mlrun/api/api/deps.py
- mlrun/api/api/endpoints/feature_sets.py
- mlrun/api/db/base.py
- mlrun/api/db/filedb/db.py
- mlrun/api/db/sqldb/db.py
- mlrun/api/db/sqldb/models.py
- mlrun/api/migrations/versions/863114f0c659_refactoring_feature_set.py
- mlrun/api/schemas/__init__.py
- mlrun/api/schemas/feature_store.py
- mlrun/api/schemas/object.py
- mlrun/db/base.py
- mlrun/db/filedb.py
- mlrun/db/httpdb.py
- mlrun/db/sqldb.py
- mlrun/errors.py
- mlrun/utils/helpers.py
- requirements.txt
- tests/api/api/test_feature_sets.py
- tests/api/db/test_feature_sets.py
- tests/api/db/test_projects.py
- tests/rundb/test_httpdb.py
Changing the feature-set API to support the following:
- Schema validation on a (small) subset of fields, allow any other field to be added to the objects, such as FeatureSet
- Added fields will be stored in DB and retrieved on get/list queries. Queries can still use a filter on schema'd fields
- APIs are:
* POST - (add_feature_set) - create a new feature-set. If exists, fail.
* PUT - (store_feature_set) - update or create a feature-set. Can be called multiple times on the same object, even if it has the same UID
* PATCH (updade_feature_set) - apply a set of changes to an existing feature-set, using partial object structure. Supports replace mode (default) that will replace container contents on change, and additive mode which will add entries to containers (for example, add a feature to …
> [Feature store] Feature set api refactoring

- mlrun/render.py
the link in run widget was broken, needed to add /monitor after /jobs
> [SDK] Fix hyperlink to UI (to include /monitor)

- mlrun/runtimes/function.py
- mlrun/runtimes/kubejob.py
There were several execution branches in which deployment was successful but function wasn't saved to DB
> [SDK] Save function on deploy success

- mlrun/config.py
- mlrun/runtimes/sparkjob.py
Spark image tag has it's own config value `spark_app_image_tag`, no need to default it to the `igz_version`
> [Spark] Don't use igz version for spark image tag

- mlrun/runtimes/base.py
- mlrun/runtimes/daskjob.py
- mlrun/runtimes/function.py
- mlrun/runtimes/mpijob/v1.py
- mlrun/runtimes/mpijob/v1alpha1.py
- mlrun/runtimes/pod.py
- mlrun/runtimes/sparkjob.py
If the the API's svc name was not `mlrun-api` or it wasn't deployed in the `default-tenant` namespace, things gone wrong, this fixes it
> [Runtimes] Support running with non default API name and namespace

- dockerfiles/mlrun/Dockerfile
- dockerfiles/test-system/Dockerfile
This shrinks the `mlrun/mlrun` image size from 1.49GB to 721MB (~51% decrease)
> [Build] Use python's -slim tag for mlrun/mlrun image

- dockerfiles/mlrun/Dockerfile
- dockerfiles/test-system/Dockerfile
https://github.com/mlrun/mlrun/pull/555 caused:
```
File "/usr/local/bin/mlrun", line 5, in <module>
from mlrun.__main__ import main
File "/usr/local/lib/python3.7/site-packages/mlrun/__init__.py", line 34, in <module>
from .projects import load_project, new_project
File "/usr/local/lib/python3.7/site-packages/mlrun/projects/__init__.py", line 18, in <module>
from .project import load_project, new_project, MlrunProject
File "/usr/local/lib/python3.7/site-packages/mlrun/projects/project.py", line 23, in <module>
from git import Repo
File "/usr/local/lib/python3.7/site-packages/git/__init__.py", line 85, in <module>
raise ImportError('Failed to initialize: {0}'.format(exc)) from exc
ImportError: Failed to initialize: Bad git executable.
The git executable …
```
> [Build] Add git to mlrun/mlrun image

- dockerfiles/mlrun/Dockerfile
- dockerfiles/test-system/Dockerfile
This increases the image size from 808MB to 922MB
Without it building the system test image failed cause it's needed for building `psutil` which is a requirement of `dask-kubernetes` (which is our requirement), added to the `mlrun/mlrun` image although it's not a must currently, this was the error:
```
Running setup.py install for psutil: started
Running setup.py install for psutil: finished with status 'error'
ERROR: Command errored out with exit status 1:
command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-xgvud5xo/psutil/setup.py'"'"'; __file__='"'"'/tmp/pip-install-xgvud5xo/psutil/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, …
```
> [Build] Add gcc to slim images

- mlrun/api/api/endpoints/schedules.py
- mlrun/api/schemas/schedule.py
- mlrun/api/utils/scheduler.py
- tests/api/api/test_schedules.py
- tests/api/utils/test_scheduler.py
- Schedules Labels and Kind got mixed up in one of the function calls
- Made schedules labels as dict in API(input and output)
- Addressed a situation when the schedule exists but no job exists
- Added Labels filter test in api tests
> [Schedules] Fix labels bugs

- mlrun/api/utils/projects/leader.py
- mlrun/utils/helpers.py
- mlrun/utils/regex.py
- tests/api/api/test_utils.py
- tests/api/conftest.py
- tests/api/db/test_feature_sets.py
- tests/api/db/test_projects.py
- tests/api/runtime_handlers/base.py
- tests/api/utils/projects/test_leader_member.py
This ensures that a project name conforms the k8s name regex (which is dns subdomain)
Upgrade concerns - 2 options:
* MLRun will have already existing project names that does not conforms to the regex - the validation happens only on creation, so existing projects are uneffected.
* MLRun will sync projects with invalid names from Nuclio - can't happen, Nuclio projects names pass the same validation
> [Projects] Ensure project name regex

- mlrun/api/db/sqldb/db.py
- tests/api/db/test_projects.py
upgrading to `unstable` which has https://github.com/mlrun/mlrun/pull/542 in it with a DB that had projects resulted in failure to list projects since we were not supporting the old record format, this PR add support for it (+test), this was the failure:
```
> 2020-12-03 10:29:27,564 [debug] Initialized leader and followers: {'leader': 'mlrun', 'followers': []}
ERROR:    Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 526, in lifespan
async for item in self.lifespan_context(app):
File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 467, in default_lifespan
await self.startup()
File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 502, in startup
await handler()
File …
```
> [Projects] - Support old project records

- dockerfiles/mlrun-api/requirements.txt
- requirements.txt
From system tests:
```
Run python automation/system_test/prepare.py run \
Warning: -06 21:12:50,405 [warning] Failed resolving version info. Ignoring and using defaults
File "automation/system_test/prepare.py", line 11, in <module>
import mlrun.utils
File "/home/runner/work/mlrun/mlrun/mlrun/__init__.py", line 30, in <module>
from .db import get_run_db
File "/home/runner/work/mlrun/mlrun/mlrun/db/__init__.py", line 21, in <module>
from .sqldb import SQLDB
File "/home/runner/work/mlrun/mlrun/mlrun/db/sqldb.py", line 19, in <module>
from mlrun.api.db.sqldb.db import SQLDB as SQLAPIDB
File "/home/runner/work/mlrun/mlrun/mlrun/api/db/sqldb/db.py", line 37, in <module>
from mlrun.api.utils.singletons.project_member import get_project_member
File …
```
> [SDK] Move humanfriendly to SDK requirements

- dockerfiles/test-system/Dockerfile
- dockerfiles/test-system/requirements.txt
```
==================================== ERRORS ====================================
_______________ ERROR collecting examples/basics/test_basics.py ________________
ImportError while importing test module '/tests/system/examples/basics/test_basics.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
usr/local/lib/python3.7/importlib/__init__.py:127: in import_module
return _bootstrap._gcd_import(name[level:], package, level)
tests/system/examples/basics/test_basics.py:3: in <module>
import matplotlib.pyplot as plt
E   ModuleNotFoundError: No module named 'matplotlib'
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
```
> [System tests] Add matplotlib as requirement

- mlrun/runtimes/daskjob.py
In https://github.com/mlrun/mlrun/pull/568 I changed `dask-kubernetes` from `==0.10.0` to `~=0.11.0` which apparently broke dask, from `0.10.0` to `0.10.1` they did this (non BC 🤦 ) change - renaming `scheduler_timeout` to `idle_timeout` - https://github.com/dask/dask-kubernetes/commit/ccc3e3808f836c16a57d9a5b224bd87e8d01f348
> [Dask] Fix KubeCluster initialization

- mlrun/api/utils/projects/leader.py
- tests/api/utils/projects/test_leader_member.py
* Added the name validation also on store project (which creates when doesn't exist)
* Added logic to skip syncing project with wrong names, since this will fail anyway and just spam the logs. these projects with wrong names can't be created now, but can come from old DBs
> [Projects] Skip old invalid project syncing + name validation fix

- .github/workflows/system-tests.yml
We need to be able to use one system tests system for 0.5.x and one for development (0.6.x)
> [CI] Enable using several system tests systems

- docs/mlrun-kit.md
- mlrun/config.py
- mlrun/runtimes/base.py
- mlrun/runtimes/daskjob.py
- mlrun/runtimes/function.py
- mlrun/runtimes/pod.py
- mlrun/runtimes/sparkjob.py
before https://github.com/mlrun/mlrun/pull/550 jobs was able to "talk" with the mlrun API only if its svc name was `mlrun-api`, that PR was purposed to solve this by passing the configured DBPATH from the client to the `function.spec.rundb` attribute which will then be set as an env (`MLRUN_DBPATH`) on the job pod itself. While that worked for some of the cases, it caused a new bug:
sometimes the dbpath (api link) configured in the client side is something like https://mlrun-api.default-tenant.app.hedingber-30-1.iguazio-cd2.com which is the API's ingress URL, in order to "talk" through that ingress credentials are needed, and therefore jobs configured with this as their dbpath failed communicating with the API.
This PR revert some of the stuff from the previous PR, and this time tackle it …
> [Runtimes] Set jobs dbpath from configuration instead of client

- .github/workflows/system-tests.yml
One of the secrets last character was & which caused 
`/home/runner/work/_temp/216b8f8e-40b9-4c58-a516-cde15f5363a8.sh: line 12: --override-image-registry: command not found`
> [System tests] Wrap secrets with quotes

- mlrun/api/migrations/env.py
- mlrun/api/utils/alembic.py
- tests/api/utils/test_alembic_util.py
When initializing the database:
- On db initialization a backup of the DB is made before the upgrade to the latest schema revision, with its previous alembic revision as its name (Any new backup overrides the old backup if it is the same revision)
- If the current DB revision doesn't exist in the known revision history, this means the DB is too new for the code, and we will try to fall back to the backup of the latest know revision.
- If no such backup exists - raise a RuntimeError and fail initializing the DB.
In addition - completely unit-tested the AlembicUtil
> [DB migrations] Added downgrade support and AlembicUtil Tests

- dockerfiles/jupyter/Dockerfile
- hack/local/README.md
- hack/local/mlrun-local.yaml
- hack/mlrun-all.yaml
- hack/mlrunapi.yaml
- mlrun/api/api/endpoints/healthz.py
- mlrun/builder.py
- mlrun/config.py
- mlrun/db/httpdb.py
- mlrun/kfpops.py
- mlrun/runtimes/base.py
- mlrun/runtimes/kubejob.py
- mlrun/runtimes/utils.py
- mlrun/utils/helpers.py
- tests/test_config.py
- tests/utils/test_helpers.py
* Move builder configuration to use the main `config.py` instead of reading from env var directly, this caused a change with the env vars naming: `DEFAULT_DOCKER_REGISTRY` -> `MLRUN_HTTPDB__BUILDER__DOCKER_REGISTRY`, `DEFAULT_DOCKER_SECRET` -> `MLRUN_HTTPDB__BUILDER__DOCKER_REGISTRY_SECRET `
* Added support to giving the docker repository inside the registry config value, which will override the default repository (mlrun)
* Added logic in config so that when dbpath is being set we connect to the db (API) which will sync config from it
* Bump kaniko tag - I had a bug similar https://github.com/GoogleContainerTools/kaniko/issues/245 and upgrade solved it
* related docs fixes
* Reordered the jupyter dockerfile to improve caching
> [Builder] Change registry URL configurations

- .github/workflows/system-tests.yml
- automation/system_test/prepare.py
- examples/mlrun_jobs.ipynb
- mlrun/api/api/endpoints/functions.py
- mlrun/builder.py
- mlrun/config.py
- mlrun/db/httpdb.py
- mlrun/runtimes/kubejob.py
- tests/system/examples/jobs/test_jobs.py
So far when `with_mlrun` was true (the default) the builder added `pip install mlrun` command to the dockerfile, but that would install the latest mlrun, which is not surely the mlrun we want.
Add logic in the builder which resolves the version specifier in this precedence:
1. version given from the client
2. default specifier configured on the server
3. `git+https://github.com/mlrun/mlrun@development` if the version is `unstable` else `mlrun==<version>`
Fixed the system tests to use that new option and pass the tested version to be used by the builder
> [Builder] Install specific mlrun version

- automation/system_test/prepare.py
- mlrun/api/api/api.py
- mlrun/api/api/endpoints/background_tasks.py
- mlrun/api/api/endpoints/functions.py
- mlrun/api/schemas/__init__.py
- mlrun/api/schemas/background_task.py
- mlrun/api/schemas/object.py
- mlrun/api/utils/background_tasks.py
- mlrun/db/httpdb.py
- mlrun/runtimes/daskjob.py
- tests/api/api/test_background_tasks.py
I saw several failures recently running our [dask example notebook](https://github.com/mlrun/mlrun/blob/development/examples/mlrun_dask.ipynb)
The image used for the dask cluster is `mlrun/ml-models` which is a pretty big image.
Before this PR the start cluster endpoint was waiting for the cluster to actually come up, which could take long time since just pulling the image can take several minutes, and in Iguazio system the ingress timeout is 2 minutes.
Added a new resource `BackgroundTask` that the endpoint will return, then the client query the background tasks endpoint to determine when the task is finished
Unrelated:
* fix in system tests prepare
* fix feature sets router tag
> [Dask] Change start cluster endpoint to be async 

- mlrun/runtimes/base.py
- tests/api/runtime_handlers/base.py
In https://github.com/mlrun/mlrun/pull/568 I bumped the `kubernetes` package version from `==10.0.0` to `~=11.0` and didn't notice that [version 11.0.0](https://github.com/kubernetes-client/python/blob/release-11.0/CHANGELOG.md#v1100) had this change https://github.com/kubernetes-client/gen/pull/142 which caused our `delete_namespaced_custom_object` to fail with:
```
> 2020-12-15 01:01:32,319 [warning] Cleanup failed processing CRD object train-7f9ca89e: Traceback (most recent call last):
File "/mlrun/mlrun/runtimes/base.py", line 1144, in _delete_crd_resources
namespace, crd_group, crd_version, crd_plural, crd_object
File "/mlrun/mlrun/runtimes/base.py", line 1400, in _delete_crd
client.V1DeleteOptions(),
TypeError: delete_namespaced_custom_object() takes 6 positional arguments but 7 …
```
> [Cleanup] Fix crd objects cleanup

- automation/system_test/prepare.py
Our CI that builds image tag the images with `<latest-version>-<commit-hash>`
the `<latest-version>` is resolved by `curl -sf https://pypi.org/pypi/mlrun/json | jq -r '.info.version'` which (as of writing this) outputs `0.5.4`.
It means that currently our system tests running on development are patching the system to versions like `0.5.4-daafbed` the problem with this is that since this 0.5.x it makes provctl patch picking 0.4.x chart, while [this PR](https://github.com/mlrun/mlrun/pull/582) that will be only in 0.6.x requires this [chart PR](https://github.com/v3io/helm-charts/pull/532) that will only in 0.5.x charts. 
Bottomline provctl patch gives the wrong chart which is causing these failures in the `TestJobs` suite:
```
E               mlrun.db.base.RunDBError: POST …
```
> [System tests] Skip chart patching in provctl patch

- mlrun/api/api/endpoints/feature_sets.py
- mlrun/api/db/base.py
- mlrun/api/db/filedb/db.py
- mlrun/api/db/sqldb/db.py
- mlrun/api/schemas/__init__.py
- mlrun/api/schemas/feature_store.py
- mlrun/db/base.py
- mlrun/db/filedb.py
- mlrun/db/httpdb.py
- mlrun/db/sqldb.py
- tests/api/api/feature_store/base.py
- tests/api/api/feature_store/test_feature_sets.py
- tests/rundb/test_httpdb.py
Added a REST API that allows to list feature-set entities. This is needed for the UI. API is very similar to the list-features API, except there's no filter on entities (obviously).
> [Feature store] Added list entities endpoint

- .github/workflows/system-tests.yml
- automation/requirements.txt
- dockerfiles/mlrun-api/requirements.txt
- dockerfiles/test/Dockerfile
* Saw this error in the system tests:
`error: chardet 4.0.0 is installed but chardet<4.0,>=2.0 is required by {'aiohttp'}`
and [reading this](https://stackoverflow.com/questions/19048732/python-setup-py-develop-vs-install) I understand this is happening because we `python setup.py develop` which is discouraged, changed to `pip install -e .`
* noticed that in the automation requirements we're still `click==7.0` which was pinned because of kfp, already bumped kfp in https://github.com/mlrun/mlrun/pull/568 so was able to change it to `click~=7.0`
* Found a conflict with new distributed version see detailed explanation in comment
> [Requirements] Fix conflicts

- mlrun/api/api/endpoints/projects.py
- mlrun/api/db/base.py
- mlrun/api/db/filedb/db.py
- mlrun/api/db/sqldb/db.py
- mlrun/api/schemas/__init__.py
- mlrun/api/schemas/object.py
- mlrun/api/schemas/project.py
- mlrun/api/utils/clients/nuclio.py
- mlrun/api/utils/projects/leader.py
- mlrun/api/utils/projects/member.py
- mlrun/api/utils/projects/remotes/member.py
- mlrun/api/utils/projects/remotes/nop.py
- mlrun/db/__init__.py
- mlrun/db/base.py
- mlrun/db/filedb.py
- mlrun/db/httpdb.py
- mlrun/db/sqldb.py
- mlrun/projects/project.py
- tests/api/api/test_projects.py
- tests/api/db/test_projects.py
- tests/api/utils/clients/test_nuclio.py
- tests/api/utils/projects/test_leader_member.py
- tests/projects/test_project.py
- tests/projects/workflow.py
- tests/rundb/test_httpdb.py
- tests/rundb/test_sqldb.py
- tests/rundb/workflow.py
* So far the SDK class was completely disconnected from the API, (confusingly) even doing `.save()` would cause the project to be saved to a file, there was no useful way to actually back up the projects to the DB. (Note the projects were getting created in the DB when you created a resource of a project (function,run,artifact etc..) but it was only the name without all the project data) - This PR changed that, from now on `.save()` would save to the DB (in addition to saving to file) + all of the API methods (httpdb) are accepting and returning `MlrunProject` instances, so you can get a project from the db by doing:
```
from mlrun import get_run_db
get_run_db().get_project(<name>)
```
* Since https://github.com/mlrun/mlrun/pull/542 anyways does non-backwards compatible changes to the …
> [Projects] Sync SDK class with API methods + structure change

- .github/workflows/system-tests.yml
*Saw this error in the system tests:
error: chardet 4.0.0 is installed but chardet<4.0,>=2.0 is required by {'aiohttp'}
and reading this I understand this is happening because we `python setup.py develop` which is discouraged, changed to `pip install --editable .`
> [Requirements] Fix conflicts [0.5.x Backport]

- .github/workflows/build.yaml
- .github/workflows/system-tests.yml
+ configure the build workflow (build images) to automatically run on push to branch with name matching this regex: `[0-9]+.[0-9]+.x` (so it will run on `0.5.x`)
> [System tests] Enable to take UI from action branch name in mlrun/ui

- README.md
- docs/examples.md
- docs/index.rst
- mlrun/serving/README.md
Our convention is to spell "life cycle" as two words (or hyphenated — "life-cycle" — when the phrase modifies subsequent text).
@gilad-shaham FYI. @zilbermanor please merge.
> [DOC REVIEW] "lifecycle" > "life cycle"

- README.md
- docs/job-submission-and-tracking.md
- mlrun/__init__.py
- mlrun/__main__.py
- mlrun/config.py
- mlrun/datastore/datastore.py
- mlrun/db/__init__.py
- mlrun/execution.py
- mlrun/model.py
- mlrun/projects/project.py
- mlrun/run.py
- mlrun/runtimes/base.py
- mlrun/runtimes/sparkjob.py
- mlrun/runtimes/utils.py
- tests/api/conftest.py
- tests/rundb/test_rundb.py
- tests/test_run.py
* remove the need to use connect() and cache the db object
> [SDK] Cache run db instance

- mlrun/api/api/endpoints/projects.py
- mlrun/api/db/base.py
- mlrun/api/db/filedb/db.py
- mlrun/api/db/sqldb/db.py
- mlrun/api/schemas/__init__.py
- mlrun/api/schemas/constants.py
- mlrun/api/utils/clients/nuclio.py
- mlrun/api/utils/projects/leader.py
- mlrun/api/utils/projects/member.py
- mlrun/api/utils/projects/remotes/member.py
- mlrun/api/utils/projects/remotes/nop.py
- mlrun/db/base.py
- mlrun/db/filedb.py
- mlrun/db/httpdb.py
- mlrun/db/sqldb.py
- mlrun/errors.py
- tests/api/api/test_projects.py
- tests/api/db/test_projects.py
- tests/api/utils/clients/test_nuclio.py
Following [Nuclio's PR](https://github.com/nuclio/nuclio/pull/1996), added support in deletion strategies for project deletion:
* `restrict` - will return 412 when project exists and has related resources (won't check related resources if project doesn't exist, will succeed)
* `cascade` - will remove all related resources with the project
strategy is given using the header `x-mlrun-deletion-strategy`
> [Projects] Support different deletion strategies

- .github/workflows/ci.yaml
- Makefile
- automation/package_test/test_imports.sh
- automation/system_test/prepare.py
- dockerfiles/base/Dockerfile
- dockerfiles/jupyter/Dockerfile
- dockerfiles/mlrun-api/Dockerfile
- dockerfiles/mlrun/Dockerfile
- dockerfiles/models-gpu/Dockerfile
- dockerfiles/models-gpu/py36/Dockerfile
- dockerfiles/models/Dockerfile
- dockerfiles/models/py36/Dockerfile
- dockerfiles/test-system/Dockerfile
- dockerfiles/test/Dockerfile
- mlrun/builder.py
- mlrun/datastore/datastore.py
- mlrun/errors.py
- mlrun/runtimes/daskjob.py
- requirements.txt
- setup.py
- tests/Dockerfile.test-nb
Fixes https://github.com/mlrun/mlrun/issues/551
This PR leverages setuptools' `extras_require` to enable a user to install only the dependencies they really need. This will give:
* Faster installation
* Less conflicts with local venv
* Don't install un-needed dependencies
The extras we will support are:
* `api` - already existed - needed dependencies to run the API
* `s3` - `boto3~=1.9` - needed dependencies to use s3 as the storage layer
* `azure-blob-storage` - `azure-storage-blob~=12.0` - needed dependencies to use azure blob storage as the storage layer
* `complete` - all of the above excluding `api`
* `complete-api` - all of the above including `api`
For examples on how to install package with extras using `pip` [see this](https://pip.pypa.io/en/latest/reference/pip_install/#examples) …
> [Requirements] Support extras

- dockerfiles/jupyter/requirements.txt
- dockerfiles/mlrun/requirements.txt
The `mlutils` module is used as a "helpers module" for our functions in the [function hub](https://github.com/mlrun/functions)
This module requires several dependencies that are not part of the package dependencies but we still want to be able to use it on the `mlrun/mlrun` image (otherwise it will require using the `mlrun/ml-models` image which is very big)
So aligned the `mlrun/mlrun` requirements to settle `mlutils` requirements
Also aligned `mlrun/jupyter` requirements
> [Images] Ensuring mlrun/mlrun and mlrun/jupyter has mlutils dependencies

- dockerfiles/models-gpu/Dockerfile
- dockerfiles/models-gpu/py36/Dockerfile
From horovod v0.19 to v0.20 the docs changed from suggesting to add `HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_GPU_BROADCAST=NCCL` to suggesting to add `HOROVOD_GPU_OPERATIONS=NCCL`
> [GPU Images] Fix horovod NCCL env var

- dev-requirements.txt
- dockerfiles/test/Dockerfile
- mlrun/runtimes/serving.py
- mlrun/serving/server.py
- mlrun/serving/states.py
- mlrun/serving/v2_serving.py
- mlrun/utils/helpers.py
- requirements.txt
- tests/serving/demo_states.py
- tests/serving/test_async_flow.py
- tests/serving/test_flow.py
- tests/serving/test_serving.py
* add support for flows/DAG in serving runtime
* enhance the graph, support streams, multi-function, ..
* work with Storey as async runtime engine
> [Serving] Add flow topology support

- .github/workflows/ci.yaml
- Makefile
- dev-requirements.txt
- dockerfiles/base/Dockerfile
- dockerfiles/jupyter/Dockerfile
- dockerfiles/mlrun-api/Dockerfile
- dockerfiles/mlrun/Dockerfile
- dockerfiles/models-gpu/Dockerfile
- dockerfiles/models-gpu/py36/Dockerfile
- dockerfiles/models/Dockerfile
- dockerfiles/models/py36/Dockerfile
- dockerfiles/test-system/Dockerfile
- dockerfiles/test/Dockerfile
* Storey added `s3fs` to their requirement in https://github.com/mlrun/storey/pull/124, and `s3fs` is compatible only on python 3.7 and above, so not installing storey on python 3.6
* (I think this is also because of some sub-dependancy of storey) pip installing start taking ages (I stopped waiting after an hour) I saw this one https://github.com/pypa/pip/issues/9215 and decided that for now we'll go back to use the legacy resolver.
Ideally I could keep using latest pip and just add `--use-deprecated=legacy-resolver` but they are planning to deprecate it in `21.0` (could work around by pinning pip to `~=20.3.0`) + since we're doing installation as part of our business logic (people using MLRun to build images with custom packages for them) I feel like this new resolver is still no stable …
> [Images] Pin pip version and use legacy resolver + install storey package only on python 3.7 or above

- dockerfiles/jupyter/Dockerfile
- dockerfiles/mlrun-api/requirements.txt
- requirements.txt
* Jupyter is running the api inside so need complete-api flavor
* Distributed moved to SDK requirements (needed to run Dask, it was a breakage from before, the change that revealed it is installing the SDK requirements in the system tests and not the API requirements)
> [Requirements] Extras addition followup fixes

- mlrun/api/api/endpoints/runtimes.py
- mlrun/api/crud/__init__.py
- mlrun/api/crud/logs.py
- mlrun/api/crud/pipelines.py
- mlrun/api/crud/projects.py
- mlrun/api/crud/runtimes.py
- mlrun/api/utils/clients/nuclio.py
- mlrun/api/utils/projects/leader.py
- mlrun/runtimes/base.py
- tests/api/api/test_projects.py
Fixes IG-17647
A project deletion wasn't removing the runtime resources of the jobs (a bug)
That caused to the next cycle of jobs monitoring to find out that a Run doesn't exist for the job, and therefore to create one, that caused ensured project to be called, and that caused to project to be re-created after it deleted already
> [Projects] Remove runtime resources on project deletion

- mlrun/api/db/sqldb/db.py
- tests/api/db/test_artifacts.py
- tests/rundb/test_sqldb.py
There was a problem in the tagging logic that caused each `store_artifact` call to create a new Tag record, therefore when trying to get a specific artifact's `latest` version, `one_or_none` would explode.
Fixed that - in a followup PR will add logic that will fix DBs with duplicated tags
> [Artifacts] Fix artifacts tagging

- dockerfiles/base/requirements.txt
- dockerfiles/models-gpu/requirements.txt
- dockerfiles/models/requirements.txt
- requirements.txt
Copying comment from requirements.txt:
```
>=2.5.2, <3 in the client resolves to 2.30.1, and mlrun/ml-models comes pre-installed with 2.11.0 which
```
> [Dask] Set distributed min bound to 2.23.0

- docs/quick-start.ipynb
- mlrun/__init__.py
return project_name, artifact_path in set_environment, this is in order to simplify the use of user projects
> [SDK] Return project name in set_environment

- README.md
- docs/general.md
- docs/index.rst
Changes include a doc review for recent MLRun-overview product edits in PR #645 (Gilad) and integrate product doc edits in the MLRun getting-started tutorial demo (Adi) with my doc-review edits.
@gilad-shaham @gaydailan please approve. You can see the modified README on the PR branch: https://github.com/Sharon-iguazio/mlrun/blob/doc-readme-edits/README.md
This PR also includes the typo fix in PR #666. => If this PR is merged before PR #666, the latter can be canceled. => UPDATE: PR #666 has now been merged to `development`.
> [Doc] MLRun overview & basic-components doc edits

- .github/workflows/release.yaml
- Makefile
**What do we want to do ?**
we basically want that this CI will use the `MLRUN_VERSION` it got (representing some git tag), take all of its contents, and put them "as is" in the relevant release branch, as one commit.
What I've done before this PR is:
`git checkout $(MLRUN_TAG) .` - the problem with it was that it was only adding changes and file additions, but don't do file deletions
I've tried going to the `git merge` direction, I ended up with:
```
git replace --graft $(MLRUN_VERSION) HEAD; \
git merge $(MLRUN_VERSION) --allow-unrelated-histories --squash -X theirs; \
git replace --delete $(MLRUN_VERSION); \
```
* `--allow-unrelated-histories` - we're basically trying to merge from the release tag, which its history is like the dev branch history, to the release branch, which its …
> [CI] Fixing release branch automation to include file deletions

- mlrun/serving/server.py
fix exception handling in serving (nuclio context was missing the verbose attribute)
> [Serving] Fix exception handling

- dockerfiles/models/Dockerfile
`mlrun/ml-models` started failed building in the horovod installation step, I noticed that it started when `intel-tensorflow` 2.4.0 released, so pinned it back to 2.3.0. attaching the failure log:
[intel-tensorflow.log](https://github.com/mlrun/mlrun/files/5900490/intel-tensorflow.log)
> [Models image] Pinning intel-tensorflow to 2.3.0

- mlrun/runtimes/serving.py
The serving function was overriding the `_get_runtime_env` method but wasn't calling the super (and extending its value) that caused the `MLRUN_DBPATH` to not be configured on the serving pod, which caused the pod to not being able to communicate with the API in cases where it's not named `mlrun-api` (covered by the sane default)
> [Serving] Add base runtime env

- dockerfiles/base/requirements.txt
- dockerfiles/models/requirements.txt
- requirements.txt
- tests/artifacts/test_dataset.py
When we upload a dataset we turn it into a file, be default we use the parquet format, we recently started hitting this error:
```
> 2021-02-02 22:14:14,111 [error] Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/mlrun/runtimes/local.py", line 217, in exec_from_params
val = handler(*args_list)
File "main.py", line 15, in vwvtwewczd
context.log_dataset('mydf', df=df)
File "/usr/local/lib/python3.7/site-packages/mlrun/execution.py", line 526, in log_dataset
labels=labels,
File "/usr/local/lib/python3.7/site-packages/mlrun/artifacts/manager.py", line 155, in log_artifact
item.upload()
File "/usr/local/lib/python3.7/site-packages/mlrun/artifacts/dataset.py", line 140, in upload
**self._kw,
File "/usr/local/lib/python3.7/site-packages/mlrun/artifacts/dataset.py", …
```
> [Requirements] Upbound numpy to 1.20

- mlrun/api/db/sqldb/db.py
- tests/api/api/feature_store/test_feature_sets.py
- tests/api/api/feature_store/test_feature_vectors.py
Fixing a known issue in the SQLDB where a DB query for objects with multiple labels would return nothing. For example, if looking for a feature-set with:
`GET /projects/<proj>/feature-sets?label=label1=value1&label=label2=value2`
This will return nothing, even if an object with both labels and values exist. The reason is the SQL query that was used in the `_add_labels_filter()` method which could not handle this kind of complex query.
The fix allows for multiple labels to be queried, and also takes care of the special (and weird) case of asking for:
`label=label1&label=label1=value1`
In this case it will reduce the query to `label=label1=value1` and ignore the predicate without the value which is redundant.
The fix applies to all objects which use the `_add_label_filter()` method, which …
> [API] Add support for query with multiple label values

- tests/system/base.py
- tests/system/demos/base.py
- tests/system/examples/basics/test_db.py
- tests/system/examples/dask/test_dask.py
- tests/system/examples/jobs/test_jobs.py
The fix to reload the config after changing the env (done as part of this PR - https://github.com/mlrun/mlrun/pull/691) was the reason the re-initialization was needed
> [System tests] Remove unneeded re-initialization of rundb

- mlrun/api/api/endpoints/healthz.py
- mlrun/config.py
- mlrun/db/httpdb.py
- mlrun/kfpops.py
* Make the client get the `kfp_image` from the server
Since the pipelines yaml is currently being rendered in the client side, the kfp image is "taken" from config in client side, so if we want to be able to actually control it, we want to sync this config value from server to client.
(This is also the reason in our system tests the pipelines pods are using `mlrun/mlrun:unstable` and not the tested version)
* Add a `dask_kfp_image` config value (because.. we need a way to configure it, we don't want it to be hardcoded)
and for the same reasons as the above, we made the client sync it from the server
> [SDK] Read kfp image from server + make dask kfp image configurable

- dev-requirements.txt
- requirements.txt
Upbound cryptography to `cryptography~=3.3.2` since 3.4 and above failed builidng in some images - see https://github.com/pyca/cryptography/issues/5771
Also pinning storey to 0.3.2 since 0.3.3 breaks CI for some reason
> [Requirements] Upbound cryptography version and pin storey

- dev-requirements.txt
- mlrun/datastore/__init__.py
- mlrun/datastore/azure_blob.py
- mlrun/datastore/base.py
- mlrun/datastore/datastore.py
- mlrun/datastore/filestore.py
- mlrun/datastore/s3.py
- mlrun/datastore/store_resources.py
- mlrun/datastore/v3io.py
- mlrun/feature_store/sources.py
- mlrun/serving/states.py
- requirements.txt
- setup.py
- tests/test_datastores.py
* support fsspec filesystem for all stores (file, http, s3, v3io, ..)
* support .as_df() through fsspec fs (eliminate file copy and allow work with dask)
* support get_filesystem and storage_options per type (used by storey and feature store)
* support DataItem.open(), open data item as fsspec file
* support path mapping from dataitem/fsspec paths to spark paths (for feature store)
> [Datastore] Add fsspec support to all data stores

- .github/workflows/system-tests-enterprise.yml
- .github/workflows/system-tests-opensource.yml
- CONTRIBUTING.md
- Makefile
- tests/system/base.py
- tests/system/demos/churn/test_churn.py
- tests/system/demos/horovod/test_horovod.py
- tests/system/demos/sklearn/test_sklearn.py
- tests/system/examples/basics/test_basics.py
- tests/system/examples/basics/test_db.py
- tests/system/examples/dask/test_dask.py
- tests/system/examples/jobs/test_jobs.py
- Added facilities for running system tests against MLRun Kit (and not only Iguazio system):
- Pytest markers for enterprise only tests.
- Env can only contain `MLRUN_DBPATH` if the test isn't enterprise only.
- `make test-system-open-source` runs the tests that aren't enterprise.
- Added CI for periodically bringing up the latest MLRun Kit and running system tests against it.
- Updated CONTRIBUTING.md to reflect the new pytest markers
> [Tests] Adding open source MLRun-Kit system tests

- docs/quick-start.ipynb
Fixed a small typo in "Quick-Start Guide" document page.
> [Doc] Fix typo in "Quick-Start Guide"

- tests/api/runtimes/base.py
- tests/api/runtimes/test_dask.py
- tests/api/runtimes/test_kubejob.py
Adding framework and initial tests for Dask runtime unit-tests. Currently running through the standard flow of creating a Dask runtime as shown [here](https://docs.mlrun.org/en/latest/runtimes/dask-mlrun.html), and validating that the spec for the Dask runtime pods is correct.
Additional tests may be added in the future with further validations and configurations.
> [Tests] Dask runtime unit test

- mlrun/runtimes/constants.py
- mlrun/runtimes/mpijob/v1.py
- mlrun/runtimes/mpijob/v1alpha1.py
The [clean pod policy](https://github.com/kubeflow/common/blob/master/pkg/apis/common/v1/types.go#L137) describes how to deal with pods when the job is finished (success or failure)
We want to set it to `All` by default, since without it, the operator default is None, that means the worker pods will stay there, which means that if for example GPU was used, it will still be occupied for the worker pods although the job finished.
It is possible to change the policy by doing:
```
import mlrun.runtimes.constants
function.spec.clean_pod_policy = mlrun.runtimes.constants.MPIJobV1CleanPodPolicies.running
```
This resolves https://jira.iguazeng.com/browse/ML-22
> [MPIJob] Support configuring clean pod policy and set to All by default

- .github/workflows/ci.yaml
- mlrun/datastore/targets.py
- mlrun/execution.py
- requirements.txt
- tests/artifacts/test_dataset.py
Since this change https://github.com/mlrun/mlrun/pull/752 we started providing pandas the file when writing `to_csv`
The file is open with `wb` and pandas had a bug with that which was solved in 1.2.0, so changed the requirement from `~1.0` to `~1.2`, the problem is that in 1.2.0 pandas dropped support to python 3.6, so only in python 3.6, the requirement will stay the same, and we'll open the file in `wt` mode which might prevent some features
The error we were seeing was:
```
File "/opt/conda/lib/python3.7/site-packages/mlrun/execution.py", line 651, in log_dataset
labels=labels,
File "/opt/conda/lib/python3.7/site-packages/mlrun/artifacts/manager.py", line 155, in log_artifact
item.upload()
File "/opt/conda/lib/python3.7/site-packages/mlrun/artifacts/dataset.py", line 136, in upload …
```
> [Artifacts] Fix data frame artifacts failure to write as csv

- mlrun/config.py
This PR removes a duplication that was created in the default configuration of mlrun. In addition, this PR changes the default port for v3io framesd
> [Configuration] Duplicated configurations removal + default value fixes

- mlrun/runtimes/pod.py
- mlrun/utils/regex.py
- tests/api/runtimes/test_pod.py
When calling `with_limits` or `with_requests` we validate that the given quantity is a valid one
This will help prevent common failures like users mistakenly set memory limit to `1g` which is invalid (should be `1G`)
This implements https://jira.iguazeng.com/browse/ML-14
> [Functions] Validate k8s resources quantity regex on assignment

- mlrun/run.py
- mlrun/runtimes/base.py
- mlrun/runtimes/function.py
- tests/integration/sdk_api/run/test_run.py
What happened ?
Inside a Nuclio function (i.e. no actual Run context, code inside is of function context), in the init_context part, `get_or_create_ctx` called, that call is generating a Run object, but it was being generated in the `default` project + the Run object itself didn't contain the `project` attribute
This PR do 2 things:
1. Ensure to fill the project attribute in the Run object created in the ctx creation
2. Sets the `MLRUN_DEFAULT_PROJECT` env var on every job/function pod, so that in that job/function context, the default project will be the project of the job/function
> [Runtimes] Set the default project in the runtime context to be the run project

- mlrun/api/db/sqldb/db.py
- tests/api/api/feature_store/test_feature_sets.py
- tests/api/api/feature_store/test_feature_vectors.py
Scenario:
1. Perform store on object, with `tag != 'latest'`
2. Look for the object - the tag is wrong, and entered as `latest`
3. Perform same store again, with same tag
4. Results in 409 (Conflict)
Issue was in the `store_*` methods which in case the object did not previously exist did not honour the tag parameter, and the object was stored with tag `latest` instead (which is the default tag if none is provided).
> [Feature store] Fix store new feature-set or vector not setting tag properly

- mlrun/api/db/sqldb/db.py
- tests/api/db/test_artifacts.py
- tests/rundb/test_sqldb.py
When listing or querying artifacts, the returned results will have a `tag` field in them indicating the tag of the object. 
The `tag` field will always be present, even if there's no tag (in which case it will be `None`).
As is the case for every other object in the MLRun DB - if an artifact has multiple tags and a list API requests all of them (i.e. doesn't filter by tag), the same object will be returned multiple times, each with a different tag associated.
> [Artifacts] Add tag to artifacts returned in get/list APIs

- automation/system_test/prepare.py
If the system tests run at during a provazio release. The system tests' preparer can fail because the latest release of provazio hasn't yet a built provctl binary.
Made the preparer loop over the latest 3 releases to look for the binary in each release before failing. 
(It should never exceed the second release, but added a third for safety)
> [System tests enterprise] Fix failure on pulling provctl while provazio is mid release

- dockerfiles/models-gpu/Dockerfile
- dockerfiles/models/Dockerfile
I started seeing a failure when building the `models-gpu` image, full log is attached.
The error happened at the layer that installs horovod and the message is:
```
Could NOT find Tensorflow: Found unsuitable version "1.14.0", but required
is at least "1.15.0" (found
-L/opt/conda/lib/python3.7/site-packages/tensorflow;-l:libtensorflow_framework.so.1)
```
I tried going back in the code to 0.6.1 (which when we released it, the models-gpu image was built successfully) and trying to build produced the same error, so I understood the problem is not a change in code that we did.
I found [here](https://anaconda.org/anaconda/tensorflow-gpu/files) that a new version of `tensorflow-gpu` 2.4.1 - was released recently (8/3)
Looking on the build logs I saw that we install the `tensorflow-gpu` two …
> [Images] Pin and align tensorflow in models and models-gpu images

- mlrun/runtimes/daskjob.py
- mlrun/runtimes/function.py
- mlrun/runtimes/kubejob.py
- mlrun/runtimes/mpijob/abstract.py
- mlrun/runtimes/mpijob/v1.py
- mlrun/runtimes/mpijob/v1alpha1.py
- mlrun/runtimes/pod.py
- mlrun/runtimes/remotesparkjob.py
- mlrun/runtimes/sparkjob.py
- tests/api/runtimes/base.py
- tests/api/runtimes/test_dask.py
- tests/api/runtimes/test_kubejob.py
- tests/api/runtimes/test_pod.py
- tests/runtimes/test_run.py
Exposing [k8s ways](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/) to assign jobs to run on specific nodes, shortly there are 3 ways:
* Using node name:
```
function.with_node_selection('k8s-node1')
```
* Using node selector:
```
function.with_node_selection(node_selector={'kubernetes.io/hostname': 'k8s-node2'})
```
* Using affinity:
```
from kubernetes import client as k8s_client
affinity = k8s_client.V1Affinity(
node_affinity=k8s_client.V1NodeAffinity(
preferred_during_scheduling_ignored_during_execution=[
k8s_client.V1PreferredSchedulingTerm(
weight=1,
preference=k8s_client.V1NodeSelectorTerm(
match_expressions=[
k8s_client.V1NodeSelectorRequirement(
key="kubernetes.io/hostname",
operator="In",
values=[
"k8s-node2",
"k8s-node3",
],
)
]
),
)
],
),
) …
```
> [Runtimes] Support setting node name, node selector and affinity

- mlrun/api/api/endpoints/schedules.py
- mlrun/api/db/base.py
- mlrun/api/db/filedb/db.py
- mlrun/api/db/sqldb/db.py
- mlrun/api/db/sqldb/models.py
- mlrun/api/migrations/tests/test_migrations.py
- mlrun/api/migrations/versions/e1dd5983c06b_schedule_concurrency_limit.py
- mlrun/api/schemas/constants.py
- mlrun/api/schemas/schedule.py
- mlrun/api/utils/scheduler.py
- mlrun/config.py
- mlrun/db/filedb.py
- mlrun/runtimes/constants.py
- mlrun/utils/helpers.py
- tests/api/api/test_schedules.py
- tests/api/db/test_projects.py
- tests/api/utils/function.py
- tests/api/utils/test_scheduler.py
- tests/rundb/test_dbs.py
Concurrency limit for scheduled jobs and local functions.
Schedule has a concurrency limit integer field which defaults to 1 (no concurrency). The user can set this integer to a larger number in order to allow overlapping scheduled jobs.
Implements: https://jira.iguazeng.com/browse/ML-154
> [Scheduler] Add concurrency limit

- mlrun/api/api/endpoints/runtimes.py
- mlrun/api/crud/runtimes.py
- mlrun/api/schemas/__init__.py
- mlrun/api/schemas/runtime_resource.py
- mlrun/runtimes/base.py
- mlrun/runtimes/daskjob.py
- tests/api/runtime_handlers/base.py
- tests/api/runtime_handlers/test_kubejob.py
- tests/api/runtime_handlers/test_mpijob.py
- tests/api/runtime_handlers/test_sparkjob.py
Due to time restrictions I did some non-consistent stuff here/broke the existing terminology, hopefully I'll be able to align it soon
Added a `GET /projects/{project}/runtime-resources` endpoint (Added TODO to replace to old `GET /runtimes` with this one)
which supports giving `group-by` query param, currently only possible value (beside empty) is `job` which will return the runtime resources grouped by job
Implements https://jira.iguazeng.com/browse/ML-29
> [Runtime resources] Support grouping by job

- dockerfiles/test-system/requirements.txt
System tests stopped working after https://github.com/mlrun/mlrun/pull/814 was merged since graphviz is missing
> [System test] Add graphviz to requirements

- dockerfiles/test-system/Dockerfile
Following https://github.com/mlrun/mlrun/pull/822 we need the executable as well
> [System test] Add installation of graphviz executable to image

- mlrun/api/api/endpoints/feature_sets.py
- mlrun/api/db/base.py
- mlrun/api/db/filedb/db.py
- mlrun/api/db/sqldb/db.py
- mlrun/db/base.py
- mlrun/db/filedb.py
- mlrun/db/httpdb.py
- mlrun/db/sqldb.py
- tests/api/api/feature_store/test_feature_sets.py
- tests/api/api/feature_store/test_feature_vectors.py
Added REST API and DB implementation for deleting specific versions of feature-set and feature-vector objects. Versions are identified by a reference (either `uid` or `tag`), as usual.
APIs are also supported through the httpdb interface in `delete_feature_vector` and `delete_feature_set`.
Delete REST APIs supported now are:
```
DELETE /projects/{project}/feature-sets/{name}
DELETE /projects/{project}/feature-sets/{name}/references/{reference}
```
(and of course, same for feature-vectors)
> [API] Adding APIs to delete specific versions of feature-store objects

- mlrun/api/api/endpoints/tags.py
The `get_tagged()` API would use a version of `to_dict` that used Python introspection. In SQLAlchemy 1.4, a new attribute `registry` was added to the `base_declarative` class as part of a major change done to support declarative mapping. When calling `get_tagged()` it attempts to serialize the `registry` attribute for the HTTP response, and it fails.
To fix, switched to using the `BaseModel.to_dict()` function instead, which extracts just the DB columns and ignores other Python attributes. Note that this is only done for tags APIs, as these are the only APIs currently exposing DB objects externally (and not going through `from_orm` or something similar).
> [API] Fix get tagged objects API serialization 

- docs/install.md
There seems to be a typo in the documentation in the helm uninstall with a preceding "-" for mlrun-kit
> [Doc] Remove preceding "-" in front of mlrun-kit in installation guide

- docs/howto/remote.md
- docs/install.md
- docs/store/artifacts.md
- mlrun/projects/project.py
- mlrun/run.py
- mlrun/runtimes/base.py
- mlrun/utils/helpers.py
- tests/utils/test_helpers.py
In certain setup configuration we configure the default artifact path to have the `{{run.project}}` this was not working with the [recently added](https://github.com/mlrun/mlrun/pull/786) project's log_x methods
To solve that, and for the terminology to make sense, I added support to `{{project}}` for artifact path (while keeping BC with `{{run.project}}`) And added this support in the project's log_x methods as well
Fixes https://jira.iguazeng.com/browse/ML-302
> [Artifacts] Support {{project}} in artifact path + support template for project's log_x methods

- mlrun/api/schemas/constants.py
- mlrun/api/utils/scheduler.py
* Fixed schedule name label from `schedule-name` to `mlrun/schedule-name"`
* The condition for checking if we passed the limit was `if len(active_runs) > schedule_concurrency_limit:` instead of `if len(active_runs) >= schedule_concurrency_limit:`
> [Scheduler] Fix concurrency limit check + schedule label name

- docs/install.md
- Fixing ports - addresses https://github.com/mlrun/mlrun/issues/827
- Adding references from original chart [README](https://github.com/v3io/helm-charts/blob/development/stable/mlrun-kit/README.md) referring to minikube/VM installation and `externalHostAddress` value, with slight edits to fit the local doc structure
> [Doc] - MLRun - kit fixes

- mlrun/api/api/endpoints/functions.py
- mlrun/api/utils/scheduler.py
There were several endpoints defined as `async def` meaning they are [running on the reactor](https://fastapi.tiangolo.com/async/#in-a-hurry) meaning any call to sync code should be wrapped with `run_in_threadpool` - the wrapping was missing
> [API] Fix endpoints running sync code on the reactor

- mlrun/projects/project.py
- tests/projects/test_project.py
In the legacy project structure users did `project.artifact_path` while now they should do `project.spec.artifact_path`
Added a proxy property to allow still doing `project.artifact_path` to keep backwards compatibility
> [Projects] Support accessing artifact path from root

- mlrun/feature_store/common.py
- mlrun/feature_store/retrieval/local_merger.py
* When I was working on https://github.com/mlrun/mlrun/pull/830 I was changing `write_dataframe` to return tuple (2 values), but then rollback that change, mistakenly leaving the local merger reading 2 values - fixed that
* Noticed that it is using `mlrun.errors` but not importing it so fixed that as well
* Noticed the same in `common.py`
* function setter in the same file was mistakenly doing `self.function` instead of just `function`
> [Feature store] Fix some typo bugs

- mlrun/config.py
This queries on the DB every 5 sec make too much load, loosening it a bit
> [Monitoring] Change default runs monitoring interval to 30 sec (from 5)

- setup.py
adlfs requirement was `~0.6`, 0.7.0 was released few days ago, in the version [they upbound fsspec to 0.8.7](https://github.com/dask/adlfs/commit/0db94169b14d3fbfa494dacdaaaf33223dc2956b) which caused conflicts since fsspec is sub-requirement of `v3iofs` in which it's `>=0.6.2` and was practically installing `0.9.0`
For that reason changed adlfs to be `~=0.6.0` i.e. limiting it to patch changes only.
This also our general convention - when packages are 0.x, minor bumps can have backwards incompatible changes so we bound to patch changes only, saw that the same was going in `s3fs` so fix it as well
> [Requirements] Lock adlfs and s3fs to patch changes only

- dockerfiles/models/requirements.txt
- requirements.txt
- setup.py
It seems like the actual right fix for what described in https://github.com/mlrun/mlrun/pull/850 was to bump adlfs and replicate fsspec restrictions since probably adlfs (0.6.x or 0.7.x) is actually not compatible with fsspec bigger than 0.8.7 (they didn't add it for no reason)
Just didn't want to do it then cause it was moments before releasing 0.6.2, and all tests were done with 0.6.x
> [Requirements] Bump adlfs to 0.7.x

- mlrun/api/utils/projects/leader.py
- tests/api/utils/projects/test_leader_member.py
This thing happened several times in system tests causing transient failures, copying the reproducement test docstring:
```
This reproduce a bug in which projects sync is running mid deletion
The sync starts after the project was removed from followers, but before it was removed from the leader, meaning the
sync will recognize the project is missing in the followers, and create it in them, so finally after the delete
process ends, the project exists in the followers, and not in the leader, on the next sync, the project will be
created back in the leader causing the the project to practically not being deleted.
```
> [Projects] Don't sync projects while mid deletion

- mlrun/db/httpdb.py
In https://github.com/mlrun/mlrun/pull/812 I made the scrape metrics configurable, as part of it, I added logic for the client to read this value from the server, when the server don't have value, it defaults to what the client currently have (`config.scrape_metrics`). I had a typo that it default to `config.kfp_image` instead
Practically in every 0.6.2 server this will be configured, but the meaning is that running a 0.6.2 client with 0.6.1 server (which don't have it configured) will cause weird failures (trying to set the scrape metrics to an image name)
> [Config] Fix typo in config enrichment from server

- mlrun/api/api/endpoints/grafana_proxy.py
- mlrun/api/crud/model_endpoints.py
- mlrun/config.py
- mlrun/db/httpdb.py
- mlrun/serving/server.py
- mlrun/serving/v2_serving.py
- tests/api/api/test_grafana_proxy.py
- tests/api/api/test_model_endpoints.py
* Updated model monitoring config to allow a similar functionality to the feature store config, this PR introduces a single template for data store paths instead of individual paths for kv, tsdb and parquets. 
* Implemented endpoint "registration" in v2_model_server.
> [Model Monitoring] Add endpoint registration to v2 serving + config changes

- mlrun/api/api/endpoints/secrets.py
- mlrun/projects/project.py
- mlrun/utils/vault.py
Had an issue where if the MLRun configuration on Jupyter didn't include the `mlconf.secret_stores.vault.url` parameter, the code would explode when doing `func.run()` for a function using Vault secrets, since there is no `http://` prefix to the url. 
This is a fatal error on server side, but the `get_secrets()` API is called on client side as well, while not required to return values. Therefore made sure this flow failed gracefully in this case.
Also, added 2 other small fixes found while testing this:
1. Calling `project.get_vault_secrets()` with `local=True` was missing a return statement (this is a rare flow anyway, and is discouraged, but still needs to be handled properly)
2. The `initialize_project_secrets` API endpoint, when called with empty secret list, was deleting all project …
> [Vault] Fix client to work when url is not configured

- setup.py
We started seeing packages CI failing with:
```
Warning!!! Possibly conflicting dependencies found:
* aiobotocore==1.3.0
- botocore [required: >=1.20.49,<1.20.50, installed: 1.20.50]
------------------------------------------------------------------------
```
That is happening since botocore recently released 1.20.50, which is incompatible with the latest aiobotocore (which is a sub requirement of s3fs)
boto3 from 1.17.50 requires botocore>=1.20.50,<1.21.0 which conflicts with s3fs 0.5.2 that has aiobotocore>=1.0.1
which resolves to 1.3.0 which has botocore>=1.20.49,<1.20.50, so added <1.17.50 to boto3
boto3 1.17.49 has botocore<1.21.0,>=1.20.49, so we must add botocore explictly
> [Requirements] Bound boto3 to <1.17.50 and add botocore explicitly 

- mlrun/runtimes/utils.py
> [Builder] Fix function image tagging syntax

- mlrun/api/api/endpoints/grafana_proxy.py
- mlrun/api/api/endpoints/model_endpoints.py
- mlrun/api/crud/model_endpoints.py
- tests/api/api/test_grafana_proxy.py
- tests/api/api/test_model_endpoints.py
> [API] Fix model monitoring endpoints sync/async separation

- mlrun/api/api/endpoints/feature_sets.py
- mlrun/api/schemas/feature_store.py
- mlrun/feature_store/api.py
- mlrun/feature_store/feature_set.py
Changing the ingest API such that the `source` parameter is optional - the value in `feature_set.spec.source` can be used if set properly. If both are empty then `ingest` would still fail of course.
Change is applied both to the SDK API and to the REST API. This means the REST API can be called with an empty payload, assuming the feature-set is properly configured and saved prior to the call.
> [API] Making source parameter for ingest API optional

- mlrun/api/api/endpoints/feature_sets.py
After this fix, ingest API can be called without any payload. Until now, body was mandatory, so an empty body was required or else 422 was returned.
> [API] Making payload of ingest API optional

- mlrun/api/api/endpoints/feature_sets.py
- mlrun/api/db/sqldb/db.py
- mlrun/api/schemas/feature_store.py
The code in `FeatureSetSpec` had features and entities as mandatory lists. This means that if a user does `feature_set.save()` on an object without them, it will cause failures. This is not the expected behavior.
As a side effect, once they became optional, had to change the way `feature_set.dict()` behaves and add `exclude_none=True`, because otherwise the dictionary created would have (for example) `{"entities": None}`, and various get calls such as `entities = feature_set_spec.pop("entities", [])` would return `None` rather than the expected `[]` since the default value is only used when the key does not exist in the dictionary, not when it is None. Using `exclude_none` fixes this behaviour.
> [Feature Store] Making features/entities optional in feature-set spec

- mlrun/builder.py
- mlrun/config.py
- mlrun/runtimes/kubejob.py
A call to `.deploy()` when nothing specified doesn't really require deploy since the default base image is `mlrun/mlrun` so although by default `with_mlrun` is `True` there's no need to install mlrun on it, since it's already installed.
There was a bug that caused the wrong image to be set on the function's spec + deploy was returning False as if it was failed - Fixed it
Also changed the default base image to be configurable
Fixes https://github.com/mlrun/mlrun/issues/900
> [Runtimes] Fix skipped deployment to set the right image

- mlrun/api/crud/runs.py
- tests/api/api/test_runs.py
Our current way for aborting runs is removing their runtimes resources (pods/crds) which practically stops their execution.
In Dask runtime the runtime resources - pods - are per function, meaning several runs can use the same pods - meaning killing the pod is not an option - so we don't really have a way to abort dask runs - so we're rejecting requests to do so
Fixes https://jira.iguazeng.com/browse/ML-409
> [API] Reject request to abort dask run

- requirements.txt
Alembic 1.6.0 was released today, after it happened the migration CI started to constantly fail, we are about to release 0.6.3 so for now just bounding to not using this version, and afterwards will actually solve the issue
To reproduce the issue simply remove this bound on alembic an run the migration tests
> [Requirements] Bound alembic to lower than 1.6.0 

- mlrun/runtimes/daskjob.py
- mlrun/runtimes/pod.py
- tests/api/runtimes/base.py
- tests/api/runtimes/test_dask.py
When setting resources it doesn't really make much sense to set the same for the workers and scheduler, especially for example when setting a GPU.
This PR is adding new methods: `with_scheduler_limits`, `with_worker_limits`, `with_scheduler_requests` and `with_worker_requests` 
The old methods `with_requests`/`with_limits` are still working to keep backwards compatibility and just assigning requests/limits for both the scheduler and worker. Added deprecation plan for the support of this methods for Dask runtime.
Fixes https://jira.iguazeng.com/browse/ML-475
Implements https://jira.iguazeng.com/browse/ML-446
> [Dask] Enable to set resources for scheduler/worker separately

- dockerfiles/base/requirements.txt
- dockerfiles/models-gpu/requirements.txt
- dockerfiles/models/requirements.txt
We started getting this error trying to build the models image on the step installing its requirements file:
```
ERROR: Cannot uninstall 'llvmlite'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```
The reason pip tries to install a new version of llvmlight is a new version (1.9.0) of dask-ml released yesterday, since we're moments from releasing a version, I'm just limiting dask-ml to less than 1.9.0.
In the next version this shouldn't be a problem anymore since we're changing the base images (https://github.com/mlrun/mlrun/pull/873) and llvmlight won't be there (currently it's coming from the anaconda base image)
> [Requirements] Bound dask-ml to less than 1.9.0

- mlrun/runtimes/daskjob.py
- tests/api/runtimes/test_dask.py
In https://github.com/mlrun/mlrun/pull/914 we changed the resources to be saved in the `scheduler_resources` and `worker_resources` attribute but didn't handle the `gpus` method which was still saving in the `resources` attribute and therefore nothing is happening when using it
> [Dask] Handle gpus method correctly

- mlrun/api/db/sqldb/db.py
- mlrun/api/db/sqldb/helpers.py
- tests/api/api/feature_store/test_feature_sets.py
- tests/api/api/feature_store/test_feature_vectors.py
- tests/api/db/test_artifacts.py
- tests/api/utils/test_scheduler.py
Modifying the logic behind how name queries are done in list APIs for all MLRun objects:
- If name starts with `~`, query will be an `ilike %name%` query (also ignore case). For example using: `name=~hello` will return names: `myHello`, `heLLoween` and similar
- Else, name is an exact query, and should match in both content and case
As can be seen, the default is now **exact query**, rather than a like query as was before. To create a like query the `~` prefix must be added.
The only caveat here is around Artifacts, due to how the `iter` is encoded in the `key` field. If you ask for an exact artifact name, but do not provide a specific `iter` to look for, the query will still be a like query on `%name`, since the iter is at the beginning of the string. This means that names with prefixes …
> [DB] Change default identifier query to be exact match and support ~ prefix for doing ilike match

- dockerfiles/jupyter/Dockerfile
The image building started failing with the attached failure, not sure what exactly happened, seems like another package changed for us "under the hood" (or a python version ?) and anyways it's not "healthy" that we use `latest` tag as the base image, it all happened just when we released 0.6.3, failing the release, pinning the image tag to `:python-3.8.8` mainly because it works, will re-visit the whole thing after 0.6.3 is out
[Jupyter-image-failure-log.txt](https://github.com/mlrun/mlrun/files/6448714/Jupyter-image-failure-log.txt)
> [Jupyter image] Pin base image tag

- mlrun/runtimes/pod.py
- mlrun/runtimes/utils.py
- tests/api/api/test_utils.py
Adding support to providing node selection attributes on job submission request body to enrich the function, example body attached, notes:
* The fields in affinity are the same as the k8s object (details [here](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#scheduling))
* There is a technical limitation enforcing the affinity inner structure to be camelCase (and not snake_case as the rest of our API)
```
{
"task": {...},
"function": {
"spec": {
"node_name": "k8s-node1",
"node_selector": {"kubernetes.io/hostname": "k8s-node1"},
"affinity": {
"nodeAffinity": {
"preferredDuringSchedulingIgnoredDuringExecution": [
{
"preference": {
"matchExpressions": [
{
"key": "some_node_label",
"operator": "In",
"values": [
"possible-label-value-1",
"possible-label-value-2", …
```
> [API] Enable to enrich function with node selection attributes on job submission endpoint

- dockerfiles/jupyter/Dockerfile
We noticed that when we installing certain packages (like `nuclio-jupyter`) that are already installed pip doesn't remove the old installation
Also when trying to manually uninstall them we got permission errors
It happened because we're running the `pip install` in the docker file under the root user, and not the notebook user
Fixed that
> [Jupyter image] Fix installations to be done by notebook user

- mlrun/__init__.py
make `auto_mount` importable by `import mlrun` only (instead of `import mlrun.platforms`)
> [SDK] Make auto_mount importable from root

- mlrun/builder.py
- mlrun/config.py
Also - document the way to disable the scheduler min interval validation in a comment in `config.py`
> [Builder] Use `python -m pip` instead of `pip` (best practice)

- requirements.txt
Mainly cause we want https://github.com/nuclio/nuclio-jupyter/pull/110
> [Requirements] Bump nuclio-jupyter minimum to 0.8.13

- mlrun/platforms/other.py
In `auto_mount` to detect whether we should use `mount_pvc` we check for the `MLRUN_PVC_MOUNT` env var existence which is a clear cut - if someone set it they wanted us to use it. in contrast, the detection for `mount_v3io` is done by checking the `V3IO_ACCESS_KEY` env var existence, which is a heuristic.
So generally, makes sense to prefer pvc when both are defined.
Specifically, it happened to us that someone tried to use the mlrun-kit which uses pvc mounts, but they also had a v3io access (but no mount support) so they set the `V3IO_ACCESS_KEY` and the `auto_mount` tried to mount v3io which failed.
Fixes https://jira.iguazeng.com/browse/ML-555
> [Runtimes] Fix `auto_mount` precedence to PVC->V3IO

- automation/package_test/test.py
- mlrun/db/httpdb.py
- mlrun/feature_store/api.py
- mlrun/feature_store/feature_set.py
- mlrun/projects/project.py
Fixed bug originated in https://github.com/mlrun/mlrun/pull/946 importing API code path in SDK context causing this error to be raised:
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-9be87cd72dd7> in <module>
----> 1 import mlrun
2 from os import getenv
3 
4 mlrun.set_environment(project='fsdemo', user_project=True)
5 # location of the output data files
~/.pythonlibs/jupyter/lib/python3.7/site-packages/mlrun/__init__.py in <module>
20 from os import environ, path
21 
---> 22 from .config import config as mlconf
23 from .datastore import DataItem, store_manager
24 from .db import get_run_db
~/.pythonlibs/jupyter/lib/python3.7/site-packages/mlrun/config.py in …
```
> [SDK] Fix SDK to not import API requirements

- dev-requirements.txt
- requirements.txt
Bumping nuclio-jupyter to 0.8.14 in order to get https://github.com/nuclio/nuclio-jupyter/pull/113
> [Requirements] Bump nuclio-jupyter minimum to 0.8.14

- dockerfiles/test-system/requirements.txt
`pytest-tornasync` added in https://github.com/mlrun/mlrun/pull/947 but needed for the system tests requirements as well
> [Requirements] Add pytest_tornasync to system tests as well

- dockerfiles/jupyter/Dockerfile
- dockerfiles/jupyter/requirements.txt
- tests/test_requirements.py
* Pull `mlrun/demos` hackathon branch - which is suited for the mlrun-kit
* Adding the `graphviz` and `python-dotenv` package
* Removing the examples from since not all of them are mlrun-kit compatible
> [Jupyter image] Use hackathon mlrun/demos branch, add graphviz & python-dotenv, remove examples

- dockerfiles/jupyter/requirements.txt
- requirements.txt
See https://github.com/nuclio/nuclio-jupyter/pull/115 for full explanation
> [Requirements] Bump nuclio-jupyter to 0.8.15 and use its jupyter-server extra in jupyter image

- mlrun/api/api/endpoints/artifacts.py
- mlrun/api/db/base.py
- mlrun/api/db/filedb/db.py
- mlrun/api/db/sqldb/db.py
- mlrun/db/base.py
- mlrun/db/filedb.py
- mlrun/db/httpdb.py
- mlrun/db/sqldb.py
- tests/api/db/test_artifacts.py
- tests/rundb/test_httpdb.py
Added a new boolean query-param `best-iteration` to the artifacts list API. When using this parameter, the following logic is applied:
- In artifacts resulting from hyper-param (multi-iteration) runs, the artifact at iteration 0 is examined, and the value of `link_iteration` is used to retrieve the artifact from that iteration. That artifact (which is expected to be the best iteration) is returned for that key.
- In artifacts where iteration 0 is a real artifact (not link), that artifact is returned. Artifacts from any other iteration are omitted from the results.
**Notes:**
1. The `best-iteration` parameter cannot co-exist with the `iter` parameter - specifying both will result in an error.
2. The expected usage for this parameter is  with filtering on project/name. Other filters are …
> [API] Adding best-iteration parameter to artifacts list

- mlrun/api/api/endpoints/functions.py
- mlrun/builder.py
- mlrun/db/httpdb.py
- mlrun/errors.py
- mlrun/runtimes/kubejob.py
- tests/rundb/test_httpdb.py
Also:
* Fix httpdb to propagate mlrun errors (instead of `RunDBError`)
* Raise when `.deploy()` failed (instead of returning False)
Fixes https://jira.iguazeng.com/browse/ML-566
> [SDK+API] Move deploy enrichment and validation to API

- docs/tutorial/01-mlrun-basics.ipynb
Fixing old wrongs
2 Things here:
- Projects are first and foremost for namespacing. The packaging aspect is both not the main thing, and also not fully developed, shouldn't be mentioned here.
- Creating projects should be favored from the UI (mentioned UI/API for symmetry and correctness) - NOT as a side effect of creating functions/objects. This was discussed internally and we even wanted to remove the the behavior of creating projects as a side effect as projects will become more meaningful and their creation should be more involced and opinionated, and we want to pull users to create and manage projects with purpose and not haphazardly.
> [Docs] Basic tutorials projects text change

- mlrun/runtimes/serving.py
Most times, the best option is to execute the entire pipeline rather than any step individually. This allows users to use multi-function syntax without changing anything when running the mock server.
> [Serving] Set current_function to all functions by default

- mlrun/api/db/sqldb/db.py
- mlrun/api/schemas/object.py
- mlrun/utils/helpers.py
- tests/api/api/feature_store/test_feature_sets.py
- tests/api/api/feature_store/test_feature_vectors.py
The `created` field already exists in the DB today, now it's reflected in the objects returned from the APIs in the `metadata.created` field.
> [API] Adding metadata.created to feature-store objects

- dockerfiles/test-system/requirements.txt
https://github.com/mlrun/mlrun/pull/1033 added usage of deepdiff to the system tests, and then they started to break, fixing it
> [System Tests] Add deepdiff to system tests requirements

- mlrun/config.py
- mlrun/datastore/sources.py
- mlrun/serving/server.py
- mlrun/serving/states.py
Usage:
```
from mlrun.runtimes import nuclio_init_hook
from mlrun.config import config
config.datastore.use_async_source = "enabled"
def init_context(context):
nuclio_init_hook(context, globals(), 'serving_v2')
async def handler(context, event):
return await context.mlrun_handler(context, event)
```
> [Datastore] Allow switching source to AsyncEmitSource in ingestion service

- tests/system/api/test_projects.py
marking as enterprise until we'll release a new mlrun-kit that uses the new (0.6.3) mlrun helm chart which adds
secrets permission to the mlrun-api role
> [System Tests] Change projects secrets system tests location + mark as enterprise

- setup.py
- tests/test_requirements.py
This will allow to use `git+https://github.com/nuclio/nuclio-jupyter.git@some-branch#egg=nuclio-jupyter` on the `requirements.txt`
> [Requirements] Allow install dependencies from remote endpoints

- mlrun/api/utils/scheduler.py
- mlrun/config.py
- tests/api/utils/test_scheduler.py
Firing our jobs include things like creating pods which might not be instant, therefore in the case of multiple schedules scheduled to the same time, there might be delays, the default of the scheduler for misfire_grace_time is 1 second, we do not want jobs not being scheduled because of the delays so setting it to None.
Fixes https://jira.iguazeng.com/browse/ML-524
> [Scheduler] Configure `misfire_grace_time` to None by default

- requirements.txt
nuclio-jupyter has notebook>=5.2.0 which resolves to 6.4.0 which has ipykernel without specifier, which from 0.6.0 (released several hours ago) has ipython>=7.23.1 which is incompatible with our ipython specifiers, therefore instsalling ipykernel 5.x before nuclio-jupyter
> [Requirements] Bound ipykernel to 5.x

- mlrun/execution.py
- mlrun/feature_store/api.py
- mlrun/runtimes/base.py
- mlrun/runtimes/function.py
* currently when the API service initializes the client context object (execution) it also try to initialize/fetch the input artifacts this can lead to errors with store artifacts and is not really needed
*  fix deploy of an ingestion service with empty or partial function reference (read Nuclio/serving runtime functionSourceCode from spec.build not just from spec.base_spec)
> [API] Fix bugs when using feature vectors and in real time ingestion

- mlrun/config.py
- mlrun/k8s_utils.py
- mlrun/model.py
- mlrun/runtimes/function.py
- mlrun/runtimes/kubejob.py
- mlrun/runtimes/pod.py
- mlrun/runtimes/serving.py
- mlrun/secrets.py
- tests/api/runtimes/base.py
- tests/api/runtimes/test_kubejob.py
- tests/system/api/assets/function.py
- tests/system/api/test_projects.py
Completing the MLRun k8s project-secrets functionality. This adds a `kubernetes` secret provider. Now if a function is created, its `RunConfig` can have this secret source configured. This will cause the Pod created to have environment variables attached to it that will get their value from the k8s project secret managed by MLRun. 
The user can still use `context.get_secret()` as usual to retrieve the value of these secrets. An example for an end-to-end flow can be seen in the `test_k8s_project_secrets_with_runtime` system-test added.
> [Secrets] Add kubernetes secrets provider

- dockerfiles/jupyter/requirements.txt
- mlrun/api/api/endpoints/functions.py
- mlrun/builder.py
- mlrun/config.py
- mlrun/db/httpdb.py
- mlrun/k8s_utils.py
- mlrun/runtimes/function.py
- requirements.txt
- tests/api/runtimes/test_serving.py
- tests/test_requirements.py
This is a work in progress 🚬 
- added "unhealthy" to the function states when deployment needs to raise an error
- support internal / external invocation urls, this is a Nuclio >= 1.6.x feature. I left the `address` field for backwards compatibility for those working against nuclio 1.5.x
Invoking a function would use the `internal` invocation url if applicable and running within Kubernetes cluster. else will fallback to external url or the good-old address.
deploy function will return the external address, for backwards compatibility. the return address can be used on your jupyter notebook.
> [Nuclio] Support internal external invocation urls

- mlrun/api/api/endpoints/functions.py
- mlrun/config.py
- mlrun/runtimes/constants.py
- mlrun/runtimes/function.py
- tests/api/runtimes/test_nuclio.py
To allow MLRun working with functions having service type `ClusterIP` and being remotely available, this PR introducing a new working mode where as functions can be assigned with ingresses created by Nuclio ingress host template.
| mode name        |  description
| :--- | :--- |
|never       |  never enrich with an ingress
|always      |  always enrich with an ingress, regardless the service type
|onClusterIP |  enrich with an ingress only when `mlrun.config.httpdb.nuclio.default_service_type` is set to ClusterIP
> [Nuclio] Allow creating function with ingresses automatically

- mlrun/api/db/sqldb/models.py
- mlrun/api/schemas/function.py
Saw this error when trying to downgrade from 0.6.5 to 0.6.4:
```
File "/usr/local/lib/python3.7/site-packages/uvicorn/protocols/http/h11_impl.py", line 394, in run_asgi
File "/usr/local/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
return await self.app(scope, receive, send)
File "/usr/local/lib/python3.7/site-packages/fastapi/applications.py", line 190, in __call__
await super().__call__(scope, receive, send)
File "/usr/local/lib/python3.7/site-packages/starlette/applications.py", line 111, in __call__
await self.middleware_stack(scope, receive, send)
File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 181, in __call__
raise …
```
> [Schemas] Change `FunctionState` to regular string constants class to enable downgrading to 0.6.4

- docs/install.md
- hack/local/README.md
WSL 2 handles file permissions differently. If left as is, MlRun will not be able to write the sqllite database. For WSL 2, SHARED_DIR has to be created first.
> [Docs] Add note about running MLRun with Docker on WSL 2

- mlrun/runtimes/base.py
- tests/api/api/test_functions.py
- tests/api/api/test_projects.py
- tests/api/conftest.py
- tests/api/runtime_handlers/base.py
- tests/api/runtimes/base.py
- tests/api/runtimes/test_kubejob.py
- tests/api/runtimes/test_nuclio.py
- tests/api/runtimes/test_serving.py
Project deletion was failing in non k8s env on trying to remove runtime resources (trying to list pods and failing):
```
> 2021-07-09 13:52:09,780 [warning] Request handling failed. Sending response: {'status_code': 500, 'request_id': '6bb08a60-20b5-4c3a-be08-d7159a1aa56d', 'uri': '/api/projects/default', 'method': 'DELETE', 'exc': AttributeError("'K8sHelper' object has no attribute 'v1api'")}
ERROR:    Exception in ASGI application
File "/opt/conda/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 394, in run_asgi
File "/opt/conda/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
return await self.app(scope, receive, send)
File …
```
> [Runtimes] Skip list/delete runtime resources in non k8s env

- automation/requirements.txt
- automation/system_test/prepare.py
Before this we were simply picking by the order of the response from github which is done by creation time which caused us to take "backport releases" which caused system tests to fail
> [System Tests] Use semver-latest Provazio releases

- dockerfiles/jupyter/requirements.txt
- mlrun/api/api/endpoints/functions.py
- mlrun/runtimes/function.py
- requirements.txt
moved internal / external hardcoding knowledge back to nuclio-jupyter, which has more awareness of compiling the correct internal address
> [Nuclio] Fix external / internal invocation urls resolution

- mlrun/api/api/endpoints/projects.py
- mlrun/api/db/sqldb/db.py
- mlrun/api/schemas/__init__.py
- mlrun/api/schemas/constants.py
- mlrun/api/schemas/project.py
- mlrun/api/utils/clients/iguazio.py
- mlrun/api/utils/projects/follower.py
- mlrun/api/utils/projects/leader.py
- mlrun/api/utils/projects/member.py
- mlrun/api/utils/projects/remotes/leader.py
- mlrun/api/utils/projects/remotes/nop_leader.py
- tests/api/utils/clients/test_iguazio.py
- tests/api/utils/projects/test_follower_member.py
Basically in follower mode our projects source of truth is the leader and the data in the DB is not relevant or maintained. The leader format purpose is a specific upgrade scenario where we're moving from leader mode (in which the projects are maintained in the DB) to follower mode in which the leader needs to be aware of the already existing projects so we're allowing only to the leader, to read from the DB, and return it in the leader's format
> [Projects] Support listing projects from DB in leader format for upgrade scenarios

- tests/integration/sdk_api/httpdb/test_exception_handling.py
On my mac `gaierror(-2, 'Name or service not known')` is raised but on my linux machine `gaierror(-3, 'Temporary failure in name resolution')`, change the error message assertion regex to include both
> [Tests] Fix httpdb  exception handling integration test

- mlrun/utils/helpers.py
Updated Slack run link format for RunNotifications. Uses new format of "https://dashboard.default-tenant.app.my-cluster.iguazio-cd0.com/mlprojects/PROJECT/jobs/monitor/UID/overview"
> [Utils] Update Slack run link format used for the RunNotifications

- mlrun/api/crud/artifacts.py
- mlrun/api/crud/feature_store.py
- mlrun/api/crud/functions.py
- mlrun/api/crud/runs.py
- mlrun/api/db/base.py
- mlrun/api/db/filedb/db.py
- mlrun/api/db/sqldb/db.py
- mlrun/api/schemas/auth.py
- mlrun/api/utils/background_tasks.py
- mlrun/api/utils/clients/opa.py
- mlrun/api/utils/projects/follower.py
- mlrun/api/utils/projects/member.py
- mlrun/api/utils/scheduler.py
- mlrun/config.py
- mlrun/runtimes/base.py
- tests/api/utils/clients/test_opa.py
When a project is being ensured if the project is actually created, it may take some time for the OPA manifest to be updated, until then, requests may fail, to reduce the noice, we cache the project owner and allow him all actions on the project for a configurable (by default 30 seconds) ttl
Also:
1. Removed unneeded `ensure_project` call in `update_schedule` logic
2. Improved `monitor_run` error log
> [Projects] Cache ensured project owners to allow permissions until OPA manifest published

- mlrun/datastore/azure_blob.py
- tests/common_fixtures.py
- tests/integration/azure_blob/test_azure_blob.py
Fail if a `put` request was sent with `append=True`.
Modified the integration tests such that they can run on a single auth method (does not need to fill in all the parameters for all methods). Tests will execute according to the auth parameters available in the yml file.
> [Datastore] Small improvements to Azure blob handling & testing

- mlrun/feature_store/retrieval/local_merger.py
- tests/system/feature_store/test_feature_store.py
> [Feature Store] Don't remove entity timestamp column when `vector.spec.with_indexes` is `True`

- mlrun/api/migrations/versions/d781f58f607f_tag_object_name_string.py
2 separate alembic revisions were created in parallel. Fixed the tree so there is one head.
> [DB] Fix Alembic Tree

- mlrun/runtimes/kubejob.py
- mlrun/runtimes/pod.py
- mlrun/runtimes/serving.py
- mlrun/secrets.py
- tests/api/runtimes/test_kubejob.py
- tests/system/api/test_projects.py
Had a bug where passing an empty list of secrets to `with_secrets` would actually expose no secrets to the running job if working with the `kubernetes` provider.
For example:
```
task = mlrun.new_task().with_secrets("kubernetes", [])
function.run(task)
```
Is expected to allow the function access to all project secrets, and it didn't.
Also, fixed another small issue where code was calling `k8s_helper.get_project_secret_keys` even though this name was changed in another PR.
> [Secrets] Fix k8s project secrets to support an empty list of secrets in `with_secrets`

- mlrun/api/crud/secrets.py
- mlrun/api/utils/scheduler.py
- mlrun/utils/helpers.py
- tests/api/crud/test_secrets.py
- tests/api/utils/test_scheduler.py
We started saving each schedule credentials in project secrets, so far we used the schedule key to generate the secret key, but secret keys in k8s have restriction which schedule names might not X to.
Therefore I added a mechanism to save a key map in a value of another secret key, that is simply a json dump of a map between the schedule names to generated uuids that are used as the actual secret keys.
Note that we're using the key map only when needed - for schedule names that are invalid secret keys
2 other solutions brought up that we decided not to choose:
1. "Hashing"/base64 encoding the schedule name - hashing is not bidirectional, and base64 has characters that are invalid in a secret key
2. Adding an annotation on the schedule holding the secret key - this makes debugging harder …
> [Secrets] Support using key maps for secrets

- dev-requirements.txt
- requirements.txt
* `google-auth` explanation in comments in code
* `pytest-alembic` 0.4.0 was just released and caused breakages (we were `~0.2`), we anyways usually lock on patches for Major that is 0, so locked on 0.3.x for now
* Noticed that `pytest-asyncio` was also mistakenly locking major only (`~=0.14`), fixed to `~=0.15.0`
> [Requirements] Bound google-auth to 1.x, and pytest-alembic to 0.3.x

- mlrun/projects/pipelines.py
- mlrun/projects/project.py
- mlrun/runtimes/base.py
- mlrun/runtimes/function.py
- mlrun/runtimes/serving.py
- tests/common_fixtures.py
- tests/runtimes/test_base.py
- tests/runtimes/test_function.py
If a user wishes to prevent auto-mount on a specific run or nuclio deployment, can now set the `disable_auto_mount` parameter. This parameter was added to:
* `BaseRuntime.run()` - for any runtime that is not a nuclio function (of course, auto-mount in general only has effect when the runtime is k8s-based)
* `RemoteRuntime.deploy()` and `ServingRuntime.deploy()` - for nuclio-based runtimes.
* `MLRunProject.run()` - for running a workflow.
In all cases the default for this parameter is `False`, executing auto-mount if needed.
> [Runtimes] Adding option to manually disable auto-mount on a specific run

- mlrun/api/api/endpoints/frontend_spec.py
- mlrun/api/crud/client_spec.py
- mlrun/api/schemas/client_spec.py
- mlrun/api/schemas/frontend_spec.py
- mlrun/config.py
- mlrun/db/httpdb.py
- mlrun/k8s_utils.py
- mlrun/runtimes/daskjob.py
- mlrun/runtimes/function.py
- mlrun/runtimes/mpijob/abstract.py
- mlrun/runtimes/mpijob/v1.py
- mlrun/runtimes/mpijob/v1alpha1.py
- mlrun/runtimes/pod.py
- mlrun/runtimes/remotesparkjob.py
- mlrun/runtimes/sparkjob.py
- mlrun/runtimes/utils.py
- tests/api/runtimes/base.py
- tests/api/runtimes/test_dask.py
- tests/api/runtimes/test_kubejob.py
- tests/api/runtimes/test_nuclio.py
- tests/runtimes/test_run.py
Config holds default priority class name and valid priority class names.
SDK Exposes:
1. `func.with_priority_class(name=<name>)` to apply priority to job
2. `func.list_valid_and_default_priority_class_names()` to receive available priority class name selections to user and the default selection.
> [Runtimes] Support pods priority

- mlrun/runtimes/function.py
- mlrun/runtimes/pod.py
Default argument values are evaluated only once per module load, Therefore mlconf.default_function_priority_class_name default argument will never be evaluated again and we always get an empty string.
The convention for achieving the desired result in Python is to provide a default value of None.
> [Runtimes] Fix `with_priority_class` default param

- mlrun/api/db/sqldb/db.py
- mlrun/api/db/sqldb/models.py
- tests/api/utils/test_scheduler.py
Fixes: https://jira.iguazeng.com/browse/ML-877
> [DB] Improve conflict error message

- mlrun/artifacts/model.py
- mlrun/builder.py
- mlrun/datastore/base.py
- mlrun/db/httpdb.py
- mlrun/projects/pipelines.py
- mlrun/run.py
- mlrun/runtimes/local.py
- mlrun/utils/clones.py
`tempfile.mktemp()` manifests a known vulnerability wrt race condition between setting the path and obtaining the file handle, which is sometimes worrying, and pops up in security scans even when used in a safe context - https://cwe.mitre.org/data/definitions/377
It is hence deemed deprecated and vulnerable: https://docs.python.org/3/library/tempfile.html#deprecated-functions-and-variables
The underlying issue here will still exist in some cases because the use case is valid - however, we will appease the scans
> [Refactor] Scrubbing mktemp calls (CVE)

- Makefile
- dockerfiles/test-system/Dockerfile
- mlrun/builder.py
- mlrun/datastore/base.py
* Horovod demo - another breakage from mktemp change - https://github.com/mlrun/mlrun/pull/1257
* Fixing system tests dockerfile to use make command - so not duplicating the pytest command - allowing to easily make only specific tests to run
> [System Tests] More fixes

- mlrun/api/api/endpoints/feature_store.py
Lambda functions had wrong order of parameters in them - was `(name, project)` rather than `(project, name)`. Caused feature (and probably entity) lists to return empty. 
Fix for issue - https://jira.iguazeng.com/browse/ML-1075
> [Feature Store] Fix OPA verification for list features/entities

- mlrun/runtimes/pod.py
- tests/runtimes/test_base.py
Explode when an invalid auto-mount mode is provided. If it's missing, continue doing as before - using `auto` mode.
Also fixed test that was using an invalid mode (`v3io_cred` was used instead of `v3io_credentials`)
> [Runtimes] Explode when invalid auto-mount is configured

- mlrun/api/api/endpoints/feature_store.py
- mlrun/feature_store/common.py
- mlrun/feature_store/ingestion.py
When ingestion is executed through the API, set the proper labels on the task (and therefore on the run as well). 
Up until now both `owner` and `v3io_user` would be set to `pipelines` rather than the user that actually triggered the ingestion through the UI. Besides presentation issue, this may also result in wrong `output_path` if the `{{run.user}}` annotation is used within it.
> [Feature Store] Add owner to ingest api

- mlrun/config/dynamic.py
- mlrun/runtimes/pod.py
- split method to get valid priority class names and default priority class name to 2 different methods
- preserve order of valid priority class name received externally
> [Runtimes] Keep order in valid pod priority class names list, and rename methods

- tests/api/api/test_submit.py
Breakage caused by a test added in https://github.com/mlrun/mlrun/pull/1280 
the last commit in the PR didn't include yet https://github.com/mlrun/mlrun/pull/1301 so it didn't failed in CI
> [Tests] Fix `test_submit_job_auto_mount`

- dev-requirements.txt
- mlrun/runtimes/serving.py
- mlrun/serving/remote.py
- mlrun/serving/server.py
- mlrun/serving/states.py
- tests/api/runtimes/test_nuclio.py
- tests/api/runtimes/test_serving.py
- tests/serving/test_remote.py
* add parameters (path/method/headers/..) to remote steps, run async in async/story graphs
* support specify function uri ([project/]name) vs full http URL 
* support getting uri from the event using `url_expression`
* add checks for user errors, docs, and tests 
* fix child function init and add validation that the steps which follow after a queue must be in a child function
* disable model tracking in mock server by default (can still be set via a param)
example usage:
```python
flow = function.set_topology("flow")
flow.to(name="step1", handler="func1")\
.to(RemoteStep(name="remote_echo", url="https://myservice/path", method="POST"))\
.to(name="laststep", handler="func2").respond()
```
> [Serving] Fix and enhance remote graph steps

- .github/workflows/build.yaml
- .github/workflows/system-tests-enterprise.yml
- .github/workflows/system-tests-opensource.yml
- automation/system_test/prepare.py
1. (OS system tests) Minikube stopped working on the ubuntu we're using in GH actions, at first this helped - https://github.com/mlrun/mlrun/pull/1168 but then it stopped working, changing minikube, k8s and ubuntu versions following https://github.com/nuclio/nuclio/pull/2294
2. For some reason `git rev-parse --short` started generating hash of 8 characters while it used to generate length of 7 causing the tests to fail (cause images not found) - changed it to ask for 8 characters explicitly
3. Added some logging in case OS system tests helm install fails (as it used to) for easier debugging
4. Removed redundant re-configuration of auto mount type
> [CI] Fix periodic system tests

- mlrun/feature_store/ingestion.py
Partial fix for issue: https://jira.iguazeng.com/browse/ML-1095.
When performing feature-set ingest through the API, the function created was not saved to DB, since there was no DB connection in the function. Solving by copying the DB connection from the feature-set (whose DB connection is initialized in the API endpoint). This works for client-side flows as well, since it basically just copies the service API url from the feature-set.
> [Feature Store] Setting function db connection to enable saving in ingest API flow

- mlrun/runtimes/serving.py
- tests/serving/test_flow.py
this PR adds the ability to use add_model when the graph topology is a flow.
this also enable the proper use in KFP pipelines and with the CLI which use the add_model() method 
to update models in serving functions
> [Serving] Support fn.add_model() in flow topologies

- mlrun/api/api/endpoints/projects.py
- mlrun/api/crud/projects.py
- mlrun/api/db/base.py
- mlrun/api/db/filedb/db.py
- mlrun/api/db/sqldb/db.py
- mlrun/api/schemas/__init__.py
- mlrun/api/schemas/project.py
- mlrun/api/utils/clients/nuclio.py
- mlrun/api/utils/projects/follower.py
- mlrun/api/utils/projects/leader.py
- mlrun/api/utils/projects/member.py
- mlrun/api/utils/projects/remotes/follower.py
- mlrun/api/utils/projects/remotes/nop_follower.py
- mlrun/api/utils/scheduler.py
- mlrun/config.py
- tests/api/api/test_projects.py
- tests/api/utils/projects/test_follower_member.py
* Added schedules and running pipelines counters to the project summary
* Created dedicated endpoints (a follow up PR will remove the summary format):
1.  `list_project_summaries - GET /project-summaries`
2. `get_project_summary - GET /project-summaries/{name}`
* Changed default counters cache from 10 seconds to 2 minutes
> [API] Add schedules and pipelines counters to project summary & create project summary endpoints

- mlrun/api/crud/model_endpoints.py
* ML-1132: Click on the model monitoring scheduled job doesn't open the selected function
> [Model Monitoring] Scheduled job's function url is moved to `spec`

- requirements.txt
We got dependabot alert for using version lower than 0.65.2 (see https://github.com/tiangolo/fastapi/security/advisories/GHSA-8h2j-cgx8-6xv7)
> [Requirements] Bump fastapi to 0.68.x

- automation/package_test/test.py
- mlrun/api/utils/auth/verifier.py
- tests/api/utils/test_scheduler.py
We started seeing this bug originating from https://github.com/mlrun/mlrun/pull/1361
```
File "/home/runner/work/mlrun/mlrun/tests/common_fixtures.py", line 13, in <module>
import mlrun.api.utils.singletons.project_member
File "/home/runner/work/mlrun/mlrun/mlrun/api/utils/singletons/project_member.py", line 1, in <module>
import mlrun.api.utils.projects.follower
File "/home/runner/work/mlrun/mlrun/mlrun/api/utils/projects/follower.py", line 9, in <module>
import mlrun.api.utils.auth.verifier
File "/home/runner/work/mlrun/mlrun/mlrun/api/utils/auth/verifier.py", line 8, in <module>
import mlrun.api.api.utils
File "/home/runner/work/mlrun/mlrun/mlrun/api/api/utils.py", line 18, in <module>
from mlrun.api.utils.singletons.scheduler import get_scheduler
File …
```
> [System Tests] Fix import bug

- mlrun/api/api/endpoints/secrets.py
Validating that the project exists before doing anything else in secret APIs. This is required so we can properly return `404` if the project does not exist, rather than a permission-related error (or even success, if the user has permission on `*` projects).
> [API] Checking project existence in secret-related APIs

- .github/workflows/system-tests-opensource.yml
- dockerfiles/test-system/Dockerfile
This is not ideal - the system tests eventually are purposed to mock a real life usage, running in a user env, in which the API requirements **will not** be installed.
But our test files have a lot of imports of the API code, causing too often breakages in system tests because of missing dependencies
> [System Tests] Add API requirements

- mlrun/runtimes/function.py
- mlrun/runtimes/pod.py
- tests/api/conftest.py
- tests/api/runtimes/base.py
- tests/api/runtimes/test_kubejob.py
- tests/api/runtimes/test_nuclio.py
Closing an existing gap - when a nuclio (`remote` runtime) function is deployed, add project-secrets automatically as env variables.
Unlike other runtimes, since the nuclio function does not execute MLRun code, the env variables are added with the same name as the secret key, not adding special prefix/uppercasing. This way, if a project secret called `AWS_SECRET_ACCESS_KEY` is configured, then in the nuclio function itself it will be an env variable called `AWS_SECRET_ACCESS_KEY` - this way it's usable through `fsspec`, for example.
Implements https://jira.iguazeng.com/browse/ML-1109
> [Runtimes] Add project secrets to Nuclio functions

- mlrun/api/api/endpoints/schedules.py
- mlrun/api/api/utils.py
- mlrun/api/crud/secrets.py
- mlrun/api/schemas/__init__.py
- mlrun/api/schemas/auth.py
- mlrun/api/schemas/feature_store.py
- mlrun/api/schemas/schedule.py
- mlrun/api/utils/scheduler.py
- mlrun/config.py
- tests/api/crud/test_secrets.py
- tests/api/utils/test_scheduler.py
- tests/system/projects/test_project.py
The previous handling was using the `auth_info.session` which is not good since the session will expire
Now we're using the new `auth_info.access_key`, we're supporting auto-generating it, allowing to get it back in get & list schedules and more
> [Scheduler] Fix secrets handling

- mlrun/api/initial_data.py
- mlrun/api/utils/db/alembic.py
- tests/api/utils/test_alembic_util.py
Only backup database if data/schema migration is needed.
*Database migration doesn't require backup as it is non-destructive to the old sqlite db
> [DB] Only backup database if data/schema migration is needed

- mlrun/feature_store/feature_vector.py
- mlrun/runtimes/serving.py
- mlrun/serving/remote.py
- mlrun/serving/routers.py
- mlrun/serving/server.py
- mlrun/serving/states.py
- mlrun/serving/utils.py
- mlrun/serving/v2_serving.py
- tests/serving/test_flow.py
- tests/serving/test_remote.py
- tests/serving/test_serving.py
* fix impute policy (values where reset after to_mock_server())
* fix model serving in multi-function graph (init the model `function` attribute)
* pass event id/path to the next functions via headers
* do not register model endpoint when running mock (unless set_tracking=True in `to_mock_server`)
* add the parallel remote step class to mlrun (`BatchHttpRequests`)
* `V2ModelServer` classes can now work without a router (the path should be without the router prefix e.g. `/infer`)
* auto serialization of graph steps to dict (models, routers, remote, ..) allow using the class in the `.to` and `.add_step`
> [Serving] Bug fixes and enhancements to Serving/Graph

- mlrun/feature_store/feature_set.py
- tests/system/feature_store/test_feature_store.py
can now use `stocks_set = fs.FeatureSet(name, entities=["ticker"])`
instead of `stocks_set = fs.FeatureSet(name, entities=[Entity("ticker")])`
> [Feature Store] Support passing FeatureSet entities as strings

- mlrun/execution.py
`handler` was missing in the job run json/yaml, so `re-run` cannot work, this PR adds the handler to the job spec section
> [Runtimes] Fix `MLClientCtx` to persist the job handler

- mlrun/projects/project.py
ignote cases where active_branch is not set (e.g. Gitlab CI)
> [Projects] Ignore bad `active_branch` in load project (fix gitlab ci)

- dev-requirements.txt
- dockerfiles/jupyter/requirements.txt
- dockerfiles/mlrun/requirements.txt
- dockerfiles/test-system/requirements.txt
- tests/test_requirements.py
We've seen CI fail in `test_run_mlbase_sklearn_classification` with this bug - https://github.com/scikit-optimize/scikit-optimize/issues/981
Bumping scikit learn should solve it
> [Requirements] Bump scikit-learn to 1.x

- .gitignore
* `venv` to `*venv*` allowing to have multiple virtual environments (I usually go with `venv-X` (e.g. `venv-py36`) that way it's near the venv in the file list)
* Added `.python-version` which is a file pyenv create when you change the python version locally for the project
> [General] Improve git ignore

- mlrun/api/api/endpoints/functions.py
- mlrun/api/crud/model_endpoints.py
- mlrun/api/crud/secrets.py
- mlrun/runtimes/pod.py
- tests/api/conftest.py
- tests/api/runtimes/test_kubejob.py
Fix the following behaviors w.r.t secret management:
1. Auto-adding of project secrets used to retrieve the secrets directly from the k8s provider, and would retrieve internal secrets, such as the secrets added by scheduled tasks. Those secrets are created with the format `mlrun.schedules.<job name>.access_key` and would be attached to all jobs from the project. With this fix, internal secrets are no longer automatically added, even if the user specifically added them in a secret source through `with_secrets()`.
2. Model monitoring user-access-key is modified as follows:
2.1. If user didn't provide an access-key using `project.set_model_monitoring_credentials()`, then project-owner's access-key is retrieved and used for this purpose
2.2. If the user added an access-key through the …
> [Secrets] Avoid auto-adding internal project secrets + model monitoring access-key changes

- mlrun/datastore/sources.py
- mlrun/feature_store/steps.py
- mlrun/serving/remote.py
- mlrun/serving/server.py
- mlrun/serving/states.py
- requirements.txt
- tests/serving/test_flow.py
- tests/serving/test_remote.py
* add configurable timeout support to `RemoteStep` and `BatchHttpRequests`
* add retries and exponential backoff support to `RemoteStep` and `BatchHttpRequests`
* support setting Storey source arguments via serving spec params["source_args"]
* change function endpoint default to external (ingress) IP
> [Serving] Handle timeouts and retries in remote step

- Makefile
Our Jenkins uses image similar to the alpine image in which `sed --version` gives:
`This is not GNU sed version 4.0` which fails when executing `echo "0.9.0-rc1" | sed 's/\+/\-/g'` on
`sed: bad regex '\+': Repetition not preceded by valid expression`
adding `-E` forces it to use the extended regex which makes it to work
> [Makefile] Force sed to use extended regex

- mlrun/datastore/google_cloud_storage.py
When working with GCP, users may use workload-identity (https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity) for authentication. In that case the `GOOGLE_APPLICATION_CREDENTIALS` environment variable will not be set, as auto-discovery will work with the GCP metadata server to inject the identity to the GCP API calls.
To enable working this way, removed the exception raised if this env variable is not set. If the user is not in a context that supports auto-discovery, the calls to access storage will fail due to no authentication, which is fine.
> [Datastore] Enable no credentials for working with GCP workload identity

- mlrun/api/initial_data.py
- tests/api/test_initial_data.py
When initializing from scratch - the DB is empty - meaning `db.get_current_data_version` will fail on Table doesn't exist - with sqlite `sqlalchemy.exc.OperationalError` was raised, but with MySQL `sqlalchemy.exc.ProgrammingError` is raised - catching it as well
> [API] Fix MySQL initialization from scratch

- mlrun/runtimes/function.py
- tests/api/runtimes/test_nuclio.py
When the function's kind is `nuclio:mlrun` it runs MLRun code wrapped up by a nuclio function. To enable using `context.get_secret()` in such functions, the project-secrets environment variable names need to be formatted properly (with prefix etc.).
> [Runtimes] Properly handle project secrets for `nuclio:mlrun` kind

- mlrun/artifacts/base.py
- mlrun/artifacts/manager.py
- mlrun/execution.py
- mlrun/projects/project.py
- mlrun/run.py
- tests/artifacts/test_artifacts.py
- tests/common_fixtures.py
- tests/test_run.py
* fix use of local context (get_or_create_context() outside of a run()) with artifacts
* allow using the default artifact path with local context
* support using artifact_path="+/subpath" when logging artifacts (add subpath to default path)
* support get/update artifacts in the execution context (allow the auto logging framework to update model objects after the log)
> [Runtimes] Fix and enhance work with context and artifacts

- mlrun/api/api/endpoints/functions.py
- mlrun/api/api/utils.py
- mlrun/api/crud/secrets.py
- mlrun/runtimes/base.py
- mlrun/runtimes/function.py
- mlrun/runtimes/pod.py
- tests/api/api/test_submit.py
- tests/api/api/test_utils.py
- tests/api/conftest.py
- tests/api/runtimes/test_nuclio.py
- tests/api/runtimes/test_serving.py
- tests/api/utils/test_scheduler.py
Up until now there was no mechanism to limit the service account that a user can set on a function (using `function.spec.service_account = '<something>'`. This is a potential security issue, for example if users are utilizing Google workload identity that maps service accounts to Google service accounts.
This PR adds the following mechanism to limit the service accounts:
Use 2 internal project secrets (per project):
* `mlrun.service-accounts.allowed` - a list of allowed service accounts, separated by `,`. For example - `sa1, sa2, sa3`
* `mlrun.service-accounts.default` - a default service account per project. This will be automatically assigned to every function deployed from that function, unless the user manually set a different SA
The logic is as follows:
1. If the allowed SAs list is …
> [Runtimes] Limit function's service accounts based on project configuration

- mlrun/api/api/endpoints/secrets.py
- mlrun/db/base.py
- mlrun/db/filedb.py
- mlrun/db/httpdb.py
- mlrun/db/sqldb.py
Set the k8s provider to be the default parameter in all secret-related calls (other than `create_user_secrets` which is only implemented for Vault).
> [Secrets] Make k8s provider the default secrets provider in httpdb and API calls

- mlrun/db/base.py
- mlrun/db/filedb.py
- mlrun/db/httpdb.py
- mlrun/db/sqldb.py
- tests/integration/sdk_api/artifacts/test_artifacts.py
- tests/rundb/test_httpdb.py
Add the option to pass `kind` and `category` filters to the `list_artifacts` API in httpdb. This was already supported in the REST API.
> [API] Support artifact list filtering by kind & category in httpdb

- mlrun/runtimes/function.py
- mlrun/runtimes/nuclio.py
- mlrun/runtimes/pod.py
- tests/api/runtimes/test_nuclio.py
The change introduced at PR #1499 was based on using the `spec.function_kind` to distinguish between `nuclio` and `nuclio:mlrun` functions. However, this turned out to be wrong, as the `function_kind` is set to `mlrun` when calling `new_function` on nuclio functions, which is always done when deploying a nuclio function.
This fix uses a different approach:
* Project secrets in nuclio runtimes are always attached to the pod as env variables without any specific prefix (using just the secret key name)
* Another env variable is used to store the list of secrets that were attached (since there's no other way to distinguish between "regular" env variables and those originating from secrets)
* When initializing the MLRun context object for `nuclio:mlrun` functions, the secrets from the list are …
> [Secrets] Fix project secret injection for `nuclio` and `nuclio:mlrun` runtimes

- mlrun/utils/helpers.py
- tests/utils/test_helpers.py
When the MLRun version is being set to some free text and we're building an image (e.g. `MLRUN_VERSION=abcd make api`) the makefile will generate the `mlrun/mlrun-api:abcd` image, but the version of the code would be `0.0.0+abcd` because pip requires us to comply to it's version regex.
Therefore when we enrich the tag, if we see `0.0.0+` in the version, we should take that off
> [Utils] Fix tag enrichment

- docs/feature-store/transformations.md
- mlrun/datastore/utils.py
Added support for ingestion with spark for 's3://'.
Fixes the issue of get_offline - [ML-1047](https://jira.iguazeng.com/browse/ML-1047)
*** Also support of s3:/// was removed.
> [Feature Store] Fix inconsistency of s3 paths

- mlrun/db/httpdb.py
https://github.com/mlrun/mlrun/pull/1524 Changed from `get_background_task` to `get_project_background_task` but not in the `httpdb.py` itself
Fixes https://jira.iguazeng.com/browse/ML-1490
> [Dask] Fix get background task call

- requirements.txt
- tests/test_requirements.py
From the moment storey 0.8.12 published our `CI / Run package tests` step started failing
The failure can be reproduced very easily by `pip install .` of mlrun (note to have the right pip installed - `python -m pip install --upgrade pip~=21.2.0`)
What happens is that pip resolver just tries finding a resolution forever, therefore I assume this is the root cause https://github.com/mlrun/storey/pull/314 - probably requirements are now too loose
> [Requirements] Limit storey to <0.8.12

- Makefile
- mlrun/api/db/sqldb/db.py
- tests/integration/sdk_api/run/test_run.py
We started getting this when calling the function:
```
sqlalchemy.exc.IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(pymysql.err.IntegrityError) (1062, "Duplicate entry 'v3io_user-115' for key '_runs_labels_uc'")
[SQL: INSERT INTO runs_labels (name, value, parent) VALUES (%(name)s, %(value)s, %(parent)s)]
```
It's happening because we were creating new label objects instead of using the existing ones
Fixes: https://jira.iguazeng.com/browse/ML-1492
> [DB] Fix labels setting in `update_run`

- mlrun/api/crud/model_endpoints.py
- mlrun/api/crud/projects.py
- tests/api/api/test_projects.py
- tests/api/utils/projects/test_follower_member.py
When deleting a project with `restricted` mode, existence of project secrets did not fail the deletion as expected. Adding this verification.
The same issue existed for model-endpoints, added verification for that as well.
Fixes https://jira.iguazeng.com/browse/ML-1503
> [Secrets] Verify project secrets do not exist when deleting a project

- requirements.txt
* 0.8.16 fixes an important bug.
* 0.9.0 is a minor version bump to match mlrun version.
> [Requirements] Bump storey version to 0.9.0

- docs/feature-store/transformations.md
From slack chat on #feature_store
rotem naimark:headphones:  1:24 PM
feature store documentation code has an issue in https://docs.mlrun.org/en/latest/feature-store/transformations.html#using-spark-execution-engine
fstore run config is set and right afterwards is created new empty one
config = fstore.RunConfig(local=False, function=my_func, handler="ingest_handler")
fstore.ingest(feature_set, source, run_config=fstore.RunConfig(), spark_context=spark_service_name)
docs.mlrun.orgdocs.mlrun.org
Feature set transformations
Feature set transformations A feature set contains an execution graph of operations that are performed when data is ingested, or when simulating data flow for
adih  2:23 PM
@Jason Novich can you fix it?
it should be run_config=config
> [Docs] Fix feature store transformation doc

- mlrun/api/db/sqldb/session.py
- mlrun/config.py
We've hit 
```
> 2021-12-07 22:15:43,608 [error] Traceback (most recent call last):
File "/mlrun/mlrun/api/api/endpoints/functions.py", line 425, in _build_function
fn.save(versioned=False)
File "/mlrun/mlrun/runtimes/base.py", line 932, in save
obj, self.metadata.name, self.metadata.project, tag, versioned
File "/mlrun/mlrun/db/sqldb.py", line 221, in store_function
versioned,
File "/mlrun/mlrun/db/sqldb.py", line 308, in _transform_db_error
return func(*args, **kwargs)
File "/mlrun/mlrun/api/crud/functions.py", line 26, in store_function
db_session, function, name, project, tag, versioned,
File "/mlrun/mlrun/api/db/sqldb/db.py", line 461, in store_function
fn = self._get_class_instance_by_uid(session, Function, name, project, uid)
File "/mlrun/mlrun/api/db/sqldb/db.py", line 2025, in …
```
> [DB] Make connection pool size and max overflow configurable and raise numbers

- tests/integration/sdk_api/base.py
- tests/integration/sdk_api/httpdb/test_exception_handling.py
Also fix the integration tests base class to remove the containers it creates also when tests fail
> [Integration Tests] Fix httpdb exception handling regex

- .github/workflows/release.yaml
- automation/scripts/pypi_release_waiter.sh
The `released_versions` there looks something like `0.5.0,0.5.1,0.5.1rc1,0.5.1rc2,0.5.2`... 
So conditioning it on equality with `*"$version"*` was making 0.5.1 to match with 0.5.1rc1 as well
Fixed it to `*,"$version",*`
> [Automation] Fix the pypi release waiter script

- .github/workflows/ci.yaml
- Makefile
- tests/api/api/test_docs.py
https://jira.iguazeng.com/browse/ML-1274
A few tools have been examined:
1. https://github.com/OpenAPITools/openapi-diff
2. https://github.com/Tufin/oasdiff
3. https://www.npmjs.com/package/openapi-diff
Since we are currently using 3.0.1 of OpenApi with FastApi, there are a few differences in the capabilities that JSON schema provides that are only available in the 3.1.0 version of OpenApi.
That is further explained at https://github.com/tiangolo/fastapi/issues/240#issuecomment-638992109.
These distinctions have an impact on the usability of `oasdiff` and `npm/openapi-diff`.
Currently, `openapi-diff` is the only one capable of handling the aforementioned differences.
Important Notes
- I was impressed by the tool’s explainability capabilities after resolving the OpenApi and JsonSchema …
> [CI] Add step that runs backward compatibility tests on PRs

- .github/workflows/ci.yaml
- Makefile
- tests/api/api/test_docs.py
When executing docker run using the makeFile, the $(PWD) variable is not being defined at the container runtime, to use the current working directory anyway the alternative is to use $(shell pwd).
This topic is being discussed in the following links :
- https://jerome-wang.github.io/2015/08/13/pwd-in-sudo-make/
- https://stackoverflow.com/questions/15050748/what-value-does-shell-pwd-give
Also:
* Caching was not working for the migrations CI job because of configuration in the wrong place - fixed that
* Added log to the openapi test
> [CI] Refactor use of pwd in Makefile + fixes

- mlrun/api/db/sqldb/db.py
- tests/api/db/test_runs.py
- tests/rundb/test_httpdb.py
Fixes: https://jira.iguazeng.com/browse/ML-145
When storing run the logic was that on creation the start time column is either coming from the body or `datetime.now()` (by that precedence), and on update, nothing happens with it.
When running a job the first the triggering client is storing the run, it's the first store, so it's creation, no start time is in the body, therefore the time is just now. but then, when the job starting, on the `MLClientCtx` initialization, the start time is being set to now, and then when the job is finishing, the context store the run again, this time causing an update, but now the column doesn't change, while the body is being changed to have a different time (it takes some time for the pod to come up and actually start running the code)
So bottomline the …
> [DB] Align run `start_time` column and body field

- mlrun/execution.py
- tests/system/runtimes/assets/function_with_params.py
- tests/system/runtimes/test_kubejob.py
Added a convenience function `context.get_project_param()` which gets a parameter from the parent project parameters. This was possible before by loading the project from the MLRun DB, this function simplifies the process. It loads the project object on first activation, so further calls will utilize the same object.
> [Execution] Add utility function to get project parameter from context

- mlrun/frameworks/_ml_common/mlrun_interface.py
- mlrun/frameworks/lgbm/__init__.py
- mlrun/frameworks/sklearn/__init__.py
- mlrun/frameworks/xgboost/__init__.py
Exposed the `tag` attribute for logging a model in the `apply_mlrun` of all the ML frameworks: SKLearn, XGBoost and LGBM.
> [Frameworks] Add the `tag` attribute to the ml frameworks

- mlrun/api/crud/artifacts.py
- tests/api/api/test_artifacts.py
- tests/integration/sdk_api/artifacts/test_artifacts.py
https://jira.iguazeng.com/browse/ML-1322
> [API] Fix artifact storing without project in body

- mlrun/projects/operations.py
- mlrun/projects/pipelines.py
- mlrun/projects/project.py
- mlrun/runtimes/base.py
- tests/projects/test_project.py
- tests/system/projects/assets/newflow.py
* support setting `project.spec.default_requirements` with list/path to python requirements (will be added to all project functions)
* support `requirements` in set_function: `project.set_function("my.py", "f1", requirements=["pandas"])`
* support passing `hub://xx` url to run/build/deploy_function() methods (no need to import first)
> [Projects] Support setting requirements in project & functions and accept hub urls in project ops

- automation/system_test/prepare.py
Config map values have to be strings (bug from https://github.com/mlrun/mlrun/pull/1620), plus, changing the command runner methods to raise after capturing the stdout and stderr to fix a logging issue
> [Automation] Fix system test prepare script API configuration

- mlrun/feature_store/api.py
- mlrun/utils/helpers.py
- tests/system/feature_store/test_feature_store.py
- tests/utils/test_helpers.py
start_time and end_time attrs in get_offline_features() accept time strings (e.g. "2021/1/1 9:34") or relative time strings ("now", "now - 1d1h", "now + 2m") in addition to pd.Timestamp objects
> [Feature Store] Support fixed/relative time string ranges in `get_offline_features()`

- mlrun/feature_store/steps.py
- mlrun/serving/remote.py
- mlrun/serving/server.py
- tests/feature-store/test_steps.py
* set event time (default to now) in MockEvents 
* fix failue in RemoteStep when event.id is missing
* add `SetEventMetadata` step class to set event metadata from event body fields
> [Serving] Set proper event metadata defaults, add step for setting metadata from body

- Makefile
- mlrun/config.py
- mlrun/projects/pipelines.py
- mlrun/projects/project.py
- tests/projects/assets/localpipe.py
- tests/projects/test_local_pipeline.py
- tests/system/projects/test_project.py
When running a workflow through `project.run()`, impose the following on the artifact path:
* If the user provided the `artifact_path` in the `project.run()` call, do nothing (use the artifact path the user provided)
* if the artifact path already contains `{{workflow.uid}}` in it, do nothing
* else, add `/{{workflow.uid}}` to the artifact path
Added a config parameter (`enrich_artifact_path_with_workflow_id`) to control this - if set to `False` don't do anything. Default is `True`.
Also fixed the implementation of `_LocalRunner` to replace `{{workflow.uid}}` with the workflow id - up until now running local pipelines would not do this replacement (probably assumed this is done elsewhere, but in remote workflows the `KFP` implementation would take care of that, not MLRun, so it was not …
> [Workflows] Automatically add `{{workflow.uid}}` to artifact path when running workflows

- mlrun/model.py
- mlrun/projects/operations.py
- mlrun/projects/pipelines.py
- mlrun/projects/project.py
- mlrun/run.py
- mlrun/runtimes/base.py
- mlrun/runtimes/daskjob.py
- mlrun/runtimes/kubejob.py
- mlrun/runtimes/remotesparkjob.py
- tests/system/projects/assets/sentiment.py
- tests/system/projects/test_project.py
* fix project.build_function(), was broken
* do not copy function object in enrichment when its user provided objects (fixes scenario when you use fn.run() after build_function(), it does not use the updated object with the build status/image and will fail)
* when the function require a build we treat the user provided `image` name as the build `base_image`
* add `with_mlrun` to the build spec and try to auto determine if to add `mlrun` package, eliminate the need to specify it on build/deploy
* add `auto_build` option to the build spec, if set and a build is required the function will build the image on the first `.run()`
> [Projects] Fix and simplify function enrichment and build flow

- dockerfiles/mlrun-api/Dockerfile
- mlrun/api/initial_data.py
- mlrun/api/utils/db/alembic.py
- mlrun/api/utils/db/backup.py
- mlrun/api/utils/db/mysql.py
- mlrun/config.py
- tests/api/test_api_states.py
- tests/api/utils/test_alembic_util.py
- tests/api/utils/test_db_backup.py
- Move backup logic out of alembic util
- Fix mysql backup
- No automatic load from backup
- Backup condition is now: data/schema migration is needed, not from scratch and database migration is not needed.
For loading MySQL from backup:
Either exec into the mlrun pod and run:
```
mysql -h mlrun-db -P 3306 -u root mlrun < DB_BACKUP_FILE_PATH
```
Or exec into the db pod and run
```
mysql -S /var/run/mysqld/mysql.sock mlrun < DB_BACKUP_FILE_PATH
```
Fixes: https://jira.iguazeng.com/browse/ML-1652
> [DB] Improve backup logic

- dockerfiles/models-gpu/Dockerfile
Continuing https://github.com/mlrun/mlrun/pull/1603 we need to bump CUDA as well according to https://www.tensorflow.org/install/source#gpu
Implements https://jira.iguazeng.com/browse/ML-1535
> [Images] Bump CUDA to 11.2.1 in `ml-models-gpu` image 

- mlrun/api/crud/pipelines.py
After we bumped kfp in https://github.com/mlrun/mlrun/pull/1439 we started getting this error when trying to create a pipeline:
```
2022-01-26 01:07:05,618 [warning] Failed creating pipeline: {'traceback': 'Traceback (most recent call last):
File "/mlrun/mlrun/api/crud/pipelines.py", line 145, in create_pipeline
experiment = kfp_client.create_experiment(name=experiment_name, namespace=namespace)
File "/usr/local/lib/python3.7/site-packages/kfp/_client.py", line 450, in create_experiment
experiment_name=name, namespace=namespace)
File "/usr/local/lib/python3.7/site-packages/kfp/_client.py", line 582, in get_experiment
resource_reference_key_id=namespace)
File "/usr/local/lib/python3.7/site-packages/kfp_server_api/api/experiment_service_api.py", line 567, in list_experiment
return …
```
> [API] Fix pipelines creation breakage

- mlrun/platforms/iguazio.py
- mlrun/serving/routers.py
- mlrun/serving/v2_serving.py
- tests/serving/test_tracking.py
* allow tracking of complex data types like `numpy.ndarray`  (previously failed on the json.dumps)
* allow control of which inputs/outputs values are tracked (using the model server `logged_results()` hook, see the doc string), this is useful for e.g. in deep learning models where you may want to log metrics of the in/out vector (e.g. RGB values) vs the full vector
* add tests for model tracking and v3io simulation
> [Model Monitoring] Support tracking of complex types + custom inputs/outputs

- mlrun/kfpops.py
- mlrun/runtimes/function.py
- mlrun/runtimes/serving.py
allow using/passing KFP PipelineParams (pipeline args or step outputs) to Nuclio/Serving function spec elements, e.g. in graph steps
> [Serving] Improve handling of KFP PipelineParams in nuclio/serving functions

- dockerfiles/README.md
- docs/cli.md
- docs/install.md
- hack/local/README.md
- hack/local/mljupy.yaml
- hack/local/mlrun-local.yaml
- hack/mlrun-all.yaml
- hack/mlrunapi.yaml
- hack/mlrunui.yaml
Backport https://github.com/mlrun/mlrun/pull/1695
> [Docs] Bump docs docker tag to 0.9.3 [Backport 0.9.x]

- mlrun/api/api/endpoints/functions.py
- mlrun/runtimes/function.py
Two fixes to the build status API:
1. When a tag is passed to the API and it is `latest`, the nuclio function was not found. This is due to the fact that the UI explicitly passes the tag as `latest`, while most of the flows for building functions do not pass a tag at all, and the `latest` tag is implicitly added to the function when stored to the DB. To overcome this, the nuclio function name was modified to not take the tag into account if it is `latest`. If the user specifically asked for a tag (i.e. `v1` or something) the tag would still be accounted for.
2. If the API didn't get the `last_log_timestamp` parameter, it would use default of `0`, with the intention of providing all logs - for example, the MLRun UI does that. However, the nuclio `get_deploy_status` function uses this to …
> [Runtimes] Fixes in nuclio build status API

- mlrun/api/utils/db/backup.py
- tests/api/utils/test_db_backup.py
Added some flags to the `mysqldump` command:
- `--single-transaction` produces a checkpoint that allows the dump to capture all data prior to the checkpoint while receiving incoming changes. Those incoming changes do not become part of the dump. That ensures the same point-in-time for all tables.
- `--routines` dumps all stored procedures and stored functions.
- `--triggers` dumps all triggers for each table that has them.
> [DB] Safer MySQL Backup

- mlrun/__main__.py
- tests/conftest.py
- tests/projects/assets/handler.py
- tests/projects/test_project.py
mlrun cli run/build/deploy now support specify function name (-f name) and if it is not a db or .yaml path it will be looked up in the current path project.yaml spec, this can be combined with `mlrun project` command:
```python
mlrun project -n myproj -u "git://github.com/mlrun/project-demo.git" ./proj
cd proj
mlrun run -f data-prep -p x=5 -w
```
> [CLI] Run/deploy/build project function (from project.yaml)

- dockerfiles/jupyter/Dockerfile
- mlrun/db/httpdb.py
- mlrun/platforms/other.py
- tests/runtimes/test_base.py
In the mlrun-kit, in the getting started demo, we are running some function locally, meaning it was passing through `self.try_auto_mount_based_on_config()` from the runtimes base class, then, when we're running `function.apply(auto_mount())` it receives the same volume mount again, this time for a volume with a different name (`pvc` the default from the code) therefore ending up with two volume mounts on the same path which caused a failure creating the pod:
```
'volume_mounts': [{'mountPath': '/home/jovyan/data',
'name': 'shared-persistency'},
{'mountPath': '/home/jovyan/data',
'name': 'pvc'}],
...
'volumes': [{'name': 'shared-persistency',
'persistentVolumeClaim': {'claimName': 'mlrun-kit-shared-pvc'}},
{'name': 'pvc',
'persistentVolumeClaim': {'claimName': 'mlrun-kit-shared-pvc'}}]}
> …
```
> [Images] Remove Jupyter wrong pvc config

- mlrun/execution.py
- mlrun/projects/operations.py
Fix broken artifact URIs when using `run_function()` (due to None in workflow label)
> [Artifacts] Fix broken artifact URIs when using `run_function()` 

- .github/workflows/system-tests-enterprise.yml
- .github/workflows/system-tests-opensource.yml
- Makefile
As part of our CI workflows, for each merge to development, a Build workflow is set up to create images for that specific merge so that when the System tests run, they can pull the image versions that correspond to the current development.
Please keep in mind that our ghcr.io image repo is only for Open Source and Enterprise system tests, and it only contains versioned development images in the following format: "\<image-name>:\<latest-version>-\<merge-commit>", like : mlrun/mlrun:0.9.3-f65cf13e.
The MLRun kit started with the current development images(created in the Build workflow from ghcr.io) when we ran our Open source system tests, but the client running the tests was unversioned because the code it pulled was from the development branch.
As a result, the client version sent an …
> [System Tests] Set the client version to fix image enrichment

- mlrun/api/api/endpoints/frontend_spec.py
- mlrun/api/schemas/__init__.py
- mlrun/api/schemas/frontend_spec.py
- mlrun/config.py
- tests/api/api/test_frontend_spec.py
Define default_function_pod_resources scheme in frontend_spec for UI purposes.
Requirements :
https://jira.iguazeng.com/browse/ML-375
Part of :
- https://jira.iguazeng.com/browse/ML-374
- https://jira.iguazeng.com/browse/IG-18106
Next PR's will include the logic for the backend.
> [API] Add `default_function_pod_resources` to the frontend spec endpoint response

- mlrun/builder.py
- mlrun/config.py
- tests/test_builder.py
When building an image (using Kaniko) if we're using an insecure docker registry (for pulling from or pushing to) we need to add the appropriate flags (`--insecure-pull`/`--insecure` accordingly)
So far we were resolving whether to have those flags by whether a secret was provided or not (by setting `function.spec.build.secret` or `mlrun.mlconf.httpdb.builder.docker_registry_secret`)
There is no real connection between whether our registry is secured (http vs https) to whether it requires auth, in addition we might have different registries for pull and push and all/one/none of them might be insecure.
To enable controlling that I added two new values under the `mlrun.mlconf.httpdb.builder` config section:
* `insecure_pull_registry_mode`
* `insecure_push_registry_mode`
Both supports the …
> [Builder] Allow to configure whether push/pull registries are insecure

- .github/workflows/system-tests-enterprise.yml
- .github/workflows/system-tests-opensource.yml
- Makefile
- In Enterprise and Open source system tests changes the MLRUN_VERSION that is passed to test-system-dockerized from image_tag to mlrun_version.
- Added logic in Makefile that if MLRUN_VERSION is set to image tag version then when setting MLRUN_PYTHON_PACKAGE_VERSION we modify the version to be PEP 440 compatible which in other words replace the first occurrence of "-" to "+"
> [System Tests] Fix failing system tests as a result of none PEP 440 compatiblity 

- mlrun/api/api/endpoints/frontend_spec.py
- mlrun/api/schemas/frontend_spec.py
- mlrun/builder.py
- mlrun/config.py
- mlrun/runtimes/utils.py
- requirements.txt
- tests/api/api/test_frontend_spec.py
- tests/test_builder.py
Adding a new config value under the `mlconf.httpdb.builder` block - `function_target_image_name_prefix_template` which defaults to `func-{project}-{name}`
So far this default template was used when no target image was provided to generate the target image, from now on, in addition to that, if the target image is provided, and as long as it's targeted to the configured registry, we'll enforce the image name to have the configured prefix
To allow the UI to do the same verification added 2 new fields in the frontend spec response:
* `function_deployment_target_image_name_prefix_template` - which just sends the template (e.g. `some-prefix-{project}-{name}-suffix`)
* `function_deployment_target_image_registries_to_enforce_prefix` - which send the possible values for the registry prefix which …
> [Builder] Support configuring image name prefix template to enforce

- mlrun/api/api/endpoints/functions.py
- mlrun/builder.py
- mlrun/feature_store/common.py
- mlrun/projects/project.py
- mlrun/runtimes/base.py
- mlrun/runtimes/daskjob.py
- mlrun/runtimes/kubejob.py
- mlrun/runtimes/local.py
- mlrun/runtimes/remotesparkjob.py
- mlrun/runtimes/sparkjob/abstract.py
- tests/system/projects/test_project.py
generated function.spec.image (from build) got cleared when using function.save() due to mishandled exception, 
also turned is_deployed from property to a method in order to avoid accidental DB reads
> [Runtimes] Fix deletion of build image path after runs

- tests/system/feature_store/test_feature_store.py
- tests/system/feature_store/test_google_big_query.py
Currently google-cloud-bigquery is not installed as part of mlrun, also 'six' is not aligned with the dependencies of the related code. 
Once above issues will be fixed the tests can run as part of the system tests.
> [System Tests] Disable Google BigQuery tests

- mlrun/platforms/iguazio.py
- mlrun/runtimes/pod.py
- tests/platforms/test_iguazio.py
We had a bug where we were doing `function.apply(mlrun.mount_v3io())` twice on the same function with 2 different users and it caused k8s to return:
```
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Pod \\"some-pod-name\\" is invalid: spec.containers[0].volumeMounts[2].mountPath: Invalid value: \\"/User\\": must be unique","reason":"Invalid","details":{"name":"some-pod-name","kind":"Pod","causes":[{"reason":"FieldValueInvalid","message":"Invalid value: \\"/User\\": must be unique","field":"spec.containers[0].volumeMounts[2].mountPath"}]},"code":422}\n\n'}}
```
The problem is that we were identifying a volume mount by hashing all of its values together which allows us to have two different volume mount using the same mount path, I've changed the identifier …
> [Runtimes] Fix mount modifiers to keep mount path unique

- mlrun/builder.py
- mlrun/k8s_utils.py
- mlrun/kfpops.py
- mlrun/platforms/iguazio.py
- tests/test_builder.py
We noticed our Builder (Kaniko) and KFP pods are not getting the default function node selector when it's set, this PR fixes it
There's no workaround for the builder pod for previous versions
For KFP you can add this to your pipeline handler ([origin](https://github.com/kubeflow/pipelines/issues/2863)):
```
dsl.get_pipeline_conf().set_default_pod_node_selector(label_name="some-label", value="some-value")
```
Fixes https://jira.iguazeng.com/browse/ML-1800
> [Runtimes] Fix to enrich KFP and Kaniko pods with the default function node selector

- mlrun/config.py
- mlrun/kfpops.py
- tests/test_config.py
There was a bug in the installer component in the Iguazio system that ends up in configuring the values with `bnVsbA==` which is base64 of `null` which caused problems in places counting on the configuration to return a dict 
Add a condition to treat this value as empty
> [Config] Ignore null base64 string

- dev-requirements.txt
- mlrun/api/db/sqldb/db.py
- mlrun/config.py
- mlrun/errors.py
- mlrun/utils/helpers.py
- tests/api/api/test_functions.py
- tests/api/conftest.py
- tests/conftest.py
- tests/integration/sdk_api/httpdb/test_runs.py
- tests/utils/test_helpers.py
Most of our store_x functions starting from doing get, then if nothing is found creating the object otherwise updating attributes on the existing object. On the SQL level this translates to either INSERT or UPDATE queries.
Sometimes we have a race condition in which two requests do the get, find nothing, create a new object, but only the SQL query of the first one will succeed, the second will get a conflict error. 
Added a decorator that will retry on such scenario and applied it for all store_x methods in the DB class
In addition:
* Added support for async unit tests of the API (was needed to reproduce the race condition)
* Added 2 config values `.httpdb.db.conflict_retry_timeout` by default 15 (seconds), `.httpdb.db.conflict_retry_interval` by default None which will default to the …
> [DB] Add retry on conflict in store_x methods to prevent race condition

- mlrun/api/main.py
- mlrun/api/utils/auth/providers/opa.py
- mlrun/api/utils/clients/iguazio.py
- mlrun/api/utils/clients/nuclio.py
- mlrun/config.py
During some scale bug investigation I noticed a lot of logs like:
```
WARNI [urllib3.connectionpool] Connection pool is full, discarding connection: 127.0.0.1. Connection pool size: 10
```
This is not horrific, there's [no data loss](https://stackoverflow.com/questions/53765366/urllib3-connectionpool-connection-pool-is-full-discarding-connection) or something, but sounds like we better increase the pool size to be equal to our workers number
> [API] Increase http connection pools maxsize to be equal to number of workers

- mlrun/platforms/iguazio.py
Fixing issue with Iguazio version 3.2.3 - files' path was changed.
added a conditioned location based on the version.
fix for ticket - [ML-1878](https://jira.iguazeng.com/browse/ML-1878)
> [Platforms] Fix `mount_v3iod` for iguazio >=3.2.3

- mlrun/api/db/sqldb/db.py
- mlrun/api/initial_data.py
- tests/api/api/test_runs.py
- tests/api/db/test_runs.py
In a scale test we saw this error:
```
> 2022-03-09 12:38:06,465 [warning] Got conflict error from DB. Retrying: {'err': 'This Session\'s transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (pymysql.err.IntegrityError) (1062, "Duplicate entry \'aaaa-latest-fnc43\' for key \'functions_tags._functions_tags_uc\'")\n[SQL: INSERT INTO functions_tags (project, name, obj_id, obj_name) VALUES (%(project)s, %(name)s, %(obj_id)s, %(obj_name)s)]\n[parameters: {\'project\': \'aaaa\', \'name\': \'latest\', \'obj_id\': 72, \'obj_name\': \'fnc43\'}]\n(Background on this error at: https://sqlalche.me/e/14/gkpj) (Background on this error at: https://sqlalche.me/e/14/7s2a)'}
``` …
> [DB] Align all upserts to happen from helper method

- mlrun/api/api/endpoints/functions.py
- mlrun/api/api/utils.py
- mlrun/api/crud/__init__.py
- mlrun/api/crud/marketplace.py
- mlrun/api/crud/model_endpoints.py
- mlrun/api/crud/secrets.py
- mlrun/api/utils/scheduler.py
- mlrun/model_monitoring/helpers.py
- tests/api/api/marketplace/test_marketplace.py
- tests/api/conftest.py
- tests/api/crud/test_secrets.py
- tests/api/utils/test_scheduler.py
Make all the objects in the MLRun backend that utilize secrets go through the `Secrets` crud object. This PR changes the `marketplace` implementation (that keeps credentials in k8s secrets) to go through the `Secrets` object.
Also, to make this scalable across the board, change the implementation of the crud object such that it provides generic functionality and APIs, and also has a list of clients (in a new `enum`). Functions that were specific to a given client are removed, and the clients need to call the standard APIs while providing their client name.
**Note** It's important to note that this change is backwards compatible in terms of the secret names generated and the secret keys within. The caveat here is that for marketplace objects there is a difference in the key names …
> [Secrets] Change marketplace to use Secrets crud object + generalize it

- mlrun/api/schemas/schedule.py
v3.6.3 isn't available changed to 3.x
> [Docs] Fix `ScheduleCronTrigger` class docstring

- mlrun/api/api/deps.py
- mlrun/api/api/endpoints/operations.py
- mlrun/api/initial_data.py
- mlrun/api/main.py
- mlrun/api/utils/db/mysql.py
- mlrun/db/httpdb.py
- tests/api/test_api_states.py
- tests/integration/sdk_api/httpdb/test_operations.py
* Backup was happening before migrations were triggered - fixed that and added test
* Database migration was triggered before migrations were triggered - fixed that and added test
* Improved the logs in those flows
In addition (somewhat related):
* added an option to trigger migrations from the SDK by calling `get_run_db().trigger_migrations()`
* Enabled the `client-spec` endpoint to be called for the migration api states (so the above can happen)
Fixes https://jira.iguazeng.com/browse/ML-1933
> [DB] Fix backup and migrations not to happen before unwanted-ly

- docs/feature-store/feature-sets.md
When using pandas engine, ingestion errors out when column names includes spaces (" ") and periods (".")
> [Docs] Add limitation on column name for data ingestion with Pandas engine

- mlrun/feature_store/api.py
also returns the timestamp_key from the feature sets
> [Docs] Enhance `get_offline_features()`'s `with_indexes` docstring

- dockerfiles/jupyter/requirements.txt
- requirements.txt
We had a breakage in our integration tests root caused by a backwards incompatible change in jinja2
see - https://github.com/nuclio/nuclio-jupyter/pull/139 for more details.
> [Requirements] Bump nuclio-jupyter to 0.8.23 

- Makefile
- mlrun/feature_store/feature_set.py
- tests/system/feature_store/test_spark_engine.py
When using Spark as engine, can now ask for aggregations to happen in an emit-per-event mode (rather than emit-per-period as was done until now). This uses a different Spark query to perform the aggregations.
To use this, added back the `emit_policy` parameter to `add_aggregations` - if using `emit_policy=storey.EmitEveryEvent()` this will trigger the new mode when working with Spark. By default (as until now) no emit policy is passed, and `Spark` processing will work in the usual emit-per-period mode.
If working with storey, emit policy is currently not passed to the engine, until various emit policies are officially supported by storey.
Also fixed a small issue in Spark aggregates processing where not providing a `period` for the aggregations would cause the code to explode when trying …
> [Feature Store] Spark aggregations with support for emit-per-event

- mlrun/builder.py
- mlrun/config.py
- mlrun/k8s_utils.py
- tests/test_config.py
second part for kaniko assignment of attributes and resources
https://jira.iguazeng.com/browse/ML-1880
As part of adding the feature, I fixed a bug where when we read default function pod resources from env and not all of them are defined, we set the ones that aren't defined to be "" rather than None.
> [Builder] Pass default resource requests to kaniko pod

- mlrun/api/crud/client_spec.py
- mlrun/api/schemas/__init__.py
- mlrun/api/schemas/client_spec.py
- mlrun/api/schemas/function.py
- mlrun/api/schemas/k8s.py
- mlrun/config.py
- mlrun/db/httpdb.py
- mlrun/k8s_utils.py
- mlrun/runtimes/base.py
- mlrun/runtimes/pod.py
- tests/api/api/test_client_spec.py
- tests/api/runtimes/base.py
- tests/api/runtimes/test_kubejob.py
- tests/runtimes/test_run.py
- tests/test_config.py
Introducing new SDK API : `function.with_preemptible_mode(mode=(allow|constrain|prevent))`
With the new feature, users can specify how their function should run if and when preemptible nodes are present in the cluster.
Preemptible/Spot instances doesn't guarantee stability but they are mostly available at up to a 90% discount compared to On-Demand prices. You can use Spot Instances for various stateless, fault-tolerant or flexible applications such as big data, containerized workloads, CI/CD and etc.
We support 3 preemptible modes:
- **allow** : allows function pods to run on preemptible nodes (e.g., could be used for training jobs that uses checkpoints and are fault tolerant in case node fails).
- **constrain** : allow functions to run only on preemptible nodes (e.g., could be used for …
> [Runtimes] Add preemption mode support

- mlrun/builder.py
- mlrun/config.py
- tests/test_builder.py
- tests/test_config.py
When assigning default resource requests to Kaniko pods, pods could not be scheduled as a result of mentioning `nvidia.com/gpu` in the requests body despite the fact that it contained no value. This was due to the k8s scheduler's requirement that no GPU requests be specified unless GPU limits were defined. More details can be found at https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/.
> [Builder] Fix resources assignment to Kaniko pods

- mlrun/data_types/spark.py
When ingesting a feature-set using Spark engine, by default the code produces a preview (20 first rows of the data-frame) and histogram (calculated over all the DF) for int & float columns. The existing code was naive in its approach to these calculations, basically running a `select` on the DF for each column, which may result in tens of queries for the calculations.
This poses no issue when the DF is a basic tabular DF, and would complete in negligible time. However, when adding aggregations, these queries are done on the query that calculates the aggregations, which contains summaries and group-by expressions. Running these queries so many times would accumulate to very long execution times.
This PR reduces the amount of queries performed in both of these stages. It uses a single query …
> [Feature Store] Performance improvements for preview and hist calculation in Spark engine

- automation/requirements.txt
- requirements.txt
- tests/test_requirements.py
Version 8.1.0 of click removed a function that dask used.
For now we will pin the click version.
You can find more information here : https://github.com/dask/distributed/pull/6018
> [Requirements] Limit click versions to 8.0.x

- mlrun/data_types/spark.py
- tests/system/feature_store/test_spark_engine.py
When running Spark aggregations with multiple windows on Spark version < 3.1, the code fails. This is since the code uses `unionByName` with the `allowMissingColumns=True` parameter which was added in Spark 3.1. This PR changes the test to use a single window, which doesn't call `unionByName`, since some system-tests were running on old systems with old Spark version, and the tests failed.
> [System Tests] Change Spark tests to use a single window

- .github/workflows/system-tests-enterprise.yml
It seems like our tests became longer than 120 minutes which is our current timeout
> [System Tests] Increase enterprise tests timeout to 180 minutes

- tests/system/feature_store/test_feature_store.py
The test currently fails with
```
KeyError: 'ticker'
```
because an entity is not a feature.
> [System Tests] Fix `test_ingest_and_query`

- mlrun/api/api/endpoints/frontend_spec.py
- mlrun/api/schemas/__init__.py
- mlrun/api/schemas/frontend_spec.py
- mlrun/config.py
- mlrun/runtimes/pod.py
- tests/api/api/test_frontend_spec.py
https://jira.iguazeng.com/browse/ML-1942
UI requirement - https://jira.iguazeng.com/browse/ML-1754
> [API] Add preemption nodes info to frontend spec

- mlrun/feature_store/api.py
- tests/system/feature_store/test_feature_store.py
Fixed issue when calling get_offline_features with target to save results. 
Created a default run_id for that case - "offline-features"
[ML-1980](https://jira.iguazeng.com/browse/ML-1980)
> [Feature Store] Fix run id for get offline features with target

- mlrun/config.py
Until https://github.com/mlrun/mlrun/pull/1831 the default from config wasn't really used
We want to use 3.7 as our default but that require changes, reverting to 3.6 for now
> [Nuclio] Revert default nuclio runtime to python 3.6

- mlrun/runtimes/pod.py
- mlrun/runtimes/sparkjob/spark3job.py
https://jira.iguazeng.com/browse/ML-1942
This PR focuses on adding support for the spark operator as part of providing support for all runtimes supported by mlrun. It is split from part 2 because the way the user interacts with the preemptible mode in the spark operator is different.
I am happy to announce that the spark operator now supports affinity for both executor and driver.
And to introduce two new SDK API :
* `function.with_driver_preemption_mode()`
* `function.with_executor_preemption_mode()`
Part 1 - https://github.com/mlrun/mlrun/pull/1844
Part 2 - https://github.com/mlrun/mlrun/pull/1868
> [Runtimes] Add support for preemption mode in spark operator

- mlrun/api/db/sqldb/session.py
- mlrun/config.py
Fixes https://jira.iguazeng.com/browse/ML-1860
> [DB] Set the default pool size and max overflow to be equal to the API max workers

- mlrun/runtimes/daskjob.py
- tests/api/runtime_handlers/base.py
- tests/api/runtime_handlers/test_daskjob.py
We had some scenario happened in field (not sure what was the background) in which there were no services and it caused `build_output_from_runtime_resources` to explode when given the group by project list (happening in the crud logic), added a test and fixed, in addition added a `test_list_resources_grouped_by` that was missing for Dask
This was the stack trace:
```
File "/usr/local/lib/python3.7/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
File "/usr/local/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
return await self.app(scope, receive, send)
File "/usr/local/lib/python3.7/site-packages/fastapi/applications.py", line 199, in …
```
> [API] Fix dask list runtime resources with cluster without Kubernetes service

- mlrun/data_types/spark.py
In some cases (empty DF may cause this) when running with the Spark engine, the `summary()` calculation on the DF would not return `min` and `max` values for numeric fields. This caused the histogram calculation to explode. Fix this by verifying that the stats exist per column prior to running histogram calculation on it - if they don't exist then histogram will not be calculated for this field.
> [Feature Store] Fix issue of histogram calculation for spark failing on empty DFs

- mlrun/datastore/targets.py
- mlrun/feature_store/feature_set.py
- mlrun/model.py
- tests/system/feature_store/test_feature_store.py
Removed get_target_path from DataTargetBase - caused issues with single file targets.
Fix issue with CSV paths
get_target_path can return online in case name is passed as param
Added tests
Fix for issues:
[ML-1961](https://jira.iguazeng.com/browse/ML-1961)
[ML-1983](https://jira.iguazeng.com/browse/ML-1983)
> [Feature Store] Fix issues with CSV targets and run_id

- mlrun/config.py
- mlrun/k8s_utils.py
Nuclio (mistakenly) apply a "Max length between two periods: 63" validation rule on secret names, it was fixed already, but in order to be compatible with older Nuclio versions we want to comply to this rule, therefore using dots (`.`) as separators in the template, and switching to sha224 which generated 56 characters hash (instead of 64 for sha256)
Related to: https://jira.iguazeng.com/browse/ML-1585
> [API] Fix auth secret name template to comply to Nuclio rules

- mlrun/config.py
- mlrun/datastore/targets.py
- mlrun/feature_store/api.py
- mlrun/model.py
- tests/feature-store/test_model.py
- tests/system/feature_store/test_feature_store.py
Target is now working with or without run_id. In feature store flows run_id is generated and in case it isn't provided in path it is added.
Removed run_id place holder from the default path.
*** Few important notes:
in order to use csv target as a single file - enter path with '[filename].csv' at the end of the path
in case csv path is ending with anything other then .csv it will handle it as a path and the output filename will be the 'run_id' generated for that run
> [Feature Store] Remake run id feature store's only

- mlrun/kfpops.py
- mlrun/projects/pipelines.py
- tests/common_fixtures.py
- tests/projects/assets/remote_pipeline.py
- tests/projects/base_pipeline.py
- tests/projects/test_local_pipeline.py
- tests/projects/test_remote_pipeline.py
As part of adding the tests I came across a bug in which when running `project.save_workflow` for workflow of kind KFP it thought I was in local context because the pipeline context hasn't been set. I have added `pipeline_context.set()` into the `save` method of `_KFPRunner` which solved the issue.
> [KFP] Add tests for pipelines monkey patching and set pipeline context in `save_workflow`

- mlrun/api/schemas/function.py
- mlrun/runtimes/function.py
- mlrun/runtimes/pod.py
- mlrun/runtimes/sparkjob/spark3job.py
- tests/api/runtimes/base.py
- tests/api/runtimes/test_kubejob.py
- tests/api/runtimes/test_nuclio.py
none preemption mode allow users to define that no preemption enrichment will apply on functions.
Changed nuclio minimum required version for preemption mode support after this fix - https://github.com/nuclio/nuclio/pull/2541 which released in https://github.com/nuclio/nuclio/releases/tag/1.8.6
> [Runtimes] Add `none` preemption mode

- mlrun/runtimes/pod.py
- mlrun/runtimes/sparkjob/spark3job.py
- tests/api/runtimes/base.py
- tests/api/runtimes/test_dask.py
- tests/api/runtimes/test_spark.py
* Add `driver_volume_mounts` and `executor_volume_mounts` field to the Spark3JobSpec to enable different volume mounts
* Expose new `with_executor_host_path_volume` and `with_driver_host_path_volume`
* Add test infrastructure for spark runtime
Implements: https://jira.iguazeng.com/browse/ML-1344
> [Spark] Support setting different volume mounts for driver and executor and add helper for host path

- mlrun/api/api/endpoints/runs.py
- mlrun/api/crud/runs.py
- mlrun/api/db/base.py
- mlrun/api/db/filedb/db.py
- mlrun/api/db/sqldb/db.py
- mlrun/db/base.py
- mlrun/db/filedb.py
- mlrun/db/httpdb.py
- mlrun/db/sqldb.py
- tests/api/api/test_runs.py
- tests/integration/sdk_api/httpdb/test_runs.py
The list runs API supports partitioning over run name, but there was no good way to limit the number of runs returned while maintaining the internal number of rows per partition. Specifically, if we want to list the first 5 runs (per name) and for each show the 5 last executions, there was no way to do so. 
This PR adds the `max-partitions` parameter to the API which allows to determine how many partitions (== run names) to return. These will be ordered by the name of the run in ascending order. The new parameter is of course optional, and by default equals 0 which means no filtering.
This is the backend part of the fix needed for https://jira.iguazeng.com/browse/ML-2114.
> [API] Add `max-partitions` parameter to list runs endpoint

- tests/projects/assets/remote_pipeline_with_overridden_resources.py
- tests/projects/test_remote_pipeline.py
As part of enriching by default attributes from function and configuration into the kfp pods we want to make sure that user will be able to override the attributes in case of wanting different setup for its kfp pods.
> [KFP] Add test for overriding enriched attributes from function and default configuration

- mlrun/runtimes/function.py
- tests/api/runtimes/test_nuclio.py
In https://github.com/mlrun/mlrun/pull/1895 I changed the default Nuclio runtime to `python:3.7` but the support for it was only added in [Nuclio 1.6.0](https://github.com/nuclio/nuclio/releases/tag/1.6.0) added handling for that
> [Nuclio] Fix runtime handling for Nuclio <1.6.0 (doesn't support python:3.7)

- docs/install-kubernetes.md
Add unit (seconds) to the docker install
> [Docs] Fix helm install timeout to use seconds unit

- mlrun/runtimes/kubejob.py
- tests/test_builder.py
https://github.com/mlrun/mlrun/pull/1783 used `list(set(x))` (to ensure uniqueness) but it caused to lose the order
Fixes https://jira.iguazeng.com/browse/ML-2140
> [Runtimes] Fix `build_config()` to preserve commands order

- mlrun/lists.py
- tests/system/examples/basics/test_db.py
Was looking for `key` in the wrong place.
Also fixed the `ArtifactList` functionality which would generate empty results when using `to_df()` or similar methods on objects of the new format. This was not tested anywhere and not sure if anyone uses it. Still, added a small test to verify the results have contents (at least the `key` field).
> [System Tests] Fix broken test due to artifacts refactor

- mlrun/runtimes/sparkjob/abstract.py
- mlrun/runtimes/sparkjob/spark3job.py
- tests/api/runtimes/test_spark.py
ML-1979
Usage:
```
sj.spec.driver_java_options="-Dlog4j.configuration=file:///v3io/bigdata/log4j.properties"
sj.spec.executor_java_options="-Dlog4j.configuration=file:///v3io/bigdata/log4j.properties"
```
> [Runtimes] Add java options spark job parameters

- mlrun/config.py
- mlrun/runtimes/base.py
- mlrun/runtimes/constants.py
- tests/api/runtime_handlers/test_kubejob.py
- tests/conftest.py
https://jira.iguazeng.com/browse/ML-758
https://jira.iguazeng.com/browse/ML-679
Previously, we monitored tasks by looping over the k8s resources and then looking for the corresponding runs recorded in the database.
This caused a bug in which when a job was monitored in non-terminal state and then the node the job was running on was evicted / preempted in the time between monitoring cycles, the next time the monitoring started running it didn't find the corresponding k8s resource and the job was stuck forever as non-terminal. This has a significant impact on scheduled jobs that could not be scheduled until the job was brought to a terminal state.
The addition I've made is that now, in addition to cycling over the listed k8s resources, we also cycle through the runs recorded in the …
> [Runtimes] Fix jobs stuck in non-terminal state after node drain/preemption

- mlrun/api/main.py
- mlrun/api/schemas/__init__.py
- mlrun/api/schemas/constants.py
- mlrun/config.py
We're starting a process of making the API stateless in order to be able to run multiple instances of it
Some things, like the periodic functions (runs monitoring/cleanup) don't need to run on all instances, therefore we're introducing a new clusterization role config value which define whether the instance is a chief or a worker
> [API] Support clusterization roles

- mlrun/artifacts/dataset.py
- tests/artifacts/test_table.py
The `TableArtifact.get_body()` function called itself recursively instead of calling `spec.get_body()`.
Fixes [ML-2184](https://jira.iguazeng.com/browse/ML-2184)
> [Artifacts] Fix infinite recursive call to `TableArtifact.get_body()`

- mlrun/projects/operations.py
- mlrun/projects/pipelines.py
- mlrun/projects/project.py
- mlrun/run.py
- mlrun/runtimes/local.py
- tests/system/runtimes/test_archives.py
- Various fixes in set/run_function method to support working with handlers (without files), subpath, and archives 
- Support local run/debug when working with archives 
- Work with project level archive settings and project run/build/deploy methods
- Add various tests
example, working with archives and project:
```python
project = mlrun.load_project(
"./",
"git://github.com/mlrun/test-git-load.git",
"my-project",
user_project=True,
subpath="subdir",
)
run = project.run_function("myjob", local=True)
print(run.outputs)
project.build_function("myjob")
run = project.run_function("myjob")
print(run.outputs)
deployment = project.deploy_function("mynuclio")
resp = deployment.function.invoke("")
print(resp)
```
> [Projects] Fix/support archives with project run/build/deploy methods

- mlrun/datastore/store_resources.py
- mlrun/kfpops.py
- tests/test_datastores.py
The `get_store_resource` method does parsing of artifacts returned from DB, and if a link artifact is returned it queries again for the actual artifact from the correct iteration. However, the `link_iteration` field was taken from the location it was in the legacy artifact structure, causing the artifact to not be returned properly. Added code to properly handle new and legacy artifacts. 
Fixing [ML-2183](https://jira.iguazeng.com/browse/ML-2183).
While fixing this, found another location where backwards compatibility is needed (in `get_kfp_outputs` which only assumed new-format artifacts exist), fixed it as well.
> [Artifacts] Fix processing of link artifacts in `get_store_resource`

- mlrun/runtimes/sparkjob/spark3job.py
- tests/api/runtimes/test_spark.py
Spark operator has multiple options to control the number of cores available to the executor and driver. Up until now MLRun would set the `.coreLimit` and `.coreRequest` for both executor and driver, but this only controls the k8s properties of the pods created to run them. Spark itself uses the `spec.[executor|driver].cores` parameter to set the parallelism of tasks and cores assigned to each task within the pod - this parameter was always set to 1 until now.
See https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/581 for a discussion about those parameters and their meaning in Spark operator.
This PR adds a `.with_cores()` function to the `Spark3Runtime` class, enabling the user to control this property for both executor and driver.
This fixes …
> [Spark] Allow setting executor and driver cores parameter in Spark runtime

- mlrun/api/utils/projects/leader.py
- mlrun/api/utils/projects/remotes/nop_follower.py
- tests/api/utils/projects/test_leader_member.py
Recently we started seeing these tests almost constantly fail in CI:
```
>               assert (
follower._projects[project.metadata.name].status.state
== project.spec.desired_state
)
E               AssertionError: assert None == <ProjectDesiredState.online: 'online'>
E                 +None
E                 -<ProjectDesiredState.online: 'online'>
tests/api/utils/projects/test_leader_member.py:595: AssertionError
FAILED tests/api/utils/projects/test_leader_member.py::test_projects_sync_follower_project_adoption
FAILED tests/api/utils/projects/test_leader_member.py::test_projects_sync_leader_project_syncing
FAILED tests/api/utils/projects/test_leader_member.py::test_projects_sync_multiple_follower_project_adoption
```
In the investigation we saw that it only reproduces with the …
> [API] Fix projects leader to sync enrichment to followers

- mlrun/api/initial_data.py
- mlrun/artifacts/base.py
- mlrun/artifacts/dataset.py
- tests/api/db/test_artifacts.py
These fields were wrongly included in the `spec` part of the object, while they need to be in the `status`.
Also added some fields to the `spec` of `DatasetArtifact` to align it with feature-sets.
> [Artifacts] Move `stats` and `preview` fields from artifact `spec` to `status`

- mlrun/runtimes/sparkjob/abstract.py
- mlrun/runtimes/sparkjob/spark3job.py
- tests/api/runtimes/test_spark.py
Reverting as the PR is targeted for 1.0.4 but 1.0.3 was not released yet
> Revert "[Spark] Allow mounting v3io on driver but not executors [Backport 1.0.x]"

- automation/package_test/test.py
- requirements.txt
- tests/automation/package_test/assets/ignored_vulnerabilities.json
- tests/test_requirements.py
Following https://github.com/mlrun/mlrun/pull/2016
Storey bumped Numpy on their side, so bumping in MLRun as well to fix the vulnerabilities
> [Requirements] Bump numpy to fix vulnerabilities

- mlrun/runtimes/sparkjob/abstract.py
- mlrun/runtimes/sparkjob/spark3job.py
- tests/api/runtimes/test_spark.py
Add https://github.com/mlrun/mlrun/pull/2017 again after reverted in https://github.com/mlrun/mlrun/pull/2021
Merge only after 1.0.3 is out
> [Spark] Allow mounting v3io on driver but not executors [Backport 1.0.x]

- dockerfiles/models-gpu/Dockerfile
During the `models-gpu` image build, in the `Step 9/36 : RUN apt-get update...` step we started getting:
```
Reading package lists...
W: GPG error: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A4B469963BF863CC
E: The repository 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease' is not signed.
```
Reading https://forums.developer.nvidia.com/t/notice-cuda-linux-repository-key-rotation/212771 it seems like some keys have been rotated
Ideally they are suggesting to fix this by installing some cuda keyring package that should fix this issue permanently (won't break on future keys rotation) but it requires `wget` to …
> [Images] Fix GPU image to have new signing keys

- mlrun/api/utils/clients/iguazio.py
- mlrun/api/utils/clients/nuclio.py
- mlrun/db/httpdb.py
- tests/api/api/test_projects.py
- tests/rundb/test_unit_httpdb.py
We started seeing those failures in CI:
```
E               requests.exceptions.InvalidHeader: Header part (<DeletionStrategy.restricted: 'restricted'>) from {'x-mlrun-deletion-strategy': <DeletionStrategy.restricted: 'restricted'>} must be of type str or bytes, not <enum 'DeletionStrategy'>
/usr/local/lib/python3.7/site-packages/requests/utils.py:1038: InvalidHeader
FAILED tests/api/api/test_projects.py::test_delete_project_with_resources[leader] - requests.exceptions.InvalidHeader: Header part (<DeletionStrategy.check: 'check'>) from {'x-mlrun-deletion-strategy': <De...
FAILED tests/api/api/test_projects.py::test_delete_project_with_resources[follower] - requests.exceptions.InvalidHeader: Header part (<DeletionStrategy.check: 'check'>) from {'x-mlrun-deletion-strategy': <...
FAILED …
```
> [Tests] Send only string headers to align to new requests limitation

- mlrun/api/utils/clients/iguazio.py
- tests/api/utils/clients/test_iguazio.py
Bugfix for - https://jira.iguazeng.com/browse/ML-1692
When using Iguazio as projects leader, it wasn't possible to delete all the project's labels or annotations. We weren't allowing to update annotations or labels to an empty dictionary as we were ignoring empty dictionaries when deciding wether to include the field (`annotations` or `labels`) in the request to Iguazio.
Now checking wether the field is explicitly `None` or not.
> [Projects] Fix deleting last project label

- mlrun/api/crud/projects.py
- mlrun/api/db/base.py
- mlrun/api/db/filedb/db.py
- mlrun/api/db/sqldb/db.py
- mlrun/api/utils/projects/follower.py
- mlrun/api/utils/projects/remotes/nop_leader.py
- tests/api/db/test_projects.py
- tests/api/utils/projects/test_follower_member.py
As part of the effort of making the API stateless, we needed to change the projects follower member behavior to keep its projects in the DB instead of in cache. TBH it mainly simplified the follower logic so now it simply using the CRUD layer as is instead of implementing filters and such itself.
The only not trivial thing here was to understand that since we've been with the follower for some time, and its using cache for persistency meaning the projects table is not maintained, it means that when we're switching (persistency from cache to DB) there must be some code that will sync the projects in the DB
We basically are doing this sync periodically as part of the already existing follower logic, but this logic didn't include handling of deleting projects from persistency that are no …
> [Projects] Change follower projects store to be the DB instead of cache

- mlrun/api/api/endpoints/background_tasks.py
- mlrun/api/api/endpoints/functions.py
- mlrun/api/api/endpoints/operations.py
- mlrun/api/api/endpoints/projects.py
- mlrun/api/api/endpoints/schedules.py
- mlrun/api/api/endpoints/submit.py
- mlrun/api/main.py
- mlrun/api/utils/background_tasks.py
- mlrun/api/utils/clients/chief.py
- mlrun/api/utils/helpers.py
- mlrun/api/utils/scheduler.py
- mlrun/config.py
- tests/api/api/test_background_tasks.py
- tests/api/api/test_functions.py
- tests/api/api/test_projects.py
- tests/api/api/test_schedules.py
- tests/api/api/test_submit.py
- tests/api/utils/clients/test_chief.py
This PR, is part of a series of PRs making the API stateless. 
We decided that only the chief will be responsible for running the scheduler, which means that any code that had any effect on the scheduler behavior (e.g create / delete / update / invoke ) must run by the chief. 
To implement that requirement, when accessing code that affect the scheduler behavior we will check which instance type we are running inside, and if we are running inside a worker we will re-route the request to the chief.
- CREATE schedule- `/projects/{project}/schedules`
- PUT schedule - `/projects/{project}/schedules/{name}`
- DELETE schedule - `/projects/{project}/schedules/{name}`
- DELETE project schedules - `/projects/{project}/schedules`
- POST schedule - - `/projects/{project}/schedules/{name}/invoke`
We …
> [Scheduler] Add re-routing to chief 

- tests/projects/test_local_pipeline.py
We experienced a transient CI failures because `test_import_artifacts` relied on a list's order, which was not guaranteed.
> [Tests] Fix `test_import_artifacts`

- mlrun/__main__.py
- mlrun/projects/project.py
https://jira.iguazeng.com/browse/ML-2341
Currently when using MLRun CLI for `project run` and setting `watch=True` the default timeout value is 60 min which in not configurable from outside. This PR will allow to set the timeout from outside.
> [Projects] Add timeout attribute to run method

- mlrun/api/utils/projects/follower.py
Fixes https://jira.iguazeng.com/browse/ML-2344.
We encountered an error related to the sqlalchemy session isolation level. 
It seems we use the default isolation mode which is serializable ( probably ) which eventually means that if we query the db and then will run the same query the second try won't query the DB but rather will use the latest query result ( kind of cache ). 
To fix this issue there are a few options : 
- session.commit() before repeating queries - this will ends the current transaction and start a new one which will result in a new query to the DB.
- change the isolation level - we should strive to achieve that ( won't be part of this PR ) will require further investigation and more test coverage. 
Here are some information related to the topic : …
> [Projects] Fix project querying caching

- .github/workflows/build.yaml
Also changed the test image not to be pushed to all provided registries as there's no need to, we're building it only for caching reasons to speed up our CI which will always pull it from ghcr.io
> [CI] Enable overriding the version when triggering the build workflow

- mlrun/runtimes/base.py
When submitting a job to MLRun, if we fail getting the run logs, we would mark the run's status as `"error"` in the SDK, while the run might be working properly in the server.
Fixed it so getting the logs doesn't alter the state, but the exception that caused the failure will now be raised.
> [Runtimes] Fix false error run status when failing to get run logs

- mlrun/serving/routers.py
- mlrun/serving/states.py
- tests/serving/test_parallel.py
example:
```python
fn = mlrun.new_function("parallel", kind="serving")
graph = fn.set_topology(
"router",
mlrun.serving.routers.ParallelRun(extend_event=True, executor_type="process"),
)
graph.add_route("child1", class_name="Cls1")
graph.add_route("child2", class_name="Cls2", my_arg={"c": 7})
graph.add_route("child3", handler="my_handler")
server = fn.to_mock_server()
resp = server.test("", {"x": 8})
```
> [Serving] Add ParallelRun router for running multiple steps in parallel threads/processes

- mlrun/api/api/utils.py
- mlrun/config.py
- tests/api/api/test_submit.py
- tests/api/runtimes/test_nuclio.py
Use case: when deploying in AWS and using instance roles to allow access to S3 resources without need for creds (and also other use-cases which similarly utilize k8s service-accounts), we want every pod that is being launched by MLRun to use a default service account. This default SA should not be user-configurable, but only on the MLRun service configuration.
To support this, added a global config parameter `function.spec.service_account.default` which is `None` by default.
The SA logic now becomes:
1. If the job has a SA set in the spec, it is the one used
2. Otherwise, if the project has a default SA set in its project-secrets, assign it
3. Else, check if the global SA is set - if it does, assign it
There are no other changes to the validation flow, meaning that every SA selected will …
> [Runtimes] Add a global config (on server side) for default service account

- mlrun/api/api/utils.py
- mlrun/config.py
- tests/api/api/test_submit.py
- tests/api/runtimes/test_nuclio.py
> [Runtimes] Add a global config for default service account [1.0.x backport]

- mlrun/runtimes/serving.py
- mlrun/serving/states.py
- tests/system/runtimes/assets/child_function.py
- tests/system/runtimes/test_nuclio.py
to avoid multiple downstreams using the same consumer group.
[ML-2408](https://jira.iguazeng.com/browse/ML-2408)
> [Runtimes] Set Kafka consumer group from function name

- .github/workflows/system-tests-opensource.yml
System Tests time to run has increased over 25 minutes. Increasing the timeout to match.
> [CI][Open Source System Tests] Increase System Tests Timeout

- mlrun/datastore/s3.py
- mlrun/platforms/other.py
- tests/common_fixtures.py
- tests/runtimes/test_base.py
When working with IAM instance roles, we will not have any credentials (since they're handled by the instance role), but the connection to S3 mustn't work in `anon` mode. Up until now the `anon` parameter was deduced from the lack of credentials (i.e. no secret or key-id provided), which fails in this scenario. To properly connect in this case, we need the user to specify that auth is required even though no credentials are given.
- Added a new environment variable `S3_NON_ANONYMOUS` which when set will force the S3 provider to work in non-anonymous mode, even if no credentials are given.
- Also added a parameter to the `mount_s3` modifier that will set this env. variable.
- With this option, auto-mount can now work with IAM instance roles by using the `s3` auto-mount type, and setting …
> [Datastores] Adding option to force non-anonymous authentication when using S3

- mlrun/api/utils/clients/iguazio.py
(cherry picked from commit d0aeb064d86efca89967544fd2f2418b5ff65693)
> [Iguazio] Backport Fix `max_workers` adapter wasn't applied on https endpoint on iguazio client [1.0.x]

- dockerfiles/base/Dockerfile
- dockerfiles/mlrun/Dockerfile
- dockerfiles/models-gpu/Dockerfile
For https://jira.iguazeng.com/browse/ML-2392
Change permissions of the workdir in the runtime images (`ml-base`, `mlrun`, `ml-models`* and `ml-models-gpu`), to enable any user write privileges, as the runtime needs this to create the function's code in a file. This allows us to set any security context we like for the run pods.
*`ml-models` is based `ml-base`, so running the chmod in the base image propagates down.
> [Runtimes] Allow runtime images to run with a non-root user

- Makefile
The system tests have, over time, grown larger and larger so that they last longer than github's job timeout.
To remedy this, we want to run the tests in smaller chunks.
Added an optional env var `MLRUN_SYSTEM_TESTS_COMPONENT` which when set will select the test chunk to run.
If `MLRUN_SYSTEM_TESTS_COMPONENT` isn't set, we'll run all system tests.
If `MLRUN_SYSTEM_TESTS_COMPONENT` is set, we'll run only the system tests for the given component.
If `MLRUN_SYSTEM_TESTS_COMPONENT` starts with "no_", we'll ignore that component in the system tests.
As of now the available values are: (no value), `api`, `backward_compatibility`, `demos`, `examples`, `feature_store`, `model_monitoring`, `projects` `runtimes`, `no_api`, `no_backward_compatibility`, `no_demos`, `no_examples`, `no_feature_store`, …
> [System Tests] Allow running system tests by test suite/component

- docs/install/remote.md
- mlrun/__init__.py
- mlrun/config.py
- tests/test_convenince_methods.py
Fixes https://jira.iguazeng.com/browse/ML-2384
Raise `MLRunNotFoundError ` when using `set_env_from_file` if file doesn't exist
> [SDK] Fix no exception when using `set_env_from_file` with non-existent file

- docs/store/datastore.md
Wrong env. variable was specified. Also added note on usage of blob-client vs. using fsspec.
> [Docs] Fix error in Azure datastore doc

- mlrun/api/api/utils.py
- mlrun/config.py
- tests/api/api/test_utils.py
For security reasons, we have limited the URLs accessible through the `/files` API such that only `v3io://` paths are allowed by default. There is one additional tweak, where the parameters `httpdb.data_volume` and `httpdb.real_path` can be specified. These were intended such that if the path is prefixed with `data_volume`, it will be replaced with the `real_path`. As a side-effect, the `real_path` is allowed for the `/files` API, so specifying something like `gcs` there will allow access to paths beginning with `gcs` (even if `data_volume` is omitted).
This is not flexible enough, as users may want to specify paths to specific buckets, for example. The current mechanism does not allow that since only a single prefix can be provided.
The PR adds a new parameter - …
> [API] Better configuration for allowed paths in the `/files` API

- .github/workflows/system-tests-enterprise.yml
- tests/system/feature_store/test_feature_store.py
This test is running for more than an hour and fails at the end, skipping this test until it gets fixed.
https://github.com/mlrun/mlrun/runs/7664264987?check_suite_focus=true
```
4555.18s call     test_feature_store.py::TestFeatureStore::test_purge_nosql
FAILED tests/system/feature_store/test_feature_store.py::TestFeatureStore::test_purge_nosql
```
> [Feature Store] Skip `test_purge_nosql`

- dockerfiles/models-gpu/Dockerfile
Nvidia removed the image we were building the models-gpu image from, pushed the image to `quay.io/mlrun/cuda` and `mlrun/cuda`.
> [Docker] Change base models gpu image

- dockerfiles/models-gpu/Dockerfile
Nvidia removed the image we were building the models-gpu image from, pushed the image to `quay.io/mlrun/cuda` and `mlrun/cuda`.
backport - #2223
> [Docker] Backport Change base models gpu image [1.0.x]

- mlrun/api/api/endpoints/functions.py
- mlrun/api/api/utils.py
- mlrun/api/schemas/project.py
- mlrun/api/utils/clients/iguazio.py
- mlrun/api/utils/projects/remotes/nop_leader.py
- mlrun/api/utils/scheduler.py
- tests/api/api/test_utils.py
- tests/api/utils/clients/test_iguazio.py
- tests/api/utils/projects/test_follower_member.py
- tests/api/utils/test_scheduler.py
https://jira.iguazeng.com/browse/ML-2468
* When enriching auth info we weren't adding the relevant plane session tags, fixed that in 4 places:
*  When reloading schedules we are loading the access key from the secret, and to be able to run schedules the minimum is control plane session, so added a control plane session tag when creating that auth info.
* In `submit_run_wrapper` when access key isn't set we are enriching the auth info with the project owner access key, so as well added a control plane session tag to the auth info created. 
* In `ensure_function_has_auth_set` when access key isn't defined we are getting / creating an access key with control and data plane, so added a control and data plane session tag to the auth info.
* In `_ensure_auth_info_has_access_key` ( Scheduler ) …
> [Scheduler] Fix failing schedules with security context enrichment

- mlrun/config.py
- mlrun/db/httpdb.py
- tests/rundb/test_unit_httpdb.py
Fix for https://jira.iguazeng.com/browse/ML-2479
Add retry mechanism to `api_call` in the `HTTPDB`, so that if the sdk client experiences a connection reset, the request will be retried (similarly to the retry on error status code mechanism).
> [SDK] Fix fail to send request to MLRun API with `ConnectionResetError`

- mlrun/api/api/endpoints/functions.py
- mlrun/api/api/utils.py
- tests/api/runtimes/test_nuclio.py
- tests/api/runtimes/test_serving.py
If we had this we wouldn't encounter the bug we fixed in https://github.com/mlrun/mlrun/pull/2228. 
Eventually moved all enrichments and validations util functions under one function with feature flag for each of them, so that different runtimes could define the enrichment required depends on their need.
> [API] Re-organize the way we are enriching functions on the backend

- mlrun/api/api/utils.py
- mlrun/runtimes/remotesparkjob.py
fix for: https://jira.iguazeng.com/browse/ML-2467
- Added validation on server side when enriching security context
- Raising exception when trying to set security context for remote spark
> [Spark] Disable security context enrichment for remote spark [1.0.x]

- mlrun/api/api/utils.py
- mlrun/runtimes/remotesparkjob.py
fix for: https://jira.iguazeng.com/browse/ML-2467
- Added validation on server side when enriching security context
- Raising exception when trying to set security context for remote spark
> [Spark] Disable security context enrichment for remote spark

- mlrun/datastore/targets.py
- mlrun/feature_store/api.py
- mlrun/feature_store/feature_set.py
- mlrun/utils/helpers.py
- tests/system/feature_store/test_feature_store.py
- tests/system/feature_store/test_spark_engine.py
Currently, `ParquetTarget` defaults to `partitioned=False`, but the default offline target is `ParquetTarget(partitioned=True)`. This PR aligns the default to `partitioned=True`.
Fixes `TestFeatureStoreSparkEngine::test_aggregations_emit_every_event`.
> [Feature Store] Fix ingest with spark with default targets

- mlrun/api/schemas/__init__.py
- mlrun/api/schemas/http.py
- mlrun/api/utils/auth/providers/opa.py
- mlrun/api/utils/clients/chief.py
- mlrun/api/utils/clients/iguazio.py
- mlrun/api/utils/clients/nuclio.py
- mlrun/config.py
- mlrun/db/httpdb.py
- mlrun/serving/remote.py
- mlrun/utils/__init__.py
- mlrun/utils/http.py
- tests/rundb/test_unit_httpdb.py
Moved the "request with retries" mechanism to a general MLRun util, so it can be used in multiple places.
Now in addition to using it in the SDK for requests against the API:
- The API now uses it for requests against the project leader.
- The opa client uses it for requests against opa.
- The nuclio client uses it for requests against nuclio.
- The worker uses it for requests against the chief.
> [API] Fix requests to Projects Leader fail with `Connection Aborted`

- mlrun/config.py
- mlrun/runtimes/sparkjob/abstract.py
Spark-2 is pretty much deprecated. Changing the default configuration to be `spark-3`. Not yet removing support for Spark 2, can be configured manually if needed.
> [Runtimes] Bump the default spark operator version to `spark-3`

- docs/install/compose.with-jupyter.yaml
- docs/install/compose.yaml
- We didn't set `MLRUN_HTTPDB__REAL_PATH` to the local mounted path, by default we don't want to allow accessing to local storage of the API, but because docker compose isn't using s3 yet but rather a local mount between with jupyter we need to allow access to the local storage. https://github.com/mlrun/mlrun/issues/2266#issuecomment-1219878137
- I found out I forgot to change the UI exposed port for `compose.yaml` to 8090 instead of 80, so fixed that as well.
- Added `MLRUN_SECRET_STORES__KUBERNETES__AUTO_ADD_PROJECT_SECRETS: "false"` just to avoid misleading errors from the API.
> [Docker Compose] Fix models preview when running with jupyter

- .github/workflows/system-tests-enterprise.yml
- tests/system/demos/churn/test_churn.py
- tests/system/demos/horovod/test_horovod.py
- tests/system/demos/sklearn/test_sklearn.py
Demos in the system tests were not up to date for a long time, currently the way the demos are being tests is by QA suits which runs the demos on each released version including RC. 
Todo: Connect CI between `mlrun/demos` with `mlrun/mlrun` and run demos for each merged commit to development.
> [CI] Remove demos from system tests

- dockerfiles/jupyter/Dockerfile
Some of the demos currently only work in iguazio enterprise. 
In the demos repo we added a script which removes the relevant demos. So when building open source jupyter image, we run the script so only the working demos will remain.
> [Jupyter] Remove Enterprise Demos from Open Source Image

- mlrun/runtimes/daskjob.py
- mlrun/runtimes/pod.py
- mlrun/runtimes/sparkjob/abstract.py
- tests/api/runtimes/test_dask.py
- tests/api/runtimes/test_spark.py
- tests/runtimes/test_run.py
Per https://jira.iguazeng.com/browse/ML-2523 request.
By default when setting `with_requests(cpu="2")` this will override all the resources in the requests section.
Added option to set `with_requests(cpu="2", patch=True)` which will patch defined resources inside the requests section. 
Note that in the example I refer to `with_requests` but this applies to all `with_x_requests/limits`.
> [Runtimes] Add patch option for `with_requests` &  `with_limits`

- mlrun/projects/project.py
returning project.get_run_status() supporting remote engine with a deprecation warning
> [Project] Return `get_run_status` with deprecation warning

- mlrun/runtimes/function.py
- tests/common_fixtures.py
- tests/runtimes/test_base.py
- tests/runtimes/test_function.py
Fixes - https://jira.iguazeng.com/browse/ML-2164
When deploying a serving function, the SDK creates the function via the API, and then polls its status. Once the status is ready the SDK saves the function to the DB. The API masks the access key with a reference to a secret, but the SDK does not do this, so when it saves the function it is saved with clear text access key.
Fixed the polling so that not only the state gets updated but also all the relevant env vars and fields relating to credentials. That way the access key gets the masked version from the API. As seen in the example image:
> [SDK] Fix Access Key saved as clear text when deploying a serving function

- mlrun/feature_store/feature_set.py
- tests/feature-store/test_ingest.py
`set_targets(["parquet"])` should create the default parquet target, which is partitioned.
Fixes [ML-2527](https://jira.iguazeng.com/browse/ML-2527).
> [Feature Store] Fix `set_targets(["parquet"])`

- mlrun/datastore/targets.py
- mlrun/model.py
The `fset.status.targets` field has objects of type `DataTarget` which is different than the targets in `fset.spec.targets`. The `partitioned` field which indicates whether this target is partitioned was missing, along with other fields which describe the partitioning scheme - these fields were not copied from the spec target, and also not persisted in `to_dict()` and `from_dict()`.
Because some feature-store functionality such as `fset.to_dataframe()` rely on the targets which are in the fset status, this caused undesirable behavior - it did not remove the partitioning fields from the result DF.
Among other things, this caused the `test_aggregations_emit_every_event` system test to fail.
> [Feature store] Changed fset status targets to have partitioning related fields

- .github/workflows/system-tests-enterprise.yml
Splitting up the system tests by tests types caused a bug in which each step branched out from development rather than from the commit hash the prepare job was executed from. 
So now the jobs that actually running the system tests are using the calculated params from the prepare job.
> [CI] Fix System tests not running with the same commit hash

- mlrun/api/crud/client_spec.py
Fixes https://jira.iguazeng.com/browse/ML-2533, issue discovered when running with 0.10 client against a new 1.1 service:
The spark op version on the client side is either what is defined in the client config (which for 0.10 is by default `spark-2`) or what is reported from the MLRun service, if reported.
However, the service is only reporting the spark-op version if it differs from the default configuration. Up until now, the default config on the server was `spark-2` and it was overridden to be `spark-3`. However, with the change I entered in #2269, the default is now `spark-3`, and the override value is the same, so the service is not reporting this version to the client. This causes the client to remain with its default of `spark-2`, causing this issue.
Fix is to modify the service …
> [Spark] Fix backwards-comp issue with `spark-2` and `spark-3` in 0.10 client and 1.1 server

- mlrun/api/crud/projects.py
- mlrun/projects/project.py
- tests/api/api/test_projects.py
- tests/integration/sdk_api/projects/test_project.py
- tests/system/projects/test_project.py
When creating new project allow only creation instead of update.
Add `override` option to delete existing project with the same name before creation.
https://jira.iguazeng.com/browse/ML-2320
> [Project] Change default `new_project` to create instead of store

- .github/workflows/system-tests-enterprise.yml
- automation/system_test/prepare.py
When running the system tests, almost every test builds a docker image which is saved to the deafult-tenant docker registry. This causes a massive usage of the app node disk space, causing the node to receive a `disk-pressure` taint and pods commence restarting themselves.
Luckily, this docker registry has volatile storage, so in order to fix this, after each system test component, we restart the docker registry deployment which instantly cleans up all the docker images within.
> [CI] Run Docker Image Cleanup After System Tests

- mlrun/utils/clones.py
- tests/system/runtimes/test_archives.py
- tests/utils/test_clones.py
Fixes - https://jira.iguazeng.com/browse/ML-2417
Fix `clone_git` method to look at the `refs` in the url properly, and accept branch names with or without `/`s.
Also added support for checking out specific git tags.
> [Functions] Fix Git Branches with Slashes not Supported

- mlrun/api/utils/clients/iguazio.py
- tests/api/utils/clients/test_iguazio.py
For the response headers to be lighter, user and groups ids are included in the response body from `/sessions/verifications` (see https://github.com/iguazio/zebo/pull/6032).
Change Iguazio authentication to read this info from the body instead of headers, and fallback to the headers in case body is missing.
JIRA: https://jira.iguazeng.com/browse/IG-21097
> [API] Read session verification data from both body and headers

- tests/system/projects/test_project.py
- tests/system/runtimes/test_archives.py
Found a bug in the way we were deleting projects which had `user_project=True`. 
This caused because we were deleting `project_name` instead of `project.name`.
When defining `user_project=True` the project name get concatenated with the user name which results to `<project-name>-<user-name>`.
> [Projects] Fix project deletion in system tests

- mlrun/config.py
- mlrun/platforms/__init__.py
- mlrun/platforms/other.py
- mlrun/runtimes/pod.py
- tests/common_fixtures.py
- tests/platforms/test_other.py
- tests/runtimes/test_base.py
Added a modifier function `set_env_variables` to add multiple env. variables to a runtime. Also added an `env` auto-mount option to use this function automatically. This can be used to mount an arbitrary set of env variables to every runtime in a project.
While there are existing ways through MLRun/KFP-modifiers to add env. variables to runtimes, they have some short-comings, which this function solves:
* Since it's a modifier, it can be used with `RunConfig` which has an option to apply modifiers, but does not have ways to set env. variables on the `RunConfig` itself. Also, since auto-mount option is available, it can be used for every job submitted without having to tweak the `RunConfig` parameters
* It accepts multiple env. variables in a single execution. This makes it flexible and …
> [Runtimes] Adding a modifier and auto-mount option to configure multiple env variables

- mlrun/projects/project.py
Fixes https://jira.iguazeng.com/browse/ML-2550
`get_or_create_project` has default `save=True` which we were passing for both `load_project` (we have one for first trying to load it from db and second for if we don't find so we are trying to load it from source).
The bug was that we were passing `save=True` when loading from DB which is redundant as we just loaded it from db, this also caused a bug for users with only read permissions as it is unable to "save" ( write ) to the project.
> [Projects] Fix saving project by default when loading project from db 

- mlrun/config.py
- mlrun/datastore/redis.py
also fix redis url in mlrun-config. still need to propagate it to redis-driver in case env-var is not configured.
> [Datastore] Fix redis-store rm for single file deletion

- tests/system/feature_store/test_spark_engine.py
To avoid a potential conflict with `test_aggregations`.
> [Tests] Fix file name in `test_aggregations_emit_every_event`

- mlrun/api/api/utils.py
- mlrun/builder.py
- mlrun/runtimes/base.py
- mlrun/runtimes/pod.py
- tests/test_builder.py
Service account (default or not) will apply on both the function pod and kaniko image builder pod.
This is useful to give ECR permissions via service account on EKS with cloudformation (mlrun CE).
Default service account is resolved fro project's configuration or from the mlrun global config.
> [Builder] Add service account to kaniko pod

- mlrun/datastore/wasbfs/fs.py
[ML-2557](https://jira.iguazeng.com/browse/ML-2557)
get_offline_features fails due to error in WasbFS.info()- too many arguments
> [Datastore] Fix WasbFS info to call underlying FS correctly

- mlrun/run.py
- mlrun/runtimes/function.py
- tests/api/runtimes/test_nuclio.py
- tests/assets/hello.go
- tests/test_code_to_func.py
* align/simplify Nuclio spec to other runtimes (remove the spec.base_spec in newly generated functions)
* sets the nuclio runtime based on the code file suffix (for non python code)
* add a way to set the Nuclio noBaseImagesPull flag (spec.base_image_pull)
> [Nuclio] Simplify spec and support non py code in `code_to_function` (for Nuclio)

- mlrun/api/utils/db/backup.py
- mlrun/config.py
- tests/api/utils/test_db_backup.py
On one of our systems, migrations failed with the following error when trying to take backup of the database: 
```
mysqldump: Error 2020: Got packet bigger than 'max_allowed_packet' when dumping table `runs` at row: 4315
```
Looking at the runs table found the following lines:
```
mysql> select id, uid, OCTET_LENGTH(body), project, iteration, state, start_time, name, updated from runs where OCTET_LENGTH(body) >= 15000000;
+-------+----------------------------------+--------------------+--------------------------------+-----------+-----------+-------------------------+--------------------+-------------------------+
| id    | uid                              | OCTET_LENGTH(body) | project                        | iteration | state     | start_time              | name               | updated …
```
> [Migrations] Fix failure in backup as a result of a big blob

- mlrun/api/crud/client_spec.py
- mlrun/api/schemas/client_spec.py
- mlrun/config.py
- mlrun/datastore/redis.py
- mlrun/datastore/store_resources.py
- mlrun/datastore/targets.py
- mlrun/db/httpdb.py
- tests/system/datastore/test_redis.py
- tests/system/feature_store/test_feature_store.py
- make sure redis_url is used as default in all redis-related places
- introduce "redis" as root in config (redis_url => redis.url)
- add redis.url to the ConfigSpec, to be available across clients (client has priority over api)
- solves ML-2583 (for 1.1.x)
> [FeatureStore] Redis target: cleanup config logic

- docs/store/datastore.md
- mlrun/datastore/s3.py
- tests/integration/aws_s3/test-aws-s3.yml
- tests/integration/aws_s3/test_aws_s3.py
Two new env variables added:
* `AWS_ROLE_ARN`- Connect to AWS using the secret key and access key, and assume the role whose ARN is provided. The ARN must be of the format `arn:aws:iam::<account-of-role-to-assume>:role/<name-of-role>`
* `AWS_PROFILE` - name of credentials profile. The profile needs to be defined in the local AWS credentials file. When using a profile, the authentication secrets (if defined) are ignored, and credentials are retrieved from the local credentials file
This allows users to connect to S3 using a role, either with local credentials file (for local development, for example if the `aws` cli created a local cred file) or using role ARN (useful for running jobs etc.) which can be passed to jobs as a secret or env variable.
> [Datastore] Support S3 authentication using local profile or assuming an IAM role

- mlrun/api/schemas/client_spec.py
- mlrun/artifacts/base.py
- mlrun/artifacts/manager.py
- mlrun/artifacts/model.py
- mlrun/config.py
- mlrun/db/httpdb.py
- mlrun/projects/project.py
- tests/rundb/test_unit_httpdb.py
Fixed the way `generate_target_path_from_artifact_hash` were passed.
Motivation:
This configuration changes the behavior of the client, meaning I want the server to "suggest" his behavior but if the client wishes to use other option than it can override the server configuration.
This was done by allowing three params into the `generate_target_path_from_artifact_hash` param:
- None ( behaves as False ) **Default**
- False
- True
If server sets True and the client is set to default ( None ), then server configuration will be applied.
If server sets True and the client sets to False, then client configuration will be applied.
For all use-cases head to the test I added.
This method of setting the default to None instead of False, allow us to be able to apply server configuration on old …
> [Client-spec] Fix configuration passing of artifacts

- mlrun/config.py
- mlrun/projects/operations.py
- mlrun/projects/project.py
- mlrun/runtimes/function.py
- mlrun/runtimes/serving.py
- tests/serving/test_serving.py
Examples:
```python
fn = mlrun.new_function("fake", kind="serving")
fn.add_model("my", model, class_name=ModelClass())
mlrun.deploy_function(fn, mock=True)
resp = fn.invoke("/v2/models/my/infer", testdata)
mlrun.mlconf.mock_nuclio_deployment = "1"
mlrun.deploy_function(fn)
resp = fn.invoke("/v2/models/my/infer", data)
```
> [Serving] Support mock of deploy_function() to run demo/tutorials w/o real Nuclio

- mlrun/api/crud/client_spec.py
- mlrun/api/schemas/client_spec.py
- mlrun/config.py
- mlrun/db/httpdb.py
Add CE mode to config and client spec, so that mode will be present from the clients and server.
https://jira.iguazeng.com/projects/CEML/issues/CEML-32
Backport #2398
> [Config] Add CE mode to config and client spec [1.1.x]

- mlrun/run.py
- tests/test_code_to_func.py
If labels are not specified in `code_to_function` arguments, they default to `None` and override the labels of the created runtime object, or the labels in `spec.metadata`.
https://jira.iguazeng.com/browse/ML-2627
> [Run] Fix labels initialization in `code_to_function`

- mlrun/__init__.py
- mlrun/config.py
- mlrun/projects/operations.py
- mlrun/runtimes/function.py
- mlrun/runtimes/serving.py
- tests/serving/test_serving.py
- tests/test_convenince_methods.py
* allow use of env_file in mlrun.set_environment()
* auto detect if Nuclio is not installed and use Mock when is "auto" mock mode
> [API] Simplify env and Nuclio mock setting

- mlrun/api/api/api.py
- mlrun/api/api/endpoints/artifacts.py
- mlrun/api/api/endpoints/tags.py
- mlrun/api/crud/__init__.py
- mlrun/api/crud/tags.py
- mlrun/api/db/base.py
- mlrun/api/db/filedb/db.py
- mlrun/api/db/sqldb/db.py
- mlrun/api/schemas/__init__.py
- mlrun/api/schemas/artifact.py
- mlrun/api/schemas/tag.py
- mlrun/utils/helpers.py
- tests/api/api/test_artifacts.py
- tests/api/api/test_tags.py
https://jira.iguazeng.com/browse/ML-2579
Added the following endpoints: 
```
( POST / PUT / DELETE ) - /projects/{project}/tags/{tag} 
```
Those endpoints expects the following body: 
```
{
"kind": <artifact>,
"identifiers": [
{"name": "artifact-name", "iter": "1"},
{"uid": "adasdads123n1lk23l"},
],
} 
```
**Currently those endpoints support only artifact tagging, but in the future those endpoints will serve all objects which can be tagged**
Each element in the identifiers list is treated separately, meaning inside an identifier element we are aggregating all together, but each identifier element is queried separately (OR).
> [Tags] Add endpoints for tagging objects

- mlrun/api/db/sqldb/db.py
- tests/api/db/test_artifacts.py
When trying to delete an artifact and specifying a tag, the code created a query that used a non-existing field `tag` in the `artifacts` table. Fixed it to use the correct SQL query.
Fixes https://jira.iguazeng.com/browse/ML-2638
> [Artifacts] Fix `del_artifact` to properly support providing a tag

- mlrun/api/crud/client_spec.py
- mlrun/api/schemas/client_spec.py
- mlrun/config.py
- mlrun/datastore/redis.py
- mlrun/datastore/targets.py
- mlrun/db/httpdb.py
- requirements.txt
- tests/system/datastore/test_redis.py
- tests/test_requirements.py
- fix propagation of redis configs to runtimes.
- WA for [ML-2644](https://jira.iguazeng.com/browse/ML-2644) - limiting pandas to <1.5.0
> [FeatureStore] Fix Redis server-type config and limit pandas to <1.5.0

- mlrun/api/crud/client_spec.py
- mlrun/api/schemas/client_spec.py
- mlrun/config.py
- mlrun/datastore/redis.py
- mlrun/datastore/targets.py
- mlrun/db/httpdb.py
- requirements.txt
- tests/system/datastore/test_redis.py
- tests/test_requirements.py
* fix redis.url config-spec sync
* clean test_redis_listdir objects at test end
* set redis-type according to mlrun env-var convention
* address tom's comments
* limit pandas to <1.5.0
* addressing Adam's comment
> [FeatureStore] Fix Redis server-type config and limit pandas to <1.5.0 (#2418)

- mlrun/db/httpdb.py
[ML-2647](https://jira.iguazeng.com/browse/ML-2647)
Revert 1.1.1 backport merge breakage - remove config.artifacts from httpdb.py connect().
> [FeatureStore] Revert addition of config.artifacts [1.1.x]

- docs/store/datastore.md
- mlrun/datastore/s3.py
- tests/integration/aws_s3/test-aws-s3.yml
- tests/integration/aws_s3/test_aws_s3.py
The S3 code was checking for the env. variable `AWS_ROLE_ARN` to determine if an assume-role flow is needed. However, it turns out that when deploying using cloud-formation in AWS and using the IAM-roles-for-service-accounts feature, AWS automatically sets the `AWS_ROLE_ARN` env. variable for Jupyter etc., and when trying to access S3 we fail because it's a different role assuming flow (need `sts:AssumeRole` permission, but having `sts:AssumeRoleWithWebIdentity`).
So, changed the code to use a different env. variable for the assume-role flow. This way the `AWS_ROLE_ARN` env. variable will only hold for AWS-internal flows, and if users want to assume-role manually they'll set the `MLRUN_AWS_ROLE_ARN` env. variable instead.
Original code was entered in #2395 (1.2) and #2397 (1.1.x)
> [Datastore] Changing code to use `MLRUN_AWS_ROLE_ARN` instead of `AWS_ROLE_ARN`

- docs/store/datastore.md
- mlrun/datastore/s3.py
- tests/integration/aws_s3/test-aws-s3.yml
- tests/integration/aws_s3/test_aws_s3.py
> [Datastore] Changing code to use `MLRUN_AWS_ROLE_ARN` instead of `AWS_ROLE_ARN` [1.1.x]

- mlrun/api/utils/projects/follower.py
Localize the epoch time for the defensive programming in the project sync mechanism.
Fixes - https://jira.iguazeng.com/browse/ML-2660
> [Projects] Fix Project Sync Failing Due To `can't compare offset-naive and offset-aware datetimes`

- extras-requirements.txt
- requirements.txt
nuclio-jupyter 0.9.3 requires nbconvert 6.4 which requires Jinja2>=3.0 
for some reason when installing mlrun on a venv that already had a lower version of jinja2 it didn't upgrade it 
therefore adding it explicitly (~=3.1 to match mlrun docs requirements)
ticket - https://jira.iguazeng.com/browse/ML-2653
precedent - https://github.com/mlrun/mlrun/pull/2036
> [Requirements] Add Jinja2 explictly

- mlrun/projects/pipelines.py
Passing `artifact_path` to the runner of `load_and_run` and not just as parameter to the function.
> [Projects] Pass `artifact_path` to the function runner

- requirements.txt
- tests/test_requirements.py
backports https://github.com/mlrun/mlrun/pull/2482
> [Requirements] Explicitly require importlib-metadata >= 3.6 [1.1.x]

- mlrun/datastore/v3io.py
- tests/system/datastore/test_v3io.py
Add to v3io datastore put() method support for >5GB objects.
[ML-2358](https://jira.iguazeng.com/browse/ML-2358)
> [DataStore] support v3io datastore put() of objects larger than 5GB

- .github/workflows/system-tests-enterprise.yml
- automation/system_test/cleanup.py
During the preparation of the Enterprise System Tests, mlrun's docker images are loaded on the data node and then pushed to a local docker registry on the data node. This builds up over time, using up more and more storage on the data node.
Created a script which removes the docker images from the local docker registry and from the docker daemon on the data node. The script will run at the end of each system-test run, conserving the storage usage of the system.
> [CI] Cleanup DataNode Docker Registry and Local Docker post System Tests

- mlrun/feature_store/ingestion.py
- tests/feature-store/test_steps.py
[ML-2673](https://jira.iguazeng.com/browse/ML-2673)
> [FeatureStore]  On pandas fs-ingestion, skip setting the df index if it's already set to fs entity 0

- mlrun/k8s_utils.py
Fix for - https://jira.iguazeng.com/browse/ML-2657 
Due to a known k8s issue (https://github.com/kubernetes/kubernetes/issues/67761) scheduled jobs on GKE are failing with `"Operation cannot be fulfilled on resourcequotas \\"gke-resource-quotas\\": the object has been modified; please apply your changes to the latest version and try again","reason":"Conflict"` when trying to create the run's pod.
Added a retry to the operation as per the recommended action in the above issue.
> [API] Fix scheduled jobs on GKE are failing with resource quota error

- .github/workflows/system-tests-enterprise.yml
Fixed the cleanup script to be copied and run from absolute path instead of relative path
> [CI] Fix System tests failing on cleanup

- mlrun/feature_store/ingestion.py
- tests/feature-store/test_steps.py
This pr create option to use multi entities , when ingesting over pandas engine. In all cases the indexes of the data are became exactly as the feature set entities, and erase those entities from the features (columns).
[ML-2677](https://jira.iguazeng.com/browse/ML-2677), [ML-2703](https://jira.iguazeng.com/browse/ML-2703)
> [FeatureStore] Multi index with pandas engine

- mlrun/builder.py
- mlrun/runtimes/base.py
- mlrun/runtimes/kubejob.py
- tests/system/runtimes/test_kubejob.py
https://jira.iguazeng.com/browse/ML-2669
https://jira.iguazeng.com/browse/ML-2701
- Fixes problem of running a function which its image wasn't defined  after deploy. 
- Fixes problem of deploying a function twice in a row ( .deploy() and afterwards .deploy() again).
- Fixes problem of running a function after deploying a function which had `with_source_archive`.
- Another bug which was found while debugging and now tested is that when we were declaring an image, and then applying`with_source_archive`, we weren't using that image as base when building, but rather the function type default (mlrun/mlrun) that is why I test with `mlrun-api`.
> [Runtimes] Fix run fails after deploying function without defined image

- .github/workflows/system-tests-enterprise.yml
When running the cleanup script from the github runner via ssh (ssh from different machines works well), for some reason the python isn't configured to use utf-8 and we get this error from the `click` package:
```
RuntimeError: Click will abort further execution because Python was configured to use ASCII as encoding for the environment. Consult https://click.palletsprojects.com/unicode-support/ for mitigation steps.
```
According to the provided docs page, added the env-vars to configure python to use utf-8.
In addition the script was missing a positional argument in the command.
> [CI] Fix System Test Cleanup Failing On Unicode Support For Click

- mlrun/api/api/endpoints/runtime_resources.py
- tests/api/api/test_runtime_resources.py
Fix for - https://jira.iguazeng.com/browse/ML-1432, https://jira.iguazeng.com/browse/ML-2541 and https://jira.iguazeng.com/browse/ML-1276
If all the resources are allowed to be deleted by the user, the request will be successful and the resource will be delete. 
If at least 1 resource exists but is forbidden to be deleted, the action will fail, nothing will be deleted and the user will get a 403 response (and the SDK will raise an exception).
> [API] Fix delete runtime resources doesn't return 403 on insufficient permissions

- mlrun/api/main.py
```
> 2022-11-03 14:34:52,614 [debug] Received request: {'method': 'GET', 'client_address': '10.201.136.120:35788', 'http_version': '1.0', 'request_id': '519df661-7c28-4f3b-a74f-7bfa2c968691', 'uri': '/api/v1/frontend-spec'}
> 2022-11-03 14:34:52,634 [debug] Getting grafana service url from Iguazio
> 2022-11-03 14:34:53,048 [debug] Sending response: {'status_code': 200, 'request_id': '519df661-7c28-4f3b-a74f-7bfa2c968691', 'elapsed_time': 0.433912261, 'uri': '/api/v1/frontend-spec', 'method': 'GET'}
```
> [API] Add elapsed time attribute to API logs

- .github/workflows/build.yaml
- .github/workflows/ci.yaml
- .github/workflows/post-release.yaml
- .github/workflows/release.yaml
- .github/workflows/system-tests-enterprise.yml
- .github/workflows/system-tests-opensource.yml
- docs/projects/ci-integration.md
`Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/setup-python, azure/setup-helm, manusa/actions-setup-minikube, actions/checkout`
and 
`The "set-output" command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
`
> [CI] Bump CI actions versions 

- mlrun/api/api/endpoints/artifacts.py
- mlrun/api/crud/artifacts.py
- mlrun/api/db/base.py
- mlrun/api/db/filedb/db.py
- mlrun/api/db/sqldb/db.py
- mlrun/db/base.py
- mlrun/db/filedb.py
- mlrun/db/httpdb.py
- tests/integration/sdk_api/artifacts/test_artifact_tags.py
- tests/rundb/test_sqldb.py
- The `list_artifact_tags` API now has a new `category` parameter, which is the same as for `list_artifacts` - it can be `model`, `dataset` or `other`. If not specified the current behavior remains which is to return all tags regardless of artifact types
- Fixed this API to return a list of unique values - up until now if same tag was used by multiple artifacts, the same tag would be returned several times, forcing the caller to remove duplicities
- The same functionality was added to `httpdb` for sdk usage
Example of API usage:
`GET .../projects/{project}/artifact-tags?category=model`
- Internal modification - moved the implementation to the Artifacts crud object, rather than calling the DB directly. This is in line with the rest of the functions in the endpoint.
Addresses …
> [Artifacts] Add category option to `list_artifact_tags`, fix to return only distinct values

- mlrun/datastore/datastore.py
- tests/system/feature_store/test_feature_store.py
[ML-2779](https://jira.iguazeng.com/browse/ML-2779)
> [DataStore] Fix get_or_create_store() to use netloc instead of endpoint

- mlrun/utils/http.py
- tests/rundb/test_unit_httpdb.py
The retry we added to mlrun was on certain types of exceptions (and then it checks the exception string for the specific error). Among them was the `ConnectionError`. However, the package `requests` uses it’s own custom `ConnectionError` which doesn’t inherit from python’s `ConnectionError`, instead it inherits from `IOError`.
Changed the mechanism to catch all `Exception`s and only classify the error by looking at the exception string.
> [API] Make the HTTP retry mechanism more generic

- mlrun/utils/http.py
Optimize logic by using a generator instead of compiling to a list first
```
▶ python3 -m timeit 'all(x for x in range(1000))'  
500000 loops, best of 5: 531 nsec per loop
▶ python3 -m timeit 'all([x for x in range(1000)])'
10000 loops, best of 5: 40.6 usec per loop
```
> [API] Optimize HTTP Retry Mechanism

- mlrun/api/db/base.py
- mlrun/api/db/filedb/db.py
- mlrun/api/db/sqldb/db.py
- tests/api/api/test_tags.py
Fixes https://jira.iguazeng.com/browse/ML-2746
- changed the way we are currently listing artifacts for when we run `tag` actions
- added `use_tag_as_uid` to note to the `list_artifacts` to use the tag it receives as `uid` because currently `list_artifacts` doesn't receives uid explicitly but rather through the `tag` argument and then has some logic to infer whether it got uid or actual tag, this becomes problematic where the uid of an artifact can be `latest` which also matches tags.
> [Artifacts] Fix tag artifacts when logging artifacts through `project.log_artifact`

- requirements.txt
[ML-2643](https://jira.iguazeng.com/browse/ML-2643)
> [Requirements] Bump v3io-py and v3io-fs (#2555)

- tests/system/feature_store/test_feature_store.py
which was broken by the addition of `set_index` in #2348.
> [Tests] Fix `test_pandas_write_parquet`

- .github/workflows/system-tests-enterprise.yml
- automation/system_test/cleanup.py
- No actual need to run the cleanup of the docker registry after each type of system tests, rather just at the start of a new CI run.
- We experienced issues regarding the datanode docker registry caching, this was caused after deleting multiple images from the datanode docker registry, we weren't able to pull specific layers of images needed for the run. Found [this ](https://stackoverflow.com/questions/55971691/docker-pull-fails-for-some-layers-from-self-hosted-registry) , for us seems like restarting the container was enough to resolve the issue.
> [System Tests] Change order of system tests cleanup and add datanode docker registry restart

- mlrun/runtimes/function.py
- mlrun/utils/__init__.py
- mlrun/utils/clones.py
When working with fine-grained-tokens, the existing way of embedding token in the URL is not working anymore. Instead, one has to use `oauth2:<token>`. 
This fix identifies the type of token based on the token prefix as noted [here](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/about-authentication-to-github#githubs-token-formats), and if it is a fine-grained-token, shifts to using the new format.
*Note:* The git notifications flow is using a different mechanism to work with Git (issuing direct REST calls, rather than work with `GitPython`), and uses command headers to submit tokens. I haven't modified this flow, as it is expected to continue working even with fine-grained tokens.
Fixes https://jira.iguazeng.com/browse/ML-2766
> [Projects] Support GH fine grained tokens

- mlrun/config.py
- tests/api/api/test_utils.py
The `files` API is by default blocking access to all storage except v3io. This changes the default behavior to allow access to cloud storage providers - s3, Azure and GCS.
Fixes https://jira.iguazeng.com/browse/ML-2764 (up to the documentation part)
> [API] Adding cloud storage to default allowed file paths

- mlrun/api/main.py
- mlrun/config.py
Added config variable to select uvicorn's keep alive timeout, set it by default to `11`.
While debugging an issue where mlrun was being throttled by cpu (it had 500m cpu limit on the api pod), we noticed some requests would only arrive at the API more than 5 seconds after being by from the client.
This caused the api to drop the client connections upon receiving them as the default keep alive timeout was 5 seconds. While the cpu limit indeed was too small and we subsequently removed it, we still want to increase the default timeout just a bit to give the application some more leeway just in case.
> [API] Configure Uvicorn Keep Alive Timeout

- docs/install/compose.with-jupyter.yaml
- docs/install/compose.yaml
- docs/install/local-docker.md
- docs/tutorial/01-mlrun-basics.ipynb
Fix for - https://github.com/mlrun/mlrun/issues/2102 
Fixes:
- give mlrun network explicit name
- put nuclio function containers on the `mlrun` network
- set nuclio function env var MLRUN_DBPATH to `<host ip>:8080` (mlrun-api)
- mount shared dir in nuclio functions as /home/jovyan/data
- In basics tutorial - change serving function to be based on python3.8 in order to fix the pickling issue (according to https://github.com/mlrun/mlrun/issues/2505)
- update docs to require users to set `HOST_IP`
Because the jupyter image taken in the compose is 1.1.2, and this PR will be merged for 1.2.0, the tutorial will come up still with the old 1.1.2 tutorial without the fix. But you'll still be able to change the function as done in the above issue in order to remedy this.
> Fix Docker Compose Deployment

- mlrun/api/utils/auth/verifier.py
- mlrun/utils/notifications/notification/__init__.py
- mlrun/utils/notifications/notification/base.py
- mlrun/utils/notifications/notification/ipython.py
- mlrun/utils/notifications/notification/slack.py
- mlrun/utils/notifications/notification_pusher.py
- tests/utils/test_notifications.py
If the ipython notification is displayed, the console notification shouldn't be printed.
Added an inverse dependency mechanism to the notifications in order to implement this and allow more inverse dependencies like this in the future.
> [SDK] Fix console notification being printed when also ipython notification is displayed

- mlrun/api/utils/background_tasks.py
In the current fastapi version, there is a bug in the starlette package it uses for the background tasks. The bug causes the task to be cancelled if the client's http connection is closed before the task is done. The bug is fixed in the latest version of starlette & fastapi. We will upgrade in 1.3.0, but until then we will use this workaround to prevent the task from being cancelled all together. See https://github.com/encode/starlette/issues/1438 and https://github.com/tiangolo/fastapi/issues/5606
> [API] Fix Background Tasks Being Cancelled Prematurely

- mlrun/runtimes/function.py
- mlrun/utils/helpers.py
https://jira.iguazeng.com/browse/ML-2819
> [SDK] Support string values in min/max replicas

- requirements.txt
[ML-2859](https://jira.iguazeng.com/browse/ML-2859)
> [Requirements] Bump v3io version to 0.5.20

- mlrun/__main__.py
- mlrun/run.py
- mlrun/runtimes/base.py
- tests/run/assets/handler.py
- tests/run/test_run_local.py
when default_handler was set in the function handler arg in run_function() method was ignored
> [Run] Fix handler param in `run_function` was overwritten by default handler

- mlrun/__main__.py
- mlrun/projects/pipelines.py
- mlrun/projects/project.py
- tests/system/projects/test_project.py
By setting `overwrite=True` when submitting a workflow with schedule, the old schedule of the workflow is deleted before creating the new one.
1.1.x and 1.2.x will support this mechanism that is implemented on the SDK part.
1.3 should contain the refactor for this mechanism into the API with `store_schedule`, `_submit_run`, ...
[ML-2873](https://jira.iguazeng.com/browse/ML-2873)
> [Project] Add option to overwrite workflow schedule [1.1.x] 

- mlrun/__init__.py
- mlrun/datastore/base.py
- mlrun/execution.py
- mlrun/secrets.py
- mlrun/utils/clones.py
- mlrun/utils/notifications/notification/git.py
- tests/utils/test_get_secrets.py
Created a global function `get_secret_or_env` that will attempt to retrieve a secret value from the various locations that we support today:
- An MLRun `SecretsStore`
- A dictionary provided by the user
- Env variables, both "generic" and one with the MLRun prefix for project secrets
Modified some of the code that retrieves secrets to utilize this new function - next steps would be to detect other locations which do the same and transform them to use it.
> [Secrets] Add a global `get_secret_or_env` function to retrieve secret values

- mlrun/__main__.py
- mlrun/projects/pipelines.py
- mlrun/projects/project.py
- tests/system/projects/test_project.py
By setting `overwrite=True` when submitting a workflow with schedule, the old schedule of the workflow is deleted before creating the new one.
1.1.x and 1.2.x will support this mechanism that is implemented on the SDK part.
1.3 should contain the refactor for this mechanism into the API with `store_schedule`, `_submit_run`, ...
[ML-2873](https://jira.iguazeng.com/browse/ML-2873)
> [Project] Add option to overwrite workflow schedule [1.2.x] 

- mlrun/runtimes/mpijob/abstract.py
(cherry picked from commit 773a623e857c6a5b30ab1316061af39c50606076)
> [MPI] Fix local variable `resp` referenced before assignment [1.2.x]

- mlrun/model.py
https://jira.iguazeng.com/browse/ML-2907
When calling `run.outputs/run.output/run.artifacts` we were waiting until that run reaches terminal state, because only then the run actually contains the outputs. This was spamming the user with the run logs because we were pulling the run state using get logs rather than get state. Changed the behavior to pull state when calling those functions. 
Also added a log message explaining why calling those methods might take time when the run is not in terminal state.
Before:
Now:
> [Run] Fix outputs wait for completion

- mlrun/execution.py
- mlrun/secrets.py
- tests/utils/test_get_secrets.py
`get_secret_or_env` now has a single parameter `secret_provider` which can also be a `SecretsStore`.
This fixes a flow in `clone_git` which could get either a dict or a `SecretsStore` and passed it in the wrong parameter.
> [Secrets] Fix `get_secret_or_env`

- mlrun/__init__.py
- mlrun/__main__.py
- mlrun/datastore/datastore.py
- mlrun/db/filedb.py
- mlrun/runtimes/local.py
- mlrun/utils/helpers.py
- tests/api/conftest.py
- tests/common_fixtures.py
- tests/test_datastores.py
Added global variable for resolving whether we are running as the API, this is being done by passing `MLRUN_IS_API_SERVER` when executing `mlrun db` CLI.
Had to change the fileDB implementation due to order of imports caused by fileDB.
To resolve the import issue, I had to change the way that we currently "connect" to the datastore inside the fileDB.
Error I experienced:
```
2022-12-06T16:56:00.6419351Z [1m[31mE                 File "/mlrun/mlrun/config.py", line 1068, in <module>[0m
2022-12-06T16:56:00.6419540Z [1m[31mE                   _populate()[0m
2022-12-06T16:56:00.6419823Z [1m[31mE                 File "/mlrun/mlrun/config.py", line 898, in _populate[0m
2022-12-06T16:56:00.6420016Z [1m[31mE                   _do_populate()[0m
2022-12-06T16:56:00.6420305Z [1m[31mE …
```
> [DataStore] Fix how we resolve if running as API

- mlrun/feature_store/api.py
Only if we created it in the first place. This shuts the Java gateway down as well, so that a subsequent `ingest` will get the latest environment variables. 
[ML-2933](https://jira.iguazeng.com/browse/ML-2933)
> [Spark] Shut spark context down when `ingest` completes

- mlrun/run.py
- tests/api/api/test_utils.py
- tests/runtimes/test_run.py
When a function name contains illegal characters (underscores and whitespaces), `code_to_function` normalizes the name but `new_function` doesn't, which fails the function deployment.
This PR aligns `new_function` to normalize function names same as in `code_to_function`.
Fixes https://jira.iguazeng.com/browse/ML-2942
> [Run] Normalize function name in `new_function`

- mlrun/run.py
- tests/api/api/test_utils.py
- tests/runtimes/test_run.py
Backport of #2696
When a function name contains illegal characters (underscores and whitespaces), code_to_function normalizes the name but new_function doesn't, which fails the function deployment.
This PR aligns new_function to normalize function names same as in code_to_function.
Fixes https://jira.iguazeng.com/browse/ML-2942
> [Run] Normalize function name in `new_function` [1.2.x]

- mlrun/api/api/endpoints/schedules.py
- mlrun/api/crud/secrets.py
- mlrun/api/utils/scheduler.py
- mlrun/k8s_utils.py
- tests/api/conftest.py
- tests/api/utils/test_scheduler.py
Refactor the way scheduled-tasks access-keys were maintained and exposed. The access-keys were kept as a special type of project-secrets, and were exposed to the user if performing `GET` REST APIs with the `include-credentials` parameter.
After this change, the access-keys are using the MLRun auth-secret mechanism, which generates k8s secrets per access key, and exposes to the user a reference to the access-key with a one-way hash value that identifies it. This aligns with the way access-keys are maintained in MLRun runtimes. Now, even when asking to `include-credentials` the actual access-key is not exposed but rather just the key reference.
Other changes done as part of this fix:
* The user can specify an access-key when creating/modifying a schedule. This value (passed in the …
> [Schedules] Scheduled tasks access-key usage refactor

- mlrun/datastore/targets.py
In the past, this was problematic because the `storage_options` parameter was only introduced in pandas 1.2.0. We now restrict pandas to >=1.2 anyway, so we can count on this parameter existing.
[ML-2976](https://jira.iguazeng.com/browse/ML-2976)
> [Datastore] Fix _write_dataframe to pass `storage_options` to pandas write operations [1.2.x]

- mlrun/artifacts/dataset.py
- mlrun/execution.py
- mlrun/projects/project.py
- tests/artifacts/test_dataset.py
Port to development of #2698 .
Change the behavior of the `stats` argument in `log_dataset()` accordingly:
- if `stats=False` explicity: do not set the artifact stats.
- if `stats=True` explicitly: set the artifact stats.
- if `stats` is None (not given): set the artifact's stats only if the dataframe is small (columns <= 100, artifact length < 1000)
Also added unit tests.
Fixes https://jira.iguazeng.com/browse/ML-2901
> [Artifacts] Set dataset stats according to `stats` flag in `log_dataset`

- mlrun/feature_store/steps.py
- tests/system/feature_store/test_feature_store.py
https://jira.iguazeng.com/browse/ML-2994?filter=-1&jql=resolution%20%3D%20Unresolved%20AND%20assignee%20in%20(currentUser())%20order%20by%20updated%20DESC
includes #2712 changes
[ML-2994](https://jira.iguazeng.com/browse/ML-2994)
> [Serving] Fixing - OneHotEncoder with pandas engine - fails when the values has spaces or hyphens in them

- mlrun/__init__.py
- mlrun/__main__.py
- mlrun/config.py
- mlrun/datastore/datastore.py
- tests/api/conftest.py
- tests/common_fixtures.py
- tests/test_convenince_methods.py
- tests/test_datastores.py
* MLRun will look for env file in `~/.mlrun.env` upon import (if the MLRUN_ENV_FILE var was not set)
* use new `mlrun config set` command to update the default or specified .env files
> [CLI] Support default .env file location + CLI "config set" command

- mlrun/api/utils/scheduler.py
- tests/api/utils/test_scheduler.py
Fix incorrect label handling when reloading from DB and converting from old schedules, when the schedules had labels - was assuming each label is a dict while they are objects. Modified tests to cover this flow.
Fix [ML-3014](https://jira.iguazeng.com/browse/ML-3014)
> [Schedules] Fix label handling when reloading schedules (ML-3014)

- mlrun/artifacts/manager.py
- tests/artifacts/test_artifacts.py
- tests/artifacts/test_model.py
…t `upload=False` [1.2.x] (#2704)
(cherry picked from commit 2dc67dbd66949ec9fdc11cd4aaaef9aee97c93fa)
> [Artifacts] Don't resolve artifact `target_path` if explicitly request `upload=False`

- mlrun/runtimes/sparkjob/abstract.py
When `lastSubmissionAttemptTime` is not yet populated by k8s, it fails on getting the completion time.
> [Runtime] Fix resolving completion time

- mlrun/platforms/other.py
Added more warnings and better description to the `mount_s3` function, so that users are aware that credentials may be exposed after using it.
Related to [ML-3015](https://jira.iguazeng.com/browse/ML-3015)
> [Docs] Better docstring for `mount_s3`, added warnings

- mlrun/execution.py
- mlrun/projects/project.py
The `local_path` flag in `log_dataset` accepts a path to a local dataframe file, which will be uploaded to the datastore if exists.
This wasn't portrayed well in the docstring and caused some confusion.
https://jira.iguazeng.com/browse/ML-2900
> [Docs] Improve `log_dataset` docstring wrt `local_path` flag [1.2.x]

- mlrun/platforms/other.py
(cherry picked from commit bdaf21fd52db996c7658740a26a119567bc3e877)
Back-porting #2737
> [Docs] Better docstring for `mount_s3`, added warnings (#2737) [1.2.x]

- tests/common_fixtures.py
- tests/conftest.py
- tests/run/assets/__init__.py
- tests/run/assets/hyper_func.py
- tests/run/test_hyper.py
moved hyper param test func out - when using `new_function().run(...handler=Y)` with dask, it pickles the object and once being distributed (parallel >1), each worker loads the pickled object along with its import, thus, since the function was part of the module which imported conftest, it then imported and executed `conftest` multiple times in parallel. 
2 things was done on this pr to avoid this scenario
1. moved the hyper func to be in its own module (wont import conftest and/or execute any independent code)
2. ensured no non thread-safe code is executed when importing conftest
> [Test] fix mkdir race condition - round 2

- mlrun/execution.py
- mlrun/projects/project.py
Port #2743 to development
The `local_path` flag in `log_dataset` accepts a path to a local dataframe file, which will be uploaded to the datastore if exists.
This wasn't portrayed well in the docstring and caused some confusion.
https://jira.iguazeng.com/browse/ML-2900
> [Docs] Improve `log_dataset` docstring wrt `local_path` flag

- mlrun/execution.py
- mlrun/runtimes/base.py
- tests/api/api/test_submit.py
- tests/projects/test_project.py
Fixes https://jira.iguazeng.com/browse/ML-2862
There is a bug in `orjson` which allows int128 variables to be deserialized from JSONs but not serialize back to JSONs. (https://github.com/ijl/orjson/issues/116)
This causes a bug in which we get a request for a run with a large int as one of its parameters, it is properly received, run and saved in the database. However any and all responses which contain the parameter, fail to serialize and cause a 500 error response, effectively denying service for the most requests in the relating project.
As this bug isn't easily remedied, and `orjson` have no plans on fixing it, we need to validate upon run requests that no int parameter is larger than int64. We need to do this for both the parameters and hyperparameters, which is why the validation is …
> [API] Fix run paramaters larger than int64 corrupting projects

- .github/workflows/system-tests-opensource.yml
Remove full deployment flag from MLRun CE deployment in open source system tests. The new development chart (`0.5.1-rc1` and up) doesn't support the flag and always installs the full deployment now.
> [CI] Fix Open Source System Tests Fail Deploy

- mlrun/datastore/sources.py
- mlrun/feature_store/api.py
[ML-3046](https://jira.iguazeng.com/browse/ML-3046)
> [Spark] Use `FeatureSet`'s `timestamp_key` as fallback for source `time_field` [1.2.x]

- mlrun/feature_store/feature_set.py
- mlrun/serving/states.py
Small changes to feature-set graph:
* If multiple targets of the same kind were defined, the plot would show a single target with 2 arrows. Fixed that to show separate targets
* Added the target kind to the graph if the kind is not the same as the name (pretty much everything other than the default targets). 
A `before` example:
An `after` example of a similar, resulting graph:
> [FeatureStore] Fixing graph plot with multiple targets of same kind + adding storage kind to plot

- mlrun/artifacts/base.py
Code had a leftover `_dict_fields` in `DirArtifact` which caused dir artifacts to serialize themselves to dictionary as legacy artifacts. This caused almost no issues since we're fully backwards compatible, except for calling `export()` on the artifact which is not supported in legacy artifacts.
Fixes https://jira.iguazeng.com/browse/ML-3073
> [Artifacts] Serialize `DirArtifact` to dictionary using new format

- mlrun/artifacts/base.py
Back-porting #2778 
(cherry picked from commit fb2f4a70b8b5b942d1824583b2bef92d18d28e4a)
> [Artifacts] Serialize `DirArtifact` to dictionary using new format (#2778) [1.2.x]

- mlrun/feature_store/feature_set.py
- mlrun/serving/states.py
Back-porting #2766 
(cherry picked from commit 183506b20a25b5b2364a97d2d76fc8bf76c8f2db)
> [FeatureStore] Fixing graph plot with multiple targets of same kind + adding storage kind to plot (#2766) [1.2.x]

- mlrun/run.py
https://jira.iguazeng.com/browse/ML-3069
due to incompatibility between bokeh 2.0.2 (currently shipped with iguazio jupyter until moving to python 3.9) and Jinjja2 3.1.2 we get an import error when importing bokeh.
we don't want to explode because bokeh is not always needed. log an error to let the user know how to install the correct version of bokeh and continue.
> [Run] Ignore bokeh installation with warning on import error

- mlrun/run.py
(cherry picked from commit e484fcbc34aefb9c2145ef3758d6238a8514c33d)
backports #2791
> [Run] Ignore bokeh installation with warning on import error [1.2.x]

- mlrun/api/crud/model_monitoring/model_endpoint_store.py
- tests/api/api/test_model_endpoints.py
When applying `delete_model_endpoints_resources()` (which is automatically called through the delete project API) to delete the model endpoint resources, the path for the TSDB resources was generated with an invalid value. 
In this PR we fix that bug and validate that the TSDB path value is generated as expected in the deletion process. 
A relevant JIRA ticket for this bug: https://jira.iguazeng.com/browse/ML-3094.
> [Model Monitoring] Fix model endpoints TSDB path value when deleting resources

- mlrun/projects/pipelines.py
> [Projects] Notify Slack when scheduled load project failed  [1.1.x]

- docs/install/local-docker.md
Add note about avoiding localhost or 127.0.0.1 in HOST_IP. It generated a few issues during 'deploy_function' or 'invoke'.
> [Docs] docker-compose, HOST_IP improvement

- mlrun/__main__.py
Until now when a user set secrets in the CLI (mlrun project function) it added the secrets to the proj object but does not save it in the project itself (does not present in the UI under secrets) causing an issue when a user will try to run for example scheduling workflow that needs those secret it will not found any secrets because they are saved only in the proj object.
I kept the original code lines and add proj,.set_secrets to take the secrets and save them in the project for later use
for 1.1.3
> [CLI] Add set project cli - for 1.1.x

- mlrun/config.py
- mlrun/projects/pipelines.py
- mlrun/utils/notifications/notification/base.py
- mlrun/utils/notifications/notification/slack.py
- mlrun/utils/notifications/notification_pusher.py
1. Added also small bug fixes:
- bug 1:
> when sending `NotificationSeverity.Error` to `SlackNotification.send()` it prints "NotificationSeverity.Error" instead of the value - "error"
The correction:
> The class `NotificationSeverity`  inherit now from `str` as well.
- bug 2:
> Using str instead of NotificationType
The correction:
> Casting to the right object.
2. Example for the error in slack:
4. Added `schedule` parameter to `load_and_run` for avoiding double push to notifiers when we are not scheduling a workflow.
5. Updated the way of getting env/secrets with `get_secret_or_env` in `SlackNotification`
Will be BP to 1.2.x
> [Projects] Slack notify remote workflow

- .github/workflows/build.yaml
- Makefile
- hack/ci/free-space.sh
Looks like our models-gpu failed to be built/pushed due to lack of space. removed some unneeded packages prior to building/pushing images
> [CI] Perform cleanup prior to build images

- Makefile
- dockerfiles/models-gpu/Dockerfile
- dockerfiles/models-gpu/prebaked.Dockerfile
Build and push cuda images to quay to avoid building cuda images on each build. Cuda image and installation tend to fail and takes too long. To save time and avoid transient failures, I've built `prebake.Dockerfile` image from models-gpu and pushed to quay, from now on, models-gpu would be based on that very prebake image and install mlrun atop.
> [Images] Prebake cuda image

- mlrun/__main__.py
- tests/system/projects/test_project.py
Partially fixed [ML-2931](https://jira.iguazeng.com/browse/ML-2931)
When trying to schedule a workflow that is already scheduled without `--overwrite-schedule` the error message will fit the format of the CLI parameters instead of the SDK one.
> [CLI] Fix fail message of overwrite schedule [1.1.x]

- mlrun/db/httpdb.py
- mlrun/runtimes/base.py
Fix for - https://jira.iguazeng.com/browse/ML-3066
Continuation of https://jira.iguazeng.com/browse/ML-3029
During `submit_job` if an exception is raised during the http request, we try to update the run's state to `error`. However, if we receive a 400 status code from the API, the run was never created and we shouldn't try to update the run state.
> [SDK] Fix `submit_job` tries to update run state when run wasn't created [1.2.x]

- mlrun/projects/project.py
https://jira.iguazeng.com/browse/ML-3064
If url is None, the context will be logged:
```
> 2022-12-27 12:15:14,513 [info] loaded project my-project from ./ and saved in MLRun DB
```
> [Project] Fix `load_project` log message

- mlrun/db/httpdb.py
- mlrun/runtimes/base.py
porting - https://github.com/mlrun/mlrun/pull/2822 
During submit_job if an exception is raised during the http request, we try to update the run's state to error. However, if we receive a 400 status code from the API, the run was never created and we shouldn't try to update the run state.
> [SDK] Fix submit_job tries to update run state when run wasn't created

- mlrun/api/api/endpoints/frontend_spec.py
- mlrun/api/crud/client_spec.py
- mlrun/api/schemas/client_spec.py
- mlrun/api/schemas/frontend_spec.py
- mlrun/config.py
- mlrun/db/httpdb.py
- tests/api/api/test_client_spec.py
- tests/api/api/test_frontend_spec.py
Added to the client spec the fields:
- "default_feature_store_data_prefix"
- "ce_version" (in addition to "ce_mode")
So the UI can display the correct values depending on the deployment in which it exists
> [API] Add Fields to Client Spec for Use in UI

- tests/system/base.py
- tests/system/conftest.py
adhere to slack limitation of how long text messages can be and taking the last part of report, with the assertion failure
> [CI] Fix system test long failing reports

- mlrun/api/api/endpoints/runs.py
- mlrun/api/db/base.py
- mlrun/api/db/filedb/db.py
- mlrun/api/db/sqldb/db.py
- mlrun/db/base.py
- mlrun/db/filedb.py
- mlrun/db/httpdb.py
- mlrun/db/sqldb.py
- tests/api/api/test_runs.py
- tests/integration/sdk_api/httpdb/test_runs.py
Change the `list-runs` API to support querying a list of uids, rather than a single one.
This is for the UI purposes, to be able to query with a single API call the list of all runs that construct a pipeline. Support added to the REST API and to the sdk (`httpdb` etc.).
The REST API is automatically backwards-compatible, since a list is constructed of multiple parameters of the same name, hence a single name keeps being supported and interpreted as a list of length 1.
For example, the "old format":
`GET .../runs?project=<proj>&uid=<uid1>`
is still supported, along with the multi-uid variant:
`GET .../runs?project=<proj>&uid=<uid1>&uid=<uid2>&uid=<uid3>...`
The sdk was modified to support a union of either a `str` or a `List[str]`.
This implements …
> [API] Support to request list of uids through `list-runs` endpoint

- mlrun/db/__init__.py
```
import mlrun
> 2023-01-01 15:35:14,645 [warning] Could not detect path to API server, Using Deprecated client interface
> 2023-01-01 15:35:14,645 [warning] Please make sure your env variable MLRUN_DB_PATH is configured correctly to point to the API server!
```
> [FileDB] Add warning message when initializing FileRunDB

- mlrun/projects/project.py
- tests/projects/test_project.py
Fixes https://jira.iguazeng.com/browse/ML-3150
> [Project] Fix `sync_functions` to sync the function names from the `project.spec._function_definitions` map

- mlrun/projects/project.py
- tests/system/api/test_secrets.py
- tests/system/conftest.py
Other than sending the snippet of each failing report, send a session report including each passed/failing report and its relation to mlrun's component. e.g.:
> [Tests] Send system test session reports

- mlrun/projects/project.py
- tests/projects/test_project.py
(cherry picked from commit 501d50944e015b76dd63e4b7affe13da1061b11c)
> [Project] Fix `sync_functions` to sync the function names from the `project.spec._function_definitions` map [1.2.x]

- mlrun/api/db/sqldb/db.py
- mlrun/api/utils/scheduler.py
- tests/api/utils/test_scheduler.py
https://jira.iguazeng.com/browse/ML-3075
We are skipping runs when the concurrency limit is exceeded.
In such cases, we also need to update the next run time in the db. Otherwise, we get a "next run time" that has already passed.
> [Scheduler] Update next run time after skipping run [1.2.x]

- mlrun/api/crud/secrets.py
- mlrun/api/utils/scheduler.py
- mlrun/k8s_utils.py
- tests/api/conftest.py
Since `read_auth_secret` is expected to return a tuple it would raise an exception when unpacking `None` as it's not iterable.
Instead of getting `cannot unpack non-iterable NoneType object` exception, raise a proper one.
> [K8s] Failed to read secret exception

- mlrun/projects/operations.py
- mlrun/projects/project.py
- mlrun/run.py
- tests/projects/test_project.py
- tests/system/demos/sklearn/test_sklearn.py
- tests/system/model_monitoring/test_model_monitoring.py
- tests/system/projects/assets/kflow.py
- tests/system/projects/assets/newflow.py
- tests/system/projects/test_project.py
`sklearn_classifier` from the functions marketplace is no longer supported and might not be working following the release of `scikit-learn` v1.2. In this PR, we update the system tests to use the `auto_trainer` function (also from the functions marketplace - https://github.com/mlrun/functions/blob/master/auto_trainer/auto_trainer.py) instead of the `sklearn_classifier`.
> [Tests] Replace `sklearn_classifier` with `auto_trainer` in tests and examples

- mlrun/api/utils/scheduler.py
- tests/api/utils/test_scheduler.py
Raise more informative error when trying to update a schedule that doesn't exist in the `APScheduler` memory
> [Scheduler] Fix missing job in scheduler error message

- mlrun/model_monitoring/model_monitoring_batch.py
- mlrun/model_monitoring/stream_processing_fs.py
Replace `timeout_secs` with `flush_after_seconds` when generating the `storey.TSDBTarget` within the model monitoring stream graph. This PR is a fix for https://jira.iguazeng.com/browse/ML-3067. The `timeout_secs` is an outdated parameter in `Storey` that will be removed from the target documentation as well (https://github.com/mlrun/storey/pull/406).
Basically, the events will be written into the TSDB only when:
1 - we pushed at least 100 events.
2 - we pushed at least 1 event but less than 100 in the last 5 min interval.
There has been a bug in the 2nd condition, in which the events were not written into the TSDB although we have pushed several events (<100) and we have waited "long enough".
> [Model Monitoring] Fix the timeout waiting before writing the events into the TSDB

- mlrun/feature_store/retrieval/job.py
This attribute is not present for every function.
> [Feature Store] Fix unsafe access to `output_path`

- mlrun/api/api/deps.py
- mlrun/api/api/endpoints/grafana_proxy.py
- mlrun/api/utils/auth/verifier.py
- mlrun/api/utils/clients/iguazio.py
- tests/api/api/test_frontend_spec.py
- tests/api/api/test_grafana_proxy.py
- tests/api/api/test_submit.py
- tests/api/utils/clients/test_iguazio.py
Introducing iguazio async  http client. currently, it inherits the sync client, which means, all *public* methods the sync client will be run under async http client inside an awaitable thread. coroutine functions that async expose will be run natively on the event loop.
In this PR, I have added support for both `verify_request_session` and `verify_session` which effectively make sure the session verification dependency for our api endpoints would be 100% asynchronous.
The changes I've made to the `test_iguazio.py` are such that
- I test all functions for both async and sync iguazio http clients. 
- for `verify_request_session` and `verify_session` I do check for aiohttp response + request response
- I tried to consolidate as much as possible between two requests/aioresponses mockers
> [Iguazio] Add async client

- tests/api/utils/test_scheduler.py
wait until the run is created instead of checking once
> [Scheduler] Fix transient unit test failures take 2

- mlrun/runtimes/pod.py
- tests/api/runtimes/test_kubejob.py
Added an sdk - `set_image_pull_configuration` to modify `func.spec.image_pull_secret` and `func.spec.image_pull_policy`, instead of directly accessing these values through the spec.
[ML-3204](https://jira.iguazeng.com/browse/ML-3204)
> [Runtimes] Add an API to control image pull configuration

- mlrun/projects/project.py
- tests/artifacts/test_artifacts.py
- tests/projects/test_project.py
a fix for: https://jira.iguazeng.com/browse/ML-3070
project.import_artifact now searches in context path instead of current directory
> [Project] Fix working dir consistency behavior of project functions

- mlrun/datastore/targets.py
- mlrun/feature_store/ingestion.py
- tests/system/feature_store/test_feature_store.py
Also fix [ML-3251](https://jira.iguazeng.com/browse/ML-3251) by deduplicating each chunk before sending to frames.
> [FeatureStore] Fix pandas-engine passthrough-fset handling and deduplicte to prevent frames from out-of-order writes to online target

- mlrun/utils/regex.py
- tests/api/api/test_tags.py
- tests/utils/test_helpers.py
fix for: https://jira.iguazeng.com/browse/ML-2829
We discovered that underscore is permitted in k8, so we'd like to support it as well. Reverting the changes that prevent it in the SDK.
> [Tags] Allow artifact tags to contain underscore 

- mlrun/api/main.py
- mlrun/api/utils/clients/chief.py
- mlrun/utils/async_http.py
It is observed that when requests are being proxied from worker to chief, aiohttp quote the cookies (https://github.com/aio-libs/aiohttp/issues/2571) in a way that iguazio be cannot understand the value of the cookie. since the cookie includes special characters (such as double quotes), the actual request that goes to the chief includes malformed value.
to avoid such scenario, the client will first quote (url quoting) the content and by that, will protect the value from being escaped by quotes (e.g.: `"` -> `"\""`).
In addition, added few information when request / failure is being log as a result of debugging this issue.
Internal - https://jira.iguazeng.com/browse/ML-3252
> [Chief] Fix double quoting cookies

- mlrun/api/utils/clients/chief.py
- mlrun/api/utils/clients/iguazio.py
- tests/api/utils/clients/test_chief.py
Following up https://github.com/mlrun/mlrun/pull/2942 - I have missed the case where the cookie might be already quoted. for such cases, make sure to unquote first (so content would be raw) and then quote. Added UT as well
In addition, fixed the `on request error` flow where it didnt "await" on request body correctly.
> [Chief] Follow up fix for session escaping

- dockerfiles/base/requirements.txt
- extras-requirements.txt
- setup.py
- tests/test_requirements.py
Due to changes in `plotly==5.12.0` that uses 'latin-1' encoding, we freeze temporarily `plotly`.
This issue affects logging `plotly` artifacts, as you can see here [ML-3255](https://jira.iguazeng.com/browse/ML-3255).
> [Requirements] Freeze `plotly` version

- .github/workflows/system-tests-enterprise.yml
- .github/workflows/system-tests-opensource.yml
Following up https://github.com/mlrun/mlrun/pull/2952
Fix did not include the piping to the github output envvar, thus, envvars were empty.
> [CI] Fix CI not creating env vars correctly

- .github/workflows/build.yaml
This is follow up of  https://github.com/mlrun/mlrun/pull/2952
> [CI] Fix build workflow not outputs registries to `GITHUB_OUTPUT`

- mlrun/feature_store/steps.py
- tests/feature-store/test_steps.py
Up to now, the `Imputer` did not replace none types such as `np.nan`, `pd.NA`, `pd.NaT` with the default value, only simple `None` was take into consideration.
[ML-3258](https://jira.iguazeng.com/browse/ML-3258)
> [Feature Store] Fix `Imputer`'s `None` types check

- docs/projects/run-build-deploy.md
- mlrun/projects/pipelines.py
- mlrun/projects/project.py
- mlrun/runtimes/base.py
- tests/projects/test_project.py
- tests/system/projects/test_project.py
Add a `default_image` property to project spec, that will set the `image` property for project functions, if not explicitly specified in the function itself.
The `default_image` is applied:
* When enriching the function, as part of function retrieval from the project. This is used in the various image-related project APIs, such as `project.run_function` etc.
* When setting a new `default_image` for a project which already had one, the default image will be replaced in all already-enriched functions held by the project that had no image (after the enrichment) or used the previous `default_image`.
Also did some deprecation warning fixes per the guidelines in https://jira.iguazeng.com/browse/ML-3104
> [Projects] Add project default image

- mlrun/feature_store/feature_set.py
- mlrun/features.py
- tests/system/feature_store/test_feature_store.py
https://jira.iguazeng.com/browse/ML-3282
This pr handling 2 bugs : 
1. Setting feature of feature set with the same name of is entity - raise an error.
2. When Init `RegexValidator` class `from_dict`  so `re.compile` raised an error - using `self.regex` directly.
> [Feature Store] Validator for features only & Init `RegexValidator` class `from_dict` 

- mlrun/db/httpdb.py
- mlrun/projects/project.py
Label filters are expected to be passed to the `list_artifacts` function as a list of strings, but this was not documented anywhere. What's worse - users could pass a dictionary without getting any errors, but the labels would be passed to the backend as a list containing just the dictionary keys, which would generate unexpected results.
Fixed the `list_artifacts` method to correctly accept a dictionary, and added docstrings for `httpdb` and for `MLRunProject` methods - both `list_artifacts` and `list_models`.
Fixes [ML-3283](https://jira.iguazeng.com/browse/ML-3283)
> [Artifacts] Fix labels handling and documentation in `list_artifacts` and `list_models`

- mlrun/api/api/endpoints/functions.py
- mlrun/runtimes/function.py
Ensure that http errors being raised during nuclio api calls are converted to mlrun http errors so that the real http code would be returned to the client, other than a generic 500.
This is also useful to retain the error string itself along with the response chaining.
> [Nuclio] Fix propagating http errors

- tests/system/feature_store/test_spark_engine.py
handle system-test failure:
```
FAILED tests/system/feature_store/test_***_engine.py::TestFeatureStoreSparkEngine::test_ingest_to_redis
```
> [Spark] Skip test when no redis server is set

- go/cmd/logcollector/main.go
- go/pkg/common/consts.go
- go/pkg/common/utils.go
- go/pkg/services/logcollector/logcollector_test.go
- go/pkg/services/logcollector/server.go
- go/pkg/services/logcollector/statestore/file/client.go
- go/pkg/services/logcollector/test/logcollector_test.go
- go/proto/log_collector.proto
- mlrun/api/utils/clients/log_collector.py
- mlrun/config.py
- tests/api/utils/clients/test_log_collector.py
- tests/integration/sdk_api/base.py
In this PR there are several additions and fixes wrt the log collector gRPC service:
- Add `HasLogs` endpoint in the log collector server, for the api to call before calling `get_logs`. This enables the api to gracefully return empty logs to the client if the run has no logs to retrieve, instead of exploding.
- Align env vars according to https://github.com/v3io/helm-charts/pull/913.
- Limit the log collector to monitor goroutines, update the state file and call `StartLogs` for runs in progress only if it is in the chief pod (according the the env var `MLRUN_HTTPDB__CLUSTERIZATION__ROLE`.
- Support error codes in the grpc responses. Currently supports `NotFound` and `InternalError`.
- Fix log files and state file paths.
- Log stack trace in case of unexpected internal errors.
> [Log Collector] Add HasLogs endpoint + additional fixes

- go/pkg/services/logcollector/server.go
- go/pkg/services/logcollector/statestore/file/client.go
- mlrun/api/db/base.py
- mlrun/api/db/filedb/db.py
- mlrun/api/db/sqldb/db.py
- mlrun/api/main.py
- mlrun/config.py
- tests/api/db/test_runs.py
- tests/api/test_collect_runs_logs.py
This addition is for cases when the API was upgrade from legacy mode to sidecar mode. 
Which in this case we have two kind of scenarios we want to make sure we catch:
- Run is still running from previous log collection method, so we would like to start collecting logs for that run with the new method.
- Run changed it state while API was down and requires logs to be picked up.
Log collector service :
- Removed from directory generation to addition of `/logs` in the path as it already being passed in the helm chart
- Renamed the `metadata` generated directory to `_metadata` so it won't conflict with user project names
> [API] Add collect logs method on startup of API

- go/pkg/common/k8s/k8s.go
- mlrun/db/httpdb.py
- mlrun/utils/http.py
`stream_request` is unused by anyone, so it can be removed from `api_call`.
Also, align sidecar's namespace env var with the api's env var.
> [API] Remove stream_request from api call

- tests/api/test_collect_runs_logs.py
This test sometimes fails in CI on list with different order.
> [API] Fix CI test failure on list order

- .github/workflows/ci.yaml
- mlrun/api/main.py
- mlrun/api/middlewares.py
- mlrun/api/schemas/constants.py
- tests/api/api/framework/__init__.py
- tests/api/api/framework/test_middlewares.py
- tests/api/test_logging_middleware.py
To allow mlrun ui reload its cache post upgrade, it is required to indicate whether a clear cache is required.
the mechanism suggested is that each response will hold mlrun backend version. it is up to the client (ui) to send its cached / current `X-MLRun-UI-Version` header which its value is the ui version. The API will match both versions (backend running version and ui version, and if versions are not matched, the ui will be asked to reload its cache)
> [API] Add middlewares to ensure ui reset cache upon mlrun upgrades

- tests/system/projects/test_project.py
Replace `"should"` to `"must"`
> [Tests] Fix `test_timeout_warning` test

- extras-requirements.txt
- setup.py
until now `graphivz` wasn't a requirement of MLRun but rather an extra requirement which was installed as part of some of our images such as `jupyter` / `ml-base` / `dev-requirements`. as part of supporting both python 3.9 and 3.7 in 1.3.0 it means that users might use their old jupyter and install new conda env with python 3.9, but in that environment we wouldn't have `graphivz` pre-baked so we add `grpahivz` as part of our `[complete]` install which means the `align_mlrun` will install it.
https://jira.iguazeng.com/browse/ML-3239
> [Requirements] Add graphivz to `mlrun[complete]`

- mlrun/config.py
- mlrun/k8s_utils.py
- mlrun/runtimes/function.py
- mlrun/runtimes/pod.py
- mlrun/runtimes/serving.py
- tests/api/conftest.py
- tests/api/runtimes/test_kubejob.py
Adding a global secret capability that is equivalent to project-secrets, but with global scope. The secret name is configured in the MLRun config under `secret_stores.kubernetes.global_function_env_secret_name`, and if it exists, any job that is executed will get all the keys in that secret attached as env variables.
Project secrets will override the global secret, meaning that if the same key is defined in the global secret and in a project secret, the value will be taken from the project secret.
MLRun does not provide a facility for the user to set or manage the global secret content -  this needs to be done externally through `kubectl` or similar. All MLRun does is mounting the secret keys to jobs. MLRun also does not perform any check on the secret name - it is expected that the admin …
> [Runtimes] Add global secret option - secret whose keys will be attached to all functions
