mlrun/mlrun

- mlrun/datastore/targets.py
[ML-3321](https://jira.iguazeng.com/browse/ML-3321)
When target driver is created from a target object, copy the credentials prefix and the secrets to the driver
> [Datastore] Fix BaseStoreTarget from_spec() to set target secrets and credentials_prefix

- mlrun/api/utils/db/backup.py
Fix for https://jira.iguazeng.com/browse/ML-3348 
Currently running migrations in CE fails with
```
> 2023-02-02 15:03:43,597 [info] Checking if migration is needed: {'is_migration_from_scratch': False, 'is_schema_migration_needed': True, 'is_data_migration_needed': False, 'is_database_migration_needed': False, 'is_backup_needed': True, 'is_migration_needed': True}
> 2023-02-02 15:03:43,597 [info] DB Backup is needed, backing up...
> 2023-02-02 15:03:43,606 [error] Failed running shell command: {'command': 'mysqldump --single-transaction --routines --triggers --max_allowed_packet=64000000 -h mlrun-db -P 3306 -u root mlrun > /mlrun/db/mysql/db_backup_202302021503.db', 'stdout': b'', 'stderr': b'/bin/sh: 1: cannot create /mlrun/db/mysql/db_backup_202302021503.db: Directory nonexistent\n', …
```
> [API] Ensure DB Backup Dir Exists Before Migrations In CE

- mlrun/api/crud/model_monitoring/model_endpoints.py
Before deploying the `model-monitoring-stream` nuclio function, we need to validate that this function is yet to be deployed to avoid redeployment. Therefore, this function should be deployed only when we get exception from type `mlrun.errors.MLRunNotFoundError` (and not  `nuclio.utils.DeployError` as it was until this PR).
Please note that if the user has changed his mlrun version and want to redeploy the `model-monitoring-stream` function on existing project with existing `model-monitoring-stream` function, he has to delete this function manually before trying to redeploy it again.
> [Model Monitoring] Fix monitoring stream redeployment exception

- go/cmd/logcollector/main.go
- go/pkg/common/consts.go
- go/pkg/services/logcollector/logcollector_test.go
- go/pkg/services/logcollector/server.go
- go/pkg/services/logcollector/test/logcollector_test.go
gRPC response message is limited by 4MB, thus each message in the `GetLogs` stream response needs to be less than or equal to that.
To not limit the buffer size reading logs from pod according to the same limit, we allow different buffer size for each pool.
The default buffer size are:
- `StartLog` - 10MB
- `GetLogs` - 3.75MB (to allow some overhead)
> [Log Collector] Separate GetLogs and StartLog buffer size

- dockerfiles/jupyter/requirements.txt
- requirements.txt
Added a fix for: [ML-3224](https://jira.iguazeng.com/browse/ML-3224)
> [Requirements] Bump nuclio-jupyter to 0.9.8

- mlrun/db/httpdb.py
- mlrun/projects/pipelines.py
- mlrun/projects/project.py
- mlrun/run.py
- mlrun/utils/helpers.py
Fix for - https://jira.iguazeng.com/browse/ML-3161
TTL wasn't passed from `project.run` to the KFP workflow runner. Added it to the params being passed, and gave the parameter a more indicative description.
> [SDK] Pass Cleanup TTL to Kubeflow Workflow Runner

- go/pkg/services/logcollector/server.go
- go/pkg/services/logcollector/statestore/file/client.go
- go/pkg/services/logcollector/statestore/file/file_test.go
- go/pkg/services/logcollector/statestore/inmemory/client.go
- go/pkg/services/logcollector/statestore/types.go
- go/pkg/services/logcollector/test/logcollector_test.go
The log collector is monitoring runs that are being log-collected, and calls `StartLog` by itself for runs that stopped collecting due to an error or something else.
For restarting the log collection, it needs to get the project name from the persistent state file.
> [Log Collector] Add project name to state log items

- mlrun/api/main.py
- mlrun/api/utils/clients/log_collector.py
- mlrun/runtimes/sparkjob/abstract.py
Spark job pods were missing the `RuntimeClassMode` class mode label and thus weren't found by the log collector.
Also skip logging failure to start logs if `raise_on_error == True`, to remove log duplication.
Fixes https://jira.iguazeng.com/browse/ML-3360
> [Spark] Fix spark job pods not being found

- go/pkg/services/logcollector/server.go
- go/pkg/services/logcollector/statestore/file/client.go
- go/pkg/services/logcollector/statestore/file/file_test.go
- go/pkg/services/logcollector/statestore/inmemory/client.go
- go/pkg/services/logcollector/statestore/types.go
Run UIDs are unique for runs **in the same project**.
This means that the run UID itself is not unique enough for saving log items in the LC's state store.
In this PR the key for the log items in the state for is changed to `<runUID>-<projectName>`.
> [Log Collector] Add project name to state store key

- mlrun/model_monitoring/stream_processing_fs.py
- tests/system/model_monitoring/test_model_monitoring.py
As part of the `model-monitoring-stream` flow, we update the model endpoint record in the KV table with the related fields (e.g. the time of the last request, the number of errors, etc.). Before the update process, the `model-mointoring-stream` is unpacking the labels from the event dictionary into a separated keys and afterwards remove the `unpacked_labels` key from the event dictionary. 
In this PR we fix a bug that was related to the removal of the `unpacked_labels` key at the end of the process which has started due to the new required syntax of Python `3.9` (https://github.com/mlrun/mlrun/pull/2563). 
Note that is is also a fix for [ML-3190](https://jira.iguazeng.com/browse/ML-3190).
> [Model Monitoring] Fix stream processing by removing unpacked labels before updating the KV table

- mlrun/db/httpdb.py
- mlrun/projects/pipelines.py
- mlrun/run.py
- mlrun/utils/helpers.py
The previous function signature was problematic as it included kwargs before positional `*args`. Deprecated the whole function and created a new one with only kwargs.
> [SDK] Fix calls to `new_pipe_meta` not passing `ops`

- requirements.txt
- tests/test_requirements.py
major vulnerability found - https://security.snyk.io/vuln/SNYK-PYTHON-GITPYTHON-3113858
> [Requirements] Bump GitPython to 3.1.30

- mlrun/datastore/targets.py
- mlrun/model.py
- tests/system/feature_store/test_feature_store.py
Fixes `TestFeatureStore::test_split_graph`, which was broken when the fallback on the deprecated parameter was removed in #3075.
> [Datastore] Fix depractations removal - delete all references to `after_state` parameter

- mlrun/datastore/targets.py
- mlrun/model.py
[ML-3398](https://jira.iguazeng.com/browse/ML-3398)
During ingest() and get_online_feature_service() the target/source goes trough serialization/de-serialization process. During that process original "credentials prefix" should be preserved
> [Datastore] Fix target/source serialization to incldue credentials_prefix

- docs/serving/available-steps.md
ML-2709. For discussion, see https://github.com/mlrun/mlrun/pull/2991
> [Docs] Spark engine support for steps: MapValues, Imputer, OneHotEncoder, DropFeatures; DateExtractor (partial) 

- mlrun/runtimes/function.py
To avoid opinionated client, default to 0
> [Nuclio] Set default workers to 0 to allow backend enrichments

- go/pkg/services/logcollector/statestore/types.go
Change the state file key delimiter to `/`, resolving key as `<runUID>/<project>`.
This change is done because `-` is permitted in runUIDs and project names.
> [Log Collector] Change state file key delimiter

- tests/system/feature_store/test_spark_engine.py
The test test_spark_engine.py::TestFeatureStoreSparkEngine::test_get_offline_features_with_spark_engine[True] is failing only in GitHub workflows(not on local machine).
Added print statements for debugging.
> [Tests] Test test_get_offline_features_with_spark_engine: add temp debug logs

- mlrun/projects/project.py
Fixes - https://jira.iguazeng.com/browse/ML-3043 
If a project is pushed while the user hasn't yet configured their git environment, a warning message will appear:
> [SDK] Fix no warning message when pushing project while git is not configured

- mlrun/api/api/endpoints/client_spec.py
- mlrun/api/crud/client_spec.py
- mlrun/config.py
- mlrun/kfpops.py
- tests/api/api/test_client_spec.py
- tests/integration/sdk_api/base.py
KFP workflows are being built on client side and therefore we need to provide the client with the right image to run the kfp step with. 
When running an MLRun step inside a KFP workflow two pods are being created, the first is the KFP step which  is responsible for spawning the actual mlrun job (on another pod) now because we have the whole image enrichments stuff we need to replicate the client environment into the KFP step environment(same mlrun version and python version) so that the pod which is being spawned from the KFP step will be enriched with the right image version.
> [API] Enrich kfp images based on the client versions

- mlrun/runtimes/function.py
- tests/system/runtimes/test_nuclio.py
Create ability for getting url of RemoteRuntime function after deploy.
Note : dashboard is deprecated because security issues
> [Runtimes] Creating an external get_url function

- mlrun/api/api/endpoints/functions.py
- mlrun/api/crud/functions.py
- mlrun/api/db/base.py
- mlrun/api/db/filedb/db.py
- mlrun/api/db/sqldb/db.py
- mlrun/db/sqldb.py
- tests/api/api/test_functions.py
- tests/api/db/test_functions.py
a fix for: https://jira.iguazeng.com/browse/ML-2534
Adding a hash_key filter parameter to `list_functions` so that the UI can query the API for the function tag using the function uri.
> [DB] Add `hash_key` filter to `list_functions`

- automation/system_test/prepare.py
In case of preparation errors, show debug logs
> [CI] Enable verbose logging for enterprise system test preparation

- mlrun/projects/operations.py
- mlrun/projects/project.py
- mlrun/runtimes/function.py
- mlrun/runtimes/kubejob.py
- tests/api/runtimes/test_nuclio.py
Until today we would pass the build secret name to nuclio image pull secret and we would ignore the functions' image pull secret.
Added logic to resolve the secret to set with giving precedence to image pull secret.
Nuclio will use the 1 secret for both the build pod and the deployment.
**NOTE**: With ECR we must differentiate between the secrets. To resolve that nuclio must have the registry provider secret set and it will be used regardless of the secret we provide.
> [Nuclio] Fix image pull secret enrichment

- go/pkg/common/utils.go
- go/pkg/services/logcollector/logcollector_test.go
- go/pkg/services/logcollector/server.go
- go/pkg/services/logcollector/statestore/abstract/client.go
- go/pkg/services/logcollector/statestore/file/client.go
- go/pkg/services/logcollector/statestore/inmemory/client.go
- go/pkg/services/logcollector/test/logcollector_test.go
This PR introduces several fixes to the log collector server:
- The 2 state stores that the sever has were renamed for better readability and usability:
- `stateManifest` - this is the persisted state and it is the source of truth. It depicts which runs should be log collected, and is periodically written to a file for persisting the state in case of pod restarts.
- `currentState` - this state holds the runs that currently have running goroutines collecting logs. It is used for monitoring by going through the runs in the state manifest and verifying they are present in the current state.
- The file state store client has 2 mutex locks - one for the state itself, and one for reading/writing the persisted file. 
There were some race conditions between those two locks that have sometime …
> [Log Collector] Fix lock race conditions and state overwrites

- requirements.txt
- tests/test_requirements.py
Resolve regression tests failure
> [Requirements] Freeze pyarrow version 10.0 to keep ParquetDataset v1

- go/pkg/common/utils.go
When not appending to a file, truncate it by adding the os flag.
> [Log Collector] Truncate file if not appending to it

- mlrun/__init__.py
- mlrun/projects/operations.py
- mlrun/projects/pipelines.py
- mlrun/run.py
- tests/system/examples/dask/test_dask.py
- tests/system/examples/jobs/test_jobs.py
- tests/system/runtimes/test_kubejob.py
- tests/system/test_kfp.py
Fixes https://jira.iguazeng.com/browse/ML-3437
Issue appears when having a pipeline with `run_function` method, as the `run_function` depends on the pipeline context being set prior to running it (which happens when using `project.run()`), while running `run_pipeline` directly doesn't enriches the `pipeline_context` which caused the flow to try submit the pipeline as KFP but the functions inside thought that it has to run locally.
Found out `run_pipeline` should not be used directly - therefore added deprecation warning, left the relevant stuff in the `run_pipeline` and added new `_run_pipeline` which will handle only work on the API which already relies on initialized `pipeline_context` . moved the `pipeline.run()` to use the lightweight `_run_pipeline`.
> [Pipelines] Handle case when running `run_pipeline` directly with `run_function`

- mlrun/api/main.py
- mlrun/runtimes/base.py
- mlrun/runtimes/daskjob.py
- tests/api/test_collect_runs_logs.py
In dask, the pods have a function name label, instead of `run_id`.
When resolving the run's label selector for starting log collection, the `object_id` value should be the function name for dask runtime, and run id for all other runtimes.
In this PR I added the `resolve_object_id` method for the runtime handlers, returning function name for dask, and `run_id` for all other runtimes.
Fixes https://jira.iguazeng.com/browse/ML-3484
> [Dask] Resolve object id label as the function name

- dependencies.py
- extras-requirements.txt
- tests/test_requirements.py
by introducing an upper limit for google-cloud-bigquery (see TODO for details).
[ML-3478](https://jira.iguazeng.com/browse/ML-3478)
> [Datastore] Fix google cloud import error 

- docs/feature-store/basic-demo.ipynb
- mlrun/execution.py
raised by system test: `tests.system.examples.basics.test_db.TestDB.test_db_commands`
Added execution parameters that can be updated during the run to the list of updates.
We then use that list to update the run in the db (reminder we use update and not store since update does not override with `None` values)
> [Execution] Update run params, inputs and outputs

- mlrun/api/api/endpoints/functions.py
- mlrun/config.py
- mlrun/runtimes/function.py
- Changed the pulling interval of the nuclio deploy status to default of 10s, this is because the logs that are being returned to the user are not live logs from the builder container but rather a high level status of the builder status ( averages to 5 lines log output if no errors occurs )   .
- When querying the deploy status we were storing the function on each request, this becomes more and more consuming when the build function process take long time (as bigger the image the longer time it will take), I were able to count 250 store function actions for a single deploy function that took 4min to finish deploying. Therefore I added a validation that checks whether something has changed before storing it to the database.
Both these changes together are expected to reduce the load on the …
> [Nuclio] Fix pulling interval and reduce the amount of storing to the database

- dependencies.py
- extras-requirements.txt
- requirements.txt
Since it's only needed by azure libraries.
> [Requirements] Move pyopenssl requirement to azure extra

- mlrun/utils/clones.py
Cloning a git branch only supported `GIT_TOKEN` as source for git token, unlike the git notifications code that also supported the `GITHUB_TOKEN` parameter.
Added support for `GITHUB_TOKEN` to align our usage across the codebase.
> [Projects] Support `GITHUB_TOKEN` when searching for git token in `clone_git`

- mlrun/__main__.py
- mlrun/projects/operations.py
- mlrun/projects/project.py
- mlrun/runtimes/function.py
- mlrun/runtimes/serving.py
It is has been deprecated internally for a while, expose deprecation warning.
> [Nuclio] Deprecate nuclio dashboard url

- mlrun/db/httpdb.py
- mlrun/utils/http.py
- tests/rundb/test_unit_httpdb.py
bottom line, retry on cases where we hit read timeout
https://jira.iguazeng.com/browse/ML-3511
> [HTTP] Make retryable HTTP client more resilient to errors

- mlrun/db/httpdb.py
- tests/rundb/test_httpdb.py
a fix for [ML-2515](https://jira.iguazeng.com/browse/ML-2515)
Validation checks the following:
- if server major != client major raise a warning states the versions are incompatible 
- If the server minor version is greater than the client minor version+2, raise a warning that this violates our backwards compatibility policy.
- If the client minor version is greater than the server minor version, raise a warning stating that the client version cannot be greater than the server version
- If the client is within our compatible range (2 versions back), log a message stating that the server and client versions are not identical but are compatible
> [DB] Fix version compatibility validation

- .gitignore
- go/pkg/common/utils.go
- go/pkg/services/logcollector/logcollector_test.go
- go/pkg/services/logcollector/server.go
- go/pkg/services/logcollector/test/logcollector_test.go
- mlrun/config.py
Few changes were introduced in this PR
1. If `HasLogs` failed, return internal error so MLRun API would resolve the error itself and return appropriate error to user
2. Optimized finding log file by caching found log file and using `WalkDir` (introduced on go.16)
3. Reduced spammy logs
https://jira.iguazeng.com/browse/ML-3488
> [LogCollector] Enhance finding log files

- mlrun/api/api/endpoints/functions.py
- mlrun/runtimes/base.py
- tests/system/runtimes/test_archives.py
https://jira.iguazeng.com/browse/ML-3540
Aligning how we were returning the created image by the build flow, after build finished we are setting the `spec.build.image` to the `spec.image` and cleaning the `spec.build.image`, but we had a bug that in one of the flows when function was already ready we were returning the `spec.build.image` instead of the `spec.image`
> [Function] Fix build status doesn't return the created image after reaching `ready` state 

- mlrun/model_monitoring/stream_processing_fs.py
Following https://github.com/mlrun/mlrun/pull/3157, instead of raising an error, the model monitoring stream function will log an error about the out of order issue. In that way, the events with the out of order issue will be processed through the rest of the monitoring stream graph (although these event won't be written into the TSDB).
> [Model Monitoring] Log an error for out-of-order event request in the monitoring stream function

- mlrun/runtimes/utils.py
- tests/runtimes/test_utils.py
Found during local development where I had a stale remote (without url), running local tests crashed immediately. 
This fix ensure the remote have url before trying to access it.
> [Runtimes] Fix resolving code origin

- mlrun/projects/project.py
- mlrun/runtimes/base.py
- tests/projects/test_project.py
- tests/runtimes/test_base.py
before, if user would pass 'requests>=5, <4' then the space between `5` to `<` would not be escaped correctly when the command was executed.
This PR escapes the pip command more correctly and handle flags accordingly
https://jira.iguazeng.com/browse/ML-3518
> [Runtimes] Escape and encode requirements correctly

- mlrun/api/db/sqldb/models/models_mysql.py
- mlrun/api/db/sqldb/models/models_sqlite.py
- mlrun/utils/helpers.py
- tests/api/db/test_feature_sets.py
When using the `ingest` REST API, code would attempt to store to DB objects generated from client-side objects (`FeatureSet` in this case). If the object had fields of type `datetime`, then DB code would explode when trying to convert the object to JSON for `uid` calculation and storing in DB table. This only happens when client-side objects are directly used, since otherwise the objects are already serialized to string when creating payload for the REST API calls, so the DB code doesn't usually get `datetime` objects.
I've fixed this in a general way, rather than just fixing the `fset.spec.source` fields - ensuring that any non-serializable objects are converted to string as part of the JSON `dumps` call. There's still a TODO which is to change the serializing of objects for DB table …
> [Feature-store] Fix issues with storing to DB objects with non-JSON-serializable fields (in `ingest` REST API)

- mlrun/projects/project.py
- tests/projects/test_project.py
Following https://github.com/mlrun/mlrun/pull/3163, when the user loads a project from remote (e.g. git source, yaml, etc.), we remove the owner name from `project.spec.owner` to avoid possible conflicts. 
A related tickets: https://jira.iguazeng.com/browse/ML-3571, https://jira.iguazeng.com/browse/IG-21676
> [Projects] Remove owner name when loading project from remote

- mlrun/runtimes/function.py
- tests/api/runtimes/test_nuclio.py
When nuclio return with meaningful error string, use it
in addition, reduce spammy log when nuclio version is not set
[ML-3446](https://jira.iguazeng.com/browse/ML-3446)
> [Nuclio] Populate errors to clients

- mlrun/serving/server.py
- mlrun/serving/states.py
- mlrun/utils/logger.py
- tests/utils/logger/test_logger.py
following and my misleading comment about `log_with` https://github.com/mlrun/mlrun/pull/3244 - the reason for ci to pass while real function fails is that ci uses mock server (that relay on mlrun logger) while real deployments uses nuclio logger which expects `log_with`. In this PR I've added an alias on mlrun logger to behave like nuclio one. so in that case
> [Serving] Fix serving log prints

- tests/system/feature_store/test_spark_engine.py
This test is unstable, so I added several logs to it for to better understand what happens when it fails. ([ML-3587](https://jira.iguazeng.com/browse/ML-3587))
> [Tests] Add logs to `TestFeatureStoreSparkEngine::test_as_of_join_result`

- mlrun/api/api/endpoints/submit.py
- mlrun/api/api/utils.py
- mlrun/api/schemas/schedule.py
- mlrun/api/utils/scheduler.py
- mlrun/runtimes/base.py
- tests/api/api/test_utils.py
We don't check if a schedule already exists when creating a new schedule (idempotency), thus, API fails because DB already have a schedule record.
To allow users to update function's schedule more easily, such as below, it is required to perform create_or_update kind of flow.
```py
func.run(schedule="0 * * * *")
...
func.run(schedule="0 12 * * *")
```
https://jira.iguazeng.com/browse/ML-3542
> [Schedule] Allow submit jobs to create or update schedules idempotently

- dependencies.py
To improve ease of development.
Without this change, building `mlrun/mlrun` with a custom version of a dependency from git fails.
> [Requirements] Avoid failure on git-located requirements

- mlrun/runtimes/base.py
- tests/api/runtimes/assets/requirements.txt
- tests/api/runtimes/test_kubejob.py
- tests/runtimes/test_base.py
- tests/test_requirements.py
Following up with https://github.com/mlrun/mlrun/pull/3237#issuecomment-1461696497 to handle inline comments
For the record, handling inline comments is just a cosmetic, because doing `pip install 'requests # just a comment'` is legit.
> [Base] Sanitize inline comments when using `with_requirements` 

- mlrun/errors.py
- tests/test_errors.py
related to https://jira.iguazeng.com/browse/ML-3599
use the error clase name as an error message when a description is not provided
> [Errors] Fix `err_to_str` without error description

- automation/package_test/test.py
Security fixes are not applied to <= python 3.7 anymore
> [CI] Skip numpy vulnerabilities test when running under python 3.7

- mlrun/__main__.py
- mlrun/projects/pipelines.py
- mlrun/projects/project.py
- tests/system/projects/test_project.py
Since https://github.com/mlrun/mlrun/pull/3254 , all schedule storing is idempotent - there are no more conflicting schedules, and the store function modifies the existing schedule if it exists (This logic is handled in `function.run`.
Therefore, there is no more need for the override flags in `project.run` (which ultimately calls `function.run`).
The flags were introduced in an 1.3.0 RC, so no need for deprecation.
See the "task schedule modified" log below
> [Schedule] Remove workflow schedule override flags

- tests/system/feature_store/test_spark_engine.py
We believe that the write to the target is append and not overwrite in `get_offline_features`, so I try now to delete the target before.
[ML-3587](https://jira.iguazeng.com/browse/ML-3587)
> [Tests] test_as_of_join_result: delete `get_offline_features` target before running it

- tests/system/projects/test_project.py
The test runs a workflow 3 times. The first time it gets created, the second time we expect override (previously by using an `override` flag, but now the override behavior is the default), and on the third there was an expectation for a conflict when not using the flag. However this isn't the case anymore, so no need to run 3 times.
> [System Tests] Fix Schedule Workflow Test

- docs/tutorial/05-model-monitoring.ipynb
Using `tqdm.notebook` requires `ipywidgets` installation
[ML-3607](https://jira.iguazeng.com/browse/ML-3607)
> [Docs] Add `ipywidgets` installation

- dockerfiles/models/Dockerfile
note this tensorflow installation shows warnings of missing GPU / cuda which should be ignored
~~~
2023-03-15 09:05:15.351346: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-03-15 09:05:15.351388: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2023-03-15 09:05:17.849317: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2023-03-15 09:05:17.849370: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed …
> [Models] Install tensorflow instead of intel-tensorflow

- mlrun/__main__.py
- mlrun/projects/project.py
https://github.com/mlrun/mlrun/pull/3265 assumed the `overwrite` flag was introduced in 1.3.0. However it is also in 1.1.3 and 1.2.1. Therefore, for backwards compatibility, the flag still exists and can be used but now does nothing except raise a deprecation warning.
> [SDK] Bring back the `overwrite` flag with deprecation warning

- go/pkg/services/logcollector/logcollector_test.go
- go/pkg/services/logcollector/server.go
- mlrun/artifacts/model.py
- mlrun/runtimes/base.py
Reducing by providing a mutex on top of walking project dir files, this should ensure only one project dir file listing to occur at a specific time.
In addition, increased the scope of errors to retry on when failing listing dir
https://jira.iguazeng.com/browse/ML-3488
> [LogCollector] Reduce readdirent when finding run log file path

- mlrun/runtimes/function.py
- mlrun/runtimes/serving.py
- tests/api/runtimes/test_nuclio.py
Support overriding default `service_type` and `add_templated_ingress_host_mode` via SDK
> [Nuclio] `with_service_type` SDK

- dockerfiles/models/requirements.txt
- tests/system/runtimes/test_mpijob.py
mpi4py is required when running mpijob with python.
Adding it helps with faster tests since there is no need to build the image which can take 8 mins on open source system tests and it does not introduce any new dependencies.
> [Models] Add mpi4py requirement

- mlrun/api/schemas/schedule.py
When defining type hints for `pydantic` objects with `typing.Union`, `pydantic` will attempt to match any of the types defined under `typing.Union` and will use the first one that matches.
However, when adding `typing.Optional`  (e.g. `Optional[Union[datetime, str]]`) the user may face unexpected behaviour in which the order within the `Union` has been changed and `pydantic` will match the wrong type (e.g. trying to match `str` before `datetime` although `datetime` is the first type in the `Union` list). This bug occurs following different imports of 3rd libraries. More info about this `pydantic` behaviour can be found here: https://github.com/pydantic/pydantic/issues/4474 
https://github.com/pydantic/pydantic/issues/4519
To avoid this unexpected behaviour, in this PR we replace …
> [Schedule] Update type hints for ScheduleCronTrigger to avoid unexpected pydantic behaviour

- mlrun/serving/v2_serving.py
[ML-2539](https://jira.iguazeng.com/browse/ML-2539)
> [Serving] Fix monitoring stream pod losing events when event timestamp's microsecond equals zero [1.3.x]

- dockerfiles/models/Dockerfile
Since we added mpi4py to the image requirements we now need to set the CFLAGS before
> [Models] Set CFLAGS before requirements installation

- mlrun/projects/project.py
- tests/projects/test_project.py
A fix for: https://jira.iguazeng.com/browse/ML-3071
The function name will now be normalized in set_function, and any underscores will be replaced with dashes.
The user will be warned, and we intend to reject such requests in the future.
> [Project] Fix function name isn't treated uniformly 

- mlrun/runtimes/base.py
Changed to import the class from the package instead of importing the whole package because for some reason importing the package would mess up the other imports (would not find `mlrun` in line 1102)
> [Notifications] Fix importing API from Client code

- docs/monitoring/dashboards/iguazio-3.5.2-and-older/model-monitoring-details.json
- docs/monitoring/dashboards/iguazio-3.5.2-and-older/model-monitoring-overview.json
- docs/monitoring/dashboards/iguazio-3.5.2-and-older/model-monitoring-performance.json
- docs/monitoring/dashboards/model-monitoring-details.json
- docs/monitoring/dashboards/model-monitoring-overview.json
- docs/monitoring/dashboards/model-monitoring-performance.json
- mlrun/api/api/endpoints/grafana_proxy.py
- mlrun/api/crud/model_monitoring/grafana.py
- mlrun/api/crud/model_monitoring/model_endpoint_store.py
- tests/api/api/test_grafana_proxy.py
At the moment there are several Grafana charts and KPIs that are based on MLRun API datasource (e.g. `drift_status`). In order to reduce the amount of calls to MLRun API from Grafana, in this PR we adjust these charts and KPIs to use the data store target directly. That means adjust the model monitoring dashboards to use only `V3IO Framesd` datasource. 
Please note that we are still using MLRun API service for listing and selecting the projects in the user's cluster but apart of that, all of the other charts and KPIs are based on the `V3IO Framsed`.
A ticket for this improvement https://jira.iguazeng.com/browse/ML-3605.
This PR also includes fixes for open issues in Grafana:
* [IG-21324](https://jira.iguazeng.com/browse/IG-21324)
* [IG-2991](https://jira.iguazeng.com/browse/ML-2991)
* …
> [Model Monitoring] Adjust Grafana dashboards to use V3IO datasource instead of MLRun API

- mlrun/datastore/targets.py
- tests/system/feature_store/test_feature_store.py
backport of https://github.com/mlrun/mlrun/pull/3325
[ML-3404](https://jira.iguazeng.com/browse/ML-3404)
> [Datastore] Fix leading zeros in time partition names [1.3.x]

- mlrun/api/api/deps.py
- mlrun/api/schemas/constants.py
- tests/api/test_api_states.py
When worker is waiting for chief to be available, reflect a correct message and not just "migration is required"
https://jira.iguazeng.com/browse/ML-3678
Next: make worker wait for chief upon deployment
> [API] Reflect correct message wen waiting for chief

- mlrun/api/api/endpoints/healthz.py
- mlrun/errors.py
- tests/api/api/test_healthz.py
- tests/api/test_api_states.py
To ensure that k8s deployment finishes only when worker find and clusterize with its chief
part (2) of https://github.com/mlrun/mlrun/pull/3336
> [API] Fail `healthz` requests when offline / waiting for chief

- mlrun/api/crud/model_monitoring/model_endpoints.py
- mlrun/model_monitoring/model_monitoring_batch.py
- mlrun/serving/routers.py
- tests/api/api/test_model_endpoints.py
- tests/system/model_monitoring/test_model_monitoring.py
This PR includes minor fixes that were exposed due to system tests failures following https://github.com/mlrun/mlrun/pull/2685:
- **Model monitoring batch job** - `endpoint[endpoint_type]` value from the DB is retrieved as a `string`. Therefore we convert it to an `int` when checking if the endpoint type is a router (Which based on the `IntEnum` class `EndpointType` class).
- **Create children endpoints of a router** - No need to convert `current_endpoint` into a dictionary when writing the endpoint into the DB as this object is already from type `mlrun.model_monitoring.model_endpoint.ModelEndpoint`. The `HTTPDB` class will convert it to a dictionary before the API call. 
- **Generting endpoint id for model endpoints in system tests** - when using the `_mock_random_endpoint()` we have to …
> [Model Monitoring] Update system tests and fix endpoint_type in batch job

- .github/workflows/system-tests-enterprise.yml
- automation/system_test/prepare.py
With the coming up introduction of system tests over patch development branches (e.g. 1.3.x) we need to purge the DB before running the system tests since we do not support migrating mlrun db to lower versions.
**Note the mysql credentials secrets need to be created before merging**
> [Tests] System test prepare purge DB

- mlrun/features.py
system tests: 
`test_feature_validator.py::TestFeatureValidator::test_validator_types - Failed
test_feature_validator.py::TestFeatureValidator::test_feature_set_entities - Failed
test_feature_validator.py::TestFeatureValidator::test_feature_set_features - Failed`
> [Features] Fixing issue when value_type is `ValueType` instance

- mlrun/runtimes/local.py
- tests/runtimes/assets/verbose_stderr.py
- tests/runtimes/test_local.py
Cherry picked from commit bf07df6eb0aa986da5e1ce805a87b58e02239433. Corresponding development PR is #3364
> [Runtimes] Avoid hang on large stderr output in `run_exec` [1.3.x]

- mlrun/datastore/targets.py
- tests/system/feature_store/test_spark_engine.py
[ML-3443](https://jira.iguazeng.com/browse/ML-3443)
> [Spark] Support more than 2 keys in spark online target ingestion engine [1.3.x]

- mlrun/serving/server.py
Cherry-pick backport of #3377 / 549d9994ec882154c14afb6d726cc54d629cf692.
> [Serving] Fix 200x logging in CI (and potentially elsewhere) [1.3.x]

- mlrun/utils/logger.py
- tests/utils/logger/test_logger.py
Cherry-pick backport of #3381 / 422940611b719d5efb7788e4bc1c7e2fa31d39b1.
> [Utils] Fix multiple logs [1.3.x]

- Makefile
- conda-arm64-requirements.txt
- dev-requirements.txt
- tests/test_requirements.py
With moving to ARM64 (apple silicon) some packages are not working properly when installing with pip.
This forces us to find other solutions, one of them is setting a conda environment.
Once the conda environment is set up, run `make install-conda-requirements` to install all dev requirements with specific requirements installed with conda to mitigate the migration to ARM64.
> [Requirements] ARM64 requirements over conda env

- .github/workflows/system-tests-enterprise.yml
- automation/system_test/prepare.py
This PR will allow MLRun maintainers to easily choose the branches on which the system tests will run.
Instead of storing hard coded the branch on which we run on which was development in the workflow yaml, now we will store a configuration file in our datanode which will contain a list of branches separated with commas.
Each system test schedule the workflow will read the file and pop the first branch in the list and append it to the end of the list and will run the system tests against it (will patch all the images and system with the branch code and will run the branch tests).
SSH to the datanode of the system tests and edit the `/tmp/system-tests-branches-list.txt`.
> [CI] Support multi branch system tests

- tests/system/runtimes/test_notifications.py
The notification status moved from the run spec to the run status. Fixed the test to reflect the change.
> [System Tests] Fix Run Notifications System Test

- docs/tutorial/src/workflow.py
- mlrun/feature_store/common.py
- mlrun/projects/operations.py
- mlrun/projects/project.py
- mlrun/run.py
- mlrun/runtimes/serving.py
- tests/api/api/test_utils.py
- tests/projects/test_project.py
- tests/system/demos/churn/test_churn.py
- tests/system/demos/horovod/test_horovod.py
- tests/system/demos/sklearn/test_sklearn.py
- tests/system/model_monitoring/test_model_monitoring.py
- tests/system/projects/assets/kflow.py
- tests/system/projects/assets/newflow.py
- tests/system/projects/test_project.py
Fix failing tests during (#3287) by replacing all underscores used when setting a getting function.
You can see the system tests failures [here](https://iguazio.slack.com/archives/C04GL7EE65R/p1680580973029999)
There will be a client-side follow-up PR that includes the following changes:
- Make it clearer to the user that underscores have been replaced with dashes.
- If a user attempts to obtain a function with an underscore-containing name and receives a 404, we will try to query the name with dashes in case the user missed the message.
> [Tests] Fix pipeline system tests

- mlrun/builder.py
- tests/test_builder.py
When building a pod to EKS node having attached policy with build permission role, project with secrets "AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY" will conflict kaniko thinking those are the credentials required to push to ECR
This PR fixes the race by emptying the project secret for those specific envvars by adding explicit envvar on container as they take precedence over the project secrets (which are mounted).
The only issue would raise by this PR is that, if access to some AWS resource (not ecr) is required during buildtime - it would fail as the secrets are not available anymore (reset with empty values)
https://jira.iguazeng.com/browse/ML-3743
> [Builder] Fix pushing to ECR

- mlrun/datastore/spark_udf.py
ML-3754. Fixing bug introduced in https://github.com/mlrun/mlrun/pull/3412. As part of the refactoring case when single entity is saved to Redis was not handled properly
> [Spark] Fix Redis key generation for single entity

- mlrun/feature_store/api.py
- tests/system/feature_store/test_spark_engine.py
Fixes the output path when running system tests in local mode.
Before this fix, files were written to `tests/system/feature_store/file:/var/folders/qr/hxtsdg117_jftdk9wpgvkfqw0000gn/T/tmpcm5gar1d` (last part varies between runs) instead of `/var/folders/qr/hxtsdg117_jftdk9wpgvkfqw0000gn/T/tmpcm5gar1d`.
> [Spark] Allow ingesting to a local path

- mlrun/api/api/endpoints/healthz.py
some old scripts / clients expect mlrun server to be on healthz endpoint
> [API] Add version to healthz endpoint

- mlrun/projects/pipelines.py
- mlrun/projects/project.py
- tests/system/projects/test_project.py
Currently, we didn't forward the project subpath value to the scheduled job workflow which is an issue when trying to schedule a workflow that is stored in a relative path in the source e.g git repo.
https://github.com/mlrun/system-tests/pull/1
> [Projects] Fix forwarding project subpath value to schedule workflow

- mlrun/runtimes/function.py
- tests/serving/test_serving.py
MLRun client should always request the api to deploy nuclio functions, and go through the same flow for validation/enrichment.
When using the `dashboard` argument, the following warning is displayed:
Resolves https://jira.iguazeng.com/browse/ML-3777
> [Runtimes] Remove option to deploy Nuclio function straight from client

- mlrun/model.py
- mlrun/projects/pipelines.py
- mlrun/projects/project.py
- tests/integration/sdk_api/run/test_main.py
- tests/system/projects/assets/handler_workflow.py
- tests/system/projects/test_project.py
In order to run a pipeline from local code without having to push it to git / upload a source archive it was needed that the project source value will not be dependant on the context path since we do not load directories into pods but we only allow archives and git sources.
The correct flow is that we use `code_to_function` in order to keep the code inside the pod env and not try to load it from a source.
> [Project] Fix running pipelines with local code

- mlrun/model_monitoring/stream_processing_fs.py
- tests/system/model_monitoring/test_model_monitoring.py
A fix for [#ML-3737](https://jira.iguazeng.com/browse/ML-3737).
Following [#2685](https://github.com/mlrun/mlrun/pull/2685), the monitoring stream graph retrieves the endpoint record directly from the DB. Therefore, the `error_count` value is provided as a `string` and not as an `integer`. When there is a new error in the monitoring stream graph, it tries to increase that `error_count` value by 1 but since it is a string we are getting the following `TypeError`:
`TypeError: can only concatenate str (not "int") to str`
In this PR, we validate that that the `error_count` value is converted into an integer before applying additional calculations on that value. Moreover, this PR also includes a new test for validating that `error_count` value is recorded as expected when the user provides …
> [Model Monitoring] Convert error_count value to integer in the monitoring stream graph

- mlrun/db/httpdb.py
A docstrings fix for the `list_model_endpoints()` function within `mlrun/db/httpdb.py`.
> [Model Monitoring] Fix list_model_endpoints docstrings

- docs/monitoring/dashboards/model-monitoring-details.json
Instead of providing datasource type and uid, we need to define only the relevant datasource name (`iguazio` in this case).
> [Model Monitoring] Fix Grafana datasource name in details dashboard

- .importlinter
- Makefile
- dev-requirements.txt
- mlrun/common/__init__.py
- mlrun/serving/server.py
- mlrun/serving/utils.py
(#3457)
(cherry picked from commit bd82117fd43744ae38a9aa1a73072628f32df199)
> [Serving] Backport - Fix passing MLRun event headers with underscore in RemoteStep

- mlrun/api/api/endpoints/grafana_proxy.py
When calling `/grafana-proxy/model-endpoints` endpoint for validating the grafana proxy for the model-endpoints API, we are verifying that the access key has a valid data session. However, this validation is unnecessary in CE deployments in which there is no access key.
> [Model Monitoring] Validate access key in Grafana only in non-CE deployment

- mlrun/api/api/endpoints/grafana_proxy.py
Backport for:
- [Model Monitoring] Validate access key in Grafana only in non-CE deployment: https://github.com/mlrun/mlrun/pull/3476
> [Model Monitoring] Backport validate access key in Grafana only in non-CE deployment [1.3.x]

- mlrun/api/crud/projects.py
- mlrun/api/db/sqldb/db.py
- mlrun/api/schemas/project.py
- mlrun/api/utils/clients/iguazio.py
- mlrun/api/utils/helpers.py
- mlrun/api/utils/projects/remotes/nop_follower.py
- mlrun/db/httpdb.py
- tests/api/db/test_projects.py
- tests/api/utils/clients/test_iguazio.py
In order to save on the size of the responses (as many real world projects are over a couple MBs large), Listing projects from iguazio will not return the project struct, therefore we need to GET each projects separately once we get there names.
> [Projects] Minimal Project Response and Request Iguazio Projects Separately During Sync

- mlrun/model_monitoring/stores/sql_model_endpoint_store.py
- tests/system/model_monitoring/test_model_monitoring.py
Following the refactoring process in https://github.com/mlrun/mlrun/pull/3461, the `EndpointType` is now stored within `mlrun.common.model_monitoring.py`. In this PR, we update two references for that class that were missing in the refactoring process. 
@liranbg @TomerShor FYI
> [Model Monitoring] Fix EndpointType imports 

- mlrun/common/model_monitoring.py
- mlrun/model_monitoring/stores/kv_model_endpoint_store.py
A fix for [ML-3795](https://jira.iguazeng.com/browse/ML-3795).
For projects that have been deployed in previous versions (<1.3.1), the model endpoint unique id was stored under a key named `endpoint_id`. Since [#2685](https://github.com/mlrun/mlrun/pull/2685), the key is named `uid`. 
In this PR, we fix backwards compatibility issue when trying to delete model endpoints with the old key name.
> [Model Monitoring] Fix BC issue when deleting a model endpoint from KV

- .github/workflows/system-tests-opensource.yml
- automation/deployment/ce.py
- automation/deployment/deployer.py
Fix deployer cli tool with a couple of changes and make the Open Source System Tests workflow use the cli tool
Example run - https://github.com/quaark/mlrun/actions/runs/4913793406/jobs/8774364851
> [CI] Use CE Deployer in Open Source System Tests CI

- requirements.txt
- tests/test_requirements.py
orjson does not behave well with latest pytest due to a bug with the stack trace below.
orjson 3.8.12 changelog mentiones the following (https://github.com/ijl/orjson/releases/tag/3.8.12)
> Exceptions raised in default are now chained as the __cause__ attribute on orjson.JSONEncodeError.
and it seems that pytest is yet to catch up on this change.
<details>
<summary>
Stack trace
</summary>
```
2023-05-08T19:23:08.8033830Z INTERNALERROR> Traceback (most recent call last):
2023-05-08T19:23:08.8034674Z INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/_pytest/main.py", line 269, in wrap_session
2023-05-08T19:23:08.8035073Z INTERNALERROR>     session.exitstatus = doit(config, session) or 0
2023-05-08T19:23:08.8086045Z INTERNALERROR>   File …
```
> [Requirements] Blacklist orjson 3.8.12

- automation/deployment/deployer.py
- ce.logs
By using its own logger, the deployer is now self contained and doesn't need to import mlrun. Making it so it can run without any prerequisites.
> [CI] Make Community Edition Deployer Self Contained

- mlrun/api/utils/singletons/k8s.py
- mlrun/utils/helpers.py
When running locally and trying to use remote k8s, it is needed to understand the exception when loading kubeconfig
> [API] Add k8s util exception logging 

- mlrun/db/httpdb.py
- tests/system/runtimes/test_notifications.py
`test_run_notifications` fails in the open source system tests.
The issue was that we had an inconsistent name for the "with-notifications" option, with a dash in the runs endpoint but an underscore in the httpdb.
> [System tests] Fix test run notifications

- tests/system/feature_store/test_feature_store.py
Before #3449, `ingest()` ignored all but the first chunk. This PR adjusts `test_sync_pipeline_chunks` to expect all data to be returned, not just the first chunk.
> [Tests] Fix `test_sync_pipeline_chunks`

- automation/system_test/prepare.py
Before the `if not mlrun_db_pod_name_cmd:` was never resolved to true because the returned as a command templated string. 
Now it actually returns the pod name if found
> [System Tests] Fix finding mlrun db pod name

- mlrun/feature_store/api.py
[ML-3793](https://jira.iguazeng.com/browse/ML-3793)
Fixes `TestFeatureStore::test_pandas_stats_include_index`
> [Feature Store] Fix empty dataframe result from `preview()` with pandas engine

- mlrun/feature_store/api.py
[ML-3793](https://jira.iguazeng.com/browse/ML-3793)
Fixes `TestFeatureStore::test_pandas_stats_include_index`
Backport of #3519 / b51baf0.
> [Feature Store] Fix empty dataframe result from `preview()` with pandas engine [1.3.x-next]

- tests/system/feature_store/test_feature_store.py
> [Tests] Fix `test_sync_pipeline_chunks` [1.3.x-next]

- automation/system_test/prepare.py
We still need to log the exception for debugging. verbosity simply drop logging the command itself as it might include sensitive content
> [CI] Fix logging errors when verbose is set

- mlrun/api/db/sqldb/db.py
- mlrun/api/initial_data.py
- tests/api/test_initial_data.py
Following https://github.com/mlrun/mlrun/pull/3409, hub sources present in the db with a `MarketplaceSource` kind failed pydantic validation during schema migrations with the following error:
```
pydantic.error_wrappers.ValidationError: 1 validation error for HubSource
kind
value is not a valid enumeration member; permitted: 'project', 'FeatureSet', 'BackgroundTask', 'FeatureVector', 'model-endpoint', 'HubSource', 'HubItem', 'HubCatalog' (type=type_error.enum; enum_values=[project, FeatureSet, BackgroundTask, FeatureVector, model-endpoint, HubSource, HubItem, HubCatalog])
```
To fix this, we add a data migration to modify the `kind` name from `MarketplaceSource` to `HubSource`.
Furthermore, when making sure a default hub source exists, we handle the above error specifically, as it means …
> [DB] Perform data migrations to rename 'Marketplace' source type to 'Hub'

- mlrun/__main__.py
- mlrun/api/api/endpoints/frontend_spec.py
- mlrun/api/api/endpoints/functions.py
- mlrun/api/utils/builder.py
- mlrun/common/constants.py
- mlrun/datastore/utils.py
- mlrun/runtimes/kubejob.py
- mlrun/runtimes/utils.py
- mlrun/utils/notifications/notification_pusher.py
- tests/api/runtimes/base.py
- tests/api/runtimes/test_kubejob.py
- tests/api/runtimes/test_mpijob.py
- tests/api/utils/test_builder.py
- tests/runtimes/test_pod.py
Part of the client server separation moved builder under the API hierarchy as it is only used by the API
> [Builder] Move `builder.py` to `api/utils/builder.py` 

- mlrun/api/launcher.py
- mlrun/launcher/base.py
- mlrun/launcher/local.py
- mlrun/launcher/remote.py
- mlrun/runtimes/base.py
the local param is passed to the launcher object
> [Launcher] Remove unused local variable from `launch`

- mlrun/api/api/endpoints/functions.py
Removing the internal import of `mlrun.api.utils.singletons.project_member` from the `function_process_model_monitoring_secret()` because this package is already a part of the general imports in this file. 
The internal import caused reference issue in that function which eventually broke the model monitoring flow. Following the refactoring process in #3461  , we have replaced `SecretProviderName.kubernetes` with the full path for that value `mlrun.common.schemas.SecretProviderName.kubernetes`. Due to the mentioned internal error, the `mlrun` package hasn't been recognized in the `_process_model_monitoring_secret()` function.
> [Model Monitoring] Fix _process_model_monitoring_secret: remove internal unnecessary import

- mlrun/api/launcher.py
- mlrun/launcher/base.py
- mlrun/launcher/client.py
- mlrun/launcher/local.py
- mlrun/launcher/remote.py
- mlrun/runtimes/base.py
Issue that was found in our system tests, when running `deploy_function` we are setting the runtime `run_db` to point to the SQLDB with the `db_session` that is being created upon request. but the launcher it self doesn't hold that db and therefor initializes a `NopDB` instead as can be seen in the api logs.
For now decided to rollback the use of the launcher.db and use the runtime.db instead, and will set a design session on how to implement that with the launcher as there are multiple methods that the `runtime` uses to access the db.
> [Runtime/Launcher] Use runtime db instead of launcher db

- mlrun/artifacts/manager.py
https://github.com/mlrun/mlrun/pull/3439 - This PR is closed and Irrelevant. After discussing the issue, we recognized that there are circumstances where the conflict is purposeful, and we are interested in obtaining a number of runs for retrieval.
Adding a remark to the code to avoid further confusion in this matter.
> [Artifact] Add a comment for allowing to create artifacts with conflicting keys

- tests/system/feature_store/assets/testdata_short.csv
- tests/system/feature_store/test_feature_store.py
`mlrun` does not use `storey.CSVSource` directly.
Therefore, the `test_read_csv` test has been updated to utilize 
mlrun's `sources.CSVSource` instead of `storey.CSVSource`.
> [Feature Store] Change `test_read_csv` to use mlrun CSVSource - ML-3820

- mlrun/datastore/sources.py
A fix for https://jira.iguazeng.com/browse/ML-3792.
`HttpSource` inherits from `OnlineSource` but in the current code it calls `super().__init__(path=path)` which is not required because the argument `path` is already exist in the base class. In addition, the other keyword arguments were not provided through the initialization (which eventually let to the mentioned bug).   
In this PR, we remove the unnecessary initialization function of the `HttpSource`.
> [Datastore] Fix HttpSource initialization

- mlrun/runtimes/local.py
- tests/run/assets/kwargs.py
- tests/run/test_run.py
- tests/system/runtimes/assets/function_with_kwargs.py
- tests/system/runtimes/test_kubejob.py
https://jira.iguazeng.com/browse/ML-3761
> [Local] Support passing more parameters to handler if handler contains `**kwargs` keyword

- mlrun/api/db/sqldb/db.py
When listing all projects, the API first loads all projects from the DB, extracts their names, filters them against OPA, and then loads the filtered projects again and returns them.
Instead of loading the entire project objects for all objects, in case the given format is `name_only` - the first query to the DB will return just the `name` column for every project.
This will reduce the number of loaded project in every request.
CAVEAT: In case the requesting user has permissions for every project in the system, listing projects will still be a heavy request and will possibly cause issues.
Fixes https://jira.iguazeng.com/browse/ML-3823
> [Projects] Query db for name only when listing projects with `name_only` format

- mlrun/api/db/sqldb/db.py
This method is unused and not relevant since we always have a 'latest' tag for functions.
> [SQLDB] Remove get function latest uid method

- mlrun/runtimes/daskjob.py
This works both from the client and the server (dask logic needs to be split for client-server separation)
> [Dask] Remove commented out "is client" test

- mlrun/utils/logger.py
- tests/utils/logger/test_logger.py
Support creating child logger
Added formatter kind that will log the logger name as well
Eventually, we would want the api logger to include the logger name, to differentiate  between which component logged what
> [Utils] Add named logger

- dockerfiles/jupyter/requirements.txt
- requirements.txt
Following the latest release https://github.com/nuclio/nuclio-jupyter/releases/tag/v0.9.10
> [Requirements] Bump nuclio-jupyter to 0.9.10

- tests/api/utils/function.py
- tests/api/utils/test_scheduler.py
Moved the creation of the cron trigger to after the IOs that store the function and list the runs because they might take too long and cause the schedule to skip the 1st-second run.
For example (schedule triggered every second with no concurrent runs):
```
11:51:05,854479 - Start time (scheduler skipped 11:51:06)
11:51:07,044 - Trigger run
11:51:09,087 - Run finished
11:51:09,854479  - End time
```
**Note** I encountered a problem locally where the function takes 3 seconds to finish and this fix will not cover it.
I'm not sure yet why it happens, could be something we can't control on the scheduler or the Python event loop.
If it pops again in CI I will look for ways to resolve it.
> [Test] Fix transient scheduler unit test failure

- mlrun/api/db/init_db.py
- mlrun/api/initial_data.py
- mlrun/api/utils/db/mysql.py
- mlrun/api/utils/db/sqlite_migration.py
- mlrun/config.py
- tests/api/test_initial_data.py
- tests/system/api/assets/function.py
- tests/system/api/test_artifacts.py
Allow setting sql mode (mysql) globally when mlrun starts 
This way, we can ensure strict-level on mysql to avoid cases where inline artifacts are truncated during store artifact causing data corruption
if no modes are set, mlrun will *not* try to override existing sql modes.
mlrun will default to use `STRICT_TRANS_TABLES` mode, more info [here](https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html#sqlmode_strict_trans_tables)
https://jira.iguazeng.com/browse/ML-3420
> [DB] Runtime configurable sql mode

- mlrun/kfpops.py
- mlrun/launcher/local.py
- mlrun/runtimes/base.py
The `_save_or_push_notifications` method was called twice once in `launch` and once in `execute` while it should have been pushed once.
The method moved from the runtimes to the launchers so we can remove it from the BaseRuntime class.
> [Launcher] Fix duplicate push notification call for local runs

- mlrun/feature_store/api.py
- mlrun/feature_store/feature_set.py
- tests/system/feature_store/test_feature_store.py
1.  set_targets now is acutely a set function.
2. allow no-target ingest if running locally 
3. default targets are part of the featureset targets,  no need to use `get_default_targets` in the ingest process 
[ML-3800](https://jira.iguazeng.com/browse/ML-3800)
> [Feature Set] Fix set_targets to overwrite the existing targets and allow no-target ingest if running locally

- mlrun/k8s_utils.py
- mlrun/runtimes/utils.py
Issue was that in #3426 ([here](https://github.com/mlrun/mlrun/pull/3426/files#diff-5ad3789c7abfd42e2535960d6b11ba72e69337af52cf26f05274afd9736c3d3bR97)) I modified the resolution of `resolve_mpijob_crd_version` to `get_run_db` even if running in `api_context` this caused the default dbpath to change to `./` which was supposed to stay empty. 
Decided to remove the the whole resolution of the `mpi_version` using the `get_run_db` due to the existence of the `client-spec` enrichment on the client side that resolves the `mpi_version` from the API.
> [Config] Fix overriding API SQL DB with nopDB

- tests/system/projects/test_project.py
In `test_project.py` every test creates/loads a project with a different name, except `test_run` and `test_run_artifact_path` that used the same project - `pipe1`. 
When running in the enterprise system tests on github, the test failed saying that the project had 4 functions instead of the expected 2 functions.
This was probably due to a race condition in the Github runners where the same project from the previous test did not finish deletion before the next test ran, causing the project to not be empty.
Changed the project's name so the tests will use 2 different tests.
> [System Tests] Change `test_run` project name

- mlrun/utils/notifications/notification/git.py
The `mlrun.errors.MLRunBadRequestError` doesn't expect the `status_code` param. Removed it.
Fixes - https://jira.iguazeng.com/browse/ML-3849
> [Notifications] Fix raising exception when git notification gets a Bad Request

- .github/workflows/system-tests-opensource.yml
- automation/system_test/prepare.py
Use mlrun automation prepare.env to generate env.yaml for OSS tests, which way, secrets including arg flags would be natively be generated
In addition, made sure to backup existing env so when generating on local, it wont override and kill the current copy.
> [CI] Fix generating env for OSS tests

- mlrun/model.py
- mlrun/utils/notifications/notification_pusher.py
Fixes - https://jira.iguazeng.com/browse/ML-3851
When listing runs (with notifications) the notification data gets split between the run spec and run status. In order to check the notification status (whether it was already sent or is pending), we need to get the notification status from the run status before checking.
> [Notifications] Fix notifications being resent when api restarts

- mlrun/api/launcher.py
- mlrun/launcher/base.py
- mlrun/launcher/local.py
- mlrun/launcher/remote.py
Fixes - https://jira.iguazeng.com/browse/ML-3850
- In client local launcher only push notifications from jupyter client and not from CLI (run pod) - this caused the duplicate notifications.
- Refactor `save_or_push_notifications`, separated to `save_notifications` for api launcher and `push_notifications` for client local launcher.
- api launcher uses notification validation function (remove code dup)
> [Notifications] Fix sending duplicate notifications

- .github/workflows/system-tests-enterprise.yml
- .github/workflows/system-tests-opensource.yml
Use flags to avoid position argument that often gets bugged due to misplace the argument
> [CI] Fix calling prepare.py script

- mlrun/api/crud/runtimes/nuclio/function.py
- mlrun/api/utils/builder.py
- tests/api/runtimes/test_nuclio.py
- tests/api/utils/test_builder.py
When an image name starts with a `.`, the mlrun builder enriches the image name and with the system's docker registry url.
Before this PR it was done only on non-nuclio runtimes, and now it will happen for nuclio runtimes as well :)
Also, I refactored the extensive `_compile_function_config` by splitting it into smaller functions and adding some comments.
Resolves https://jira.iguazeng.com/browse/ML-3858
> [Nuclio] Resolve full image names if enrichment prefix is given

- mlrun/api/db/sqldb/db.py
- mlrun/projects/project.py
- tests/api/api/test_projects.py
- tests/api/db/test_functions.py
- tests/projects/test_project.py
follow up for: https://github.com/mlrun/mlrun/pull/3287
In this previous PR we added a normalization to a function name before saving it, and notify the user of the change.
We realized that in case our users ignored/missed the warning when setting the function, and then attempted to access (import or update) it later,  they would be unable to do so using the old name, and would not know why their function was not found.
As a result, as long as we do not block requests with non-normalized names, we will normalize GET requests as well.
In this fix we handle this case by adding fall-back to get_function:
Normalize the requested name and attempt to retrieve it from the database. if no response is received, we will check to see if the original name contained underscores,  if so, we will repeat …
> [Projects] Fix BC for GET requests of non-normalized function names 

- mlrun/api/main.py
- tests/api/utils/test_scheduler.py
Adding a fix to `_push_terminal_run_notifications`. 
`_last_notification_push_time` was calculated after querying and pushing all runs, therefore a run could have been missed. Taking the time now before running the query.
This change lead to some scheduler tests taking longer and fail. 
We computed a margin of `0.5` seconds for these tests, which was already quite insufficient (`0.4` is not enough), and increased it to `0.8` in this PR.
It looks like adding even one CPU-consuming code line along the flow will cause a delay in the run time. 
This margin will only work temporarily, and we don't want this actions to influence the run time. In the future, we should consider separating this server code, but for now, we should discuss a better solution (maybe make scheduler tests not run the …
> [Notifications] Fix missed notifications in notifications pusher

- conda-arm64-requirements.txt
- requirements.txt
- tests/test_requirements.py
To support tensorflow 2.12.0 we need to have protobuf >= 3.20.3 - https://github.com/tensorflow/tensorflow/blob/v2.12.0/tensorflow/tools/pip_package/setup.py#L107
before that, tensorflow requires protobuf < 3.20
kfp requires protobuf <4
when installing mlrun you get protobuf 3.20.3.
if you install tensorflow after mlrun:
1. tensorflow 2.12.0 - OK
2. tensorflow < 2.12 - will downgrade protobuf to 3.19 which is good for us
https://jira.iguazeng.com/browse/ML-3824
> [Requirements] Remove protobuf requirement

- go/pkg/services/logcollector/logcollector_test.go
- go/pkg/services/logcollector/server.go
- mlrun/api/crud/logs.py
- mlrun/api/utils/clients/log_collector.py
**Issue:**
We have seen in the field that the current implementation, of storing the log files in the `<project>/<run_uid>_<pod_name>` format, proves to be problematic when getting the log files in systems with an extensive number of runs.
The issue happens when listing the logs directory to find the latest run log. Our flex fuse that mlrun is using for storing the logs cannot handle listing a directory with >2000 runs in it, and the log collector sidecar gets stuck.
**Fix:**
To fix it, we revert back to the old log file path format - `<project>/<run_uid>`.
We have done some research and found that currently each run has only one pod, and thus it will have only one file.
This enables us to remove the listDir operation to find the most recent log file, and just use the constant filename …
> [Log Collector] Change log file names to old format

- mlrun/api/api/endpoints/functions.py
A fix for https://jira.iguazeng.com/browse/ML-3860.
Before deploying the monitoring stream nuclio function, we need to create the V3IO monitoring stream. In general, this V3IO stream is being deployed through the function `_create_model_monitoring_stream()` which being called before the deployment of the monitoring nuclio function. At the same time, the model server which writes the events to the same stream is also trying to deploy this stream (for more info see `OutputStream` object).
However, there has been a bug in `_create_model_monitoring_stream()` that created the stream in invalid path. Then, when the monitoring stream function tries to add the V3IO stream trigger on the right path, it get's an error because the stream hasn't been deployed. After 1-2 retries, the monitoring stream …
> [Model Monitoring] Fix deployment of monitoring V3IO stream 

- mlrun/api/crud/runtimes/nuclio/function.py
- mlrun/api/utils/builder.py
- tests/api/runtimes/test_nuclio.py
Sometimes when a user gives requirements that are already present in the base image, `pip` doesn't install them, since it didn't consider it an update.
In this PR we run `pip --upgrade` when deploying installing requested by the user, as these are specifically requested by the user so we should make an effort to install the user's version.
Resolves https://jira.iguazeng.com/browse/ML-3859
> [Build] Install requirements using `pip --upgrade`

- mlrun/utils/notifications/notification_pusher.py
Fixes - https://jira.iguazeng.com/browse/ML-3887
There was an `AttributeError: 'dict' object has no attribute 'status'` because of accessing the notification status as an object instead of a dict.
> [Notifications] Fix notifications pusher failing to initialize

- mlrun/model_monitoring/stream_processing_fs.py
A fix for https://jira.iguazeng.com/browse/ML-3791.
When there is an error in the event dictionary, the monitoring stream graph returns `None` instead of raising an exception with the related error information. As a result, instead of getting the correct error information, the monitoring stream pod raise an error from `Storey` that can't handle a `None` event object. 
In this PR we fix this issue and raise the correct error event description instead of returning a `None` object. Therefore, storey will push the right error message to the error stream and the monitoring stream will log the right error message as expected.
> [Model Monitoring] Fix event error message in monitoring stream graph

- mlrun/api/crud/pipelines.py
- tests/api/api/test_pipelines.py
https://jira.iguazeng.com/browse/ML-1267
> [API] Fix get pipelines return code in case of nonexistent project

- docs/api/mlrun.feature_store.rst
- docs/api/mlrun.serving.rst
- docs/feature-store/transformations.md
- mlrun/feature_store/steps.py
Adding documentation for building graph steps that support multiple engines (up until now only doc was for `storey` steps extending `MapClass`). 
As requested in https://jira.iguazeng.com/browse/ML-3670.
> [Docs] Document building custom transformations for multiple engines

- mlrun/model_monitoring/stores/kv_model_endpoint_store.py
- mlrun/utils/model_monitoring.py
This PR is a fix for a backwards compatibility issue when calling `get_model_endpoint` API - https://jira.iguazeng.com/browse/ML-3866.
Following #2685, the key name of the unique model endpoint id in the database is stored as `uid` instead of `endpoint_id`. However, if a model endpoint record has been stored in the KV table before #2685 (`<1.3.1`) it still has the old key name - `endpoint_id`. As a result, the `uid` key has been missing from the result of `get_model_endpoint` API  when trying to get an old model endpoint record. In this PR, we fix that issue by replacing the key name `endpoint_id` with `uid`.
> [Model Monitoring] Replace `endpoint_id` with `uid` to handle old model endpoint schemas

- go/pkg/services/logcollector/logcollector_test.go
- go/pkg/services/logcollector/server.go
- mlrun/api/utils/clients/log_collector.py
We had project mutex for when trying to get the filepath of the run, this was relevant for when we were listing the directory of the project because we wanted to reduce the amount IO load. Now because we already know the run log path we don't the list dir and therefor the mutex is redundant.
This PR also fixes a bug we experienced when the log collector request hung on acquiring the mutex lock which was increasing the response time by a lot.
prior to the change, you can see that between receiving the log and looking for whether to log exists it took 9sec
```
30-05-23 12:08:32.436 collector.grpcserver (D) Received has log request :: who="log-collector.grpcserver" || runUID="460bf54e40874417b2c28a2cd0a86f0e" || project="testing-logs-admin"
30-05-23 12:08:41.257 collector.grpcserver (W) Run …
```
> [Log Collector] Remove project mutex

- go/pkg/services/logcollector/server.go
The issue is that when stream hits an error it is stuck in an infinite loop trying to get more logs. since the stream underlying is a tcp connection that might get closed, reuse it prone to error. 
This fix ensures that when hitting a fatal error, the log collector will bail out, leaving the monitor log collector to kick in and ensure that log collection is running again.
In case of an error, the log will written on top of the existing logs as append mode is on.
> [LogCollector] Better handling errors [1.3.x]

- mlrun/api/api/endpoints/functions.py
- mlrun/api/db/sqldb/db.py
- tests/api/api/test_functions.py
- tests/api/db/test_functions.py
fix for previous PR: https://github.com/mlrun/mlrun/pull/3642
resolves: https://jira.iguazeng.com/browse/ML-933
Schedules are supposed to be operated only by the chief, therefore, in this PR, we shift the deletion of the schedule to the `delete_function` endpoint and ensure that the delete request is sent only by the chief.
> [Function] Fix deleting a function with schedule only 

- mlrun/utils/notifications/notification_pusher.py
Sanitize notification params before logging them
> [Notifications] Fix sensitive data appearing in api logs

- mlrun/datastore/sources.py
- mlrun/datastore/targets.py
[ML-3928](https://jira.iguazeng.com/browse/ML-3928)
1.3.3 backport of #3680 / 353202516934fcf307fb5530e5bba138271efa37.
> [Datastore] Fix SQL injection vulnerabilities

- mlrun/datastore/base.py
- tests/datastore/test_base.py
https://jira.iguazeng.com/browse/ML-525
Check the file extension of the actual file in the URL and not the suffix of the URL itself as it may contain query params
> [Datastore] Fix DataItem as DF from url with query params

- mlrun/projects/project.py
- tests/projects/test_project.py
resolves: https://jira.iguazeng.com/browse/ML-3621
The` clear_context()` method deleted all the context with no warning, this action is extremely dangerous, essentially deleting everything in the context dir. 
Since the context is by default` ./`, if the user changed working directory for example, then very bad and unexpected things can happen.
In this PR, a deprecation warning for 1.6.0 was included, and for the time being:
- Issue a warning to the user
- If the context is a relative path, no action is taken
- If a subpath exists, it is considered and only the sub dir is cleared
> [Project] Fix project.clear_context() deletes all the context and not subpath

- mlrun/api/api/utils.py
- tests/api/api/test_submit.py
Fixes https://jira.iguazeng.com/browse/ML-3933
Full details for the fix inside the code and the ticket
> [API] Resolve function URI when submitting a schedule from hub function

- mlrun/api/main.py
- tests/api/test_collect_runs_logs.py
run might get into unknown state when its pod get evicted or moved from one node to another
> [LogCollector] Stop log collection for pod in unknown state

- mlrun/api/api/endpoints/functions.py
- mlrun/api/launcher.py
- mlrun/api/utils/builder.py
- mlrun/launcher/base.py
- mlrun/launcher/client.py
- mlrun/launcher/local.py
- mlrun/launcher/remote.py
- tests/api/api/test_functions.py
- tests/api/api/utils.py
- tests/api/runtimes/test_kubejob.py
Reverts mlrun/mlrun#3688
<details><summary>Details</summary>
<p>
```
> 2023-06-02 09:09:23,267 [info] build_function: ....
> 2023-06-02 09:09:23,272 [error] Traceback (most recent call last):
File "/mlrun/mlrun/api/api/endpoints/functions.py", line 666, in _build_function
mlrun.api.launcher.ServerSideLauncher.enrich_runtime(runtime=fn)
File "/mlrun/mlrun/api/launcher.py", line 161, in enrich_runtime
project = runtime._get_db().get_project(runtime.metadata.project)
AttributeError: 'NoneType' object has no attribute 'get_project'
> 2023-06-02 09:09:23,272 [error] {'reason': "runtime error: 'NoneType' object has no attribute 'get_project'"}
```
</p>
</details>
> Revert "[API] Enrich function object before build"

- mlrun/api/utils/builder.py
- tests/api/utils/test_builder.py
Unsets the requirements path when there are no requirements:
```
if not requirements_list:
requirements_path = ""
```
Fixes trying to access the requirements file in the dockerfile but it was never created.
> [Builder] Fix requirements path when no requirements

- mlrun/utils/notifications/notification_pusher.py
Fixes https://jira.iguazeng.com/browse/ML-3908
Backend notifications have statuses on them where local notifications don't necessarily have a status, so defaulting to PENDING.
> [Notifications] Fix local job with notification fails with `AttributeError: 'NoneType' object has no attribute 'get'`

- mlrun/common/schemas/notification.py
- mlrun/launcher/base.py
- mlrun/model.py
- mlrun/utils/notifications/notification/__init__.py
- tests/utils/test_notifications.py
Fixes https://jira.iguazeng.com/browse/ML-3910
Made validation method run on notifications when the object is created, and on enriching run objects to fail fast and not save corrupted notifications in the DB.
* note - tests currently failing until https://github.com/mlrun/mlrun/pull/3700 is merged
> [Notifications] Fix notifications not being sent if previous run was configured with wrong param

- mlrun/api/main.py
If a run is in aborted state, and it has no pod, `start_log` will constantly fail for it.
In the API, do not call `start_log` periodically for runs in aborted state.
Fixes https://jira.iguazeng.com/browse/ML-3940
> [LogCollector] Don't start logs periodically for runs in aborted state

- requirements.txt
https://jira.iguazeng.com/browse/ML-2254
The reason for the major version bump is that one of the bug fixes it not backward compatible (should not affect us explained below)
see - https://humanfriendly.readthedocs.io/en/latest/changelog.html#release-9-0-2020-12-01
> The major version number was bumped because the bug fix for [pluralize()](https://humanfriendly.readthedocs.io/en/latest/api.html#humanfriendly.text.pluralize) is backwards incompatible
The reason this does not affect us is because we don't use format timespan. We use human friendly to parse timespan and this change does not affect parsing.
> [Requirements] Bump humanfriendly to 9.2

- mlrun/feature_store/retrieval/online.py
- tests/integration/sdk_api/feature_store/test_feature_store.py
- tests/system/feature_store/test_feature_store.py
[ML-3900](https://jira.iguazeng.com/browse/ML-3900)
Before this change, the error raised was
```
AttributeError: 'RootFlowStep' object has no attribute 'respond'
```
After this change, the error raised will be
```
MLRunRuntimeError: No features found for feature vector <vector name>
```
> [Feature Store] Raise a clear error when no features are found on retrieval

- mlrun/api/utils/builder.py
- mlrun/config.py
Kaniko sometimes fails to get filesystem from image:
```
INFO[0002] Unpacking rootfs as cmd COPY --from=python-onbuild /home/nuclio/bin/processor /usr/local/bin/processor requires it. 
error building image: error building stage: failed to get filesystem from image: read tcp 10.200.254.29:58626->65.9.112.124:443: read: connection timed out
/nuclio/pkg/processor/build/builder.go:263
```
This is an issue that still hasn't been addressed by Kaniko - https://github.com/GoogleContainerTools/kaniko/issues/1717 
A current workaround is to best-effort retry extracting the image filesystem (default currently set to 3 retries).
> [Kaniko] Retry extracting image filesystem

- mlrun/runtimes/funcdoc.py
- tests/runtimes/arc.txt
- tests/runtimes/test_funcdoc.py
Fix parsing of full path types e.g. `a.b.c` or `a.b.c[a.b.d]`
previously it would ignore the prefix and for `a.b.c` it would return `c`
> [Runtimes] Fix funcdoc AST attributes parsing

- mlrun/api/utils/builder.py
- mlrun/runtimes/kubejob.py
- mlrun/utils/helpers.py
- tests/system/projects/test_project.py
resolves [ML-3826](https://jira.iguazeng.com/browse/ML-3826)
follow up for: https://github.com/mlrun/mlrun/pull/3676
The two flows can be separated, and as we agree on the solution for this one, we'll continue to think about how to handle [ML-3827](https://jira.iguazeng.com/browse/ML-3827)
> [Functions] Remove protocol prefix from image name

- mlrun/db/base.py
- mlrun/db/httpdb.py
- mlrun/db/nopdb.py
- mlrun/db/sqldb.py
resolves: https://jira.iguazeng.com/browse/ML-3457
Add a configurable timeout for `abort_run`, allowing users to set it higher than the default when necessary,
We could consider making this operation async in the future.
> [Runs] Add configurable timeout to abort_run

- mlrun/launcher/base.py
- mlrun/model.py
- mlrun/projects/project.py
- tests/launcher/test_remote.py
https://jira.iguazeng.com/browse/ML-3562
When the `error` attribute of state is not populated the user will not see any error.
Log the run status and raise an error with either 'error' 'reason' or 'status_text'
```
> 2023-06-07 14:10:10,740 [info] Run executed, status=error: {'name': 'sleepy-breast-cancer-generator'}
> 2023-06-07 14:10:10,740 [error] Runtime error: {'status': {'state': 'error', 'artifacts': [], 'start_time': '2023-06-07T13:59:48.163090+00:00', 'last_update': '2023-06-07T14:10:10.038952+00:00', 'reason': 'A runtime resource related to this run could not be found'}}
```
The exception:
```
File ~/.pythonlibs/mlrun-base/lib/python3.9/site-packages/mlrun/launcher/base.py:364, in BaseLauncher._wrap_run_result(self, runtime, result, run, schedule, err)
362         if …
```
> [Run] Fix runtime error log

- mlrun/utils/helpers.py
- tests/system/projects/test_project.py
Users are not required to specify an image.
`warnings.warn` is mainly used for deprecations and it can be filtered. mlrun usage information should be logged with mlrun logger.
> [Utils] Fix remove image protocol prefix of default image

- tests/common_fixtures.py
- tests/test_execution.py
Runs should not be under "struct". There is no value for it and we want to always return the run from `read_run` to align the behavior of real dbs.
> [Tests] Fix `RunDBMock` runs dictionary

- .github/workflows/system-tests-enterprise.yml
- .github/workflows/system-tests-opensource.yml
To ensure that commits recently pushed and havent been built are not running on open/enterprise tests
> [CI] Run tests on commit older than an hour

- mlrun/projects/project.py
- tests/projects/test_project.py
https://jira.iguazeng.com/browse/ML-3992
In order to enable function versioning in the project's function dicts we will add the function tag if it was provided and the function name was not.
> [Project] Optionally add function tag to key of project function dicts

- mlrun/utils/notifications/notification/git.py
- tests/utils/test_notifications.py
Fixes https://jira.iguazeng.com/browse/ML-3924
Gitlab notifications were only being posted to merge requests. Added distinction between issues and merge requests to allow both.
> [Notification] Fix gitlab notification not being posted on issues

- mlrun/feature_store/feature_set.py
In order to display the engine name `"storey"` in the UI, 
the `storey` engine will be saved in the `feature_set` as `storey` (not as None).
https://jira.iguazeng.com/browse/ML-3938
> [Feature Store] -  Save the engine as "storey" when the input engine is None.

- go/cmd/schemas_compiler/docker/Dockerfile
Seems like the compiled schemas were malformed with
<details><summary>Details</summary>
<p>
```python
File "/mlrun/mlrun/api/utils/periodic.py", line 34, in _periodic_function_wrapper
await function(*args, **kwargs)
File "/mlrun/mlrun/api/main.py", line 278, in _initiate_logs_collection
await _start_log_and_update_runs(start_logs_limit, db_session, runs)
File "/mlrun/mlrun/api/main.py", line 296, in _start_log_and_update_runs
results = await asyncio.gather(
File "/mlrun/mlrun/api/main.py", line 340, in _start_log_for_run
mlrun.api.utils.clients.log_collector.LogCollectorClient()
File "/mlrun/mlrun/utils/singleton.py", line 23, in __call__
cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
File "/mlrun/mlrun/api/utils/clients/log_collector.py", line 77, in __init__ …
```
> [gRPC] Fix compiling schemas docker image [1.3.x]

- mlrun/run.py
I decided to not replace the code with a call to the launcher because some parameters can not be passed to the launcher and they should be set by the user upon creating the function:
1. tag
2. secret - this is used to extract the "command" file from remote source and is not supported with `fn.run`
3. mode
4. allow_empty_resources
https://jira.iguazeng.com/browse/ML-3547
> [Run] Deprecate `run_local`

- tests/system/base.py
Tests were failing because before 1.4.x it expected artifact run outputs to be full path (the source path) rather than the "reference" mlrun holds for those artifacts (aka destination path).
see origin change at https://github.com/mlrun/mlrun/pull/3333/files#diff-391847342995c01c5190eef868647ffd33183b03eba033b71baa13e3df39b0c5R100-R104
> [CI] Fix failing tests

- mlrun/datastore/spark_udf.py
The Spark User Defined Function (UDF), which is responsible for creating synthetic entry names for Redis during dataframe storage, should accommodate varying input formats. Depending on the calling context, Spark may provide entity arguments as a list or as separate variable parameters. This variability in argument presentation must be handled within the UDF
[ML-4008] (https://jira.iguazeng.com/browse/ML-4008)
> [Spark] Fix storing multiple keys from a Spark dataframe into Redis

- mlrun/api/api/endpoints/pipelines.py
- mlrun/api/crud/pipelines.py
- mlrun/kfpops.py
1. Do not "str" on None fields - to avoid "None"
2. Use snake case for schema fields
In addition, 
1. fixed a potential hogging on main event loop where kfp get pipeline is a sync call on async function
2. on pipelines endpoint - move endpoints to first, help functions at bottom
> [KFP] Align pipelines output with mlrun conventions

- mlrun/serving/v2_serving.py
- tests/serving/test_serving.py
In order to check if the serving model has been deployed successfully and that is ready to process new events, the user can invoke the function under the `/ready` path. At the moment, the user receives an empty response with no details about the serving model status.
In this PR, we generate a valid response object that will be returned to the user when the function is ready for process new events.
A fix for https://jira.iguazeng.com/browse/ML-3362.
> [Serving] Fix response for readiness status

- mlrun/datastore/base.py
- tests/system/feature_store/test_feature_store.py
[ML-4025](https://jira.iguazeng.com/browse/ML-4025)
Fixes PyArrow error
```
Cannot compare timestamp with timezone to timestamp without timezone, got: timestamp[us, tz=UTC] and timestamp[us]
```
similar to the solution for [ML-3566](https://jira.iguazeng.com/browse/ML-3566).
This fixes a regression in v1.4.0-rc13 that was introduced by https://github.com/mlrun/mlrun/pull/3637, which propagated time filtering from `preview()`.
> [Datastore] Fix time zone error

- requirements.txt
https://jira.iguazeng.com/browse/ML-4022
https://fastapi.tiangolo.com/release-notes/#0952
FastAPI updates from upgrading:
1. Introduction of lifespan instead of shutdown and startup events - lifespan is the new recommended way but events are still supported even though they are deprecated in starlette.
2. Support for dependencies and parameters using `Annotated` (resolves code duplication)
> [Requirements] Bump fastapi to fix security vulnerability

- tests/system/projects/test_project.py
So that we don't aggregate projects to delete and try to delete many projects that were deleted
> [System Tests] Clear custom project names to delete after deletion

- mlrun/feature_store/api.py
- tests/system/feature_store/assets/fields_with_space.csv
- tests/system/feature_store/test_feature_store.py
Columns with special characters, such as spaces, need to be renamed.
In the `ingest` function, we have implemented the renaming of these columns by utilizing the `_rename_source_dataframe_columns` function.
This PR also updates the `preview` function to behave in the same way.
https://jira.iguazeng.com/browse/ML-3539
> [Feature Store] Fix preview to rename column headings containing the `space` char

- mlrun/api/utils/clients/iguazio.py
- mlrun/utils/http.py
- requirements.txt
- tests/test_requirements.py
Following https://jira.iguazeng.com/browse/ML-4001 which indicates a retry mechanism during create project, Ive added some log lines to provide better debugging experience when such issue occurs
In addition "increase" the urllib3 lock as its internal api changed between 1.25.x to 1.26.x (no breaking, just deprecations) thus, limited the range of versions and narrowed it down to 1.26 while fixing some of the deprecations
> [API] Debug create project

- dockerfiles/test/Dockerfile
python-slim changed its debian dist, thus docker cli installation failed. updated script as per official docker installation script suggests
> [CI] Update test dockerfile docker installation

- mlrun/api/db/sqldb/db.py
- mlrun/projects/project.py
- mlrun/utils/async_http.py
- mlrun/utils/http.py
1. Separated try/except flow for get or create project so that when load fails + create fails -> the stacktrace does not include both exceptions but rather fall and shows the create exception only.
2. Added "User-Agent" to requests/ client containing mlrun version
related to https://jira.iguazeng.com/browse/ML-4001
> [Debug] Improve flows for better debugging

- docs/monitoring/dashboards/iguazio-3.5.2-and-older/model-monitoring-overview.json
- docs/monitoring/dashboards/model-monitoring-overview.json
- mlrun/api/crud/model_monitoring/grafana.py
- mlrun/model_monitoring/stream_processing_fs.py
A fix for https://jira.iguazeng.com/browse/ML-1767.
This PR is a fix for a bug in the `model monitoring overview` dashboard within Grafana when the project includes a router model. The latency of the router model is combined from the router process time along with the latency time of the related child models. That means, when calculating the average latency of all of the models in the project, the latency of the router model should be excluded. At the moment, Grafana also considers the average latency time of the router model in both the **Average Latency KPI** at the top of the screen and the **Average Latency time series chart** at the bottom of the screen. In this PR, we fix it by excluding the router model from these calculations. 
Please note that due to changes in Grafana dashboards …
> [Model Monitoring] Filter router models from the total average latency in Grafana

- Makefile
- dockerfiles/base/Dockerfile
Updating the conda environment resolves an issue we experience with compiling scikit packages
I chose 23.1.0 because the next version does not support python 3.7
> [Images/Base] Update conda to 23.1.0

- mlrun/common/schemas/auth.py
MLRun 1.5.0 will be using marketplace APIs, and this requires the OPA manifest to support it. We need to support older igz versions which only support the `/marketplace/sources` path, so we need to keep using the OPA `/marketplace/sources` rather than shift to the new `/hub/sources`, which will only be supported in igz 3.5.4.
Once MLRun will only be supported with igz >=3.5.4, this can be changed back to point at `/hub/sources`.
> [Authz] Revert OPA `hub` path to `marketplace`

- requirements.txt
- tests/test_requirements.py
pydantic 1.10.8 fixes a bug with literal and typing-extension 4.6.0  https://docs.pydantic.dev/latest/changelog/#v1108-2023-05-23
> [Requirements] Bump pydantic

- mlrun/api/crud/pipelines.py
- mlrun/kfpops.py
- mlrun/utils/helpers.py
- tests/api/api/test_pipelines.py
resolves: [ML-3912](https://jira.iguazeng.com/browse/ML-3912?filter=-1)
A run's time field that has not yet occurred (such ad `finished_at`, when there is still no finished time) is represented by `1970-01-01 00:00:00+00:00`, which appears as a deceptive date in the UI.
In this PR, changing the value to `None`, and  it appears as follows in the UI:
> [Workflows] Fix fields being set to misleading value when setting workflow

- .run/MLRun API.run.xml
assuming `mlrun.env` file to be located under `hack/mlrun.env`. running mlrun api via this run configuration will allow using debugger from pycharm.
mlrun.env file should include relevant mlrun configuration in form of "envvars" so that config.py will be able to parse it and load it accordingly.
e.g.:
```
MLRUN_HTTPDB__DSN=mysql+pymysql://root@localhost:3306/mlrun
MLRUN_LOG_LEVEL=DEBUG
...
```
> [DevEnv] Added pycharm MLRun API run configuration

- mlrun/api/api/utils.py
- mlrun/api/main.py
- tests/utils/test_notifications.py
Fixes https://jira.iguazeng.com/browse/ML-4035
While trying to unmask a notification's params, if failed unmasking, Instead of raising the exception and stopping the notification sending iteration, log the error and save the notification with `ERROR` status.
> [Notifications] Fix secret unmasking fails the whole notification mechanism

- dockerfiles/jupyter/requirements.txt
- requirements.txt
Following some fixes released in https://github.com/nuclio/nuclio-jupyter/releases/tag/v0.9.11
> [Requirements] Bump nuclio-jupyter to 0.9.11

- mlrun/common/schemas/__init__.py
- mlrun/common/schemas/regex.py
- mlrun/runtimes/base.py
- mlrun/runtimes/function.py
- mlrun/runtimes/utils.py
- mlrun/utils/helpers.py
- mlrun/utils/regex.py
- tests/integration/sdk_api/httpdb/test_exception_handling.py
- tests/run/test_run.py
- tests/system/projects/assets/pipeline_with_resource_param.py
- tests/system/projects/test_project.py
- tests/utils/test_helpers.py
https://jira.iguazeng.com/browse/ML-3713
Until now we weren't able to pass pipeline param to function spec due to two reasons:
- strict regex validation that was applied on function attributes specifically resources attribute
- when running a function inside a pipeline we were storing the function to the DB and holding only the function url inside the workflow spec, this caused failure in converting the pipeline param to actual value because that this transformation happens when kfp transforms the kfp step to actual k8s resource, therefor we had to add logic that if we find pipelineparam in the function spec we don't save the function to the db but rather saves the full function spec in the workflow spec so that pipeline will convert that placeholder to value.
Actions made -
- Added an …
> [Pipelines] Support passing pipeline param to function spec resources

- mlrun/artifacts/base.py
- tests/artifacts/test_artifacts.py
Before pr, logging `"x.tar.gz"` artifact would have been saved as `x.gz` as the function took the last part only.
After, the path would be `x.tar.gz` as expected
https://jira.iguazeng.com/browse/ML-4082
> [Artifact] Fix enriching suffixes

- tests/system/projects/test_project.py
Seems like tests from other branches leave some breadcrumbs which causes development-cycle tests to fail transiently on project existence
> [CI] Fix system test system deletion

- mlrun/common/schemas/notification.py
- mlrun/model.py
- tests/utils/test_notifications.py
resolves: [ML-4090](https://jira.iguazeng.com/browse/ML-4090) and [ML-4091](https://jira.iguazeng.com/browse/ML-4091)
The following fields must be present in the notification: kind, when, message, and severity; the rest are optional.
This PR ensures that if they are not passed, the request will not fail and will have default values, and adds validation that it is as intended when they are.
Please note that this change affects backward compatibility, but the notification feature has not been released to users yet, so we can disregard the breakage.
> [Notifications] Add default values and validation to notifications

- mlrun/artifacts/base.py
- mlrun/lists.py
- mlrun/render.py
- tests/assets/log_function.py
- tests/common_fixtures.py
- tests/test_render.py
When we show the results html in a jupyter notebook we link the artifacts to their target paths.
If logging the artifact failed and `generate_target_path_from_artifact_hash` is enabled the target path might not have been set - if that happens, warn and continue.
https://jira.iguazeng.com/browse/ML-2880
> [Artifacts] Fix resolving target path in artifacts html

- .github/workflows/build.yaml
- .github/workflows/release.yaml
- .github/workflows/security_scan.yaml
- .github/workflows/system-tests-enterprise.yml
- .github/workflows/system-tests-opensource.yml
To reduce human error when need to fill values in manual dispatch, taking advantage of [options](https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/workflow-syntax-for-github-actions#example-of-onworkflow_dispatchinputs) in defining workflow dispatch parameters.
> [CI] Add options to github workflow manual dispatches

- mlrun/db/httpdb.py
- mlrun/projects/project.py
The `name` parameter is query like only when it is used with `~` prefix.
> [Artifacts] Fix list artifacts `name` docstring

- Makefile
- automation/requirements.txt
- automation/version/version_file.py
- dockerfiles/test/Dockerfile
- tests/automation/version/__init__.py
- tests/automation/version/test_version_file.py
Added a functionality to version_file.py script to determine the current/next mlrun version based on
1. feature name
2. git branch
3. current / latest mlrun release
Such functionality is useful to to trigger release without explicitly give the prev/next version to build.
In general, once running the script with "current-version", the script will
1. iterate over current branch commits
2. iterate all tags related to commit
3. match with "unstable version prefix" to see it matches (read: unstable version prefix is how we determine the "base" version"
4. upon a match, we iterate over commit tags to find the "latest greatest"
Upon next-version, it simply takes the current-version, and based on branch name (read: feature branch or other) - it will base the next version with respect to "mode" …
> [CI] Prepare for feature release

- mlrun/frameworks/_ml_common/plans/calibration_curve_plan.py
(cherry picked from commit 8b5593bb4d3ab03a661176bd7a371cb96355f45f)
because CI fails with the same error https://github.com/mlrun/mlrun/actions/runs/5437840893/jobs/9888659535
> [Frameworks] Support SciKit-Learn 1.3 deprecated normalize [1.3.x]

- .github/workflows/build-internal.yaml
- .github/workflows/build.yaml
- .github/workflows/periodic-rebuild.yaml
- .github/workflows/release.yaml
Reuse workflow for build-internal so that it can be called from build/release and soon periodic. The idea is so use builtins by github and reduce external workflows.
In addition:
- added some fixes and tweaks for release/build to skips parts when needed without failing the entire workflow (e.g.: when skipping pypi, let it continue for create release part).
- use github token generated as per "permission" section to create release / upload container images to ghcr
> [CI] Introducing workflow reuse

- mlrun/datastore/sources.py
- mlrun/feature_store/feature_set.py
- tests/system/feature_store/test_feature_store.py
[ML-4126](https://jira.iguazeng.com/browse/ML-4126)
When preforming time filtering on parquet datasource we have to pass start and end time.
> [Feature Store] Fix `feature_set.to_dataframe` when passthrough is True 

- mlrun/projects/project.py
- tests/artifacts/test_artifacts.py
- tests/common_fixtures.py
When exporting a project we use `register_artifact` to save the artifacts which we create a new producer to save them.
Since we use the producer tag "latest" we might be overriding other artifacts with "latest" tree therfeore, we need a uniqe uid.
That being said, this doesn't completely resolve the issue as the exported project may have multiple artifact logged by different runs (different trees) and once we export them they will override each other until we are left with the last logged artifact.
https://jira.iguazeng.com/browse/ML-4074
> [Artifacts] Fix register artifacts overrides old artifacts

- mlrun/projects/project.py
- mlrun/utils/helpers.py
- tests/projects/test_project.py
resolves: [ML-3702](https://jira.iguazeng.com/browse/ML-3702)
The issue was when setting a workflow like this:
my_workflow = project.set_workflow('main', "./"), and no error message was presented to the user.
reopen for: https://github.com/mlrun/mlrun/pull/3797
should fix the issue - in case of a relative workflow_path, checking the existence of the file in the project code_path.
> [Workflows] Add validation and error message for invalid workflow setup

- mlrun/utils/notifications/notification/git.py
Fixes - https://jira.iguazeng.com/browse/ML-4145
It seems like the way the GitHub event file is structured now is changed, and we need to change it now to use the `number` attribute in the json on the top level and not under `issue`.
> [Notifications] Fix Getting Git notification issue from GitHub event file

- mlrun/api/crud/projects.py
- mlrun/api/crud/secrets.py
- mlrun/api/utils/clients/iguazio.py
- mlrun/api/utils/events/base.py
- mlrun/api/utils/events/iguazio.py
- mlrun/api/utils/events/nop.py
- tests/system/api/test_secrets.py
- tests/system/base.py
- tests/system/env-template.yml
Remove the secret name from project secret audit events as its name is opaque and says nothing to end user.
https://jira.iguazeng.com/browse/ML-4140
In addition
- Removed specific "generate_*" functions from base, as it has nothing to do with implementation when there is a factory method for that, given an "action"
- Update from latest sdk where RequestManualEvent is simply an Event
- Added system test to cover create/update/delete project secret flow
- Added parameters text, to expose the information in a json-manner
events:
deleted inspection:
updated inspection: (key is uuid4 generated by test)
created inspections:
> [Audit] Refine audit event descriptions

- tests/common_fixtures.py
- tests/projects/test_project.py
Add chdir_to_test_location fixture,
It allows seamless access to files relative to the test file.
> [Tests] Add fixture to change the working directory for tests

- mlrun/api/api/endpoints/functions.py
- mlrun/common/schemas/function.py
Previously - we were storing the function to the DB for every get request on `/build/status`
Now - we will update the function status to the DB only when changes in function status were detected
> [Function] Reduce amount of storing to the DB on `/build/status` endpoint

- README.md
Slack badge was pointing at the wrong location due to relative path usage.
> [Docs] Fix slack badge

- mlrun/model_monitoring/stream_processing_fs.py
- tests/system/model_monitoring/test_model_monitoring.py
In the monitoring stream graph we have 2 `AggregateByKey` steps: one for predictions counter and one for average latency. When applying `AggregateByKey` step, we need to provide a table path for persistence of aggregations. In our case, we have used the same table for the 2 step, which have led to wrong calculations - https://jira.iguazeng.com/browse/ML-4114.
In this PR, we fix that issue by reducing the 2 steps into a single step in which we calculate both predictions and average latency in the same window and period of time. Therefore, we can still use a single table for the calculations and avoid unexpected results. 
In addition, we had to add a new "Rename" step to change the name of the new resulted fields to the required values (`latency_count_1h` -> `predictions_count_1h` & …
> [Model Monitoring] Fix predictions and latency calculations in monitoring stream graph

- automation/system_test/prepare.py
new system tests require audit events.
more in code comments
> [Automation] Enable mlrun audit events for system tests

- mlrun/api/crud/projects.py
- mlrun/api/crud/secrets.py
- mlrun/api/utils/singletons/k8s.py
- tests/system/api/test_secrets.py
(cherry picked from commit d01ae5137772599cae73210a9341999761cadf3d)
backports https://github.com/mlrun/mlrun/pull/3890
> [Events] Fix emitting deleted secret event on 404 [1.4.x]

- .importlinter
- Makefile
This will enable us to verify that no extra "bad" imports are added.
The end goal is to not have any modules under `ignore_imports`.
> [CI] Add import-linter verification

- automation/version/version_file.py
- tests/automation/version/test_version_file.py
For cases where an rc release was not made yet and we need to trigger one for a new version
before, running with next-version --mode rc -> yields "1.4.0-rc20"
after, yields 1.5.0-rc1 (as expected) because -
current version (aka last version created - 1.4.0-rc19)
base version is 1.5.0 (as per development)
and no release (or rc) was triggered.
> [Release] Enhance resolving next version

- mlrun/api/api/endpoints/files.py
The new `files` API retrieves project secrets before accessing files, to enable access to stores that need credentials. In a situation where MLRun service is not running on k8s (Docker, local deployments), this would explode. 
Added a check to verify first that we're running inside a k8s cluster. If we're not, the file will be retrieved without attempting to get project secrets for authentication.
> [API] Fix `files` API to work on non-k8s environments

- mlrun/feature_store/api.py
- tests/system/feature_store/test_spark_engine.py
The real error is masked by this subsequent error:
```
mlrun.runtimes.utils.RunError: 'Response' object has no attribute 'persist'
```
> [Spark] Fix masking of errors in spark graph

- mlrun/feature_store/api.py
Backport of #3912 with fix from #3919.
[ML-2087](https://jira.iguazeng.com/browse/ML-2087)
Without it, the data is read in by
* [the read operation](https://github.com/mlrun/mlrun/blob/v1.4.0-rc19/mlrun/datastore/sources.py#L101) (for the schema)
* [hasattr(df, "rdd")](https://github.com/mlrun/mlrun/blob/v1.4.0-rc19/mlrun/data_types/__init__.py#L33) (!!) (1)
* [stats calculation](https://github.com/mlrun/mlrun/blob/v1.4.0-rc19/mlrun/data_types/spark.py#L114) (1)
* [get_df_preview_spark](https://github.com/mlrun/mlrun/blob/v1.4.0-rc19/mlrun/data_types/spark.py#L77) (1)
* [Per target (on write)](https://github.com/mlrun/mlrun/blob/v1.4.0-rc19/mlrun/feature_store/api.py#L955) (1)
(1) also runs graph calculations
> [Feature Store] Persist Spark dataframe in ingest to improve performance [1.4.x]

- mlrun/api/db/sqldb/db.py
- mlrun/api/db/sqldb/models/models_mysql.py
- mlrun/api/db/sqldb/models/models_sqlite.py
- tests/api/db/test_sqldb.py
- tests/api/utils/test_scheduler.py
The db's `_commit` function is a helper function that gets multiple objects and tries to commit them to the db.
It's advantage is that it is retrying the commit if it fails, with some logs which depend on the failures.
Before this PR this function assumed all given objects are of the same class for logging purposes, which might not be the issue.
Now, the logs log all of the classes given in the objects.
Also, since it is using the db schema's `get_identifier_string`, I added this method to the classes that were missing it.
> [DB] Fix `_commit` logs to support multiple object classes

- mlrun/api/utils/projects/follower.py
If for any reason the project isn't deleted (from a bug, malformed data, etc...)
We want to best-effort the procedure and delete as many projects as possible and log warnings for the projects that weren't deleted.
> [Projects] Fix Project Sync Fails on Malformed Project

- docs/concepts/notifications.md
- mlrun/common/schemas/notification.py
- mlrun/utils/notifications/notification/__init__.py
- mlrun/utils/notifications/notification/webhook.py
- tests/utils/test_notifications.py
Add Webhook notification implementation to the notification mechanism.
Users will be able to supply in notification params:
- `url`: The webhook url to which to send the notification.
- `method`: The http method to use when sending the notification (GET, POST, PUT, etc...).
- `headers`: (dict) The http headers to send with the notification.
- `override_body`: (dict) The body to send with the notification. If not specified, the body will be a dict with the `name`, `message`, `severity`, and the `runs`
> [Notifications] Add Webhook notification type

- mlrun/feature_store/api.py
- tests/system/feature_store/test_spark_engine.py
Backport of #3919.
The real error is masked by this subsequent error:
```
mlrun.runtimes.utils.RunError: 'Response' object has no attribute 'persist'
```
> [Spark] Fix masking of errors in spark graph [1.4.x]

- .flake8
- mlrun/api/runtime_handlers/base.py
- mlrun/api/utils/singletons/db.py
This way when we use `get_run_db` we get the sql run db instead of the nop one.
> [API] Set run db URL to DSN

- mlrun/api/utils/builder.py
- mlrun/common/schemas/runs.py
- mlrun/common/schemas/schedule.py
- mlrun/runtimes/kubejob.py
Do some TODOs leftovers from python 3.7 limitations
> [Schemas][Builder][Kubejob] Remove python 3.7 leftovers

- docs/install/kubernetes.md
The repo name should be mlrun-ce as mentioned in the next installation steps
> [Docs] Fix helm repo add mlrun-ce command

- mlrun/api/api/endpoints/workflows.py
- mlrun/api/crud/workflows.py
- mlrun/common/schemas/workflow.py
- mlrun/db/httpdb.py
- tests/api/api/test_workflows.py
Fixes the following bugs:
1. `parse_reference` - parsed job's uid wrongly (length can be smaller than 40)
2. Using only `store_schedule` and removing deprecated `override` field in `WorkflowSpec`.
3. Passing `subpath` into `load_and_run`.
> [API] Fix workflow bugs (system tests)

- automation/system_test/prepare.py
stderr is bytes
```
File "/home/runner/work/mlrun/mlrun/automation/system_test/prepare.py", line 238, in _run_command
if suppress_error_string in stderr:
TypeError: a bytes-like object is required, not 'str'
```
> [Automation] Fix check for suppressed errors

- .importlinter
- mlrun/api/crud/model_monitoring/helpers.py
- mlrun/api/crud/model_monitoring/model_endpoints.py
- mlrun/api/crud/secrets.py
- mlrun/model_monitoring/helpers.py
- mlrun/model_monitoring/stores/__init__.py
- mlrun/model_monitoring/stores/sql_model_endpoint_store.py
The main goal of this PR is to remove the unnecessary import from MLRun API (`import mlrun.api.crud.secrets`) when calling `get_connection_string()` from the client side. In this PR, we add a secret provider to the `get_connection_string` function that handles the call from the API side. This secret provider is actually a new callable function that can be found under `mlrun.api.crud.secrets.py`. 
A related JIRA: https://jira.iguazeng.com/browse/ML-4240
> [Model Monitoring] Secret provider for SQL connection string on API side

- mlrun/api/api/endpoints/files.py
- mlrun/api/api/endpoints/logs.py
- mlrun/api/api/endpoints/runs.py
- tests/api/api/test_files.py
- tests/api/api/test_runs.py
resolves: [ML-4100](https://jira.iguazeng.com/browse/ML-4100)
- `/files` and `/filestat` - deprecate these APIs
- GET/POST `/log/{project}/{uid}` -> GET/POST `/projects/{project}/logs/{uid}`
- GET/POST/PATCH/DELETE `/run/{project}/{uid}` -> GET/POST `/projects/{project}/runs/{uid}`
- GET/DELETE `/runs` -> GET/DELETE` /projects/{project}/runs `
> [API] Change MLRun REST API URLs to conform with the best-practice

- mlrun/api/api/endpoints/projects.py
- mlrun/db/httpdb.py
- tests/system/projects/test_project.py
The use of `BackgroundTask` in this context was not fully useful since it does not keep in hand the return value and it is impossible to watch jobs in the server side.
In order to keep track of the job state, this endpoint returns now a `RunObject` that is now watched by `run.logs()` in the `httpdb.py`.
> [API] Fix load-project return `RunObject` instead of `BackgroundTask`

- .importlinter
- mlrun/api/crud/notifications.py
- mlrun/api/main.py
- mlrun/api/rundb/sqldb.py
- mlrun/db/base.py
- mlrun/db/httpdb.py
- mlrun/utils/notifications/notification_pusher.py
As part of the server-client separation.
I decided not to create a dedicated `update_run_notification` like we have `update_run` and `store_run` separately because:
1. it will essentially do the same thing as `store_run_notification`
2. I don't see a reason to list the notifications and validate they exist (as update logic suggests).
Instead I added the flag to disable masking the notification params.
> [Notifications] Use Run DB to store run notifications

- mlrun/api/api/endpoints/files.py
Fix deprecation message that was wrongly copy-pasted.
> [API] Fix deprecation message for `files` and `filestat` APIs

- mlrun/api/api/utils.py
- mlrun/api/crud/workflows.py
- mlrun/api/db/sqldb/db.py
- mlrun/api/utils/scheduler.py
- tests/api/utils/test_scheduler.py
This PR adds the following fixes/improvements:
1. Use store schedule flow in submit job instead of update or create if not found.
2. Enriches with default concurrency limit if not specified (single point `_create_schedule_db_record`) 
3. Fixes type hints, `Schedule` is the model to commit to the db, `ScheduleRecord` is the schema returned from the db layer.
4. Adds store schedule unit tests
> [Scheduler] Store schedule improvements

- automation/system_test/prepare.py
We are getting connection reset errors quite often recently:
```
2023-07-29 16:18:03,995 - automation - INFO - Deleting mlrun db pod: {'mlrun_db_pod_name_cmd': 'mlrun-db-74b8db68c6-4qj5p'}
Socket exception: Connection reset by peer (104)
2023-07-29 16:22:45,852 - automation - ERROR - Failed running command on data cluster: {'error': 'Command failed with exit status: -1', 'stdout': '', 'stderr': b'Defaulted container "mlrun-db" out of: mlrun-db, init-mysql (init)\nUnable to use a TTY - input is not a terminal or the right kind of file\n', 'exit_status': -1}
```
Hopefully this will fix it because clearly it's a script and is not interactive
> [Automation] Remove tty flag from delete db command

- mlrun/api/api/utils.py
- mlrun/api/launcher.py
- mlrun/api/utils/scheduler.py
- mlrun/launcher/factory.py
- tests/api/api/test_utils.py
- tests/api/test_launcher.py
When the server side launcher receives the auth info it will enrich and validate the runtime with `mlrun.api.api.utils.apply_enrichment_and_validation_on_function`
This will enable using the auth info in https://github.com/mlrun/mlrun/pull/4008
Note that for schedules which also use the submit job endpoint, the auth info is stores in the `submit_run_wrapper` closure and then passed again to the submit job flow to trigger the run.
> [API] Pass auth info to launcher in submit job flow

- mlrun/__main__.py
fixes: https://jira.iguazeng.com/browse/ML-2019
in the UI, the artifact has no "tree" column ( and the term "tree" is not mentioned anywhere) , but it is "uid", so changed the CLI to be corresponding to it.
> [CLI] Get artifacts - change the "tree" column to "workflow/job uid"

- .importlinter
- mlrun/api/api/endpoints/functions.py
- mlrun/api/crud/functions.py
- mlrun/api/rundb/sqldb.py
- mlrun/api/runtime_handlers/__init__.py
- mlrun/api/runtime_handlers/daskjob.py
- mlrun/db/base.py
- mlrun/db/httpdb.py
- mlrun/runtimes/__init__.py
- mlrun/runtimes/daskjob.py
Part of client-server separation.
Moving the "start" and "status" methods to the API.
Using the run db abstraction to execute the logic from common code.
> [Dask] Move resource methods to API

- mlrun/db/httpdb.py
- mlrun/utils/helpers.py
- tests/system/datastore/test_http.py
These tests cannot use the hub since the configuration has changed and creating a new hub requires adhering to a certain file structure. Since the point of the test is to test the data store and not the hub, I changed the url straight to the https url instead of creating an extra hub which will require updating the `private-system-tests` repo to the required structure.
> [Tests] Fix HTTP Data Store tests

- mlrun/utils/helpers.py
Following #3598 , the function `parse_versioned_object_uri` has been moved from `mlrun/utils/helpers.py` to `mlrun/common/helpers.py` because it is being used by both Client and Server side.
However, to handle backwards compatibility (a fix for https://jira.iguazeng.com/browse/ML-4276), in this PR we add a reference to that function from `mlrun/utils/helpers.py`.
> [Utils] backwards compatibility for parsing object URI 

- mlrun/api/crud/client_spec.py
- mlrun/api/runtime_handlers/__init__.py
- mlrun/api/runtime_handlers/mpijob.py
- mlrun/api/utils/singletons/k8s.py
- mlrun/runtimes/__init__.py
- mlrun/runtimes/mpijob/__init__.py
- mlrun/runtimes/utils.py
- tests/api/conftest.py
- tests/api/runtime_handlers/test_mpijob.py
- tests/api/utils/singletons/test_k8s_utils.py
- tests/common_fixtures.py
Part of client-server separation - moved the code that resolves the crd version via k8s query to the API and added a dependency injector container that allows us to override the way we resolve the version.
On the client side it will be enriched by the client-spec endpoint.
> [MPI] Use dependency injection to resolve the crd version

- mlrun/api/utils/projects/follower.py
- tests/api/utils/projects/test_follower_member.py
We realise that deleting the projects immediately if not found in the leader can cause data-loss if the project wasn't returned from the leader due to some transient issue.
Instead, we now archive the project instead of deleting it. This way, if the project does come back from the leader, it will be automatically unarchived and returned to normal.
If the project indeed was deleted from the leader and is in an archived state in mlrun, it is possible to create a new project with the same name, and this will link up the newly created project in the leader with the archived one in mlrun and effectively unarchive it.
> [Projects] Fix Projects Sync Deleting Projects not found in leader

- mlrun/db/httpdb.py
Following #3977. Reportedly, this broke at least one system test (`test_function_with_builder_env`).
This reimplementation should be resilient to missing config values at all levels.
> [DB] Fix data prefix resolution in case of missing config value

- automation/system_test/prepare.py
To avoid transient error we use retry mechanism, a side effect is that the ssh client gets stale during retry and thus we need to establish new ssh connection
> [CI] Ensure ssh client is active prior to running remote commands

- mlrun/api/crud/workflows.py
- mlrun/utils/helpers.py
1. Fix `normalize_name` - use `remove_prefix()` instead of `lsplit()` which can remove unnecessary characters.
2. Use `dirty=True` when `save=True` is applied.
> [API] Fix submit workflow remote engine

- tests/system/model_monitoring/test_model_monitoring.py
Following #4020 , the model endpoint id is now added as a tag on each monitoring feature set. As a result, the default monitoring feature set URI has been changed accordingly. 
In this PR, we update the feature set URI validation in the monitoring system tests.
> [Model Monitoring] Fix monitoring feature set URI in system tests

- mlrun/api/api/endpoints/functions.py
- mlrun/api/api/endpoints/projects.py
- mlrun/api/api/endpoints/workflows.py
- mlrun/api/api/utils.py
- mlrun/api/crud/model_monitoring/deployment.py
- mlrun/api/crud/model_monitoring/model_endpoints.py
- mlrun/api/crud/workflows.py
- mlrun/api/rundb/sqldb.py
- mlrun/db/httpdb.py
- tests/api/test_rundb.py
- tests/rundb/test_unit_httpdb.py
Since the SQLRunDB is effectively a singleton (the factory holds its instance) we encountered the following errors:
1. We cannot use the session in multithreading until we move to async engine.
2. If a session query fails and not rolled back the session dies and can't be use anymore.
3. Keeping an open connection to the DB is occupying it and we see queries wait forever when the API is idle.
Here we create a new session for each operation (the session is not used from outside of the run db) and we make sure to close it when operation is done.
We still have other places where we create sessions in the API and we access the db layer (SQLDB) directly and we can improve this  mechanism but this should fix the issues we see for now.
> [SQLRunDB] Fix abuse of sessions

- mlrun/api/api/endpoints/files.py
- mlrun/datastore/dbfs_store.py
- tests/integration/test_dbfs_store/test_dbfs_store.py
In datastore default `size` is None.
This PR change default `size` from zero  to `None` also in the API.
Nevertheless, the DBFS has been modified to handle zero size.
[ML-4351](https://jira.iguazeng.com/browse/ML-4351)
> [Datastore] Fix dbfs zero size handling

- mlrun/api/api/endpoints/functions.py
- mlrun/api/api/endpoints/pipelines.py
- mlrun/api/api/endpoints/projects.py
- mlrun/api/api/endpoints/workflows.py
- mlrun/api/api/utils.py
- mlrun/api/crud/model_monitoring/deployment.py
- mlrun/api/crud/model_monitoring/model_endpoints.py
- mlrun/api/crud/pipelines.py
- mlrun/api/crud/workflows.py
- mlrun/api/db/session.py
- mlrun/api/rundb/sqldb.py
- mlrun/db/factory.py
- mlrun/db/httpdb.py
- mlrun/kfpops.py
- tests/api/api/test_pipelines.py
- tests/api/test_rundb.py
- tests/rundb/test_unit_httpdb.py
We decided to revert #4067 due to session isolation issues where if session A would be created from the endpoint dependency injection and session B would create some objects and commits them, session A would not be able to access them.
It is possible to change the isolation level to fix this but it might result in data anomalies.
Here we have to essential fixes that were the initial reasons for the fix:
1. Rollback sessions that result in sqlalchemy errors (A connection issue can corrupt a session and make it unusable until rolled back)
2. Using different sessions for concurrent operations - sessions are not thread safe. This effectively invalidates the previous session as it can't access the committed changes due to isolation level.
However, there is still work required since the run db …
> [API] Fix session rollback and multithreading

- .run/Unit tests.run.xml
Currently, the configuration flags intended for launching Pytest on Pycharm are stored on the "Parameters" field. However, that field is intended for test parameters and not for CLI arguments, so these flags end up not being received by Pytest in the intended manner.
One of the side effects of this distinction is the amount of tests compiled for execution. When the configuration flags are stored on the "Parameters" field, Pycharm detects 3302 tests for execution. But when we move the flags to the "Additional Arguments" field, the `--ignore` flags are sent to the CLI and the compiled amount of tests is reduced to 2730.
This PR makes the necessary changes on Pycharm's run configuration so that such flags are passed to Pytest as expected.
> [Tests] Pass Pytest flags on the Arguments field of Pycharm configuration

- mlrun/api/crud/workflows.py
- mlrun/config.py
- mlrun/datastore/targets.py
- mlrun/feature_store/api.py
- mlrun/feature_store/feature_set.py
- mlrun/launcher/base.py
- mlrun/model.py
- mlrun/projects/project.py
- mlrun/run.py
- mlrun/utils/helpers.py
- tests/system/feature_store/test_feature_store.py
- tests/utils/test_helpers.py
In order to format target path as artifact path, add `fill_artifact_path_template `function in `get_absolute_path`.
This function plays a role in obtaining the target path during the `ingestion` process.
[ML-4180](https://jira.iguazeng.com/browse/ML-4180)
> [FeatureStore] Fix format target path as artifact path

- mlrun/common/model_monitoring/helpers.py
- tests/model_monitoring/test_target_path.py
When calling `parse_monitoring_stream_path()` on MLRun CE deployment that has no `kafka` stream, we use the default http path of the monitoring stream function as the main endpoint for the monitoring events. This default value can be found under `mlrun.mlconf.model_endpoint_monitoring.default_http_sink`:
`http://nuclio-{project}-model-monitoring-stream.mlrun.svc.cluster.local:8080`
This PR fix the parsing function of that http value in which we enrich the project name within the http path.
> [Model Monitoring] Fix parsing of default http target

- mlrun/api/crud/client_spec.py
- mlrun/common/schemas/client_spec.py
- mlrun/db/httpdb.py
Following https://github.com/v3io/helm-charts/pull/996 & https://github.com/mlrun/ce/pull/78, the model monitoring DB is generated under the existing `mlrun-db` service (as a default behaviour in the CE). 
In this PR, we add the field `endpoint_store_connection` to the client spec which be default will be enriched with the new model monitoring DB. 
A related JIRA ticket - https://jira.iguazeng.com/browse/CEML-106
> [Model Monitoring] Add `endpoint_store_connection` to client spec

- mlrun/runtimes/__init__.py
Add `databricks` to `runtime_with_handlers`.
[ML-4402](https://jira.iguazeng.com/browse/ML-4402)
> [Runtimes] Add databricks to runtime_with_handlers

- mlrun/datastore/dbfs_store.py
In Dbfs fix the method that use to get secrets.
Instead of `mlrun.get_secret_or_env`,now  __init__ using datastore get_secret method, called `_get_secret_or_env`.
[ML-4381](https://jira.iguazeng.com/browse/ML-4381)
> [Datastore] Fix dbfs preview

- mlrun/api/utils/builder.py
- tests/api/utils/test_builder.py
- tests/system/runtimes/assets/function_with_env_vars.py
- tests/system/runtimes/test_kubejob.py
resolves: [ML-4348](https://jira.iguazeng.com/browse/ML-4348)
We identified that the issue was caused by project secrets arriving as `None` in the Kaniko pod, and consequently, this `None` value propagated into the resulting image. It is not related to the mpi-job.
Upon further consideration, we recognized that including builder envs as persistent environment variables is unnecessary. The better approach here is to keep the builder envs available during the build stage only, and not in the resulting container. This way, it won't carry over and remain present in the final container.
Additionally, we acknowledged that using environment variables for secrets could lead to redundant rebuilds if changes occurred. 
Added in this PR:
- Separation of the builder_env from the project_secrets
- …
> [Builder] Remove env vars from Dockerfile and change behavior for project secrets

- mlrun/serving/server.py
[ML-4424](https://jira.iguazeng.com/browse/ML-4424)
This was added in #1179, to work around a nuclio issue that was fixed shortly after in https://github.com/nuclio/nuclio/pull/2285.
It's no longer necessary, and corrupts the topic name. Removing it is necessary for explicit ack to work correctly.
> [Serving] Remove overriding of event path for non-http triggers

- mlrun/api/api/endpoints/functions.py
- mlrun/api/api/utils.py
- mlrun/api/constants.py
- mlrun/api/crud/logs.py
- mlrun/api/crud/runs.py
- mlrun/api/crud/workflows.py
- mlrun/runtimes/__init__.py
- tests/api/api/test_runs.py
- tests/utils/test_notifications.py
https://jira.iguazeng.com/browse/ML-4427
For local, handler, dask runs we push notifications from the client which means that the notifications params are not masked by the server and we save them in the run object. This ensures that if the notifications params were not concealed, we redact them.
> [API] Redact unmasked run notifications param

- mlrun/api/db/base.py
- mlrun/api/db/sqldb/db.py
- mlrun/api/initial_data.py
- mlrun/api/main.py
- tests/api/test_initial_data.py
https://jira.iguazeng.com/browse/ML-4396
Update of default hub source on api online event if configuration was changed.
Removed updating hub source on migrations as api online event is triggered after migrations.
This is to allow changing the default hub source once it was set. In mlrun 1.5.0 we changed the hub source but the change would not take effect prior to this fix as we would not change the DB entry if it existed before.
> [Hub] Update default hub on data init

- mlrun/runtimes/databricks/databricks_wrapper.py
- tests/system/runtimes/test_databricks.py
1) Capture errors that occur within the `Databricks environment`, raise them to make the real error message accessible to the user.
2) Provide additional information such as the `trace`, `metadata`, and other relevant details.
3) Test that demonstrates this usage.
[ML-4403](https://jira.iguazeng.com/browse/ML-4403)
> [Runtimes] Fix - propagate databricks job errors

- mlrun/db/httpdb.py
- tests/integration/sdk_api/httpdb/test_exception_handling.py
no need to hold the request and wait for mlrun api with project. let the project creation be a background job while sampling mlrun api
https://jira.iguazeng.com/browse/IG-22046
> [Client] Support non-blocking project creation

- mlrun/api/utils/builder.py
If `builder_env` or `projects_secrets` are empty, the kaniko pod envs are set as None.
Later, if an ECR registry is configured, some other env vars are appended although the pod envs can still be None.
Fixes https://jira.iguazeng.com/browse/ML-4459
> [Kaniko] Fix kaniko pod env not initialized in ECR flow

- mlrun/api/crud/model_monitoring/model_endpoints.py
- mlrun/common/model_monitoring/helpers.py
- mlrun/model_monitoring/model_monitoring_batch.py
- tests/model_monitoring/test_features_drift_table.py
- tests/model_monitoring/test_helpers.py
Resolves [ML-4219](https://jira.iguazeng.com/browse/ML-4219).
This PR indirectly fixes the metrics calculation and UI view when the actual data lies outside of the train range.
- Add the `pad_features_hist` function
- Replace `float("inf")` with `sys.float_info.max` for valid DB storage.
- Use the +/-inf padding in `create_model_endpoint`
Tests:
- Unit in this PR
- Manual system patching (EE)
The UI:
There's a small issue - the edge bins ±inf aren't presented correctly: [ML-4445](https://jira.iguazeng.com/browse/ML-4445).
> [Model Monitoring] Add edge bins for actual data outside of the expected distribution

- Makefile
- mlrun/api/crud/secrets.py
- mlrun/api/utils/singletons/k8s.py
- mlrun/common/secrets.py
- mlrun/config.py
- tests/api/api/test_submit.py
- tests/api/api/test_utils.py
- tests/api/conftest.py
- tests/api/utils/test_scheduler.py
- tests/integration/sdk_api/base.py
- tests/integration/sdk_api/projects/test_project.py
This PR serves 2 purposes:
1. Allow integration tests to cover flows which require project-secrets functionality. We have more and more flows that use this functionality, and these could not be tested in integration tests due to the lack of k8s environment to support them. This PR allows running the MLRun service and the `Secrets` crud using an in-memory implementation for secrets (the same as used until now for unit-tests), enabling these flows
2. This PR introduces a `SecretProviderInterface` abstract class, which allows different implementations for secrets storage in different deployment modes (for example, use files in Docker environments). The default mode is still k8s secrets, of course. The `Secrets` crud for now selects the implementation on initialization based on config. In the …
> [Secrets] Abstract secrets provider, allow in-mem secrets for integration-tests

- mlrun/datastore/utils.py
[ML-4460](https://jira.iguazeng.com/browse/ML-4460)
When saving a Spark dataframe to Redis using a datastore profile, the profile name is mistakenly prefixed to the Redis key.
> [Datastore] Correct the issue where the datastore name is prefixed to the Redis key

- mlrun/api/runtime_handlers/daskjob.py
default timeout to 5 minutes (and not 30s) to handle delicate/slow gke clusters.
it has been observed on gke such transient errors
<details><summary>Details</summary>
<p>
File "/usr/local/lib/python3.9/site-packages/distributed/deploy/spec.py", line 310, in _start
await super()._start()
File "/usr/local/lib/python3.9/site-packages/distributed/deploy/cluster.py", line 84, in _start
comm = await self.scheduler_comm.live_comm()
File "/usr/local/lib/python3.9/site-packages/distributed/core.py", line 774, in live_comm
comm = await connect(
File "/usr/local/lib/python3.9/site-packages/distributed/comm/core.py", line 308, in connect
raise OSError(
OSError: Timed out trying to connect to tcp://mlrun-klzfq-func-far-15af43d4-a.default-tenant:8786 after 30 s
</p> …
> [Dask] Increase timeouts to handle transient failures

- mlrun/common/schemas/model_monitoring/constants.py
- mlrun/model_monitoring/api.py
- mlrun/model_monitoring/model_monitoring_batch.py
- tests/system/model_monitoring/test_model_monitoring.py
After exposing the new `get_or_create_model_endpoint()` in MLRun SDK (https://github.com/mlrun/mlrun/pull/4020), in this PR we would like to remove the drift analysis process from `get_or_create_model_endpoint()`.
As for the batch inference job, instead of calling `get_or_create_model_endpoint()`, it will use a new SDK function called `record_results()` which wraps both `get_or_create_model_endpoint()` function and the drift analysis process.
A related JIRA ticket: https://jira.iguazeng.com/browse/ML-4443
> [Model Monitoring] Remove drift analysis from `get_or_create_model_endpoint()`

- mlrun/utils/async_http.py
- mlrun/utils/http.py
- tests/rundb/test_unit_httpdb.py
- tests/utils/test_async_http.py
- tests/utils/test_http.py
resolves: [ML-4323](https://jira.iguazeng.com/browse/ML-4323)
The pipeline step failure caused by a ConnectionError. The error was previously categorized as non-retryable, but it should be considered retryable due to its transient nature.
In this PR, Added ConnectionError to the list of retryable exceptions, and implemented a check to see if the error is related to a retryable cause in the exception chain.
> [Utils] Fix HTTP session retryable error handling 

- mlrun/model_monitoring/api.py
This PR includes the following:
- remove the patching process when the model endpoint is already exist
- remove redundant `inf_capping` param which actually is not being used in that specific flow   
- If not provided, fill the drift and possible drift thresholds from the model endpoint record or from MLRun config
- add model endpoint validations for the cases that the model endpoint record is already exist. The main validations are:
1. The provided `sample_set_statistics` should be equal to the existing `model_endpoint.spec.feature_stats`
2. The provided drift and possible drift thresholds are identical to the stored thresholds of the model endpoint. 
3. If `model_path` is provided, it should be identical to the existing `model_endpoint.spec.model_uri`.
If one of the above validations …
> [Model Monitoring] add model endpoint validations when calling `get_or_create_model_endpoint()`

- mlrun/api/api/endpoints/datastore_profile.py
- mlrun/common/schemas/datastore_profile.py
- mlrun/datastore/datastore_profile.py
- mlrun/db/httpdb.py
- mlrun/projects/project.py
- tests/api/api/test_datastore_profiles.py
- tests/system/datastore/test_datastore_profiles.py
[ML-4463 ](https://jira.iguazeng.com/browse/ML-4463), [ML-4467](https://jira.iguazeng.com/browse/ML-4467)
Adding two interfaces to MlrunProject class:  **list_datastore_pfofiles**() and **delete_datastore_profile**()
> [Datastore] Add list and delete APIs for datastore profiles

- mlrun/api/crud/model_monitoring/model_endpoints.py
- tests/api/crud/model_monitoring/test_model_endpoints.py
Fix [ML-4499](https://jira.iguazeng.com/browse/ML-4499) (caused thanks to myself in #4124).
- Add the fix line - check for `feature_stats` existence in the model object first.
- Add a test with mocks for external resources. It fails before the fix and passes after.
- Make the method a class method.
> [Model Monitoring] Fix histogram padding when model object has no feature stats

- Makefile
- dockerfiles/base/Dockerfile
- dockerfiles/gpu/prebaked.Dockerfile
- dockerfiles/mlrun/Dockerfile
- dockerfiles/mlrun/requirements.txt
- dockerfiles/models/Dockerfile
- tests/system/runtimes/test_mpijob.py
As part of the effort to provide a more simplified images and deprecate/remove mlrun/ml-models and mlrun/ml-models-gpu, this PR boost the common image `mlrun/mlrun` with miniconda and opmi ready for use.
note - the image size increases from ~1.5GB to ~2.3GB
> [Dockerfiles] mlrun/mlrun to use miniconda + opmi

- dockerfiles/base/Dockerfile
- dockerfiles/base/mlrun_requirements.txt
Base image tried installing mpi4py without having the base requirements for that (opmi) and failed. this PR remove that dependency by a hacky workaround.
> [Dockerfiles] Fix building base image

- mlrun/api/runtime_handlers/daskjob.py
- mlrun/runtimes/base.py
- mlrun/runtimes/daskjob.py
- mlrun/runtimes/mpijob/v1alpha1.py
[ML-3711](https://jira.iguazeng.com/browse/ML-3711)
The traditional process for populating Job pods with MLRun related environment variables doesn't work for Dask pods, since the their scheduler is itself separated from the MLRun API pod and, because of that, it's not aware of such variables.
This PR ensures that the MLRun API pod add the relevant variables to the pod templates used to create both scheduler and worker pods on the Dask runtime.
> [Runtimes][Dask] Ensure that MLRUN_DBPATH is available for workers

- docs/concepts/notifications.md
- mlrun/common/schemas/notification.py
Documentation Update for [ML-4498](https://jira.iguazeng.com/browse/ML-4498): Separation of "params" and "secret_params" in notifications.
> [Docs] Add docs for notifications secret_params

- dockerfiles/gpu/Dockerfile
it doesnt have OS-python preinstalled, thus - not needed
> [Dockerfiles] Fix mlrun gpu build

- tests/system/runtimes/assets/my_func.py
- tests/system/runtimes/test_kfp.py
This test used to use `run_pipeline` sdk which was deprecated and removed.
It should use project.run instead of internal methods.
> [Tests] Fix KFP pipeline param test

- tests/system/runtimes/test_kubejob.py
mlrun/mlrun is now miniconda based.
> [Tests] Fix expected mlrun executable location to conda binaries

- mlrun/datastore/datastore.py
- mlrun/datastore/datastore_profile.py
- mlrun/projects/project.py
- tests/system/datastore/test_datastore_profiles.py
- tests/system/datastore/test_redis.py
- tests/system/feature_store/test_feature_store.py
https://jira.iguazeng.com/browse/ML-4461
To clarify the access policy for datastore profiles, we've established a distinct separation between profile access from pods and from clients. Profiles registered using `project.register_datastore_profile()` are exclusively accessible from pods, while those registered via `register_temporary_client_datastore_profile()` can only be accessed by clients.
> [Datastore] Introducing the API for creating client temporary datastore profiles

- mlrun/platforms/iguazio.py
- tests/api/api/test_utils.py
- tests/api/runtimes/base.py
- tests/api/runtimes/test_nuclio.py
- tests/common_fixtures.py
- tests/platforms/test_iguazio.py
[ML-2532](https://jira.iguazeng.com/browse/ML-2532)
> [Runtimes] Fix mount_v3io: use `dirsToCreate` volume param to enforce creation of user dir with o750 permission

- mlrun/model_monitoring/api.py
- tests/model_monitoring/test_monitoring_api.py
This PR fix a bug in which the dataset is not provided as a `DateItem` object when calling `read_dataset_as_dataframe()` (part of the `batch-infer-v2` flow). 
In addition, we also add a new parameter called `feature_columns` that can be either received by the user or taken from the model artifact inputs. Note that these feature columns are being used when the provided dataset is from type list or numpy array.
A related JIRA - https://jira.iguazeng.com/browse/ML-4477
A similar fix for the `batch-infer-v1` (`read_dataset_as_dataframe` in this case defined within `mlrun/function` repo) - https://github.com/mlrun/functions/pull/662/
> [Model Monitoring] Fix different dataset types when reading a dataset as a DataFrame

- mlrun/api/rundb/sqldb.py
- mlrun/db/base.py
- mlrun/db/httpdb.py
- mlrun/db/nopdb.py
- tests/integration/sdk_api/projects/test_project.py
- tests/rundb/test_httpdb.py
Breaking change - changing list project to return project names only to reduce load on api needlessly
> [HTTPDB] Change `list_projects` default format to name only

- tests/system/model_monitoring/test_model_monitoring.py
Following model monitoring system test failures that are related to the model endpoint feature stats (e.g. https://github.com/mlrun/mlrun/actions/runs/6078927221/job/16491351301#:~:text=%3E%20%20%20%20%20%20%20assert%20endpoint,KeyError%3A%20%27predictions_count_5m%27 & https://github.com/mlrun/mlrun/actions/runs/6006655462/job/16292184281#:~:text=assert%20endpoint.status,assert%2091.0%20%3D%3D%20101, in this PR we add a sleep time of 10sec before retrieving the endpoint record from the database.
> [Model Monitoring] Add retry on model endpoint metrics assertion in system tests

- .github/workflows/system-tests-opensource.yml
- tests/system/model_monitoring/test_model_monitoring.py
Following the completion of implementing model monitoring features in the CE, in this PR we remove the flag that disabled the installation of the Prometheus stack as part of the CE system tests.
> [Model Monitoring] Enable prometheus stack installation in CE system tests

- mlrun/model_monitoring/model_monitoring_batch.py
The prometheus registry is stored under the monitoring stream pod which is deployed through the basic monitoring flow. The model monitoring batch job updates these metrics using an HTTP call to the monitoring stream endpoints. However, if the monitoring batch job is running (e.g. following `batch-infer` process) and the monitoring stream pod hasn't being deployed, then the job will fail because the HTTP endpoint is not exist. 
In this PR, we add an exception for this case. Note that in this case we won't store the drift results in a TSDB target.
> [Model Monitoring] Check stream pod health before pushing metrics to Prometheus registry

- dependencies.py
- dockerfiles/mlrun/requirements.txt
- extras-requirements.txt
- mlrun/datastore/targets.py
- mlrun/datastore/utils.py
- requirements.txt
The model monitoring database is being used by both MLRun API and the model monitoring functions that are not part of MLRun api service (e.g. model monitoring stream pod or model monitoring batch job function). The default image of the monitoring functions is `mlrun/mlrun` but following https://github.com/mlrun/mlrun/pull/4096 the default `sqlalchemy` version is not limited and installed with the newest version (`>2.0`). As a result, the monitoring functions are using `sqlalchemy>2.0` while mlrun api is using `sqlalchemy~=1.4`.
In this PR we fix this conflict by setting the default `sqlalchemy` to `1.4` in MLRun dockerfile as well. 
[ML-4553](https://jira.iguazeng.com/browse/ML-4553)
> [Requirements] Add `sqlalchemy~=1.4` to extra requirements

- mlrun/model_monitoring/stores/models/__init__.py
- mlrun/model_monitoring/stores/models/base.py
- mlrun/model_monitoring/stores/models/mysql.py
- mlrun/model_monitoring/stores/models/sqlite.py
- mlrun/model_monitoring/stores/sql_model_endpoint_store.py
Resolves [ML-4526](https://jira.iguazeng.com/browse/ML-4526).
These tables are used as a replacement for V3IO in CE.
The MySQL and SQLite SQLAlchemy tables have the same fields by design, up to a MySQL specification for two time fields.
This PR refactors the code to remove this duplication without changing the models. This is required for easier extension and addition to more models.
Before this PR:
```mermaid
classDiagram
`base.Base` <|-- `mysql.ModelEndpointsTable`
BaseModel <|-- `mysql.ModelEndpointsTable`
`base.Base` <|-- `sqlite.ModelEndpointsTable`
BaseModel <|-- `sqlite.ModelEndpointsTable`
```
The two classes could not be imported together, therefore the if was inside the `get_ModelEndpointsTable` function.
After this PR:
```mermaid
classDiagram
BaseModel <|-- …
```
> [Model Monitoring] Use a shared class for the model endpoint tables

- mlrun/api/utils/builder.py
- mlrun/config.py
observed some network issues on unstable registries
<details><summary>Details</summary>
<p>
```
error pushing image: failed to push to destination docker-registry.somewhere/spark-job-default-image:
Patch "[http://docker-registry.somewhere/v2/spark-job-default-image/blobs/uploads/dd7dc2c2-f8ef-4cc6-bdc3-5db7ce32b56a?\_state=4xfN-VHppGzlPs3aZR2DvFSpxGWDjQih-ZYz\_h9Wr2N7Ik5hbWUiOiJzcGFyay1qb2ItZGVmYXVsdC1pbWFnZSIsIlVVSUQiOiJkZDdkYzJjMi1mOGVmLTRjYzYtYmRjMy01ZGI3Y2UzMmI1NmEiLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMjMtMDktMDVUMTU6NTE6NTAuMDU0NzY4MTUyWiJ9
write tcp 10.233.67.61:45386->10.0.131.101:80: write: connection reset by peererr: 
MLRunRuntimeError:Deploy failed
```
</p>
</details> 
This pr adds a retry to when it pushes the image
https://jira.iguazeng.com/browse/ML-4545
> [Builder] Add retry mechanism to kaniko

- mlrun/api/api/endpoints/runs.py
- mlrun/db/httpdb.py
- tests/api/api/test_runs.py
- tests/integration/sdk_api/httpdb/runs/test_runs.py
- tests/rundb/test_httpdb.py
Project is always set when running from sdk as list runs is a project functionality.
That means, when querying for project runs, it will default to runs lasted 7 days ago.
if desired more than that, then refine the filter by providing specific runs as per list_run parameters.
https://jira.iguazeng.com/browse/ML-4316
> [HTTPDB] Fix list runs

- go/pkg/services/logcollector/server.go
Observed failures such as device is busy when log collector uses nfs mount
> [LogCollector] Retry upon transient failures

- mlrun/api/crud/model_monitoring/model_endpoints.py
- mlrun/common/schemas/model_monitoring/__init__.py
When calling delete project API with `cascade` policy, the model endpoints resources should be deleted as well. During that process, we used to validate that we are deleting these resources only if we are using V3IO in a valid iguazio version. However, to delete the model endpoint resources on a CE environment (which by default stores the model endpoints records under mlrun-db service) we need to modify this condition and apply it only if the model endpoints store type is indeed v3io. 
This PR should also fix a failure in the open source system tests. 
[ML-4565](https://jira.iguazeng.com/browse/ML-4565)
> [Model Monitoring] Fix delete model endpoints resources on CE 

- mlrun/projects/project.py
- tests/projects/test_project.py
https://jira.iguazeng.com/browse/ML-3739
Previously, we would not update the tagged function in the project's function objects.
This introduced inconsistencies with the DB in case a function was saved to the DB with the tag but was set in the project with a name and a tag separately. Getting such function from the project would return the old object and not the latest one set.
> [Project] Fix set tagged function

- .gitignore
- Makefile
It uses 2.0.1 which has a bug reporting breaking schema compatibility while it actually doesnt, see https://github.com/mlrun/mlrun/pull/4233 runs for an instance. while I added a field (which is considered BC) it reports non backwards compatibe.
while upgrading the docker container of openapi diff checker, it fixes the issue
> [CI] Fix backwards compatibility check

- mlrun/datastore/datastore_profile.py
https://jira.iguazeng.com/browse/ML-4521
Storing private data from the datastore as internal k8s secrets in MLRun prevents these secrets from being mounted to the pods. This, in turn, prevents the pods from accessing datastore profiles. To address this, we transition the private data to regular user secrets, which are also visible in the UI.
> [Datastore] Keep private data as user secrets instead of mlrun internal

- mlrun/datastore/targets.py
[ML-4586](https://jira.iguazeng.com/browse/ML-4586)
first introduce in #4212,  we cant save sqlalchemy as attribute of an instance.
about the dynamic import - if module is already loaded then it won't be loaded again. you will just get a reference to it.
> [Datastore] Fix sqlalchemy dynamic import in `SQLTarget`   

- mlrun/common/schemas/model_monitoring/model_endpoints.py
- tests/system/model_monitoring/test_model_monitoring.py
If not provided, drift thresholds will be filled according to `mlrun.mlconf.
model_endpoint_monitoring.drift_thresholds`. The values will be stored under `model_endpoint.spect.monitor_configuration`.
Related JIRA - https://jira.iguazeng.com/browse/ML-4592
> [Model Monitoring] Add default drift thresholds under `model_endpoint.spec.monitor_configuration`

- mlrun/api/api/endpoints/model_endpoints.py
- mlrun/api/crud/model_monitoring/model_endpoints.py
- mlrun/model_monitoring/stores/kv_model_endpoint_store.py
- `create_or_patch` model endpoint API is no longer supported.
- the deprecation warning message on validating KV schema fields has been removed. We will keep validating these fields in order to support users that created their model endpoints before `1.3.0`.
> [Model Monitoring] Remove deprecated `create_or_patch` model endpoint API

- mlrun/utils/notifications/notification_pusher.py
- tests/utils/test_notifications.py
Missed the right kwarg, added some unittests, aligned raising exception behavior between async and sync and fixed type hinting
> [Notification] Fix async notifications pushing

- mlrun/__main__.py
- mlrun/db/httpdb.py
- mlrun/lists.py
- mlrun/projects/pipelines.py
- mlrun/projects/project.py
- mlrun/runtimes/function.py
- mlrun/utils/helpers.py
Returning methods/flags that were deprecated in 1.3.0 but were not documented. They will be removed in 1.6.0
SDK:
1. new_pipe_meta
2. objects methods from artifacts list
3. ttl param from pipeline
CLI:
1. dashboard (nuclio/deploy)
2. overwrite schedule (project)
Related to https://github.com/mlrun/mlrun/pull/3971
> [SDK] Return deprecated ops missing from change-log

- mlrun/projects/project.py
- mlrun/utils/clones.py
- tests/common_fixtures.py
- tests/projects/test_project.py
[ML-3560](https://jira.iguazeng.com/browse/ML-3560)
SDK users can now provide name, email and credentials directly to the `.push` and `.pull` methods of a project instance instead of running `git config` commands on shell.
When setting name and email with the new strategy, this data is set up only for the current repository (instead of globally). 
Credential information is handled in the same way as in `mlrun.load_project`. In order to achieve this, the existing strategy was abstracted away from `mlrun.utils.clones.clone_git` and now is also leveraged by `mlrun.projects.project.MlrunProject.push` and `mlrun.projects.project.MlrunProject.pull`.
> [Project] Allow for on the fly configuration of Git while pushing and pulling

- mlrun/model_monitoring/stores/kv_model_endpoint_store.py
When storing a string attribute data under the model endpoint with a huge length, the user might face a v3io-kv string attribute length limitation. 
In this PR we fix that issue by converting the statistics data string (which used to be stored as an attribute of type string) into binary string.
A fix to [ML-4597](https://jira.iguazeng.com/browse/ML-4597).
> [Model Monitoring] Encode feature statistics data (KV)

- mlrun/utils/http.py
https://jira.iguazeng.com/browse/ML-4532
We saw in this bug that the client request for run logs is being thrown due to timeout error.
Prior to the request we see logs of connection closed in the middle of sending a response which may corrupt the connection buffers. Hopefully if we retry it will create a new connection with new buffers.
> [HTTPDB] Add retriable invalid chunks exceptions

- mlrun/datastore/sources.py
- tests/system/feature_store/test_feature_store.py
Backport of #4274.
[ML-4610](https://jira.iguazeng.com/browse/ML-4610)
> [Datastore] Remove deprecated `time_field` constructor parameter [1.5.x]

- mlrun/api/main.py
- mlrun/config.py
- tests/api/test_collect_runs_logs.py
The api periodically calls start_log for runs that do not have logs requested.
There is an issue where runs in failed terminated states, which their resources have already been deleted, are still returned in the query for runs with `requested_logs=True`. 
Since there are no resources, the Log Collector always fails to find the runs' pods and returns an error, keeping the runs `requested_logs` field as `False`.
Thus - the api and the log collector sidecar are stuck in an endless loop trying to collect logs for these old runs.
To fix this, this PR adds a limit to the number of consecutive `start_logs` requests. 
The maximum number calculated as the run resource deletion grace period divided by the start log interval, meaning that once the grace period ends the runs are marked as …
> [Log Collector] Limit consecutive start log requests on failed runs

- mlrun/datastore/targets.py
Fix `feature_store/test_feature_store.py::TestFeatureStore::test_pandas_write_parquet` - Failed after #4216
> [Datastore] Fix issue when parquet target path is directory but the parquet isn't partitioned

- mlrun/api/crud/model_monitoring/model_endpoints.py
- mlrun/common/schemas/model_monitoring/model_endpoints.py
- tests/system/model_monitoring/test_model_monitoring.py
Verify that the `model_endpoint.spec.model_uri` value represents a store uri of `models`. In addition, we also verify that during the model endpoint deployment the `model_uri` does represent a valid `ModelArtifact` object. 
Related JIRA: https://jira.iguazeng.com/browse/ML-4611
> [Model Monitoring] Validate `model_uri` prefix

- mlrun/run.py
- mlrun/runtimes/__init__.py
- tests/launcher/test_local.py
- tests/run/test_run_local.py
https://jira.iguazeng.com/browse/ML-4579
empty kind is considered local or handler
> [Runtimes] Add handler and empty kinds to abortable runtimes

- mlrun/api/crud/model_monitoring/model_endpoints.py
- mlrun/common/schemas/model_monitoring/model_endpoints.py
- tests/system/model_monitoring/test_model_monitoring.py
> [Model Monitoring] Validate `model_uri` prefix (#4280) [1.5.x]

- mlrun/run.py
- mlrun/runtimes/__init__.py
- tests/launcher/test_local.py
- tests/run/test_run_local.py
(cherry picked from commit c35349bf4ed6c5b31dda2edf2a0e87b2391a40c1)
> [Runtimes] Add handler and empty kinds to abortable runtimes [1.5.x]

- mlrun/datastore/targets.py
Cherry-picked from #4292 development PR.
First introduced in #4287.
> [Datastore] Fix issue when parquet target path is directory but the parquet isn't partitioned  [1.5.x]

- mlrun/api/db/sqldb/db.py
> [Artifacts] Increase retrieved iterations to 1k [1.5.x]

- requirements.txt
Backport of #4289.
[IG-21969](https://jira.iguazeng.com/browse/IG-21969)
> [Requirements] Bump v3io-frames to 0.10.7 [1.5.x]

- mlrun/api/crud/model_monitoring/deployment.py
- mlrun/model_monitoring/writer.py
- tests/model_monitoring/test_writer.py
Related ticket: [ML-4394](https://jira.iguazeng.com/browse/ML-4394)
Write app events to V3IO storage (EE):
- KV (need to add more keys)
- TSDB: index by
- scheduled time
- endpoint ID
- application name
The CE edition will follow this PR.
Tests:
- Manual full-flow on EE
- Automatic for some core functionalities
> [Model Monitoring] Implement apps writer (EE)

- mlrun/runtimes/funcdoc.py
- tests/runtimes/info_cases.yml
- tests/runtimes/test_funcdoc.py
When MLRun parses function signature as part of the `code_to_function` flow, the `ast_func_info` function parses the function source code. When parsing the function parameters it adds an empty default value even if there is no default at all. Meaning, there's no difference between these two functions:
```
def f1(n: str):
...
def f2(n: str = ""):
...
```
Both of these functions will produce the same entrypoint where the `n` parameter will have a `"default": ""` value.
This means that the UI, for example, cannot distinguish between a mandatory parameter (such as in `f1`) and a parameter that can be skipped since it has a default (like in `f2`).
This PR fixes this, such that if no default value exists, there will not be a `default` entry for the parameter.
Also as part of this I'm …
> [Function Docs] Fix wrongly reporting default param values when parsing function entrypoint

- mlrun/common/schemas/model_monitoring/constants.py
- mlrun/model_monitoring/writer.py
- tests/model_monitoring/test_writer.py
A part of [ML-4394](https://jira.iguazeng.com/browse/ML-4394)
Tested locally and with mocks.
Note that a Slack application and NOT a workflow is expected.
To use this feature, set the webhook secret as an [MLRun secret](https://docs.mlrun.org/en/stable/secrets.html#mlrun-managed-secrets).
> [Model Monitoring] Send a notification when an app reports "detected" status

- mlrun/model_monitoring/api.py
- tests/system/model_monitoring/test_model_monitoring.py
When generating a new model endpoint using `get_or_create_model_endpoint` the function URI format is based on `<project>/<function hash>` which is invalid - the uri must contain the function name in it.
In this PR we fix that issue and generate the function uri based on `<project>/<function name>`. 
Related JIRA: https://jira.iguazeng.com/browse/ML-4630
> [Model Monitoring] Fix generating `function_uri` when calling `get_or_create_model_endpoint`

- mlrun/model.py
- mlrun/runtimes/base.py
- mlrun/utils/helpers.py
- tests/test_model.py
resolves: [ML-4523](https://jira.iguazeng.com/browse/ML-4523)
The notification params attribute was included in the MLRUN_EXEC_CONFIG of the runtime pod, and when it was large it caused the argument list too long error. It is not necessary or in use, so it can be excluded.
> [Notifications] Remove notification params from MLRUN_EXEC_CONFIG

- mlrun/model.py
- mlrun/runtimes/funcdoc.py
- tests/runtimes/info_cases.yml
- tests/runtimes/test_funcdoc.py
Two fixes are included in this PR that are related to the function code parsing done by `code_to_function`:
1.  In #3528 new indications were added whether the handler is receiving `**kwargs` or `*vargs`. This is useful for the UI to know whether the user is allowed to add extra parameters except those that are documented. However, this improvement was not complete since the resulting dict is going through a `FunctionEntrypoint` class which serializes it to dict and this class has no notion of those new parameters. Therefore, these were omitted from the parsed entrypoint.
2. The return type hint was parsed in a weird way which didn't really provide any result. Changed this to use `ast.unparse` which returns the AST node to a textual form. Also this now distinguishes between no type hint …
> [Function Docs] Fix return type parsing + `kwargs`/`varargs` detection fix

- tests/system/model_monitoring/test_model_monitoring.py
Following the MM apps framework, the extra columns in the data are marked as "labels".
This should fix the following error:
https://github.com/mlrun/mlrun/actions/runs/6238236180/job/16936024769#step:6:2699
I ran it locally and it passed.
(`columns` is defined in L505.)
> [Tests] Fix a model monitoring system test

- mlrun/model.py
- mlrun/runtimes/base.py
- tests/test_model.py
resolves: [ML-4523](https://jira.iguazeng.com/browse/ML-4523)
The notification params attribute was included in the MLRUN_EXEC_CONFIG of the runtime pod, and when it was large it caused the argument list too long error. It is not necessary or in use, so it can be excluded.
> [Notifications] Remove notification params from MLRUN_EXEC_CONFIG 

- mlrun/api/utils/clients/iguazio.py
- tests/api/utils/clients/test_iguazio.py
Observed during delete project flow, the sync mechanism kicked in and tried to sync (aka update) a project being deleted, which took the db lock and held it for too long. this PR filters out project being deleted to simplify sync mechanism
https://jira.iguazeng.com/browse/ML-4502
> [Iguazio] Filter projects being deleted

- mlrun/datastore/sources.py
> [Datastore] Revert removal of `time_field` parameter from `CSVSource` [1.5.x]

- mlrun/db/httpdb.py
backports https://github.com/mlrun/mlrun/pull/4371 to 1.5.x
> [RuntimeResources] Fix listing by label selector [1.5.x]

- mlrun/api/api/endpoints/workflows.py
- mlrun/api/crud/workflows.py
- mlrun/db/httpdb.py
In case client want to run a workflow without explicitly set the workflow, do not force locating the workflow on project spec but simply runs it. the idea is to support backwards compatibility to the way we submitted workflows before 1.5.x.
https://jira.iguazeng.com/browse/ML-4679
> [Workflow] Fix running preloaded workflow [1.5.x]

- mlrun/projects/pipelines.py
When submitting remote workflow, the `load_and_run` initializes the project from a relative path. that means, when client code tries to run a workflow from an absolute path of his local path, the remote runner wont be able to detect the workflow file.
The fix removes the prefix and let the `load_and_run` relatively load the file.
e.g.:
running locally:
```python
import mlrun
project = mlrun.load_project(name="p0",  
context='/User/p0', 
url="git://github.com/someone/somewhere.git", 
clone=True)
```
will end up having a code located locally. to run a workflow, remotely, with a schedule, the client will invoke
```python
project.run(workflow_path="/User/p0/workflow.py", watch=False, schedule="0 */1 * * *")
```
Before the PR it would fail, because the remote pod won't have …
> [RemoteRunner] Fix sanitizing workflow spec [1.5.x]

- mlrun/model_monitoring/batch.py
When the statistical metric result (e.g. hellinger distance) is 0 it means that the reference data distribution and the new data distribution are basically the same data. 
In this PR we fix an issue in which we don't skip a 0 value when calculating the drift result dictionary for each feature. Instead, we only skip the calculation if the expected metric doesn't exist. In this case, we will log a warning message. 
Related JIRA: https://jira.iguazeng.com/browse/ML-4691
> [Model Monitoring] Fix drift result dictionary calculation when the value is 0

- mlrun/model_monitoring/batch.py
> [Model Monitoring] Fix drift result dictionary calculation when the value is 0 [1.5.x]

- mlrun/projects/project.py
Add `_set_function` method  - this method should be used in mm_app\function flows, for setting a function to the project.
> [Project] Set function to function spec only once

- mlrun/utils/notifications/notification_pusher.py
- server/api/utils/singletons/k8s.py
- tests/system/runtimes/test_notifications.py
It seems that a regression raised a change that occurs on python 3.10 on our python 3.9, most likely due to upgrading dask package.
The issue is related to the fact that a worker thread cannot get the main thread event loop and use it to schedule tasks.
Since mlrun api uses notification pusher sync method to push async notifications, it must run on a worker thread. that worker thread needs an event loop of his own, and that is the fix.
in addition, did some unification to reduce code dup.
Tested
sync, async notifications
mlrun api, mlrun sdk
remote / local runs
> [Notifications] Fix getting event loop in non-main thread

- .run/ce.run.xml
- automation/deployment/deployer.py
- tests/system/model_monitoring/test_model_monitoring.py
Also added a skip to model monitoring test temporarily
In order to deploy CE locally and run open source system tests follow these steps:
1. Start minikube
```
minikube start --addons=registry --insecure-registry "192.168.49.2:5000"
```
2. Deploy CE with the run configuration (Fill the missing parameters)
3. Expose minikube api service
```
minikube service mlrun-api -n mlrun
```
4. Copy external URL to env.yml
> [Run Configuration] Deploy CE

- automation/scripts/create_migration_mysql.sh
- automation/scripts/create_migration_sqlite.sh
In order for the alembic script to find mlrun and server modules.
> [Migrations] Set PYTHONPATH to root

- server/api/crud/model_monitoring/deployment.py
Fix `_MODEL_MONITORING_COMMON_PATH` for the model monitoring job deployment.
> [Model Monitoring ] Update `_MODEL_MONITORING_COMMON_PATH` according to mlrun server split

- mlrun/projects/pipelines.py
- mlrun/projects/project.py
added reference to remote and remote:local in docstring,  fixed warning not raised for remote:local and when no engine but schedule (which defaults to remote) is selected.
https://jira.iguazeng.com/browse/ML-4721
https://jira.iguazeng.com/browse/ML-4722
> [Workflows] Minor tweaks

- mlrun/feature_store/retrieval/job.py
(#4405)
(cherry picked from commit 937e9e6f81211b8489b26ba0ba0f6986c69e74d6)
> [Feature Store] Revert the order of the columns in the return Dataframe when running `get_offline_features` in remote [1.5.x]

- mlrun/api/api/utils.py
- mlrun/db/factory.py
- mlrun/projects/operations.py
- mlrun/run.py
- mlrun/utils/helpers.py
Fix submit function from hub due to reused session that have race condition between others using it (singleton-issue). injecting db session given by fastapi instead solves it
https://jira.iguazeng.com/browse/ML-4733
> [DB] Fix submit job not using specific db session

- mlrun/feature_store/retrieval/job.py
- tests/system/feature_store/test_spark_engine.py
(#4424)
(cherry picked from commit d2459ba924fcabd696dff8140941058b05d00353)
> [Feature Store] Drop columns according to the user `drop_columns` param when reading the result df with `RemoteVectorResponse`  [1.5.x]

- mlrun/config.py
- mlrun/k8s_utils.py
- server/api/api/endpoints/workflows.py
- tests/test_k8s_utils.py
[ML-4730](https://jira.iguazeng.com/browse/ML-4730)
When a remote runner is used to run a pipeline, its labels are also sent to the Kubernetes API, so the values used must comply to k8s' character standards. 
Refer to the following error to better understand what happens when such standards are disregarded:
https://github.com/mlrun/mlrun/actions/runs/6434045624/job/17473081675
```
Error:  :x: Workflow main run failed!, error: 400 Client Error: Bad Request for url: https://mlrun-api.default-tenant.app.mlrun-system-tests-2.iguazio-cd1.com/api/v1/projects/source-project/workflows/main/submit: details: {'reason': 'Workflow failed', 'workflow_name': 'main', 'workflow_action': 'run', 'error': '(422)\nReason: Unprocessable Entity\nHTTP response headers: HTTPHeaderDict({\'Audit-Id\': …
```
> [k8s] Sanitize label's values to ensure k8s compatibility

- mlrun/datastore/base.py
- tests/integration/aws_s3/test_aws_s3.py
https://jira.iguazeng.com/browse/ML-4751
When a datastore profile directory (as opposed to a single file) is utilized to read a pandas dataframe, the appropriate filesystem is already determined and set up. However, it remains unused. This is because, while pandas attempts to create a new instance of the filesystem, mlrun doesn't forward the filesystem to pandas. As a result, pandas encounters an error due to its unfamiliarity with the 'ds://' schema. This PR rectifies this by providing the pre-established filesystem to the pandas parquet reader and removing the 'ds://prfofile' prefix from the directory URL
> [Datastore] Fix reading parquet directory when using datastore profiles

- .gitignore
- dev-requirements.txt
- mlrun/model_monitoring/batch.py
- tests/model_monitoring/test_metrics.py
[Hypothesis](https://hypothesis.readthedocs.io/en/latest/) is a Python library that generates test data according to general requirements instead of hard-coded examples. It's a property-based testing (PBT) framework that integrates well with Pytest.
I added it to the dev requirements and used it in our test.
This test is an excellent example of the power of Hypothesis - it replaced the several chosen distribution arrays with a general formula to create them, thus covering more cases.
Resolves [ML-4647](https://jira.iguazeng.com/browse/ML-4647).
Note:
* By default, Hypothesis generates 100 examples: https://hypothesis.readthedocs.io/en/latest/settings.html#hypothesis.settings.max_examples
In this case, the tests are fast, so it's not a problem. It can be customized per-test.
* Failures can …
> [Tests] Use Hypothesis to test zero distance between the same distribution

- server/api/utils/builder.py
- tests/api/utils/test_builder.py
Reverts mlrun/mlrun#4434
Need to redo this in a way that won't break `projects/test_project.py::TestProject::test_run_git_build`.
> Revert "[Builder] Clone GitHub repository to a directory other than `/tmp`"

- mlrun/projects/project.py
Allow defining an application from a file, not only from a Jupyter notebook.
Fixes [ML-4783](https://jira.iguazeng.com/browse/ML-4783).
> [Model Monitoring] Set application filename

- mlrun/model_monitoring/writer.py
- tests/model_monitoring/test_writer.py
Resolves [ML-4707](https://jira.iguazeng.com/browse/ML-4707).
The other parts work as expected - in the KV we agreed to have a table per an endpoint ID with the app name as the key.
The Pydantic model of the result will come in a separate PR.
> [Model Monitoring] Do not write "extra data" in V3IO TSDB

- mlrun/artifacts/base.py
- mlrun/artifacts/model.py
- tests/artifacts/test_artifacts.py
- tests/artifacts/test_model.py
We encountered a user that passed a full path as the `model_file` parameter to the model artifact.
This caused issues as we assume that the model_file is always just the filename.
Instead, we can help the user by splitting the path to model_dir and model_file and not assume that model_file is just the base name.
> [Model] Fix model file parsing

- server/api/utils/builder.py
- tests/api/utils/test_builder.py
Second attempt at [ML-4741](https://jira.iguazeng.com/browse/ML-4741) after reverting #4434.
> [Builder] Clone GitHub repository to `/home/mlrun_code` instead of `/tmp`

- mlrun/model_monitoring/writer.py
- tests/system/model_monitoring/assets/application.py
- tests/system/model_monitoring/test_app.py
The first effort for [ML-4762](https://jira.iguazeng.com/browse/ML-4762).
- Add a system test - passed locally.
- Add a dummy app for the test.
- Checks:
- V3IO KV
- V3IO TSDB
- App parquet - currently only manual
- Fix the writer access key.
> [Model Monitoring] Add e2e application sys test

- mlrun/common/schemas/model_monitoring/model_endpoints.py
- mlrun/model_monitoring/model_endpoint.py
This change removes some redundancy and makes these classes more readable.
Resolves [ML-4649](https://jira.iguazeng.com/browse/ML-4649).
> [Model Monitoring] Use dataclass in `ModelEndpoint` status and spec classes

- pyproject.toml
- setup.cfg
Resolves [ML-4824](https://jira.iguazeng.com/browse/ML-4824).
See:
- https://docs.pytest.org/en/7.4.x/reference/customize.html#pyproject-toml
- https://docs.pytest.org/en/7.4.x/reference/reference.html#confval-python_files
Keep the `setup.cfg` file for now, as the "aliases" option might be used somewhere.
To verify it works - you may run a test and see the printed "configfile". For example:
```sh
pytest tests/model_monitoring/test_metrics.py
```
prints
```text
====================== test session starts ======================
...
configfile: pyproject.toml
...
```
Before this change, it was: `configfile: setup.cfg`.
> [Config] Move Pytest's config to `pyproject.toml`

- docs/install/kubernetes.md
Document the special configurations that are needed when using MLRun CE and storing artifacts in AWS S3. 
This covers the issues and workarounds described in [CEML-112](https://jira.iguazeng.com/browse/CEML-112) and [CEML-113](https://jira.iguazeng.com/browse/CEML-113)
> [Docs] Document using AWS S3 in MLRun CE

- mlrun/kfpops.py
[ML-3728](https://jira.iguazeng.com/browse/ML-3728)
Add basic MLRun labels to pods that mediate job execution with KFP in order to facilitate monitoring.
The added labels are:
```
"mlrun/class"
"mlrun/function"
"mlrun/name"
"mlrun/project"
"mlrun/tag"
"mlrun/scrape-metrics"
```
> [ML-3728] Add standard mlrun labels to pods that mediate job execution

- tests/system/model_monitoring/assets/application.py
- tests/system/model_monitoring/test_app.py
This df is read directly from the application parquet, see:
https://github.com/mlrun/mlrun/blob/c672e81d368dfd4b0e7d57dc56b0a6759ab6a8c1/mlrun/model_monitoring/batch_application.py#L441-L445
This new assertion makes sure (indirectly) that the parquet is created for the application and can be read.
To test locally with the updated mlrun/mlrun images, use this branch:
https://github.com/jond01/mlrun/tree/tests/check-parquet-in-dummy-app-check
https://github.com/jond01/mlrun/commit/f83302f1d815cf5378582d32ceaf1e2cffd0f0fc
I tested the application locally with failures, and the e2e test failed as expected.
~~There's no concrete assertion on `len(df)`, although it's currently 5, as such an assertion will make the test more susceptible to external changes.~~
This PR continues the work on …
> [Model Monitoring] Validate the app parquet length

- mlrun/model.py
- mlrun/projects/operations.py
- mlrun/projects/project.py
- mlrun/run.py
- mlrun/runtimes/base.py
- tests/projects/assets/requirements-test.txt
- tests/projects/test_project.py
https://jira.iguazeng.com/browse/ML-4844
> [ImageBuilder] Fix config with requirements file

- docs/monitoring/dashboards/model-monitoring-applications.json
- docs/monitoring/dashboards/model-monitoring-details.json
- docs/monitoring/dashboards/model-monitoring-overview.json
- docs/monitoring/dashboards/model-monitoring-performance.json
- mlrun/model_monitoring/writer.py
In this PR:
- Generate V3IO KV Schema file under `users/pipelines/{project_name}/monitoring-apps/{endpoint_id}`. 
- Add a new Grafana dashboard called `Model Monitoring - Applications`. The new Grafana dashboard includes charts and KPIs that are relevant to a specific monitoring application (under a specific model endpoint). Most of the presented stats are taken from the V3IO TSDB. 
A dashboard example:
> [Model Monitoring] Add MM applications dashboard to Grafana

- mlrun/projects/project.py
The `skip_deployed` parameter was useless anyway since a new function was always created, therefore a build was always triggered (as there was no image in the function status). Since the API is called `build_image`, it makes sense for the user to expect a build will happen once triggered.
See [ML-4865](https://jira.iguazeng.com/browse/ML-4865)
> [Project] Deprecate project API `build_image.skip_deployed` parameter [1.5.x]

- mlrun/projects/project.py
- tests/projects/test_project.py
We encountered an issue with 1.5.0 where users would sync functions of a project that had a function in an old format of:
~~~
{"name":...
"spec":{
"metadata":{...},
"spec":{...},
}}
~~~
This format can no longer be generated but we still need to support this as we did not migrate it.
This was removed in https://github.com/mlrun/mlrun/pull/4271/files#diff-c972cfb48585c0ee85184b83808a9bf592a0ddd60a07cba789023649354f6cb8L3148
> [Project] Restore init function in spec for BC [1.5.x]

- mlrun/projects/project.py
- tests/projects/test_local_pipeline.py
instead of running arbitrary workflow, force user to provide which workflow to run
https://jira.iguazeng.com/browse/ML-3169
> [Workflows] Fail if name handler or path were not given

- mlrun/projects/project.py
- server/api/api/endpoints/schedules.py
- server/api/db/sqldb/db.py
- tests/api/api/test_schedules.py
For the MLRun cross-project monitoring capability, the list-schedules API (`GET /projects/{project}/schedules`) now supports providing `*` as project-name, returning schedules across all projects. This is consistent with the support we already have in the list-runs and list-pipelines APIs.
Of course, the results are filtered according to user permissions as defined in the OPA manifest - this code was already in place.
Addresses [ML-4878](https://jira.iguazeng.com/browse/ML-4878)
> [API] Support cross-project query for list-schedules using `*` as project name

- mlrun/config.py
- tests/system/model_monitoring/assets/application.py
- tests/system/model_monitoring/test_app.py
Before this change, the monitoring stream pod wouldn't write the parquet because of "not enough" events. This can be mediated on the server side by applying the following config map:
```yml
apiVersion: v1
data:
MLRUN_MODEL_ENDPOINT_MONITORING__PARQUET_BATCHING_MAX_EVENTS: "5"
kind: ConfigMap
metadata:
name: mlrun-override-env
namespace: default-tenant
```
to the mlrun-api pods.
The parquet is written after sending the 10K events to the model endpoint, and the test passes without an additional configuration. The extra time it takes for the test to finish is negligible.
This PR continues #4473 and together with #4498 completes [ML-4762](https://jira.iguazeng.com/browse/ML-4762).
(See [ML-4889](https://jira.iguazeng.com/browse/ML-4889) for solving the client-server config issue.)
> [Tests] Use the default number of 10K events to test the app framework

- mlrun/data_types/infer.py
- requirements.txt
- tests/test_requirements.py
[ML-4853](https://jira.iguazeng.com/browse/ML-4853)
By raising pyarrow upper bound and replacing `is_numeric` with `is_numeric_dtype`.
> [Data types] Fix warnings on `ingest` when pandas>=2

- mlrun/model_monitoring/application.py
- mlrun/model_monitoring/evidently_application.py
- tests/system/model_monitoring/assets/application.py
- tests/system/model_monitoring/assets/custom_evidently_app.py
- tests/system/model_monitoring/test_app.py
Add a new application with [evidently](https://github.com/evidentlyai/evidently) logic (and package) in addition to the dummy application.
It passes locally.
This PR continues the work on [ML-4762](https://jira.iguazeng.com/browse/ML-4762),  https://github.com/mlrun/mlrun/pull/4478.
> [Model Monitoring] Add an evidently app to the system test

- dev-requirements.txt
There is no change in the list, only correctly rearranging the groups.
This change was taken from #4498.
In the future, the "formatting & linting" section will be moved to pre-commit.
> [Requirements] Arrange the dev requirements

- server/api/utils/clients/log_collector.py
- server/log-collector/pkg/services/logcollector/logcollector_test.go
- server/log-collector/pkg/services/logcollector/server.go
seems like the size and offset calculation were a bit off wrt calculating the chunk size to read
add some UT to cover its usages
https://jira.iguazeng.com/browse/ML-4747
> [LogCollector] Fix get_log size calculation

- server/api/utils/scheduler.py
- tests/api/utils/test_scheduler.py
When listing schedules, the UI asks for `/projects/<project>/schedules?include_last_run=yes` which tries to enrich the schedule record with the details of the last run executed. 
If deleting the last-run of a given schedule, the last-run uid is still stored in the schedule itself, and it doesn't get removed when the job is deleted from the DB. Therefore, when `_enrich_schedule_with_last_run` tries to retrieve the details of that run (based on its uid) from the DB, the call fails and this fails the `list-schedules` REST call with 404. This situation persists until another run is triggered by the schedule, and the last_run field is updated to point at the new run executed.
The fix is to gracefully handle the situation where the last run is not found in the DB, and also clear the …
> [Schedules] Fix `get_schedule` when the last-run was deleted

- server/log-collector/pkg/services/logcollector/logcollector_test.go
- server/log-collector/pkg/services/logcollector/server.go
more cases, more bugs. no need to add the initial offset because we subtract  it one line after
https://jira.iguazeng.com/browse/ML-4747
> [LogCollector] Get logs fix round 2

- mlrun/model_monitoring/batch.py
- tests/system/model_monitoring/test_model_monitoring.py
Fixes [ML-4696](https://jira.iguazeng.com/browse/ML-4696) and covers the case with a system test.
In the case of inference without a deployed model endpoint (serving), the TSDB schema was not created.
Therefore, writing to it failed silently:
https://github.com/mlrun/mlrun/blob/ca5fe2031f522e961d0a737ce305a643e686b3f5/mlrun/model_monitoring/batch.py#L947-L960
I have also verified that the test fails on 1.6.0-rc4:
```
> 2023-11-08 16:37:43,262 [warning] Could not write drift measures to TSDB: {'err': Error("cannot call API - write error: backend Write failed: failed to create adapter: No TSDB schema file found at 'v3io-webapi:8081/users/pipelines/infer-model-tsdb/model-endpoints/events/'."), 'tsdb_path': 'pipelines/infer-model-tsdb/model-endpoints/events/', 'endpoint': …
```
> [Model Monitoring] Create TSDB schema for batch infer

- mlrun/datastore/datastore_profile.py
https://jira.iguazeng.com/browse/ML-4971
Restore Redis datastore profile function erroneously removed in https://github.com/mlrun/mlrun/pull/4521
> [Datastore] Fix error in Redis DS profile handling

- mlrun/model_monitoring/batch_application.py
Following #4550.
The "application batch" job couldn't run successfully before this change:
```
> 2023-11-12 14:08:07,789 [error] Failed to list endpoints: {'exc': AttributeError("'MlrunProject' object has no attribute 'list_model_monitoring_applications'")}
```
> [Model Monitoring] Fix monitoring functions SDK usage

- tests/system/model_monitoring/test_model_monitoring.py
Fix the **system test** backport introduced in #4564. The non-test code is ok.
This method was changed in 1.6.x and does not work in 1.5.x the same. I tested it locally with 1.5.x, and it works now.
> [Tests] Fix frames client getter [1.5.x]

- mlrun/datastore/base.py
- mlrun/datastore/redis.py
- mlrun/datastore/targets.py
https://jira.iguazeng.com/browse/ML-4970
Resolve the issue with 'credentials prefix' for Redis when providing username and password through environment variables with prefixes
> [Datastore] Fix support for 'credential prefix'

- mlrun/api/utils/builder.py
- mlrun/runtimes/utils.py
When using the default registry explicitly, the secret name is not automatically populated as opposed to how it works when using "." as image prefix (which turns "." -> "default registry")
This PR simply checks whether the target image uses mlrun default registry and if no secret name is provided (as an override) it simply populates the secret name from mlrun default configuration
https://jira.iguazeng.com/browse/ML-4953
> [Builder] Fix resolving secret name for using mlrun default registry

- mlrun/projects/project.py
The following error occurs when calling the mentioned method without arguments:
```
TypeError: can only concatenate list (not "NoneType") to list
```
Following #4550.
This fix solves the following issue:
```
> 2023-11-13 12:19:03,511 [info] There are no monitoring application found in this project
```
Similarly to #4565, this error could be caught by a type checker.
> [Model Monitoring] Fix the labels aggregation in `list_model_monitoring_functions`

- mlrun/utils/helpers.py
- server/api/main.py
- tests/api/test_collect_runs_logs.py
- tests/utils/test_helpers.py
When list of run uids is too big, it exceeds grpc message size and fails with
```
> 2023-11-09 18:35:56,028 [warning] Failed stopping logs for runs. Ignoring: {'exc': '<AioRpcError of RPC that terminated with:\n\tstatus = StatusCode.RESOURCE_EXHAUSTED\n\tdetails = "grpc: received message larger than max (12470570 vs. 4194304)"\n\tdebug_error_string = "UNKNOWN:Error received from peer ipv4:127.0.0.1:8282 {created_time:"2023-11-09T18:35:56.025126602+00:00", grpc_status:8, grpc_message:"grpc: received message larger than max (12470570 vs. 4194304)"}"\n>', 'project': 'load-project-0', 'run_uids':  .....
```
This PR chunk the list of run uids into a smaller portion ensuring the message size is relatively small
https://jira.iguazeng.com/browse/ML-4989
> [LogCollector] Fix big stop logs

- mlrun/projects/pipelines.py
- mlrun/runtimes/pod.py
[ML-4161](https://jira.iguazeng.com/browse/ML-4161)
When a Kubeflow workflow uses pipeline parameters to change resource requests/limits on a function, KFP-specific strings are left on the `_function_objects` dictionary. It's important to stress that this contamination only affects the client's local state and is not stored on the MLRun database since the API has safeguards in place against invalid strings. 
Example:
```
resources': {'requests': {'memory': '{{pipelineparam:op=;name=val}}'},
'limits': {'memory': '{{pipelineparam:op=;name=val}}'}}
```
There are at least three reasonable strategies for dealing with this problem:
1. Add a filter to `mlrun.db.httpdb.HTTPRunDB.store_function` to avoid sending Kubeflow-specific values when saving the function after a workflow has been run. 
a. …
> [Pipelines] Clean up Kubeflow specific data from Function definitions after workflow execution

- CONTRIBUTING.md
- Makefile
- conda-arm64-requirements.txt
- tests/test_requirements.py
Without `protobuf` - a simple
```py
import mlrun
```
fails.
`protobuf` can probably be installed also via [brew](https://formulae.brew.sh/formula/protobuf), but conda is also fine.
The error from a vanilla installation before this change:
```sh
python -c "import mlrun"
```
```
File "<string>", line 1, in <module>
File "/Users/Jonathan_Daniel/projects/mlrun/mlrun/__init__.py", line 32, in <module>
from .datastore import DataItem, store_manager
File "/Users/Jonathan_Daniel/projects/mlrun/mlrun/datastore/__init__.py", line 48, in <module>
from .base import DataItem
File "/Users/Jonathan_Daniel/projects/mlrun/mlrun/datastore/base.py", line 33, in <module>
from .store_resources import is_store_uri, parse_store_uri
File …
```
> [Requirements] Fix Apple silicon conda dependencies

- docs/cheat-sheet.md
- mlrun/runtimes/function.py
- mlrun/runtimes/serving.py
- server/api/api/endpoints/functions.py
- server/api/crud/runtimes/nuclio/function.py
- server/api/crud/runtimes/nuclio/helpers.py
- tests/api/runtimes/test_nuclio.py
Jira - https://jira.iguazeng.com/browse/NUC-58 , https://jira.iguazeng.com/browse/ML-4032
Recently, we implemented a new functionality in Nuclio that allows deploying functions without a default HTTP trigger. This pull request expands this capability in MLRun, enabling users to disable or enable the default HTTP trigger through MLRun.
> [Nuclio] Allow not creating an http trigger for Nuclio functions by default

- mlrun/datastore/base.py
- mlrun/datastore/datastore.py
- mlrun/datastore/datastore_profile.py
- mlrun/datastore/dbfs_store.py
- mlrun/datastore/s3.py
- tests/integration/test_dbfs_store/test_dbfs_store.py
1) Add support for datastore Profiles.
2) Add tests.
Pay attention!
Support for datastore profiles and dask dataframe (dd) will be added in a future PR.
[ML-4828](https://jira.iguazeng.com/browse/ML-4828)
> [Datastore] Support Dbfs datastore profiles

- server/api/api/utils.py
- tests/api/api/test_utils.py
When saving functions, we replace cleartext v3io access-keys with auth-secrets. To do that we rely on username derived from either the mount path (to conform with how `mlrun.mount_v3io` works) or the env variable `V3IO_USERNAME` which is set in the function spec - the MLRun sdk/client code set this env variable.
When a function is created through the UI with user feeding manual v3io mount, those details do not exist, thus the BE code cannot mask the secret due to lack of username. The result is that the function is stored with the access-key in cleartext.
This fixes this scenario by passing the username from the REST API auth info, and using it if nothing else works.
Fixes [ML-5068](https://jira.iguazeng.com/browse/ML-5068)
> [Secrets] Fix v3io access-key that remained in cleartext when creating function through UI

- mlrun/api/api/utils.py
- tests/api/api/test_utils.py
> [Secrets] Fix v3io access-key that remained in cleartext when creating function through UI [1.5.x]

- mlrun/datastore/targets.py
This reverts commit 4546dc81bbf39e8d4800710ede6745a9706f1d69.
Wide failures in feature-store system tests (ex test_relation_join)
> Revert "[Datastore] Fixing datastore profile target path resolution in CSV and Parquet targets (#4586)"

- mlrun/projects/project.py
When calling `list_model_monitoring_functions`, the expected value is a list of registered model monitoring functions with optional additional labels (along with the default label of `mlrun__type=mlrun__model-monitoring-application`). However, at the moment, if no additional label has been provided, this function returns all registered functions, including non-monitoring functions. 
In this PR, we fix that bug and make sure that only model monitoring functions are retrieved, even if no additional labels are provided.
> [Model Monitoring] Fix labels when calling `list_model_monitoring_functions`

- mlrun/projects/project.py
- mlrun/runtimes/kubejob.py
- mlrun/runtimes/serving.py
- mlrun/runtimes/sparkjob/spark3job.py
Calling `project.build_function()` on a Spark runtime would explode with:
```
TypeError: deploy() got an unexpected keyword argument 'force_build'
```
Reason is that the `force_build` param was missing in the `Spark3Runtime.deploy()` method - it was overlooked when this functionality was implemented.
Same is done for `ServingRuntime` (though it's usually not directly invoked through project functions).
Added the missing parameter.
> [Runtimes] Fixed missing `force_build` in `deploy()` for spark and serving runtimes

- Makefile
- requirements.txt
- tests/test_requirements.py
aiohttp 3.8.4 breaks our unit tests. blacklist for now until we fix it to unblock other PRs.
> [Requirements] Temporarily blacklist aiohttp 3.8.4

- mlrun/config.py
- mlrun/model_monitoring/batch_application.py
- tests/model_monitoring/test_helpers.py
The first effort for [ML-5036](https://jira.iguazeng.com/browse/ML-5036).
* Shorten the max stream pod flush rate from 30 min -> 1 min
* Update the controller ("batch application") interval range getter logic from:
[now- delta, now]
to:
[(now - 1 min) - delta, (now - 1 min)]
The above points reduce the risk of event loss during the monitoring function processing.
Add unit tests to cover some behavior.
> [Model Monitoring] Sync the controller range with the stream pod flush interval

- mlrun/runtimes/function.py
[No ticket]
Correct the check for the existence of the HTTP trigger so it work correctly if name of trigger is not equal to `http`
> Correct the check for the existence of the HTTP trigger

- mlrun/feature_store/feature_set.py
For compatibility with pandas 2. It also fixes a warning about this deprecation in pandas 1.
[ML-5023](https://jira.iguazeng.com/browse/ML-5023)
> [Feature Store] Set unit and timezone of default start and end times

- .readthedocs.yml
This file has a few problems:
1. It's html tags aren't balanced causing a malfunctioning search index - https://github.com/readthedocs/readthedocs.org/issues/10911
2. It uses `mlrun db` which is deprecated since client/server separation.
3. It's not part of the toctree in the docs.
> [Docs] Ignore colab tutorial in search

- tests/system/model_monitoring/test_app.py
* Increase the wait time to avoid checking the data before the apps run.
* Build and deploy the two apps and model serving concurrently (with thread pools).
* ~~Test the monitoring stream pod. In about half of the cases, its deployment fails. We should still look into this issue.~~
Unfortunately, I didn't find a reliable way to test the stream pod status.
Thanks to the concurrency improvement, the test time is reduced to about 6 minutes, although the sleep time is increased by one minute.
> [Tests] Improve the model monitoring framework system test

- mlrun/runtimes/local.py
https://jira.iguazeng.com/browse/ML-5026
not a bug, the log level should be changed ( from error to debug ) in the case a handler was not provided when running a function.
> [Runtimes] Modify logger level when handler is not provided

- mlrun/projects/project.py
When project context directory has pre-initialized git repo, it is added as source to project
This PR simply adds a log to inform the user that a git repo was found
https://jira.iguazeng.com/browse/ML-5040
https://jira.iguazeng.com/browse/ML-5042
> [Project] Log when project directory has existing git remote

- mlrun/common/schemas/auth.py
- mlrun/datastore/targets.py
- mlrun/db/httpdb.py
- server/api/api/api.py
- server/api/api/endpoints/nuclio.py
- server/api/middlewares.py
- server/api/utils/clients/async_nuclio.py
- tests/api/api/test_nuclio.py
- tests/api/utils/clients/test_async_nuclio.py
We are introducing a new asynchronous client for the Nuclio API. Currently, only the method to retrieve API gateways has been implemented.
> [Nuclio] Introduce nuclio async client for mlrun api

- mlrun/datastore/dbfs_store.py
The target URL includes Databricks' host because DBFS saves the host as the endpoint.
[ML-5124](https://jira.iguazeng.com/browse/ML-5124)
> [Datastore] Fix DBFS store URL

- server/api/api/endpoints/workflows.py
The new `submit_workflow` endpoint allows scheduling workflows, but doesn't check for `create` permissions on the `schedule` resource. Add this check if a schedule was provided, like we do in `submit_job`.
> [Auth] Add missing permission check when scheduling workflows

- mlrun/datastore/sources.py
- tests/system/runtimes/test_nuclio.py
Instead, let the function spec decide this as is normally the case.
[ML-5109](https://jira.iguazeng.com/browse/ML-5109)
> [Datastore] Avoid setting number of replicas in `KafkaSource`

- tests/system/feature_store/test_spark_engine.py
Methods that start with `test_` are picked up by pytest and run as tests.
> [Tests] Avoid running helper methods as tests

- tests/system/feature_store/test_feature_store.py
The tests fails with pyarrow 12 because of a dtype now being `string[pyarrow]` instead of `object`.
> [Tests] Fix `TestFeatureStore` dask tests

- mlrun/common/schemas/model_monitoring/constants.py
- mlrun/model_monitoring/controller.py
- tests/model_monitoring/test_helpers.py
A part of [ML-5036](https://jira.iguazeng.com/browse/ML-5036) - the controller side.
Store the "last_analyzed" data per endpoint & application and start from it to avoid skipping over data.
And --- a comeback of #4016 🎉
> [Model Monitoring] Start from the last analyzed time in the controller

- server/api/launcher.py
- server/api/utils/builder.py
- tests/system/runtimes/test_archives.py
- tests/system/runtimes/test_kubejob.py
was raised by `test_run_function_with_auto_build_and_source_is_idempotent_after_failure`
> [API] Do not enrich image if build required

- mlrun/feature_store/feature_set.py
- mlrun/feature_store/feature_vector.py
- tests/feature-store/test_featureset.py
- tests/feature-store/test_featurevec.py
https://jira.iguazeng.com/browse/ML-4622
Add APIs to FeatureSet and FeatureVector
class FeatureSet:
ingest() // new method - shadows mlrun.feature_store.api.ingest 
preview() // new method - shadows mlrun.feature_store.api.preview
deploy_ingestion_service() - shadows mlrun.feature_store.api.deploy_ingestion_service_v2
class FeatureVector:
get_offline_features() // new method - shadows mlrun.feature_store.api.get_offline_features 
get_online_feature_service() new method - shadowsmlrun.feature_store.api.get_online_feature_service
> [FeatureStore] Change APIs to be FeatureSet/FeatureVector class methods

- mlrun/common/schemas/model_monitoring/__init__.py
- mlrun/common/schemas/model_monitoring/constants.py
- mlrun/db/httpdb.py
- mlrun/model_monitoring/stores/kv_model_endpoint_store.py
- mlrun/model_monitoring/tracking_policy.py
- mlrun/projects/project.py
- server/api/api/endpoints/functions.py
- server/api/api/endpoints/jobs.py
- server/api/crud/model_monitoring/deployment.py
- server/api/crud/model_monitoring/helpers.py
- server/api/utils/clients/chief.py
- tests/api/api/test_functions.py
- tests/api/crud/model_monitoring/test_helpers.py
- tests/system/model_monitoring/test_app.py
Expose an API for applying the new model monitoring applications flow without using `set_tracking`. In other words, the new API generates the controller application scheduler (with pre-defined base period) and deploys the nuclio writer pod along with the writer stream. 
The new API is available under the project:
`project.enable_model_monitoring_controller()`
To disable the controller, you can call the following API which is also available under the project: 
`project.disable_model_monitoring_controller()` 
However, while the schedule controller job will be deleted from the project, the writer nuclio function will still run (will be fixed in the future following https://jira.iguazeng.com/browse/ML-3432?jql=text%20~%20%22Delete%20Function%22). 
In addition, as part of enabling the new …
> [Model Monitoring] Add model monitoring controller API 

- requirements.txt
- tests/system/feature_store/test_feature_store.py
- tests/test_requirements.py
Fixes the following tests:
```
FAILED tests/system/feature_store/test_feature_store.py::TestFeatureStore::test_get_offline_features_with_or_without_indexes - assert False
FAILED tests/system/feature_store/test_feature_store.py::TestFeatureStore::test_pandas_write_partitioned_parquet - assert False
FAILED tests/system/feature_store/test_spark_engine.py::TestFeatureStoreSparkEngine::test_relation_asof_join[False-False] - mlrun.runtimes.utils.RunError: An error occurred while calling o42.load.
FAILED tests/system/feature_store/test_spark_engine.py::TestFeatureStoreSparkEngine::test_relation_asof_join[False-True] - mlrun.runtimes.utils.RunError: An error occurred while calling o42.load.
FAILED tests/system/feature_store/test_spark_engine.py::TestFeatureStoreSparkEngine::test_relation_asof_join …
```
> [Tests] Fix system tests failures

- mlrun/data_types/to_pandas.py
Fixes error when using newer versions of numpy:
```
E           AttributeError: module 'numpy' has no attribute 'bool'.
E           `np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
E           The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
```
> [Data types] Avoid using deprecated data type

- mlrun/model_monitoring/controller.py
- mlrun/model_monitoring/controller_handler.py
While iterating over time windows, we should not return or raise exceptions.
The loop is expected to continue for the sake of marking the current time window as completed by updating the last analyzed time.
I expect this to fix [ML-5181](https://jira.iguazeng.com/browse/ML-5181).
> [Model Monitoring] Fix the controller windows loop - continue, don't return

- mlrun/feature_store/retrieval/base.py
- mlrun/feature_store/retrieval/dask_merger.py
- mlrun/feature_store/retrieval/local_merger.py
- tests/system/feature_store/test_feature_store.py
Pandas 2 introduces timestamp resolutions, and does not allow `merge_asof` of dataframes with different timestamp resolutions. This PR introduces code that attempts to convert the timestamp resolution before merge, if necessary.
Fixes `TestFeatureStore::test_ingest_and_query` failure with
```
pandas.errors.MergeError: incompatible merge keys [1] dtype('<M8[ns]') and dtype('<M8[us]'), must be the same type
```
> [Feature Store] Try to convert timestamp resolution before merge if necessary

- server/api/api/endpoints/artifacts_v2.py
- server/api/crud/artifacts.py
- server/api/db/base.py
- tests/api/api/test_artifacts.py
- tests/api/conftest.py
Fixing a typo where `tree` and `producer_id` were not used correctly in `create_artifact`.
Also - set the `create_artifact` response status code to 201 (created).
In this PR I also added the `client_v2` fixture, that is not attaching the version prefix to the api endpoints.
This is useful when tests use several endpoints that are not under the same version prefix (e.g. create project with `v1`, then create artifact with `v2`).
> [Artifacts] Fix argument name in create_artifact

- README.md
The previous badge was always "failing" and did not indicate the build status on push to development, but the CI status on development, which rarely runs.
https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge#using-the-branch-parameter
> [Readme] Update build status badge

- server/api/db/sqldb/db.py
- server/api/initial_data.py
- tests/api/api/test_artifacts.py
- tests/api/conftest.py
- tests/api/db/test_artifacts.py
2 fixes regarding for creating tags when migrating artifacts to the new v2 table:
1. Commit the artifacts first, before the tags and labels, so the artifact object will get a db `id` which will be set in the tags and labels.
2. Search for existing multiple tags in the DB that are attached to the artifact, instead of taking the tag name from the artifact metadata.
Fixes https://jira.iguazeng.com/browse/ML-5220
> [Artifacts] Fix tag migrations

- mlrun/feature_store/retrieval/base.py
- mlrun/feature_store/retrieval/dask_merger.py
- mlrun/feature_store/retrieval/local_merger.py
- tests/system/feature_store/test_spark_engine.py
Fixes `TestFeatureStore::test_as_of_join_different_ts`.
Also fix `TestFeatureStoreSparkEngine::test_ingest_with_steps_extractor` (unrelated failure).
> [Feature store] Fix timestamp conversion in merger

- server/api/db/sqldb/db.py
- tests/api/db/test_artifacts.py
- tests/api/db/test_sqldb.py
When creating an artifact with the same key and tag of an existing artifact, but a different uid (e.g when there's a different producer), the original artifact still had its tag when listing artifacts, although the tag pointed only to the new artifact.
This is because the tag was saved in the metadata of artifact's `full_object` - so when "unpacking" the object when listing the artifacts, the tag was already in the metadata.
To fix this, we pop the tag out of the metadata before saving the `full_object` dictionary on the artifact record.
In addition, I removed the duplicated flow when storing an artifact, and there was an existing artifact but a new one should be created - now it goes to the same `create_artifact` flow.
Lastly, I reorganized some of the code - moved public methods above …
> [Artifacts] Fix artifact re-tagging

- server/api/runtime_handlers/base.py
- tests/api/runtime_handlers/base.py
- tests/api/runtime_handlers/test_kubejob.py
- tests/api/runtime_handlers/test_mpijob.py
- tests/api/runtime_handlers/test_sparkjob.py
https://jira.iguazeng.com/browse/ML-4975
In case the resource was not listed for some reason when listing resources to monitor, search for the resource one more time before declaring the run has failed.
> [API] Add resource search before failing run in monitoring

- server/api/db/sqldb/db.py
In the `create_artifact` flow we want to add the `latest` tag regardless of whether a tag was specified or not.
> [Artifacts] Always add `latest` tag when creating an artifact

- mlrun/projects/project.py
- server/api/crud/model_monitoring/deployment.py
- tests/system/model_monitoring/test_app.py
Fixes [ML-5223](https://jira.iguazeng.com/browse/ML-5223).
The "delay" mechanism in the schedule was designed for the legacy batch job.
It isn't relevant for the model monitoring applications framework, where we address the intricate scheduling details in the controller.
I ran the e2e system test locally.
> [Model Monitoring] Don't delay the controller's schedule

- server/api/api/endpoints/runs.py
- server/api/crud/logs.py
- server/api/crud/projects.py
- server/api/crud/runs.py
- server/api/rundb/sqldb.py
- server/api/utils/projects/member.py
- tests/api/crud/test_runs.py
- tests/api/test_rundb.py
When deleting a run, delete its logs using the log collector first, and if it fails call the legacy deletion in which the api deletes the files by itself.
Also - refactored a bit of the code so deleting logs will be in the `Logs` crud, and so we can share code between runs an projects.
Resolves [ML-4883](https://jira.iguazeng.com/browse/ML-4883)
> [API] Delete run logs when deleting run

- mlrun/config.py
- mlrun/runtimes/constants.py
- server/api/api/endpoints/runs.py
- server/api/crud/runs.py
- server/api/db/base.py
- server/api/db/sqldb/db.py
- server/api/rundb/sqldb.py
- tests/api/crud/test_runs.py
- tests/api/test_rundb.py
Delete run now deletes all of the runtime resources (pods, crds, logs...)
That means that deleting multiple runs should take deletion of the resources into consideration which makes it a heavy operation.
This PR adds async batch runs deletion.
https://jira.iguazeng.com/browse/ML-5307
> [API] Cascade and batch multiple runs deletion

- mlrun/model_monitoring/application.py
- tests/system/model_monitoring/assets/application.py
- tests/system/model_monitoring/test_app.py
Fixes [ML-5291](https://jira.iguazeng.com/browse/ML-5291).
- Return a list of one item from the dummy app - the system test covers this case now, and it passes.
- This error could be caught by a type checker - see [ML-5304](https://jira.iguazeng.com/browse/ML-5304).
> [Model Monitoring] Fix the option to return a list of results

- mlrun/common/schemas/artifact.py
- server/api/crud/artifacts.py
- tests/api/api/test_artifacts.py
In the artifact refactor we removed all legacy artifacts, so we do not support this artifact format anymore.
If a request is made with a `format=legacy` query, it will get a 422 (Unprocessable Entity) response from FastAPI.
> [Artifacts] Remove `legacy` format

- setup.cfg
This file is not used anymore, including the test alias.
> [Config] Remove an unused legacy `setup.cfg` file

- server/api/crud/runs.py
- server/log-collector/pkg/services/logcollector/server.go
- tests/api/crud/test_runs.py
Requests to the log collector for stopping and deleting logs were ignored if they didn't come from the Chief. 
This caused requests to delete runs to not delete logs, if the workers handled them.
Stopping logs can only happen in the Chief because it keeps an in-memory state of which runs are currently collected for logs.
Stop logs is called for terminated runs, and since we can delete runs that are terminated or creating (ie . meaning we do not have logs for them yet) we can skip stopping logs before deleting run logs.
As for deletion - the Chief-only limitation was instilled due to the chief being the sole deleter of projects, however there is no actual limitation in the log collector for the worker to delete the logs.
So to allow workers to delete runs:
- Don't stop logs explicitly …
> [API] Fix run logs not deleted in worker

- mlrun/projects/pipelines.py
- mlrun/projects/project.py
- server/api/crud/workflows.py
This is not yet supported.
What needs to be done is to watch the run of the remote engine because it starts a kubejob and runs the functions locally on that pod but it requires some design.
The KFP runner also lists the runs with a label of the workflow id - need to make sure this label is added to the local runs as well to get the results.
This will fix system test `test_remote_pipeline_with_local_engine_from_github` which is not really testing anything because it doesn't wait for the pipeline to complete.
> [Pipelines] Ignore get run status for remote:local

- dependencies.py
- extras-requirements.txt
- mlrun/datastore/azure_blob.py
- mlrun/datastore/datastore_profile.py
- tests/integration/azure_blob/test_azure_blob.py
- tests/test_requirements.py
We have removed the usage of the BlobServiceClient in the Azure Datastore.
From now on, we will rely solely on the azure fsspec class (AzureBlobFileSystem for the 'az' protocol) in the Datastore.
1) Fixed delete (rm in azure datastore) function.
2) Added tests for delete and download items.
[ML-5303](https://jira.iguazeng.com/browse/ML-5303)
> [Datastore] bugfix Azure delete

- mlrun/datastore/targets.py
This can probably only happen when debugging locally.
> [Datastore] Avoid failure on serialization

- mlrun/config.py
- server/api/api/endpoints/functions.py
- server/api/api/endpoints/runs.py
- server/api/constants.py
- server/api/crud/runs.py
- server/api/main.py
- server/api/runtime_handlers/base.py
- server/api/utils/background_tasks.py
- tests/api/api/test_runs.py
Add the background task id of the abortion to the run status.
When aborting again, check with the ID if there is a task already running.
Do a best effort to determine if it is running or just finished, return it.
Otherwise, create. new task.
https://jira.iguazeng.com/browse/ML-5279
> [API] Handle recurrent abort runs

- mlrun/config.py
Avoid flooding the logs with uninformative "shard not found" debug messages.
Fixes the MLRun part of [ML-5325](https://jira.iguazeng.com/browse/ML-5325).
There are still "garbage" logs before the first record to the stream, which should be treated in Nuclio ([NUC-113](https://jira.iguazeng.com/browse/NUC-113)).
> [Model Monitoring] Update the number of application stream shards to 1

- mlrun/db/httpdb.py
Be more explicit in the docstring as to what is the structure of the artifact to pass to `store_artifact`.
Resolves https://jira.iguazeng.com/browse/ML-5357
> [Docs] Fix `store_artifact` docstring in httpdb

- server/api/initial_data.py
- tests/api/db/test_artifacts.py
Before the refactor, artifacts that weren't created as part of a hyper param run did not have an `iter` field.
When we migrate the artifacts to the new V2 table, we set the `iteration` and `best_iteration` fields on the record itself.
Previously we ignored these fields if the artifact didn't have an `iter` field in its metadata, but then these artifacts weren't returned when listing artifacts with `best_iteration=True` (which is the default UI behavior).
Now, if artifacts do not have an `iter` field, we set `iteration = 0` and `best_iteration = True`, so they are returned properly as before.
Resolves https://jira.iguazeng.com/browse/ML-5337
> [Artifacts] Fix migrating artifacts without iteration

- mlrun/artifacts/base.py
- mlrun/artifacts/dataset.py
- tests/artifacts/test_dataset.py
[ML-4922](https://jira.iguazeng.com/browse/ML-4922)
This PR is a follow-up to https://github.com/mlrun/mlrun/pull/4779, and it changes the `header_original_length` field to be part of `ArtifactStatus` instead of `DatasetArtifactSpec`.
> [Artifacts] Header length information for datasets must be stored as a status property

- Makefile
Any linter failures should be raised by `lint`.
> [Makefile] `fmt` target should never fail

- mlrun/runtimes/databricks_job/databricks_wrapper.py
- tests/system/runtimes/test_databricks.py
Add databricks output to logs....
Including non-logs info - such as metadata.
[ML-5310](https://jira.iguazeng.com/browse/ML-5310)
> [Runtimes] Databricks output as logs

- server/api/db/sqldb/db.py
- tests/system/base.py
When storing a new artifact, we first tried to get an existing artifact with the same project, key, producer_id, etc.
However, this was too broad. 
When we update artifact specs, we basically just create a new artifact with the same metadata but a different spec. 
When calculating the artifact's `uid`, we get a new `uid` - so it does become a new artifact, but when getting an existing artifact, we search for `one_or_none` - but get multiple artifacts.
In this PR I moved the check for an existing artifact to after the `uid` calculation, so the query for the existing artifact will include it and will be more specific.
In addition, I fixed the issue for marking best iteration artifacts so it will return the best iteration artifact's uid, just like `store_artifacts` returns the artifact's …
> [Artifacts] Check existing artifact with uid when storing artifact

- mlrun/projects/project.py
- tests/projects/test_project.py
[ML-5047](https://jira.iguazeng.com/browse/ML-5047)
Both sync_functions and set_source must return more explicit error messages to help the user debug synchronization issues.
Here's an example of what the output can look like:
```
[error] Failed to resolve all function related dependencies while working with the new project source. Aborting
File "/Users/laury/dev/iguazio/misc_workspace/mlrun/mlrun/projects/project.py", line 2397, in sync_functions
name, func = _init_function_from_dict(f, self, name)
File "/Users/laury/dev/iguazio/misc_workspace/mlrun/mlrun/projects/project.py", line 3570, in _init_function_from_dict
func = code_to_function(
File "/Users/laury/dev/iguazio/misc_workspace/mlrun/mlrun/run.py", line 745, in code_to_function
name, spec, code = …
```
> [Project] Return clear error messages when set_source triggers unresolvable function dependencies

- mlrun/feature_store/steps.py
- mlrun/model_monitoring/stream_processing.py
- server/api/crud/model_monitoring/deployment.py
Fixes [ML-5335](https://jira.iguazeng.com/browse/ML-5335) and [ML-5347](https://jira.iguazeng.com/browse/ML-5347).
The source of these issues is that the "last_request" field of the model endpoint is not updated for every request. This behavior stems from the sample step in the monitoring stream graph.
The solution introduced in this PR is to move the "update endpoint" branch after the "rename" step.
It guarantees a reliable "last_request" field, independent of the cadence of events.
The main change is 319f759, the other commits are mostly style and typing.
The graph before the change:
After:
> [Model Monitoring] Update the "last_request" field for each request

- mlrun/utils/helpers.py
https://jira.iguazeng.com/browse/ML-5343
In specific situations, such as when invoking the `init_featureset_graph()` function, we must determine the namespace from which the call originates in order to generate user-introduced objects within that namespace. Presently, we search for the first namespace that is not prefixed with 'mlrun.*'. However, in cases where a 'deprecated' decorator is used, an additional namespace appears before the primary one, labeled as 'deprecated.*'. We should also disregard this additional namespace.
> [Utils] Skip 'derecated' when looking for caller function's namespace

- mlrun/projects/project.py
- mlrun/utils/helpers.py
- server/api/initial_data.py
Add an optional argument to get an artifact with a specific `tree` (`producer_id`).
Additionally, improve the naming and docstring of `mlrun.utils.parse_artifact_uri` for better usability.
Related to https://jira.iguazeng.com/browse/ML-4974
> [Project] Add `tree` argument to `get_artifact`

- mlrun/model_monitoring/evidently_application.py
- tests/model_monitoring/test_evidently_base.py
- tests/system/model_monitoring/test_app.py
Resolves [ML-5374](https://jira.iguazeng.com/browse/ML-5374), [ML-5345](https://jira.iguazeng.com/browse/ML-5345).
- Since evidently broke the interface between patches, raise a warning when the current version is not "compatible".
- Upgrade to version [0.4.11](https://github.com/evidentlyai/evidently/releases/tag/v0.4.11).
> [Model Monitoring] Upgrade evidently and specify the supported version

- server/api/initial_data.py
Take the resolved iteration, in case the `iter` value wasn't present in the artifacts metadata and was set to `None`.
> [Artifacts] Fix iteration in uid calculation during migration

- mlrun/feature_store/common.py
As it results in a double trace ("During handling of the above exception, another exception occurred: ...").
> [Feature Store] Avoid catching and re-raising error

- tests/system/model_monitoring/assets/custom_evidently_app.py
Following #4794.
I verified that all the evidently imports work with versions 0.4.11 and 0.4.12.
> [Model Monitoring] Fix an evidently import

- tests/system/model_monitoring/test_app.py
In some edge cases, it might take longer for the controller -> app -> writer to complete.
> [Model Monitoring] Fix the e2e sys test wait time

- server/api/crud/runs.py
- tests/api/api/test_runs.py
- tests/api/crud/test_runs.py
Raising an exception so that the background task will know it failed.
https://jira.iguazeng.com/browse/ML-5403
> [API] Mark background task as failed when abort run fails

- mlrun/common/model_monitoring/helpers.py
- mlrun/model_monitoring/batch.py
- mlrun/model_monitoring/controller.py
- tests/model_monitoring/test_helpers.py
Fixes [ML-5387](https://jira.iguazeng.com/browse/ML-5387).
In "batch infer" model endpoints, these bins might not be present, resulting in an inconsistent behavior between shared and unshared features (e.g., "target").
It is beneficial and required to add these bins, as some "live" data may fall under them.
> [Model Monitoring] Always add ±inf bins to histograms

- mlrun/utils/helpers.py
- server/api/db/sqldb/db.py
- tests/api/db/test_artifacts.py
Artifacts created timestamps are saved in the DB as strings without timezone, and a milliseconds.
When first creating an artifact, the created timestamp includes timezone, but when updating it may not include it.
This can cause errors when updating artifacts and trying to force a format with timezone offset using `datetime.strptime`.
The fix is to always make sure the timestamp exists, whether creating a new artifact or updating it.
Fixes https://jira.iguazeng.com/browse/ML-5389
> [Artifacts] Fix timezone in created timestamp

- server/api/runtime_handlers/base.py
- server/api/runtime_handlers/sparkjob/spark3job.py
- tests/api/runtime_handlers/test_sparkjob.py
https://jira.iguazeng.com/browse/ML-5014
Notes on the solution:
- If the crd has no state and we are in monitoring we skip the specific run.
- if the crd has no state and we are in delete resource flow we force deletion but don't update the run state.
> [API] Skip monitoring when CRD state is not populated

- mlrun/common/model_monitoring/helpers.py
The value we use is not platform-dependent, see:
https://github.com/mlrun/mlrun/pull/4824#discussion_r1436840152
Keep the variable with a name for readability.
> [Model Monitoring] Remove a factor from inf edge detection

- mlrun/db/httpdb.py
- server/api/api/endpoints/logs.py
- server/log-collector/pkg/services/logcollector/server.go
When getting logs, the offset is an offset inside the log file.
Passing a negative offset can cause several issues when calculating the chunk sizes and result with large logs returning in the responses, and errors such as:
```
MLRunRuntimeError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
```
Resolves https://jira.iguazeng.com/browse/ML-5391
> [Logs] Validate positive offset when getting logs

- mlrun/errors.py
- mlrun/runtimes/databricks_job/databricks_runtime.py
- mlrun/runtimes/pod.py
- mlrun/utils/helpers.py
- server/api/runtime_handlers/base.py
- server/api/runtime_handlers/kubejob.py
- server/api/utils/singletons/k8s.py
- tests/api/runtime_handlers/base.py
This was raised by databricks runtime as it uses a grace period of 60 seconds to lay off some time for the cancel task execution.
When testing state thresholds it was apparent that for states like pending scheduled and image pull backoff, the pod would hang on terminating forever, for these states, the cancel task is not needed therefore we can force deletion.
https://jira.iguazeng.com/browse/ML-5271
> [API] Force delete pods after grace period passed

- mlrun/db/httpdb.py
- mlrun/feature_store/feature_set.py
- mlrun/projects/project.py
- mlrun/runtimes/__init__.py
- mlrun/runtimes/pod.py
The `KubeResource` class has documentation for several functions which are not documented elsewhere (for example `with_security_context`). Added this class to the documentation so that it's visible.
Also fixed some small docstring issues (mostly fixing `:return:` to `:returns:`).
> [Doc] Add `KubeResource` to docs and fix some malformed doctrings

- mlrun/runtimes/databricks_job/databricks_wrapper.py
- tests/system/runtimes/test_databricks.py
Including relevant information such as run_id, job_id run_name and more...
1) Update the wrapper to log the metadata as an artifact.
2) Add tests that check the artifact.
[ML-5310](https://jira.iguazeng.com/browse/ML-5310)
> [Datastore] Log databricks metadata run as an artifact

- mlrun/feature_store/api.py
https://jira.iguazeng.com/browse/ML-5409
To enable Spark's access to storage, it's necessary to provide Spark with the appropriate credentials. This Pull Request eliminates the logging of this confidential information.
> [Spark] Remove logging of spark options

- mlrun/model_monitoring/application.py
- mlrun/model_monitoring/writer.py
Resolves [ML-5400](https://jira.iguazeng.com/browse/ML-5400).
Save in the following file:
```
/users/pipelines/{project_name}/monitoring-apps/{model_endpoint_id}
```
The key is the application name, and the value is a dictionary with metric names as the keys:
```
app1:
{
m1: "...",
m2: "...",
}
> [Model Monitoring] Save all the metrics of an application in KV storage

- mlrun/db/httpdb.py
- server/api/api/endpoints/logs.py
- server/api/crud/logs.py
- server/api/utils/clients/log_collector.py
- server/log-collector/pkg/services/logcollector/logcollector_test.go
- server/log-collector/pkg/services/logcollector/server.go
- server/log-collector/proto/log_collector.proto
- tests/api/crud/test_logs.py
- tests/api/utils/clients/test_log_collector.py
- tests/rundb/test_httpdb.py
- tests/system/logs/test_logs.py
Add an option to get a log file size for a specific run, without getting the actual logs.
Supported both as an endpoint in the SDK.
This was implemented by replacing the log collector's `HasLogs` function with `GetLogSize`.
`get_logs` will use `GetLogSize` to verify there are actually logs to get, instead of `HasLogs`.
Resolves https://jira.iguazeng.com/browse/ML-5411
> [Logs] Add get log size endpoint and sdk method

- mlrun/db/httpdb.py
When "watching" a run, keep watching if the run is in transitional states, which include:
- `pending`
- `running`
- `created`
- `aborting`
Also, use constants instead of raw strings.
Resolves https://jira.iguazeng.com/browse/ML-5430
> [HTTPDB] Keep watching on created and aborting states

- dependencies.py
- extras-requirements.txt
- tests/test_requirements.py
Databricks version 0.15.0 can cause conflicts with gcs.
The required version is 0.13.0.
[ML-5441](https://jira.iguazeng.com/browse/ML-5441)
> [Requirements] Fix databricks requirements

- mlrun/datastore/v3io.py
- mlrun/model_monitoring/controller.py
Parquet files are stored on the user side, while the controller operates on the server side. To delete these Parquet files through the controller, it's necessary to establish a file system with the appropriate v3io access key for the relevant permissions.
[ML-4982](https://jira.iguazeng.com/browse/ML-4982)
> [Model Monitoring] Fix delete old parquet function

- mlrun/db/base.py
- server/api/rundb/sqldb.py
Followup to #4836, so the method will be easily accessible.
> [RunDB] Add get_log_size to rundb interface

- .run/Deploy CE.run.xml
- automation/deployment/ce.py
- automation/deployment/deployer.py
- server/api/crud/logs.py
- tests/api/crud/test_logs.py
- tests/system/env-template.yml
Add options in the deployer script to:
1. override the log collector image
2. disable log collector (was always disabled, now enabled by default)
3. disableable components will always be part of the helm command - if they were enabled, the script would not specify it and count on the default value. Now it will be explicit.
Add precondition check for get log size endpoint - supported only with log collector.
This will make the open source system tests run with log collector.
> [CI] Enable log collector in deployer and OS system tests

- mlrun/execution.py
- mlrun/package/context_handler.py
- tests/package/test_context_handler.py
- tests/system/runtimes/assets/mpijob_function.py
- tests/test_execution.py
https://jira.iguazeng.com/browse/ML-5282
When creating a context from a run dict, we tend to store the run without taking into consideration multiple workers scenarios like MPI.
Added a verification for the logging worker before storing the run to avoid conflicts.
Updating runs is safe to use from workers, it will update any conflicting values instead of exploding.
We want to allow updating the run from the workers to ensure we log valuable information about the runs in the workers. For the initial store, the information is practically the same so we skip it.
> [Context] Verify logging worker before storing run

- requirements.txt
- tests/test_log_serialization.py
- tests/test_requirements.py
[ML-4855](https://jira.iguazeng.com/browse/ML-4855)
Also clean test that use numpy.float (deprecated in newer versions of numpy).
Datastore system tests pass (s3, azure, google and dbfs)
> [Requirements] Change numpy version for tensorflow 2.14

- requirements.txt
* CVE-2023-37276 7.5 Inconsistent Interpretation of HTTP Requests ("HTTP Request Smuggling") vulnerability with High severity found
* CVE-2023-47627 7.5 Inconsistent Interpretation of HTTP Requests ("HTTP Request Smuggling") vulnerability with High severity found
* CVE-2023-49082 5.3 Improper Neutralization of CRLF Sequences ("CRLF Injection") vulnerability with Medium severity found
> [Requirements] Relax aiohttp requirement to resolve security vulnerabilities

- docs/cheat-sheet.md
- docs/data-prep/ingest-data-fs.md
- docs/feature-store/feature-sets.md
- docs/feature-store/transformations.md
[ML-4622](https://jira.iguazeng.com/browse/ML-4622)
[ML-3856](https://jira.iguazeng.com/browse/ML-3856): on sdk ingestion + recreation of the fset object, a new ingest with overwrite=false still creates a new run_id (ie behave like overwire=true)
> [Docs] Updates for FS/FV APIs are now FeatureSet / FeatureVector class methods

- mlrun/model_monitoring/application.py
- mlrun/model_monitoring/evidently_application.py
- mlrun/projects/project.py
- tests/system/model_monitoring/assets/application.py
- tests/system/model_monitoring/assets/custom_evidently_app.py
- tests/system/model_monitoring/test_app.py
Resolves [ML-5456](https://jira.iguazeng.com/browse/ML-5456).
* Rename the "Application" base classes to "ApplicationBase"
* Inherit from `ABC`, mark the run method as an `abstractmethod` to block direct instantiation by mistake
* Rename the `run_application` method of the `ApplicationBase` class to `do_tracking`
* Fix some docstrings + a typo
> [Model Monitoring] Improve the model monitoring application Python API

- mlrun/common/schemas/model_monitoring/constants.py
- mlrun/model_monitoring/api.py
- mlrun/model_monitoring/batch.py
- mlrun/model_monitoring/controller.py
- mlrun/model_monitoring/helpers.py
- mlrun/model_monitoring/stream_processing.py
- mlrun/model_monitoring/writer.py
- tests/model_monitoring/test_helpers.py
- tests/system/model_monitoring/test_app.py
Fixes [ML-5407](https://jira.iguazeng.com/browse/ML-5407) - remove +3h TSDB end time.
This change is generally backward compatible. We previously TZ oblivious timestamps in model monitoring, and these can be parsed by the [`datetime.datetime.fromisoformat`](https://docs.python.org/3/library/datetime.html#datetime.datetime.fromisoformat) function, resulting in an object without a TZ.
> [Model Monitoring] Use timezone aware timestamps and objects

- mlrun/projects/project.py
- tests/projects/test_project.py
The `project.build_image()` function did not take into account the project source. If the user is setting a source to the project (for example `git` source) and set `pull_at_runtime = False`, then it is expected that images used would contain the project source in them. This worked for specific functions when building them, but not in the project level.
The expectation is that running this code:
```
project = mlrun.get_or_create_project(
name="project-name", context="./"
)
project.set_source(
"git://some/repo",
pull_at_runtime=False
)
project.build_image(image=".some-project-image")
```
Would build the `.some-project-image` image with the source in it, such that running a function will work without having to specify an image:
```
func = project.set_function(handler="package.function", …
```
> [Project] Take project source into account when running `build_image`

- server/api/runtime_handlers/sparkjob/spark3job.py
Instead of `/tmp/spark-events`.
[ML-4690](https://jira.iguazeng.com/browse/ML-4690)
> [Spark] Default spark event log dir to `/tmp`

- automation/patch_igz/patch_env_template.yml
- automation/patch_igz/patch_remote.py
Add support to push the built images to the iguazio data node registry.
This requires using the data node IP from the local host and to overwrite the IP with the domain named registry from the app cluster.
> [Automation] Support patch with data node registry

- mlrun/datastore/base.py
- tests/test_datastores.py
Require that it be nonempty and to have a scheme.
[ML-4617](https://jira.iguazeng.com/browse/ML-4617)
> [Datastore] Add validation for empty URL

- mlrun/config.py
Fix 'Unauthorized path' error when trying to preview/download artifact using datastore profile path.
https://jira.iguazeng.com/browse/ML-5464
> Add ds to allowed file paths

- .github/pr-title-validation-config.json
Javascript is not familiar with  `\\p{Lu}` so falling back to A-Z which means every pr title must start with a capital letter
> [CI] Use Javascript regex conventions

- server/api/utils/builder.py
- server/api/utils/singletons/k8s.py
[ML-3728](https://jira.iguazeng.com/browse/ML-3728)
Add more MLRun-related labels to pods that build function and project images in order to facilitate monitoring.
The added labels are:
```
mlrun/name
mlrun/function
mlrun/tag
```  
It's worth noting that `mlrun/class` and `mlrun/project` are already present on builder pods.
> [Functions] Add more labels to the image builder pods to facilitate resource usage tracking

- mlrun/execution.py
Host label describes the running pod. When running with multiple workers, it will result with conflicting values and as consequence, storing the run will fail.
https://jira.iguazeng.com/browse/ML-5512
> [Execution] Don't add host label to non logging workers

- mlrun/errors.py
- mlrun/model_monitoring/controller.py
- mlrun/model_monitoring/helpers.py
- tests/model_monitoring/test_helpers.py
- tests/system/model_monitoring/test_app.py
Resolves [ML-5495](https://jira.iguazeng.com/browse/ML-5495).
Take the actual monitoring time window from the last run of the controller's job.
> [Model Monitoring] Fix bumping the last request for batch inference 

- mlrun/datastore/azure_blob.py
- mlrun/datastore/base.py
- mlrun/datastore/dbfs_store.py
- mlrun/datastore/google_cloud_storage.py
- mlrun/datastore/s3.py
- mlrun/datastore/v3io.py
https://jira.iguazeng.com/browse/ML-5518
https://jira.iguazeng.com/browse/ML-5521
Hadoop configurations for Azure Spark were based on the presumption that underlying storage options are present only if they are non-empty. However, this assumption proved to be inaccurate. The proposed Pull Request (PR) addresses this issue by excluding empty storage options, thereby ensuring the proper functioning of Spark.
> [Datastore] Filter out 'none' values when passing storage options for Azure

- mlrun/datastore/datastore_profile.py
In addition to https://github.com/mlrun/mlrun/pull/4901
[ML-5504](https://jira.iguazeng.com/browse/ML-5504)
> [Datastore] Rename access_key to access_key_id in S3 datastore-profile private

- server/api/db/sqldb/db.py
- tests/api/db/test_artifacts.py
Add the option to use tilde `~` as a prefix to enable case-insensitive label queries. This works the same as it does for names, meaning it's not just case-insensitive, but also searches for substring. For example, looking for `~IKA` will match `pikachu`.
The same works for label name and value, so if an artifact has a label `Key : Value`, looking for `Key=~V` will do an exact match on the key but insensitive match on the value, looking for `~K=~V` will do insensitive match on both.
This change works on every label query that uses the `_add_labels_filter` method, so it works for artifacts, functions, runs, fsets, fvecs, projects and schedules. 
Fixes [ML-5480](https://jira.iguazeng.com/browse/ML-5480)
> [DB] Support case-insensitive label queries

- server/api/utils/builder.py
- tests/api/utils/test_builder.py
The mount sets the permissions for the directory to read only. Setting it to tmp, blocks writing anything to it. Block /tmp/aws instead.
https://jira.iguazeng.com/browse/ML-4937
> [Builder] Mount AWS credentials to /tmp/aws

- automation/deployment/README.md
- automation/deployment/ce.py
- automation/deployment/deployer.py
Currently, the MLRun CE deploy script reads the local CPU architecture to infer whether Helm can install Kubeflow Pipelines. This check doesn't consider that the target cluster of the procedure may be running in a separate environment with a different CPU, like a Virtual Machine.
This PR adds the flag `--force-enable-pipelines` to bypass this behavior if the user chooses to.
> [Automation] Extend MLRun CE deploy script to allow for a forceful Kubeflow Pipelines installation

- server/api/api/utils.py
- tests/api/api/test_utils.py
When submitting a scheduled batch run and overriding the function's configuration, the task still keeps a reference for the original function URI, with the default values.
So although the actual run includes the custom spec, this affects editing a schedule (in the UI) by not populating the config fields with the correct custom values.
To overcome this, we create a new versioned function in the DB with the enriched configuration, and set its URI on the scheduled task, same as we do with hub functions.
Now, the task will reference the enriched function instead of the original one.
Fixes https://jira.iguazeng.com/browse/ML-5111
> [Run] Save enriched function to db when submitting job schedule with custom spec

- mlrun/projects/project.py
first introduce #4550
[ML-5547](https://jira.iguazeng.com/browse/ML-5547)
> [Model Monitoring] Fix `remove_model_monitoring_function` to remove function from db

- mlrun/execution.py
- tests/integration/sdk_api/run/test_run.py
The host label is needed to resolve if the worker is the logging worker or not.
Do not set labels from non logging workers
https://jira.iguazeng.com/browse/ML-5536
> [Execution] Fix non logging worker lables

- mlrun/model_monitoring/helpers.py
- tests/model_monitoring/test_helpers.py
Fixes [ML-5542](https://jira.iguazeng.com/browse/ML-5542).
Assuming controller runs in 1.6.0 is problematic, as we still support the legacy model monitoring without the newer application framework enabled.
If no controller runs are found - don't bump the last_request field of the model endpoint.
> [Model Monitoring] Fix bumping last_request without controller runs

- docs/data-prep/ingest-data-fs.md
- docs/feature-store/end-to-end-demo/01-ingest-datasources.ipynb
- mlrun/feature_store/api.py
- tests/feature-store/test_featureset.py
- tests/feature-store/test_infer.py
- tests/integration/sdk_api/feature_store/test_feature_store.py
- tests/system/feature_store/test_feature_store.py
- tests/system/runtimes/test_nuclio.py
And a few mentions of the older `mlrun.feature_store.api.deploy_ingestion_service()`.
> [Feature Store] Replace calls to deprecated `deploy_ingestion_service_v2()`

- mlrun/model_monitoring/batch.py
- tests/model_monitoring/test_metrics.py
Fixes [ML-5054](https://jira.iguazeng.com/browse/ML-5054).
We divided by zero and multiplied by inf before selecting the elements with `np.where`.
This change masks the arrays first to avoid these unnecessary and warning-producing calculations.
BTW, scipy has a nice utility function `xlogy` that calculates the log and tolerates zeros: [`scipy.special.xlogy`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.xlogy.html#scipy.special.xlogy).
I didn't use it, as this code is in the SDK, and it doesn't list scipy in its requirements.
> [Model Monitoring] Fix "divide by zero" warning in KL divergence metric

- server/api/db/sqldb/db.py
- tests/api/db/test_artifacts.py
The previous implementation of _delete_artifacts_tags gets a list of artifact objects, but then extract their key and deletes all the  tags that belong to artifact with those keys. 
The code should be much more precise and only the specific artifacts chosen should get their tags removed.
Resolves:
https://jira.iguazeng.com/browse/ML-4678
> [Artifacts] Fix tag deletion to target only specified artifacts

- mlrun/execution.py
- mlrun/projects/project.py
If you try to register an artifact from the UI with the same key and tag as an existing artifact it fails uniqueness validation.
However, in the SDK it is possible to log a artifact with key/tag of an existing artifact, and the data itself is overridden
This behavior is OK, but since it is different in the SDK and the UI, this PR adds information on it in the sdk functions' dosctring (for logging artifact / dataset / model).
Resolves https://jira.iguazeng.com/browse/ML-5523
> [Dataset] Document overwriting behavior of `log_dataset`

- mlrun/artifacts/dataset.py
- tests/artifacts/test_dataset.py
[ML-5533](https://jira.iguazeng.com/browse/ML-5533)
This PR adds validation logic to the Dataset initializer method so that only an existing column of a dataframe can be used as a data label.
Such change is beneficial when logging datasets through the SDK.
> [Artifacts] Datasets should only allow an existing column to be used as label

- requirements.txt
- tests/test_requirements.py
Fixes this error
```
>       cur = self.con.cursor()
E       AttributeError: 'Connection' object has no attribute 'cursor'
```
which is caused by pandas refusing to import sqlalchemy because it's below 2.0.0.
https://github.com/pandas-dev/pandas/commit/b57080bf216582454e379a4e702fd7246dfbb8c4#diff-ccd2950d6f16d881f395b22ef38c981ed269b2b1609dd26a9d6e9daf0f78e104R55
> [Requirements] Limit pandas to <2.2 because it requires sqlalchemy 2

- mlrun/projects/pipelines.py
- mlrun/projects/project.py
- mlrun/utils/helpers.py
- tests/projects/test_project.py
Fixes nested paths inside project code path e.g.
```
code_path = ./
workflow_path = src/workflow.py or ./src/workflow.py
```
https://jira.iguazeng.com/browse/ML-5568
> [Project] Improve workflow path validation

- mlrun/model_monitoring/stores/kv_model_endpoint_store.py
- server/api/api/endpoints/operations.py
- server/api/api/endpoints/projects.py
- server/api/api/endpoints/projects_v2.py
- server/api/api/utils.py
- server/api/utils/background_tasks/internal.py
- server/api/utils/singletons/k8s.py
- tests/api/api/test_background_tasks.py
Due to session isolation levels, keeping the same db session results in the verification always failing as it does not know that the project was deleted by a different session. For some reason, this caused mlrun-api-chief container to restart each time a project was deleted.
Along side this fix I also moved the background task addition to the endpoint functions instead of sharing the background tasks object between threads for better thread safety.
> [API] Verify project deletion with new db session

- mlrun/projects/project.py
- tests/integration/sdk_api/artifacts/test_artifacts.py
- tests/projects/test_project.py
Following https://github.com/mlrun/mlrun/pull/4917, we retain existing `spec.db_key` when logging artifacts.
When importing artifacts using `project.import_artifact`, we can set an explicit `new_key`. This `new_key` was set in the artifact's metadata, but not in the spec db_key property, causing artifacts with an existing `db_key` to be saved in the db with it instead of the new key.
In this PR - if `new_key` is given it will overwrite both `metadata.key` and `spec.db_key`.
Fixes https://jira.iguazeng.com/browse/ML-5544
> [Artifacts] Overwrite `spec.db_key` when importing artifact with `new_key` arg

- mlrun/model_monitoring/api.py
This should remove the following deprecation warning from batch-infer:
```
Call to deprecated function (or staticmethod) ingest. ('ingest' will be removed in 1.8.0, use 'FeatureSet.ingest()' instead) -- Deprecated since version 1.6.0.
```
In addition, replace direct usages of `datetime.datetime.now` with `mlrun.utils.datetime_now`.
> [Model Monitoring] Update deprecated ingest usage

- mlrun/model_monitoring/api.py
- tests/model_monitoring/test_monitoring_api.py
Fixes [ML-5566](https://jira.iguazeng.com/browse/ML-5566).
Inference with the `batch_inference` function did not update the "last_request" field of the model endpoint.
It caused issues in model monitoring, as we rely on this field in the windows logic.
The relevant system test passed (`tests/system/model_monitoring/test_app.py::TestRecordResults`).
> [Model Monitoring] Update "last_updated" in `record_results`

- mlrun/model_monitoring/application.py
[ML-5468](https://jira.iguazeng.com/browse/ML-5468)
> [Model Monitoring] raise `MLRunInvalidArgumentError` if the `ModelMonitoringApplicationResult` name didn't match [a-zA-Z_][a-zA-Z0-9_]* format

- tests/api/utils/test_scheduler.py
observed some transient errors on this suite, decided to do some unification with time stamps and usage of datetime now. might not resolve the transient error, but test dates would be accurate wrt timezone
> [CI] Enforce mlrun now on test scheduler

- pyproject.toml
- tests/pytest.ini
Following
- https://github.com/mlrun/mlrun/pull/4479
- https://github.com/mlrun/mlrun/pull/4931
Move all Pytest's related configurations to `pyproject.toml`.
Resolves [ML-5578](https://jira.iguazeng.com/browse/ML-5578).
> [Config] Migrate `pytest.ini` config to `pyproject.toml`

- mlrun/db/base.py
- mlrun/db/nopdb.py
- mlrun/run.py
- server/api/rundb/sqldb.py
- tests/system/datastore/test_v3io.py
- tests/system/logs/test_logs.py
- tests/system/projects/test_project.py
- tests/system/runtimes/test_archives.py
- tests/system/runtimes/test_nuclio.py
putting a list as class attribute field means it is shared across class instances, this is a bug and should not happen
each test creates a class instance, which then means each test deletes all previous projects as well (though they are not found but that is something else).
added `get_pipeline` to base to allow abstraction propagate to autocompletion 
added some log lines for future test cycles
> [CI] Fix some tests

- mlrun/feature_store/retrieval/storey_merger.py
- tests/system/feature_store/test_feature_store.py
Reverts mlrun/mlrun#4989
Fixes `TestFeatureStore::test_ingest_and_query`.
> Revert "[Feature Store] Use timestamp key to get online features"

- server/api/api/endpoints/functions.py
The enrichment is already done in
```
launcher.enrich_runtime(runtime=fn, full=is_nuclio_runtime)
```
For some reason some side feature branch reverted the removal of the enrichment.
Also refactored by method extraction because `_build_function` was over 200 lines...
> [Nuclio] Revert duplicate enrichment on build

- server/api/api/endpoints/pipelines.py
- server/api/crud/pipelines.py
- tests/api/api/test_pipelines.py
[ML-5540](https://jira.iguazeng.com/browse/ML-5540)
When listing runs, MLRun's UI removes the project string from their names to avoid visual repetition and allow for a cleaner list for the end user since the project's name prefixes every run in a project. However, this change is only done to runs explicitly named by the user when triggered. The ones that weren't named keep the project's name on the UI listing.
Despite being reasonable, this frontend-only change creates an unexpected behavior when a user searches for runs using the project name as the query. In such case, all existing project runs will be listed despite, apparently, only the non-named runs having the `project_name` string on their name. In other words, the named runs shouldn't appear since they don't show the project name …
> [Workflows] Disregard project name on named runs while filtering

- server/api/main.py
- tests/api/api/test_artifacts.py
- tests/api/api/test_docs.py
- tests/api/api/test_projects.py
- tests/api/conftest.py
Swagger URL shouldn't be versioned since it docs all versions.
> [API] Change Swagger URL to unversioned API

- server/api/db/sqldb/db.py
- server/api/utils/helpers.py
- tests/api/api/feature_store/test_feature_sets.py
**Bug:**
A feature set has features without any labels.
When adding a feature with the same name and  new labels, the labels are not saved in the database.
**RCA:**
In the DB layer, when we update the feature (in `_update_feature_set_features`) we only look at the `features_to_add`, according to their name.
Since the features already exist on the feature set, we ignore them and don't update their labels.
**Fix:**
Check the existing features labels compared to the "new" feature labels, and update them if needed.
Resolves https://jira.iguazeng.com/browse/ML-5574
> [DB] Update labels for existing features if needed

- mlrun/datastore/targets.py
- mlrun/model.py
- tests/datastore/test_targets.py
[ML-5559](https://jira.iguazeng.com/browse/ML-5559)
Follow up fix for #4967.
> [Datastore] Remove run ID from stream and Kafka target status

- server/api/db/sqldb/db.py
- server/api/runtime_handlers/base.py
https://jira.iguazeng.com/browse/ML-4991
Prefer patch run instead of store run when possible (run exists) so that only given attributes will be updated instead of overriding the full run struct in DB.
> [Monitoring] Fix inconsistent runs overriding

- mlrun/runtimes/daskjob.py
- mlrun/runtimes/function.py
Nuclio and Dask do not support state thresholds. This overrides the default so that when you create a nuclio/dask function you won't have any state thresholds in the spec.
> [Runtimes] Remove default state_thresholds from Nuclio and Dask

- mlrun/datastore/sources.py
- mlrun/kfpops.py
- mlrun/projects/operations.py
- mlrun/projects/project.py
- mlrun/runtimes/function.py
- mlrun/runtimes/serving.py
- tests/serving/test_serving.py
Remove unused dashboard param.
Deprecate it only in `invoke` because it wasn't deprecated there.
> [SDK] Remove nuclio `dashboard` param

- mlrun/model_monitoring/api.py
- mlrun/model_monitoring/helpers.py
- tests/model_monitoring/test_helpers.py
- tests/model_monitoring/test_monitoring_api.py
First introduce #4709.
[ML-5607](https://jira.iguazeng.com/browse/ML-5607)
Now we are updating last request only once in record_result run.
> [Model Monitoring] Fix update\bumping endpoint last_request timestamp when using batch infer

- server/api/db/sqldb/db.py
- tests/api/db/test_runs.py
https://jira.iguazeng.com/browse/ML-5608
Due to race condition it tries to create a label that already exists and gets conflict error. There is no need to create labels if they are not in the updates.
> [SQLDB] Don't update run labels if non given

- server/api/db/sqldb/db.py
We have seen cases where parallel runs with the same "producer_id" are all trying to log artifacts with the same tag simultaneously.
This sometimes caused multiple "latest" tags pointing to artifacts with the same key, iteration and producer id, due to the tagging race conditions.
To avoid that, we want to lock the row of the specific artifacts that are being tagged.
This is done using SQL's "FOR UPDATE" (see [this](https://www.cockroachlabs.com/blog/select-for-update/) for more info).
The artifacts will be locked for the entire transaction, until the session is committed.
Resolves https://jira.iguazeng.com/browse/ML-5596
> [DB] Lock db rows when tagging artifacts

- mlrun/artifacts/base.py
Users should be warned that loading legacy artifacts will not be supported in 2 minor versions.
This ensures each time we load one, we tell the users that they need to save the artifact in the new format.
> [Artifacts] Warn loading legacy artifacts

- mlrun/artifacts/dataset.py
- tests/system/projects/test_project.py
When logging a dataset artifact and uploading to the target path, it was only uploaded if it contained a dataframe.
For other cases, such as where the dataset was an imported parquet file, it was just ignored and wasn't actually uploaded to the data store, causing it to be basically useless.
In this PR, when uploading a dataset we check if the dataframe is set, and if not we try to upload the dataset's body.
Resolves https://jira.iguazeng.com/browse/ML-5613
> [Datasets] Support uploading dataset body when it is not a dataframe

- mlrun/package/utils/_archiver.py
- tests/package/utils/test_archiver.py
- tests/system/projects/assets/create_file_artifact.py
- tests/system/projects/assets/use_artifact.py
- tests/system/projects/test_project.py
The packager saves file artifacts as zip archives.
When zip artifacts are exported and the imported, the files lose their `.zip` suffix, but still remain extractable zip files.
When the packager then tries to unpack these archives, it assumes the files has a `.zip` suffix, and tries to extract them to a directory of the same name (e.g. extract `my-artifact.zip` to `my-artifact` dir). 
The directory creation fails in case the suffix is missing, because a file of the same name already exists.
The simple solution is to just add a random suffix (`datetime.now()`) to the directory name, as it is just a temporary directory. The directory can then be created and the artifacts are usable in the run.
Fixes https://jira.iguazeng.com/browse/ML-5614
> [Packager] Add timestamp to archive directory path for uniqueness

- dockerfiles/mlrun/Dockerfile
As https://github.com/mlrun/mlrun/pull/5042 this is also needed for horovod.
build-essential package include development tools for creating DEB packages from the source code of an application - https://itsfoss.com/build-essential-ubuntu/
Fixes this error:
```
CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
```
> [Images] Add build-essential to mlrun/mlrun

- server/api/api/endpoints/functions.py
Running stuff in fastapi background tasks is occupying the main thread.
This ensures the the background task will not block the API.
> [API] Run `start_function` in threadpool

- tests/system/projects/test_project.py
When registering artifacts during project loading, if the artifact was exported, it will be imported using `import_artifact`.
Following #4970, `import_artifact` overwrites the db_key to the given new key.
This PR aligns `test_load_project_with_artifact_db_key` to the new change.
> [Project] Fix load project with artifacts test

- mlrun/datastore/filestore.py
- mlrun/utils/logger.py
- tests/integration/sdk_api/run/test_main.py
- tests/utils/logger/test_logger.py
Making it a bit faster but the main reason for this change is to enable logging of pydantic structure / arbitrary datetime objects when being logged
> [Logger] Use orjson to dump log lines

- mlrun/model_monitoring/stream_processing.py
Works also on previous nuclio versions.
According to @TomerShor the changes are only when using `V3ioStream`.
[ML-5659](https://jira.iguazeng.com/browse/ML-5659)
> [Model Monitoring] Fix path filtering according to nuclio changes

- server/api/api/endpoints/workflows.py
- tests/api/api/test_workflows.py
When running a workflow, wether to schedule it or not is decided in the client. If a schedule was requested it will be in the workflow spec. This bug was caused by not requesting a schedule and then having the project enriching the workflow which not only adds a schedule the user didn't ask for, but it also fails when the request reaches the worker because the worker doesn't have a scheduler.
This also introduced another issue where a schedule (which is essentially a remote workflow) can start another remote workflow. There is no real reason to support this but the fix is a bit more complex and not worth the risk for 1.6. Will be done in another PR as this will be backported to 1.6.
https://jira.iguazeng.com/browse/ML-5652
> [API] Do not enrich workflow schedule when given spec

- server/api/api/endpoints/jobs.py
- server/api/utils/clients/chief.py
Includes:
1. Validate authorization for both monitoring batch job and monitoring controller APIs.  
2. Add chief re-routing to monitoring batch job API (This API mainly used as part of the batch infer in cases the scheduled job hasn't been deployed through the monitoring basic flow). 
A fix for [ML-5676](https://jira.iguazeng.com/browse/ML-5676)
> [Model Monitoring] Fix monitoring jobs API query permissions 

- docs/monitoring/dashboards/model-monitoring-details.json
- server/api/api/endpoints/grafana_proxy.py
Following #4263 , we encode some of the model endpoint columns before storing the data in the KV table. When querying the table using MLRun API, we decode these columns before returning the results. However, when querying the table using Framsed API, we don't decode the data and as a result the related Grafana dashboard can't parse the encoded values. 
Therefore, in this PR we fix that issue by replacing the Grafana datasource to MLRun API. 
A fix for [ML-5055](https://jira.iguazeng.com/browse/ML-5055).
> [Grafana] Set MLRun API datasource for `Feature Analysis` chart

- mlrun/datastore/targets.py
- mlrun/utils/helpers.py
- tests/datastore/test_targets.py
Improves error when attempting to write too many partitions.
[ML-5622](https://jira.iguazeng.com/browse/ML-5622)
[ML-5677](https://jira.iguazeng.com/browse/ML-5677)
> [Datastore] Fix `ParquetTarget.write_dataframe()` and improve error

- tests/system/model_monitoring/test_app.py
A workaround for [ML-5588](https://jira.iguazeng.com/browse/ML-5588). Add a datetime-based suffix to the project name for uniqueness.
I checked it locally twice and it passed.
> [Tests] Use a unique name for the monitoring app sys test

- mlrun/datastore/targets.py
- mlrun/utils/helpers.py
- tests/datastore/test_targets.py
Improves error when attempting to write too many partitions.
[ML-5622](https://jira.iguazeng.com/browse/ML-5622)
[ML-5677](https://jira.iguazeng.com/browse/ML-5677)
Cherry-pick of #5073 / f1d4631.
> [Datastore] Fix `ParquetTarget.write_dataframe()` and improve error [1.6.x]

- server/api/crud/model_monitoring/model_endpoints.py
port from #5068
(cherry picked from commit ea5d6ad31f2d50997cf859c129d6e346cb725042)
> [Model Monitoring] Saving feature_stats as empty dict and not as null in the model_endpoint [1.6.x]

- tests/system/model_monitoring/test_app.py
Backport #5067 to 1.6.x.
This should fix the `tests/system/model_monitoring/test_app.py::TestMonitoringAppFlow::test_app_flow` system test failures also on the 1.6.x branch.
https://github.com/mlrun/mlrun/actions/runs/7781461481/job/21228976349#step:9:1362
> [Tests] Use a unique name for the monitoring app sys test [1.6.x]

- server/api/crud/projects.py
As written on code, nuclio first delete CRDs, then its controller is triggered to delete the runtime resources. In order to ensure project directory is safely deleted, mlrun needs for nuclio resources to get deleted before it continues
https://jira.iguazeng.com/browse/ML-5588
> [Project] Ensure nuclio function pods are deleted

- mlrun/config.py
- server/api/crud/model_monitoring/deployment.py
[ML-5700](https://jira.iguazeng.com/browse/ML-5700)
Cherry-pick of #5105 / d5b0fc2.
> [Model Monitoring] Fix server-side nuclio version resolution in explicit ack switch [1.6.x]

- tests/system/model_monitoring/test_app.py
[ML-5588](https://jira.iguazeng.com/browse/ML-5588) is fixed, and the same project name works when running this system test multiple times - verified.
> [Tests] Remove unique project name suffix

- mlrun/model_monitoring/api.py
- mlrun/model_monitoring/features_drift_table.py
- tests/model_monitoring/test_features_drift_table.py
Fixes [ML-5265](https://jira.iguazeng.com/browse/ML-5265).
This change covers two cases:
- Extra features in the inputs (current data), as in the original issue.
- Missing keys, e.g. "mean", from existing features in the inputs. This happens when there's a placeholder for a label, but a new label name is used.
> [Model Monitoring] Improve the error messages in drift table creation

- mlrun/serving/routers.py
Wrong reference was introduced in #5018 and cherry-picked to 1.6.x in #5131.
[ML-5728](https://jira.iguazeng.com/browse/ML-5728)
Cherry-pick of #5137 / c67c84a.
> [Serving] Fix reference to nonexistent field

- mlrun/config.py
- server/api/api/endpoints/projects.py
When deleting a project, the project deletion in Nuclio takes some time to start, and even after Nuclio deletes the functions' deployment, it might take some time for the actual function pods to be deleted (due to kubernetes' graceful termination, which defaults to 60s).
Thus, increasing the timeout for project and function pods deletion verification from a minute to 5 minutes
Fixes https://jira.iguazeng.com/browse/ML-5758
> [Project] Increase nuclio project deletion verification timeout

- server/api/utils/projects/follower.py
long lived db session might stale during project creation with anomaly of mysql reject due to `BrokenPipeError`
fixes https://jira.iguazeng.com/browse/ML-5764
In addition to that, remove the old way of committing. anyway we create a new db session that would have the newly committed project to get on
> [Project] Fix project creation in foreground

- mlrun/common/db/sql_session.py
- mlrun/config.py
It has been observed that not using mlrun for very long of period forcing mysql to stale the connection, later on discovering it while using connection to perform db operations. this pr ensure sqlalchemy recycle the connection pool in a default of 1 hour + perform a pre-ping prior using the connection to perform db operation
https://jira.iguazeng.com/browse/ML-5772
> [SQLAlchemy] Recycle & ping connection prior using them

- mlrun/projects/project.py
- tests/projects/test_project.py
If a `project.yml` file exists, there is no reason for `mlrun.load_project` to fail.
As an improvement, support both `yaml` and `yml` extensions for project and function files.
> [Project] Support loading project from files with both `yaml` and `yml` extensions

- server/api/crud/runtimes/nuclio/function.py
If the project doesn't exist than something else went wrong.
When mlrun is not leader, nuclio will go to the leader to create the project but the project already exists there so it will fail.
> [Nuclio] Disable project creation on deploy

- docs/cli.md
- docs/conf.py
`&minus;` is not rendered correctly by latex. It can be configured but it is ultimately a misuse of math characters in text.
https://tex.stackexchange.com/questions/482100/inputenc-unicode-character-not-set-up-for-use-with-latex
So to fix that, I escaped the 1st minus sign where lines start with double hyphen and disabled smartquotes. It seems to have done the job (see `--name` compared to --project`) without any noticeable side effects.
> [Docs] Disable smartquotes and fix double hyphens rendering

- tests/system/datastore/test_v3io.py
Skipping test_v3io_large_object_upload as it hangs when running against the CI system. ML-5598
> [Tests] skipping test_v3io_large_object_upload as it hangs when running against the CI system

- server/api/initial_data.py
- tests/api/db/test_artifacts.py
We noticed that when migrating the artifacts table to the new v2 table, the new artifacts are saved with the `key` taken from `metadata.key` only.
However, some artifacts have different `db_keys`, meaning the key they are saved with in the DB can be different then the value in `metadata.key`.
Since we want to be backwards compatible, we want to persist the original key in the DB, **with a caveat**:
Artifacts from a hyper param run, with iterations, had a key in the DB that was a concatenation `{iter}-{key}`. We do not persist this behavior, but remove the `iter` part of the key, and save the iteration in a different column.
This should not affect reading/listing artifacts with iterations, as this concatenation was done behind the scenes.
Resolves https://jira.iguazeng.com/browse/ML-5799
> [Artifacts] Persist db key when migrating to artifact v2 table

- mlrun/model_monitoring/features_drift_table.py
- tests/model_monitoring/test_features_drift_table.py
Fixes [ML-5790](https://jira.iguazeng.com/browse/ML-5790).
Before this PR, the histogram in plotly artifact suffered from two issues:
1. Background didn't match the scatter line:
2. "Input" (current) data could be outside of the original range but was not shown:
Now the histograms are presented with bars, and the ±∞ bins are accounted for:
> [Model Monitoring] Fix plotly artifact histogram

- mlrun/utils/helpers.py
- requirements.txt
No need to force anyio on mlrun when it comes to sending notification. asyncio is good enough here
> [Utils] Use asyncio instead of anyio

- mlrun/serving/server.py
[ML-5801](https://jira.iguazeng.com/browse/ML-5801)
Fixes error(*) introduced in #4724. It turns out that model monitoring doesn't use storey at all (which also explains why `V2ModelServer` doesn't use any of storey's facilities). #4724 didn't take this into account.
Fixes `TestMonitoringAppFlow::test_app_flow` and other model monitoring tests, as well as `TestProject::test_local_cli` and `TestArchiveSources::test_serving_deploy`.
(*) The actual error as it occurs in the pod:
```
File "/opt/nuclio/_nuclio_wrapper.py", line 151, in serve_requests
await self._handle_event(event)
File "/opt/nuclio/_nuclio_wrapper.py", line 441, in _handle_event
entrypoint_output = await entrypoint_output
File "/opt/conda/lib/python3.9/site-packages/mlrun/serving/server.py", line 394, in …
```
> [Model Monitoring] Fix to use sync handler

- tests/system/model_monitoring/test_model_monitoring.py
See [ML-5820](https://jira.iguazeng.com/browse/ML-5820) for reference.
They pollute the test results and hide important failures of maintained tests. Ultimately, one should address them and fix them accordingly. Skipping for the time being.
> [Model Monitoring] Skip 3 chronically failing system tests
