mlrun/mlrun

mlrun/feature_store/retrieval/spark_merger.py, tests/system/feature_store/test_spark_engine.py
[ML-3421](https://jira.iguazeng.com/browse/ML-3421)
=> [Feature Store] Fix Spark asof join returns wrong results

docs/runtimes/dask-mlrun.ipynb
updating api calls (set_worker_request)
=> [Docs] Update runtimes dask-mlrun

mlrun/feature_store/retrieval/__init__.py, tests/api/runtimes/test_spark.py
[ML-3280](https://jira.iguazeng.com/browse/ML-3280)
=> [Feature Store] Improve error message on unknown merger

mlrun/api/utils/db/mysql.py
even tho the input is hard-coded, fix the query for generative security reports
=> [SQL] Fix query for sqllite to be more safe

mlrun/feature_store/feature_set.py, tests/system/feature_store/test_spark_engine.py
[ML-2896](https://jira.iguazeng.com/browse/ML-2896)
=> [Feature Store] Fix sqr and stdvar aggregations in spark with `EmitEveryEvent`

docs/tutorial/05-model-monitoring.ipynb
Add pip install tqdm line in notebook beginning.
[ML-3439](https://jira.iguazeng.com/browse/ML-3439)
=> [Docs] Fix tqdm import failure

requirements.txt, tests/test_requirements.py
[ML-3299](https://jira.iguazeng.com/browse/ML-3299)
=> [Requirements] Bump storey and v3io-frames versions

mlrun/runtimes/base.py
https://jira.iguazeng.com/browse/ML-3078
=> [Run] Add error message when weren't able to resolve status of run due to unexisting runtime resource 

mlrun/feature_store/api.py, tests/system/feature_store/test_feature_store.py, tests/system/feature_store/test_spark_engine.py
[ML-3225
](https://jira.iguazeng.com/browse/ML-3225
)
Main changes on api.py in ingest function and on test_spark_engine in  test_ingest_with_steps_drop_features function.
=> [Feature Store] Fix ingestion with a DropFeatures(entity) step to return an error

requirements.txt, tests/test_requirements.py
Resolve https://issues.apache.org/jira/browse/ARROW-16838 bug that is triggered by ingest ([ML-3299](https://jira.iguazeng.com/browse/ML-3299))
=> [Requirements] Require pyarrow version 10

mlrun/datastore/targets.py, mlrun/feature_store/api.py
[ML-3403](https://jira.iguazeng.com/browse/ML-3403)
=> [Feature Store] Fix Error on Spark ingestion with offline target without defined path (set resource for default path)

requirements.txt, tests/test_requirements.py
Fixing due to rust incompatibility on some images will be tackled upon need.
=> [Security] Relief cryptography to allow latest security updates

dockerfiles/jupyter/requirements.txt, requirements.txt, tests/test_requirements.py
nuclio jupyter ipython bump - https://github.com/nuclio/nuclio-jupyter/pull/166
https://jira.iguazeng.com/browse/ML-3463
=> [Requirements] Bump `ipython` and `nuclio-jupyter`

.github/workflows/build.yaml, .github/workflows/release.yaml, .github/workflows/system-tests-enterprise.yml, .github/workflows/system-tests-opensource.yml
=> [CI] Move github input to envvar

mlrun/feature_store/steps.py, tests/system/feature_store/test_spark_engine.py
[ML-3414](https://jira.iguazeng.com/browse/ML-3414)
=> [Feature Store] Fix spark implementation of `DateExtractor`

mlrun/api/db/sqldb/db.py, mlrun/config.py, mlrun/datastore/sources.py, mlrun/runtimes/base.py, mlrun/runtimes/daskjob.py, mlrun/utils/helpers.py
Fix - https://jira.iguazeng.com/browse/ML-3477
=> [Run] Fix throwing a warning when running a function that contains handler with `_`

mlrun/datastore/targets.py
[ML-3398](https://jira.iguazeng.com/browse/ML-3398)
=> [Datastore] Propagate authentication from RedisNoSqlTarget to RedisStore

go/pkg/services/logcollector/server.go, mlrun/api/main.py
Improve logging for a better debugging experience:
- Remove redundant, spammy logs
- Add logs to `HasLogs` endpoint
- Add error stack to wrapped errors
- API: log run UIDs instead of entire runs in periodic functions
=> [Log Collector] Improve logging

mlrun/datastore/datastore.py
a fix for: [ML-3344](https://jira.iguazeng.com/browse/ML-3344)
Add support for all drivers a-z
=> [Datastore] Add support for all drivers

mlrun/feature_store/common.py
=> [Docs] improve description of watch parameter in RunConfig

docs/install.md
=> [Docs] update client-server backward compatibility description

mlrun/data_types/infer.py, mlrun/data_types/spark.py
[ML-2641](https://jira.iguazeng.com/browse/ML-2641)
=> [Feature Store] Log a warning when entity type is changed

mlrun/runtimes/remotesparkjob.py
pip introduced a new resolver that fixes resolving underlying dependencies.
the default spark base image comes with pip 20.2.4 which doesn't have the fix.
https://pip.pypa.io/en/stable/news/#id376 - Switch to the new dependency resolver by default.
=> [Spark] Upgrade pip when building default image

mlrun/execution.py, tests/common_fixtures.py, tests/run/test_run.py
related to https://github.com/mlrun/mlrun/pull/3198
=> [Test] Update run from context

tests/datastore/test_base.py
follow up to: https://github.com/mlrun/mlrun/pull/3173
Adding test coverage
=> [Datastore] Add test for schema_to_store

dependencies.py, extras-requirements.txt, tests/test_requirements.py
And relax upper bound.
[ML-3478](https://jira.iguazeng.com/browse/ML-3478)
=> [Requirements] Fix `google-cloud-bigquery` by adding `bqstorage`

.github/workflows/system-tests-enterprise.yml, automation/requirements.txt, automation/system_test/prepare.py
Bumped some deps, fixed resolving iguazio version, fetch s3 locally then upload to datanode using aws creds
=> [CI] Fixed system test fetching provctl from s3

go/pkg/services/logcollector/logcollector_test.go, go/pkg/services/logcollector/server.go
and improve retry, reduce spammy logs
=> [LogCollector] Ensure directory prior to has logs

docs/projects/create-project.md, examples/load-project.ipynb, mlrun/projects/project.py
`The user needs to add those line and run one push command before he tries to run project.push`
https://jira.iguazeng.com/browse/ML-3043
Note that if the branch is up to date the user will still be prompted for username and password but the push will pass with `Everything up-to-date`
=> [Project] Fix git push warning message

mlrun/runtimes/base.py, tests/system/runtimes/assets/kubejob_function_custom_requirements.py, tests/system/runtimes/assets/requirements.txt, tests/system/runtimes/test_kubejob.py
Added system test to cover providing requirements from file / specifics
=> [Runtimes] Ignore comments on provided requirements file

tests/system/projects/test_project.py
Fix failed system test:
https://github.com/mlrun/mlrun/actions/runs/4370121538/jobs/7645021878#step:7:3846
=> [Tests] Fix system test `test_remote_workflow_source` assertion

mlrun/datastore/targets.py, tests/system/feature_store/test_spark_engine.py
[ML-3504](https://jira.iguazeng.com/browse/ML-3504)
=> [Datastore] Fix Spark ingest to Redis with numeric index

mlrun/datastore/targets.py
[ML-3453](https://jira.iguazeng.com/browse/ML-3453)
=> [Data Store] Fix raise `SQLTarget` don't support aggregation

mlrun/projects/project.py
https://jira.iguazeng.com/browse/ML-3574
=> [Project] Add workflows getter and setter

mlrun/runtimes/__init__.py, mlrun/runtimes/base.py, tests/run/test_run.py
https://jira.iguazeng.com/browse/ML-1577
the test is not related to change and was written as part of debugging
=> [Run] Warn artifact path is local and no volume mounts

examples/load-project.ipynb, examples/mlrun_dask.ipynb, examples/mlrun_export_import.ipynb, examples/mlrun_jobs.ipynb, examples/mlrun_sparkk8s.ipynb, examples/mlrun_vault.ipynb
NewTask task was removed and now we use new_task instead
=> [Examples] Replace removed `NewTask` with `new_task`

docs/tutorial/01-mlrun-basics.ipynb
https://jira.iguazeng.com/browse/ML-3445
=> [Demos] Deploy with python 3.9

mlrun/execution.py, tests/run/test_run.py
https://jira.iguazeng.com/browse/ML-3599
=> [Execution] Fix setting state to error

mlrun/api/db/sqldb/db.py, mlrun/artifacts/manager.py, mlrun/utils/helpers.py, mlrun/utils/regex.py, tests/api/api/test_artifacts.py, tests/utils/test_helpers.py
fix for: https://jira.iguazeng.com/browse/ML-2421
=> [Artifact] Add validation to artifact name to not contain slashes

tests/system/feature_store/test_spark_engine.py
This test is unstable, so I added several logs to it for better understand what happens when it fails. ([ML-3587](https://jira.iguazeng.com/browse/ML-3587))
=> [Tests] Add logs to TestFeatureStoreSparkEngine::test_as_of_join_result 

.github/workflows/system-tests-opensource.yml
=> [CI] Increase open source tests timeout

tests/system/model_monitoring/test_model_monitoring.py
Each model monitoring system test in `tests.system.model_monitoring.test_model_monitoring.py` creates a new project at the beginning of the test and deletes it at the end of that test. Until now, all of the monitoring system tests were defined under the same `TestMLRunSystem` object with the same project name: `model-monitor-sys-test4`. 
This behaviour can cause issues when the resources of one of the projects are still being deleted while the resources of a new project are being processed. In addition, using the same project name for all of the monitoring tests complicates the debugging process. 
Therefore, in this PR we split the main tests into different `TestMLRunSystem` objects with different project names:
- `TestModelEndpointsOperations`: Apply basic model endpoint CRUD operations …
=> [Model Monitoring] Split monitoring tests into different projects

mlrun/config.py, mlrun/db/httpdb.py, tests/rundb/test_httpdb.py
https://jira.iguazeng.com/browse/ML-3653
=> [HTTPDB] Replace invalid utf-8 characters on watch logs

dockerfiles/README.md, docs/cli.md, docs/install/compose.with-jupyter.yaml, docs/install/compose.yaml, docs/projects/ci-integration.md, docs/runtimes/images.md, hack/local/README.md, hack/local/mljupy.yaml, hack/local/mlrun-local.yaml, hack/mlrun-all.yaml, hack/mlrunapi.yaml, hack/mlrunui.yaml
=> [Docs] Bump MLRun Versions For Release

mlrun/execution.py, tests/run/test_run.py
a fix for: https://jira.iguazeng.com/browse/ML-3633
=> [Context] Fix failed to import a context from dict

mlrun/api/crud/pipelines.py, mlrun/db/httpdb.py
relates to - https://github.com/mlrun/mlrun/pull/1809
https://jira.iguazeng.com/browse/ML-3638
=> [API] Allow sorting pipelines when specifying project

dockerfiles/models/Dockerfile
(cherry picked from commit b44bc18b620cd20c889c24b3520f71c82e638c5d)
=> [Models] Set CFLAGS before requirements installation [1.3.x]

mlrun/projects/project.py, tests/projects/test_project.py
backport for (#3287) 
https://jira.iguazeng.com/browse/ML-3679
=> [Project] Fix function name isn't treated uniformly [1.3.x]

.github/actions/image-matrix-prep/action.yaml, .github/workflows/build.yaml, .github/workflows/security_scan.yaml, Makefile, automation/scripts/github_workflow_free_space.sh, go/Makefile
Allow running grype (except for ml-models-gpu, which are too heavy for github action) using dispatch workflow
=> [CI] Security scan github action

docs/change-log/index.md
(cherry picked from commit a8a47df30139de19f39721c937f1fbe4308e6c92)
=> [Docs] Fix mlrun 1.3.0 client installation guide [1.3.x]

.github/workflows/ci.yaml
(cherry picked from commit 245649a4cb185b047062710195964e4ab0fa58d0)
=> [CI] Trigger CI on pull request against `feature/` branches (#3345)

mlrun/api/api/deps.py, mlrun/api/schemas/constants.py, tests/api/test_api_states.py
https://jira.iguazeng.com/browse/ML-3678
=> [API] Reflect correct message wen waiting for chief [1.3.x]

mlrun/serving/states.py
[ML-3654](https://jira.iguazeng.com/browse/ML-3654)
=> [Serving] Fix initialization of graph steps in error flow

tests/api/test_api_states.py
healthz now returns service unavailable when worker is waiting for cheif
=> [Test] Fix API states healthz status code

mlrun/runtimes/kubejob.py, mlrun/runtimes/local.py, mlrun/runtimes/sparkjob/abstract.py, tests/api/runtimes/test_kubejob.py
need to add the clone target dir to the spark code path
=> [Spark] Fix resolving code path

mlrun/builder.py, mlrun/runtimes/base.py, mlrun/runtimes/daskjob.py, mlrun/runtimes/function.py, mlrun/runtimes/kubejob.py, mlrun/runtimes/local.py, mlrun/runtimes/mpijob/abstract.py, mlrun/runtimes/mpijob/v1.py, mlrun/runtimes/pod.py, mlrun/runtimes/remotesparkjob.py, mlrun/runtimes/serving.py, mlrun/runtimes/sparkjob/abstract.py, mlrun/runtimes/sparkjob/spark3job.py, tests/api/runtimes/test_spark.py, tests/runtimes/test_run.py, tests/test_builder.py
(cherry picked from commit ee62334e8e0df66757cccb915dc733f904b48aa4)
=> [Runtimes] Fix workdir and source target dir [1.3.x]

mlrun/runtimes/kubejob.py, mlrun/runtimes/local.py, mlrun/runtimes/sparkjob/abstract.py, tests/api/runtimes/test_kubejob.py
(cherry picked from commit b948c1dba5fb85f58ddfbdcb7fac4fad0654eaa8)
=> [Spark] Fix resolving code path [1.3.x]

docs/change-log/index.md
Repair link to Logging data using `hints`
=> [Docs] Repair reference

mlrun/runtimes/local.py, tests/runtimes/assets/verbose_stderr.py, tests/runtimes/test_local.py
[ML-3710](https://jira.iguazeng.com/browse/ML-3710)
=> [Runtimes] Avoid hang on large stderr output in `run_exec`

.github/workflows/release.yaml
Adding update-tutorials step to release tutorials tar
=> [CI] Publish tutorials tarball asset on releases

mlrun/serving/server.py
Reduced the log size for the "Run Dockerized Tests" stage from 95MB to 18MB.
=> [Serving] Fix 200x logging in CI (and potentially elsewhere)

mlrun/datastore/targets.py, tests/system/feature_store/test_spark_engine.py
[ML-3443](https://jira.iguazeng.com/browse/ML-3443)
=> [Spark] Support more than 2 keys in spark online target ingestion engine

mlrun/runtimes/base.py, mlrun/runtimes/kubejob.py
Continuous of https://github.com/mlrun/mlrun/pull/3385
=> [Runtimes] Adjust `require_build` logic to include new requirements attribute

mlrun/serving/routers.py, mlrun/serving/states.py
Process executer in ParallelRun is failing due to serialization error.
Also change global routes - not shared between process.
[ML-3720](https://jira.iguazeng.com/browse/ML-3720)
=> [Serving] Fix process executer in ParallelRun 

.github/workflows/system-tests-enterprise.yml, automation/system_test/prepare.py, tests/system/conftest.py
=> [CI] Backport #3401 and #3393

mlrun/__main__.py
Fixes https://github.com/mlrun/mlrun/pull/2934
=> [MLRun] Fix use of json instead of simplejson

mlrun/api/main.py, mlrun/utils/notifications/notification_pusher.py
no need to log when no notifications / runs are available
=> [API] Reduce spammy logs

mlrun/serving/routers.py
(cherry picked from commit 8c9d84470938bad62b2398df2b188f98d08d6424)
=> [Serving] Fix process executer in ParallelRun [1.3.x]

mlrun/datastore/spark_udf.py, mlrun/datastore/targets.py, tests/system/feature_store/test_spark_engine.py
Cherry-pick 156821f9 from development
=> [Spark] Fix UDF - remove dependencies [1.3.x]

mlrun/builder.py, mlrun/db/filedb.py, tests/test_builder.py
https://jira.iguazeng.com/browse/ML-3743
=> [Builder] Fix pushing to ECR [1.3.x]

tests/system/feature_store/test_spark_engine.py
```
tests/system/feature_store/test_***_engine.py::TestFeatureStoreSparkEngine::test_get_offline_features_with_filter_and_indexes[None]
FAILED tests/system/feature_store/test_***_engine.py::TestFeatureStoreSparkEngine::test_get_offline_features_with_filter_and_indexes[timestamp]
FAILED tests/system/feature_store/test_***_engine.py::TestFeatureStoreSparkEngine::test_relation_join[inner-True]
FAILED tests/system/feature_store/test_***_engine.py::TestFeatureStoreSparkEngine::test_relation_join[inner-False]
FAILED tests/system/feature_store/test_***_engine.py::TestFeatureStoreSparkEngine::test_relation_join[outer-True]
FAILED tests/system/feature_store/test_***_engine.py::TestFeatureStoreSparkEngine::test_relation_join[outer-False]
FAILED …
```
=> [Tests] Fix spark system tests

tests/system/feature_store/test_spark_engine.py
(cherry picked from commit 69a4ea46e82edc34665569577ca07f701ddd3fff)
=> [Tests] Fix spark system tests [1.3.x]

mlrun/config.py, mlrun/datastore/store_resources.py, mlrun/datastore/targets.py, mlrun/platforms/iguazio.py, mlrun/serving/states.py, tests/test_config.py
https://jira.iguazeng.com/browse/ML-3652
=> [DataStore] Enrich `V3ioDriver` with `mlconf.v3io_api`

mlrun/config.py, mlrun/datastore/store_resources.py, mlrun/datastore/targets.py, mlrun/platforms/iguazio.py, mlrun/serving/states.py, tests/test_config.py
(cherry picked from commit 90391e0d91ca0d40da4db425e29d096a54b8715f)
=> [DataStore] Enrich `V3ioDriver` with `mlconf.v3io_api` [1.3.x]

mlrun/feature_store/api.py, mlrun/feature_store/feature_set.py
[ML-3628](https://jira.iguazeng.com/browse/ML-3628)
=> [Feature Set] Fix ingest to raise error when user did not provide targets and called set_targets with_default=False

mlrun/api/api/endpoints/healthz.py, mlrun/errors.py, tests/api/api/test_healthz.py, tests/api/test_api_states.py
backport of https://github.com/mlrun/mlrun/pull/3344 to 1.3.x
https://jira.iguazeng.com/browse/ML-3678
=> [API] Fail `healthz` requests when offline / waiting for chief [1.3.x]

mlrun/feature_store/api.py, mlrun/feature_store/feature_set.py
(cherry picked from commit d8adcfd26555ad9eab507f87d13a78f32d124bf7)
=> [Feature Set] Fix ingest to raise error when user did not provide targets and called set_targets with_default=False [1.3.x]

mlrun/serving/__init__.py, mlrun/serving/states.py, tests/serving/test_async_flow.py, tests/serving/test_flow.py
(cherry picked from commit 7a308ddc313df3647541dc39d582d77b608c80ec)
=> [Serving] Graph/Step custom error-handler - fix bug and provide cleaner api

mlrun/api/api/endpoints/healthz.py
backporting https://github.com/mlrun/mlrun/pull/3445 to 1.3.x
https://jira.iguazeng.com/browse/ML-3772
=> [API] Add version to healthz endpoint [1.3.x]

docs/store/datastore.md, mlrun/datastore/sources.py
Related to [ML-3745](https://jira.iguazeng.com/browse/ML-3745)
=> [Datastore] Improve `BigQuerySource` documentation to cover credentials

mlrun/datastore/sources.py, mlrun/feature_store/api.py, mlrun/feature_store/feature_set.py, mlrun/feature_store/ingestion.py, tests/system/feature_store/test_google_big_query.py
[ML-3759](https://jira.iguazeng.com/browse/ML-3759)
Includes the following related fixes and improvements to get the `TestFeatureStoreGoogleBigQuery` test suite to pass:
* Fix `BigQuerySource` tests
* Validate that a source supports storey when using storey engine
* Validate that `chunksize` is a multiple of `max_results_for_table`
* Fix `return_df`
* Fix "in case of multiple chunks only return the first chunk" behaviour – return all data instead
* Enforce `rows_limit`
* Related refactoring
=> [Feature Store] Fix `BigQuerySource` support for passthrough+`chunksize`

mlrun/datastore/sources.py, mlrun/feature_store/api.py, mlrun/feature_store/feature_set.py, mlrun/feature_store/ingestion.py, tests/system/feature_store/test_google_big_query.py
[ML-3759](https://jira.iguazeng.com/browse/ML-3759)
1.3.x backport of #3449 / be51376.
=> [Feature Store] Fix `BigQuerySource` support for passthrough+`chunksize` [1.3.x]

docs/tutorial/01-mlrun-basics.ipynb
(cherry picked from commit f1d4a543d117cc87b09ebc733b3e4bd3d7e4ceb5)
=> [Docs] Backport Fix tutorials sklearn bump version  [1.3.x]

automation/deployment/README.md, automation/deployment/deployer.py, automation/system_test/prepare.py
Moved the sqlite values to the correct method
=> [Automation] Refactor CE Deployer Script

mlrun/datastore/spark_udf.py
https://jira.iguazeng.com/browse/ML-3788
=> [Spark] Fix treating single string entity as a list when saving to Redis

mlrun/model_monitoring/constants.py, mlrun/model_monitoring/stores/kv_model_endpoint_store.py
Backport for:
- [Model Monitoring] Fix BC issue when deleting a model endpoint from KV: #3482
=> [Model Monitoring] Fix BC issue when deleting a model endpoint from KV [1.3.x]

requirements.txt, tests/test_requirements.py
(cherry picked from commit 1ace8ddee7883b698e7646e788fef3f63cb3dd84)
=> [Requirements] Blacklist orjson 3.8.12 [1.3.x]

mlrun/api/crud/projects.py, mlrun/api/db/sqldb/db.py, mlrun/api/utils/clients/iguazio.py, mlrun/api/utils/helpers.py, mlrun/api/utils/projects/remotes/nop_follower.py, mlrun/common/schemas/project.py, mlrun/db/httpdb.py, tests/api/db/test_projects.py, tests/api/utils/clients/test_iguazio.py
Ports https://github.com/mlrun/mlrun/pull/3477
=> [Projects] Minimal Project Response and Request Iguazio Projects Separately During Sync

requirements.txt, tests/test_requirements.py
(cherry picked from commit 1ace8ddee7883b698e7646e788fef3f63cb3dd84)
=> [Requirements] Blacklist orjson 3.8.12 (#3496)

mlrun/api/utils/clients/log_collector.py, tests/api/utils/clients/test_log_collector.py
Has logs in the log collector can fail on parallel access to the project's log directory, or other retryable failures/
In such cases, we do not want to raise an exception, but to return an empty byte string from `get_logs`, so the caller will retry on the request.
=> [Log Collector] Has logs - don't raise exception on retryable errors

mlrun/api/api/endpoints/artifacts.py, mlrun/api/db/sqldb/db.py
https://github.com/mlrun/mlrun/pull/3514 for 1.2.x
=> [API] Kill spammy line [1.2.x]

mlrun/api/crud/projects.py, mlrun/api/db/sqldb/db.py, mlrun/api/schemas/project.py, mlrun/api/utils/clients/iguazio.py, mlrun/api/utils/helpers.py, mlrun/api/utils/projects/remotes/nop_follower.py, mlrun/db/httpdb.py, tests/api/db/test_projects.py, tests/api/utils/clients/test_iguazio.py
=> [Projects] Minimal Project Response and Request Iguazio Projects Separately During Sync [1.3.x]

mlrun/api/utils/clients/log_collector.py, tests/api/utils/clients/test_log_collector.py
=> [Log Collector] Has logs - don't raise exception on retryable errors [1.3.x]

mlrun/feature_store/api.py
Fixes `TestFeatureStore::test_sync_pipeline_chunks[True]`
=> [Feature Store] Fix `ingest()` local namespace resolution

mlrun/projects/project.py, tests/system/projects/test_project.py
Use workflow of project instead of assets
related PR - https://github.com/mlrun/project-demo/pull/14
=> [Test] Fix workflow file of system test

mlrun/feature_store/api.py, mlrun/utils/helpers.py
Note: #3532 fixes the kind of bug that would be avoided by this new implementation.
=> [Utils] Improve `get_caller_globals` to avoid future bugs

mlrun/api/db/sqldb/db.py, mlrun/api/utils/clients/iguazio.py, mlrun/api/utils/projects/leader.py
=> [API] Reduce spammy logging

tests/api/db/test_hub.py, tests/integration/sdk_api/hub/test_hub.py
Add more in-depth testing for #3536
=> [DB] Test HubSource kind migrations

mlrun/api/schemas/model_endpoints.py, tests/system/model_monitoring/test_model_monitoring.py
Backport for:
- [Model Monitoring] Fix error-count by converting it's value to int before writing endpoint to DB: #3520
=> [Model Monitoring] Fix error-count by converting it's value to int before writing endpoint to DB [1.3.x-next]

mlrun/api/api/endpoints/runs.py, mlrun/api/crud/runs.py, mlrun/api/db/sqldb/db.py
Another round, less spammy logs
=> [API] Remove more spammy log lines [1.2.x]

mlrun/api/api/endpoints/feature_store.py, mlrun/api/api/utils.py, mlrun/api/db/sqldb/db.py, mlrun/common/schemas/tag.py, mlrun/db/sqldb.py
Following #3461 - Fixing duplicate schemas in type hints unions.
=> [Schemas] Remove duplicates from typing hints

mlrun/api/api/endpoints/functions.py, mlrun/api/crud/runs.py
=> [API] Remove more spammy log lines [1.3.x]

mlrun/api/api/endpoints/functions.py, mlrun/api/api/endpoints/runs.py, mlrun/api/crud/runs.py, mlrun/api/db/sqldb/db.py
https://github.com/mlrun/mlrun/pull/3548 for development
=> [API] Remove more spammy log lines

mlrun/launcher/local.py, tests/common_fixtures.py, tests/launcher/__init__.py, tests/launcher/assets/sample_function.py, tests/launcher/test_factory.py, tests/launcher/test_local.py, tests/launcher/test_remote.py
Server side and more in-depth tests are in progress
=> [Launcher] Unit tests and fixes

mlrun/datastore/sources.py
Backport for:
- [Datastore] Fix HttpSource initialization: #3559
=> [Datastore] Fix HttpSource initialization [1.3.x-next]

tests/rundb/test_httpdb.py
fails locally, increasing the timeout solves the problem.
=> [Tests] Increase dockerized tests timeout

mlrun/projects/project.py, mlrun/runtimes/pod.py, tests/projects/test_project.py, tests/runtimes/test_run.py
https://jira.iguazeng.com/browse/ML-3381
In addition, this PR includes a fix to the set_envs method.
=> [Projects] Fix file validation when set secrets or set envs 

mlrun/db/httpdb.py
To allow clients be forward compatible with newer formats supported by api
=> [HTTPDB] Do not enforce format

.github/workflows/system-tests-enterprise.yml, automation/system_test/prepare.py
add dev_utilities script that  uninstall and install (redis, kafka, and mysql)  using  helm
=> [CI] Add setup install fs required services script

mlrun/api/main.py, mlrun/api/utils/singletons/k8s.py, mlrun/config.py
Expose configuration to be used when running local mlrun api against remote db / k8s cluster and etc
=> [API] Prepare some configuration for local debugging

mlrun/api/utils/singletons/k8s.py, mlrun/config.py
follow up fixes pr for https://github.com/mlrun/mlrun/pull/3578
=> [API] Prepare some configuration for local debugging follow up

mlrun/api/launcher.py, mlrun/launcher/base.py, mlrun/launcher/client.py, mlrun/launcher/local.py, mlrun/launcher/remote.py, mlrun/projects/pipelines.py, mlrun/run.py, mlrun/runtimes/base.py, mlrun/runtimes/kubejob.py, tests/launcher/test_remote.py
Move `verify_base_image` to the launchers since it is only relevant in the client scope.
=> [Launcher] Prepare image for deploy

.github/workflows/system-tests-enterprise.yml
=> [CI] Move `IP_ADDR_PREFIX` to prepare run

tests/system/projects/test_project.py
=> [Test] Fix workflow file of system test [1.3.x]

mlrun/serving/states.py
[ML-3835](https://jira.iguazeng.com/browse/ML-3835)
=> [Servnig] Fix plot when before param exists.

mlrun/feature_store/api.py, mlrun/feature_store/feature_set.py, tests/system/feature_store/test_feature_store.py
(#3583)
(cherry picked from commit 94496af500a0dc0b9de361ff0819e2b045f5b229)
=> [Feature Set] Fix set_targets to overwrite the existing targets and allow no-target ingest if running locally [1.3.x-next]

automation/requirements.txt, dependencies.py, extras-requirements.txt, mlrun/api/schemas/model_endpoints.py, mlrun/datastore/sources.py, mlrun/feature_store/api.py, mlrun/feature_store/feature_set.py, requirements.txt, tests/system/feature_store/test_feature_store.py, tests/system/model_monitoring/test_model_monitoring.py, tests/test_requirements.py
More commits that were left behind
=> [13x] Merge 1.3.x-next to 1.3.x

mlrun/serving/states.py
(cherry picked from commit f7d79b822cd9e277aafab0a6535b5fe7dbf3e1db)
=> [Serving] Fix graph plot when `before` param exists [1.3.x]

automation/system_test/cleanup.py
can't use `|` in process run, need to popen and pipe its stdout
=> [CI] Fix removing stale mlrun docker images

automation/system_test/prepare.py
Fix working dir (and validated it installs / uninstalls)
Note -> Currently disabled due to required internal process
=> [CI] Fix dev utilities working directory

mlrun/api/api/endpoints/frontend_spec.py, tests/api/api/test_frontend_spec.py
Since iguazio 3.0 is no longer relevant
=> [API] Remove session param from GET /frontend-spec

mlrun/api/utils/clients/iguazio.py, tests/api/utils/clients/test_iguazio.py
Projects in creation mode dont have updated_at field just yet, fixing by using best effort mode
=> [Projects] Fix syncing iguazio projects [1.3.x]

.github/workflows/system-tests-opensource.yml
Comment for why using detach and etc in code below
=> [CI] Fix allowing tmate for OSS tests

mlrun/launcher/client.py
self explanatory - https://jira.iguazeng.com/browse/ML-3848
=> [Launcher] Fix `mlrun.config` read

automation/system_test/prepare.py
Remove some redundant options + `type` where anyway all types are string unless default is mentioned and not a string
=> [CI] Use click option instead of positional arguement

mlrun/api/api/endpoints/artifacts.py
artifact can be inline and be up to 16mb
=> [Logging] Remove spammy storing artifact log line

.github/workflows/system-tests-enterprise.yml
this field is not in used since a while, remove
=> [CI] Remove deprecated field

tests/system/api/test_artifacts.py
This tests verifies mysql behavior while currently, OSS tests uses sqlite
=> [CI] Skip test for OSS

mlrun/api/api/endpoints/functions.py, mlrun/api/utils/builder.py
Allowing log lines to be better structured, once we move to json logger, would be better indexing them
on top of that, when using log kwargs, no multiline log lines in case message containers "\n"
=> [Logs] Update some log lines to be better structured

mlrun/api/db/sqldb/db.py, tests/api/db/test_functions.py
Deleting a function did not delete its schedule if it existed.,
In this PR, a schedules delete was added to `delete_function`.
resolves: https://jira.iguazeng.com/browse/ML-933
=> [Function] Fix deleting a function with schedule

mlrun/run.py
Rather than logging "." every couple of seconds, simply write a meaningful log, add the run state for humans to understand
=> [Run] Write meaningful logs when waiting for pipeline to finish

.github/workflows/build.yaml, .github/workflows/release.yaml, .github/workflows/security_scan.yaml, .github/workflows/system-tests-enterprise.yml
Will expose the needed information for a run/workflow as `run-name` is dynamically generated.
=> [CI] Show run names

docs/projects/run-build-deploy.md
Documenting APIs added in #3594
=> [Docs] Add documentation for project `build_image` and `build_config`

mlrun/api/api/endpoints/functions.py
BP for - https://github.com/mlrun/mlrun/pull/3660
=> [Logs] Fix `/build/status` returning 500 when failing `kubectl logs` [1.3.x]

mlrun/projects/project.py, tests/projects/test_local_pipeline.py
[ML-3901](https://jira.iguazeng.com/browse/ML-3901)
=> [Projects] Fix collecting `cleanup_ttl`/`ttl` when running workflow from path

go/pkg/services/logcollector/server.go
=> [LogCollector] Better handling errors

mlrun/api/migrations_sqlite/versions/4acd9430b093_market_place_to_hub.py, mlrun/datastore/sources.py, mlrun/datastore/targets.py
Introduced in #2869.
[ML-3922](https://jira.iguazeng.com/browse/ML-3922)
=> [Datastore] Fix SQL injection vulnerabilities

mlrun/run.py
https://jira.iguazeng.com/browse/ML-3913
Fix of #3631
=> [Workflow] Fix passing arguments to `_wait_for_pipeline_completion`

mlrun/api/api/endpoints/functions.py, mlrun/api/launcher.py, mlrun/api/utils/builder.py, mlrun/launcher/base.py, mlrun/launcher/client.py, mlrun/launcher/local.py, mlrun/launcher/remote.py, tests/api/api/test_functions.py, tests/api/api/utils.py, tests/api/runtimes/test_kubejob.py
This is required in order to enrich the function source with the project source when users specify "with_repo"
=> [API] Enrich function object before build

mlrun/feature_store/api.py
Extend description for infer_option, it has significant impact to FeatureSet usage
=> [Docs] Extend description for infer_options

mlrun/api/api/endpoints/functions.py, tests/api/api/test_functions.py
resolves: https://jira.iguazeng.com/browse/ML-3949
a fix for: https://github.com/mlrun/mlrun/pull/3668
=> [Functions] Fix delete function schedules when does not exists

mlrun/projects/project.py, mlrun/run.py
The new argument was added in #3628 but missed in a few functions.
Fixes https://jira.iguazeng.com/browse/ML-3952
=> [Project] Add `requirements_file` argument to missing functions

mlrun/utils/notifications/notification/slack.py, mlrun/utils/notifications/notification_pusher.py
Fixes https://jira.iguazeng.com/browse/ML-3923 and https://jira.iguazeng.com/browse/ML-3935
Add user custom message to notification message and insert notification name to slack notification content
=> [Notifications] Fix Notification Message in slack & git

.github/workflows/system-tests-opensource.yml, mlrun/api/main.py, mlrun/api/middlewares.py
set open source mlrun api log level to debug to allow better debugging experience
log request id when reuqest handling raises an exception
=> [API] Better request handling logging

tests/api/api/test_functions.py
Add parameterize to improve `test_delete_function_with_schedule` readability
=> [Functions] Improve test readability

mlrun/utils/notifications/notification_pusher.py
Fixes https://jira.iguazeng.com/browse/ML-3946
=> [Notifications] Support notifications on aborted runs

mlrun/launcher/local.py, tests/utils/test_notifications.py
fixes https://jira.iguazeng.com/browse/ML-3953 and https://jira.iguazeng.com/browse/ML-3911
In local launcher, push notifications if local or if the runtime kind is handler.
=> [Notifications] Fix notifications are not being sent for special local run cases (handler, dask)

mlrun/api/main.py, tests/api/test_collect_runs_logs.py
https://github.com/mlrun/mlrun/pull/3690 for development
=> [LogCollector] Stop log collection for pod in unknown state

mlrun/projects/project.py, tests/system/base.py, tests/system/projects/test_project.py
Error message has changed for test `test_run_cli_watch_with_timeout`, updating the expected error
In addition, changed logger to use cls logger
=> [CI] Fix project test

mlrun/utils/notifications/notification/ipython.py, tests/utils/test_notifications.py
Fixes - https://jira.iguazeng.com/browse/ML-3961
=> [Notification] Fix remote ipython notification raising exception

mlrun/api/crud/pipelines.py, mlrun/db/httpdb.py, tests/system/projects/test_project.py
https://jira.iguazeng.com/browse/ML-1267
Fix scenario where project exists, but tag is invalid
=> [API] Fix error code in case of invalid pipeline run ID

mlrun/projects/project.py, tests/projects/test_project.py
https://jira.iguazeng.com/browse/ML-3166
=> [Project] Raise error on wrong url source in `load_project`

mlrun/datastore/sources.py, mlrun/datastore/targets.py
=> [Datastore] Fix ingestion from sql source [1.3.x] 

mlrun/datastore/sources.py, mlrun/feature_store/api.py, mlrun/feature_store/retrieval/base.py
After #3637, 
[ML-4013](https://jira.iguazeng.com/browse/ML-4013)
=> [Feature Store]  Fix issues with start/end time in `_infer_from_static_df` and the `base-merger`

docs/change-log/index.md
https://jira.iguazeng.com/browse/ML-3993
=> [Docs] Update MLRun installation Python 3.7 pip requirement

mlrun/projects/pipelines.py, mlrun/projects/project.py
resolves:[ ML-3741](https://jira.iguazeng.com/browse/ML-3741?filter=-1)
=> [Workflow] Improving workflow error messages

docs/runtimes/notifications.md
Added documentation for using the notifications SDK features.
=> [Docs] Notification usage docs

.github/workflows/system-tests-opensource.yml
the space in the value caused the issue, needed to wrap the whole parameter in quotes
=> [CI] Fix system tests deploy command

docs/cheat-sheet.md, docs/feature-store/feature-sets.md, docs/install.md, docs/install/remote.md, docs/monitoring/model-monitoring-deployment.ipynb, docs/projects/create-project.md, docs/runtimes/configuring-job-resources.md, docs/runtimes/create-and-use-functions.ipynb, docs/runtimes/load-from-hub.md, docs/serving/available-steps.md, docs/training/built-in-training-function.ipynb, mlrun/runtimes/pod.py
=> [Docs] Remove typo

docs/cheat-sheet.md, docs/feature-store/transformations.md
[ML-3782](https://jira.iguazeng.com/browse/ML-3782)
=> [Doc] Added restriction on aggregation names

mlrun/datastore/base.py
=> [Datastore] Fix `_sanitize_url` when `parsed_url.netloc` is None

mlrun/api/db/sqldb/db.py
Logging full project object will spam the logs, cherry-picked the needed fields
https://jira.iguazeng.com/browse/ML-4001
=> [API] Reduce spammy log

mlrun/api/db/sqldb/db.py, mlrun/api/utils/periodic.py, mlrun/api/utils/singletons/k8s.py, mlrun/projects/operations.py, mlrun/run.py, mlrun/utils/notifications/notification_pusher.py
looks like `test_run_notifications` fails transiently. To allow ourselves better debugging experience, Ive added some logs around.
Did some schema changes to avoid deprecation warnings, typo and docstring fixes
=> [Notifications] Fix pushing notifications

docs/cheat-sheet.md, docs/runtimes/configuring-job-resources.md, docs/runtimes/create-and-use-functions.ipynb
Tune auto-scaling details and repair samples
=> [Scaling] Tune auto-scaling details

mlrun/frameworks/_ml_common/pkl_model_server.py
https://jira.iguazeng.com/browse/ML-3222 part 1 only
=> [Serving] Add missing explain method

docs/install/compose.with-jupyter.yaml, docs/install/compose.yaml, go/cmd/logcollector/docker/Dockerfile, mlrun/config.py
=> [Build] Bump alpine to 3.18

docs/cheat-sheet.md
=> [Docs] Tune logger description

docs/feature-store/feature-sets.md, docs/feature-store/feature-vectors.md, mlrun/feature_store/api.py
[ML-3758](https://jira.iguazeng.com/browse/ML-3758)
=> [Docs] Improve description of get_offline_features

mlrun/feature_store/retrieval/base.py, tests/system/feature_store/test_feature_store.py
[ML-4083](https://jira.iguazeng.com/browse/ML-4083)
=> [Feature Store] Fix get_offline_feature when the key and the val of the relation are equal and `with_indexes=True`

mlrun/runtimes/utils.py
https://jira.iguazeng.com/browse/ML-3847
=> [Utils] Fix missing logs on failure to add git metadata

mlrun/api/utils/clients/iguazio.py, mlrun/utils/http.py
1. Increase timeout to 60s (flow can be long in case project is large enough
2. Reduce spammy log
3. Do not retry on POST methods
https://jira.iguazeng.com/browse/ML-4001
=> [API] Tweak create project flow

mlrun/render.py
=> [Render] Remove redundant quote replacement

tests/system/pytest.ini
See https://github.com/pytest-dev/pytest/pull/11043 why file is required
=> [CI] Add pytest.ini to adhere new pytest conventions

automation/system_test/dev_utilities.py
=> [CI] Fix deleting devutils namespace

Makefile, automation/version/version_file.py, setup.py
Few changes were made in this PR to support feature branch release
1. moved makefile logic to release script
2. support tags "x.y.z-rcN+feature-name"
NOTE: this PR retain BC with current release tags
=> [CI] Prep work for feature branch release

.github/workflows/system-tests-enterprise.yml
should be `yml` and not `yaml`
=> [CI] Fix system test env file suffix

docs/change-log/index.md, docs/install/remote.md
https://jira.iguazeng.com/browse/ML-4047
=> [Docs] update MLRun installation

mlrun/projects/project.py, tests/projects/test_project.py
=> [Project] Refactor load project with sync functions

dockerfiles/base/Dockerfile
(cherry picked from commit cc2bd287b99208d26f7783ea47c4c524e355b76d)
=> [Images/Base] Update conda to 23.1.0 [1.3.x]

.github/workflows/build-internal.yaml
Those registries are hard coded, cant condition whether they exist for specific commit
=> [CI] Login to registries anyway

mlrun/datastore/targets.py, mlrun/feature_store/feature_set.py, tests/system/feature_store/test_feature_store.py
[ML-4027](https://jira.iguazeng.com/browse/ML-4027)
=> [Feature Store] Fix ingest from UI with `passthrough=True` and no targets

mlrun/api/crud/pipelines.py, mlrun/api/crud/projects.py, tests/system/projects/assets/workflow.py, tests/system/projects/test_project.py
Adding deletion of pipeline runs as part of project deletion so we don't leave any leftovers of project resources
Fixes https://jira.iguazeng.com/browse/ML-4119
=> [Project] Add pipeline runs deletion to project deletion cascade flow

mlrun/datastore/utils.py, mlrun/feature_store/feature_set.py
[ML-4128](https://jira.iguazeng.com/browse/ML-4128)
=> [Data Source] Fix local retrievel when using time filter on chunked source

tests/system/feature_store/test_spark_engine.py
=> [Tests] Fix `test_get_offline_features_with_spark_engine`

mlrun/__main__.py, mlrun/lists.py, tests/test_cli.py
resolves: https://jira.iguazeng.com/browse/ML-2027
=> [CLI] Get artifacts - return the URI of the artifact

automation/system_test/dev_utilities.py, automation/system_test/prepare.py
=> [CI] Enrich envvars with dev utils outputs

mlrun/datastore/sources.py, mlrun/feature_store/retrieval/spark_merger.py
[ML-4129](https://jira.iguazeng.com/browse/ML-4129)
Also fix same issue with `SnowflakeSource` and `SQLSource`.
=> [Feature Store] Fix `get_offline_features` with passthrough `BigQuerySource`

mlrun/api/db/init_db.py, mlrun/api/db/sqldb/db.py, mlrun/api/db/sqldb/models/models_mysql.py, mlrun/api/db/sqldb/models/models_sqlite.py, mlrun/utils/db.py, setup.py, tests/conftest.py
Removes import of API from tests
=> [DB] Move `run_time_fmt` to utils

mlrun/api/crud/projects.py, mlrun/api/utils/clients/iguazio.py, mlrun/api/utils/clients/nuclio.py, mlrun/api/utils/periodic.py, mlrun/api/utils/projects/follower.py, mlrun/api/utils/projects/leader.py, mlrun/api/utils/projects/remotes/nop_follower.py, mlrun/api/utils/projects/remotes/nop_leader.py, mlrun/api/utils/singletons/project_member.py
Seems like pycharm and co fails to get overriding class hints due to long nested python modules
changing the name to a short one resolves it nicely
=> [Projects] Fix type hinting getting overriding class

mlrun/feature_store/feature_vector.py, mlrun/feature_store/retrieval/storey_merger.py
[ML-4137](https://jira.iguazeng.com/browse/ML-4137)
=> [Feature Store] Fix `get_online_feature_service` for "Viewer" user usage.

mlrun/feature_store/feature_vector.py, mlrun/feature_store/retrieval/storey_merger.py
(#3900)
(cherry picked from commit 606059241a51f0e72afd351d3fc1e776b2116760)
=> [Feature Store] Fix `get_online_feature_service` for "Viewer" user usage. [1.4.x] 

mlrun/api/launcher.py, mlrun/launcher/base.py, mlrun/launcher/client.py, mlrun/launcher/local.py, mlrun/launcher/remote.py
as in - https://github.com/mlrun/mlrun/pull/3895
=> [Launcher] Fix overriding hints with import substitutions

mlrun/runtimes/function.py
https://jira.iguazeng.com/browse/ML-4132
The purpose of this PR is to allow the user to use all requests.request parameters, in particular to allow to user to set verify=False parameter while using the invoke method.
=> [Function] Add **kwargs to remote function invoke method

dockerfiles/jupyter/requirements.txt
add the missing `jupyterlab-git` package
=> [Jupyter] Add git support to jupyter image

dockerfiles/jupyter/requirements.txt
(cherry picked from commit 11853af34023d8d21a5bb940420db4a4eded07f6)
=> [Jupyter] Add git support to jupyter image [1.4.x]

mlrun/api/api/endpoints/files.py
=> [API] Fix `files` API to work on non-k8s environments [1.4.x]

docs/tutorial/01-mlrun-basics.ipynb
=> [Docs] bump tutorials sklearn version

docs/projects/build-run-workflows-pipelines.md
https://jira.iguazeng.com/browse/ML-3548
=> [Docs] describe using outputs parameter in steps

docs/cheat-sheet.md, docs/deployment/batch_inference.ipynb, docs/feature-store/training-serving.md, docs/projects/automate-project-git-source.ipynb, docs/projects/git-best-practices.ipynb, docs/serving/model-serving-get-started.ipynb, docs/serving/serving-graph.md, docs/training/built-in-training-function.ipynb, docs/tutorial/03-model-serving.ipynb, docs/tutorial/05-model-monitoring.ipynb, docs/tutorial/src/script.py, mlrun/model.py, mlrun/package/packagers/numpy_packagers.py, mlrun/runtimes/local.py
=> [Docs] Fix a few typos

mlrun/artifacts/base.py, mlrun/artifacts/dataset.py, mlrun/artifacts/manager.py, mlrun/artifacts/model.py, mlrun/artifacts/plots.py
We'll move them after the artifacts data migrations
=> [Artifacts] Bump legacy artifacts removal version to 1.6.0

mlrun/api/crud/secrets.py, mlrun/api/utils/events/iguazio.py, mlrun/api/utils/events/nop.py, tests/api/utils/events/test_events_client.py
https://jira.iguazeng.com/browse/ML-4183
=> [API] Do not emit internal auth secrets events

mlrun/api/crud/secrets.py, mlrun/api/utils/events/iguazio.py, mlrun/api/utils/events/nop.py, tests/api/utils/events/test_events_client.py
(cherry picked from commit b8d46d13df84417f7d3c05f621caf601cab132b4)
=> [API] Do not emit internal auth secrets events [1.4.x]

mlrun/db/httpdb.py, mlrun/utils/http.py, tests/rundb/test_unit_httpdb.py
https://jira.iguazeng.com/browse/ML-4201
=> [HTTPDB] Retry on POST for idempotent paths

mlrun/db/httpdb.py, mlrun/utils/http.py, tests/rundb/test_unit_httpdb.py
https://jira.iguazeng.com/browse/ML-4201
backports https://github.com/mlrun/mlrun/pull/3950
=> [HTTPDB] Retry on POST for idempotent paths [1.4.x]

docs/runtimes/dask-mlrun.ipynb
[ML-3979](https://jira.iguazeng.com/browse/ML-3979)
=> [Docs] Add Tech Preview note to Dask

docs/runtimes/dask-mlrun.ipynb
=> [Docs] Add Tech Preview note to Dask [1.4.x]

dockerfiles/README.md, docs/cli.md, docs/install/compose.with-jupyter.yaml, docs/install/compose.yaml, docs/install/kubernetes.md, docs/projects/ci-integration.md, docs/runtimes/images.md, hack/local/README.md, hack/local/mljupy.yaml, hack/local/mlrun-local.yaml, hack/mlrun-all.yaml, hack/mlrunapi.yaml, hack/mlrunui.yaml
ports https://github.com/mlrun/mlrun/pull/3959
=> [Docs] Bump mlrun version for release

mlrun/runtimes/function.py
This is only done in the server side and rundb is set to a sql url there
=> [Nuclio] Fix HTTPDB URL

automation/system_test/prepare.py
In case a previous preparation failed after deletion we want the next one to be able to recover
=> [Automation] Warn if mlrun db deletion failed

.github/workflows/release.yaml, automation/version/version_file.py
Do not create github release for feature branch, just a tag is enough
=> [CI] Feature branch enhancements 

.github/workflows/ci.yaml, .github/workflows/go-ci.yaml, go/Makefile
Run Go github actions only when some file in the go folder has changed
Check [This should trigger go jobs](https://github.com/mlrun/mlrun/pull/3983/commits/7e804c20e08d67e5dfc308e12d3c15dba2c1205a) actions to see how I verified it works
=> [CI] Run Go jobs only when changed

.run/Unit tests.run.xml
This is useful to debug running all unit test (when CI fails but if you run it locally it passes)
=> [Run-configuration] Run all unit tests configuration

mlrun/feature_store/retrieval/job.py
[ML-4261](https://jira.iguazeng.com/browse/ML-4261)
=> [Feature Store] Raise an error when passing invalid run config

.github/workflows/release.yaml
output were not populated right
=> [CI] Fix feature branch release

.github/workflows/release.yaml
v5 uses node 12 which is deprecated
=> [CI] Bump action to use node 16

docs/cheat-sheet.md
Add sample for scale to zero via API
=> [Docs] Add sample for scale to zero via API

mlrun/runtimes/function.py, mlrun/utils/helpers.py, mlrun/utils/regex.py, tests/runtimes/test_function.py, tests/utils/test_helpers.py
adhering to regex as written below
`"^(?!_)[a-zA-Z0-9_]{1,256}$"`
This is to fail fast before getting to nuclio's side and failing there
https://jira.iguazeng.com/browse/ML-4232
=> [Trigger] Validate v3io consumer group name

mlrun/runtimes/function.py, mlrun/utils/helpers.py, mlrun/utils/regex.py, tests/runtimes/test_function.py, tests/utils/test_helpers.py
=> [Trigger] Validate v3io consumer group name [1.4.x]

mlrun/utils/notifications/notification_pusher.py
To make it easier for debugging in the future.
=> [Notifications] Add Logs for success / failure upon sending notification

mlrun/feature_store/retrieval/base.py, tests/system/feature_store/test_feature_store.py
[ML-4296](https://jira.iguazeng.com/browse/ML-4296)
=> [Feature Store] Extract indexes from `entity_rows` 

mlrun/api/api/api.py, mlrun/api/api/endpoints/functions.py, mlrun/api/api/endpoints/jobs.py, mlrun/api/crud/model_monitoring/deployment.py, mlrun/api/crud/model_monitoring/model_endpoints.py, mlrun/common/schemas/__init__.py, mlrun/common/schemas/model_monitoring/__init__.py, mlrun/common/schemas/model_monitoring/constants.py, mlrun/db/httpdb.py, mlrun/model_monitoring/__init__.py, mlrun/model_monitoring/api.py, mlrun/model_monitoring/features_drift_table.py, mlrun/model_monitoring/model_monitoring_batch.py, tests/api/api/test_functions.py
Detailed description will be added soon. 
Related JIRA tickets - https://jira.iguazeng.com/browse/ML-4088, https://jira.iguazeng.com/browse/ML-4173
=> [Model Monitoring] Expose model endpoints batch process through SDK

tests/system/base.py, tests/system/examples/basics/test_basics.py, tests/system/examples/basics/test_db.py
=> [Tests] Fix base system tests

.flake8, pyproject.toml
flake8 works both ways, just went with the way it's written in the docs
=> [Makefile] Skip isort proto dir

docs/ecosystem.md
I added two important points SQL sources (see SQLTarget, SQLSource) and Databricks.
BTW: it is important to highlight these two things
=> [Docs] Update ecosystem

mlrun/datastore/sources.py, mlrun/runtimes/serving.py
[ML-4283](https://jira.iguazeng.com/browse/ML-4283)
=> [Datastore] Turn explicit ack on when engine is async

.gitignore, automation/patch_igz/README.md, automation/patch_igz/patch_env_template.yml, automation/patch_igz/patch_remote.py, automation/requirements.txt
=> [Automation] Deploy mlrun-api on iguazio vanilla nodes

mlrun/api/api/endpoints/functions.py, tests/api/api/test_functions.py, tests/api/runtimes/test_kubejob.py, tests/api/runtimes/test_mpijob.py
https://jira.iguazeng.com/browse/ML-4336
=> [API] Mask access key on deploy

mlrun/feature_store/retrieval/base.py
[ML-4340](https://jira.iguazeng.com/browse/ML-4340)
=> [Feature Store] Fix `get_offline_feature` to not change incoming `entity_df`

docs/tutorial/align_tutorials.sh
=> [Docs] Align tutorials script

dockerfiles/mlrun-api/requirements.txt, tests/test_requirements.py
https://github.com/agronholm/apscheduler/issues/770
=> [Requirements] Blacklist APScheduler 3.10.2

mlrun/api/api/endpoints/functions.py, mlrun/api/launcher.py, mlrun/projects/pipelines.py, tests/api/api/test_functions.py, tests/system/api/assets/function.py, tests/system/api/test_secrets.py
https://jira.iguazeng.com/browse/ML-4336
Auto mount overrides the v3io access key env var
=> [Build] Fix auto mount overriding access key

mlrun/api/api/endpoints/hub.py, mlrun/api/crud/hub.py, mlrun/api/rundb/sqldb.py, tests/api/api/test_submit.py
https://jira.iguazeng.com/browse/ML-4341
=> [Hub] Implement list hub sources in SQLRunDB

mlrun/config.py
Minor improvement on the default template for `feature_store.data_prefixes.redisnosql` configuration.
=> [Config] Improve "redisnosql" default value

mlrun/projects/project.py, tests/artifacts/test_artifacts.py, tests/common_fixtures.py
(cherry picked from commit 8c4402d284c4b1b0f7685858c194aeba74149f4a)
=> [Artifacts] Fix register artifacts overrides old artifacts [1.3.x]

mlrun/feature_store/ingestion.py
[ML-4380](https://jira.iguazeng.com/browse/ML-4380)
=> [Feature Store] Fix propagation of context object at feature set init

automation/system_test/dev_utilities.py
This reverts commit 8d81f5be899cbb4cb0c08d5e25fea910fe3d79ce.
=> Revert "Update dev_utilities.py (#4109)"

mlrun/run.py, mlrun/runtimes/base.py, mlrun/runtimes/kubejob.py, tests/api/runtimes/test_kubejob.py
https://jira.iguazeng.com/browse/ML-3705
This allows using dockerfile entrypoint
=> [Runtimes] Deduct empty command in pass mode

mlrun/db/httpdb.py, mlrun/projects/project.py
https://jira.iguazeng.com/browse/ML-4419
=> [Datastore] Fixing errors introduced by last refactoring

mlrun/runtimes/databricks/databricks.py, mlrun/runtimes/databricks/databricks_wrapper.py, tests/system/runtimes/test_databricks.py
[ML-4414](https://jira.iguazeng.com/browse/ML-4414)
and rename internal parameters ([ML-4412](https://jira.iguazeng.com/browse/ML-4412))
=> [Runtimes] Add Databricks new cluster configurations

mlrun/model_monitoring/model_monitoring_batch.py, tests/model_monitoring/test_metrics.py
Resolves [ML-4375](https://jira.iguazeng.com/browse/ML-4375).
- Inherit from an ABC
- Reduce code duplication (DRY)
- Add tests
=> [Model Monitoring] Add abstraction and tests to the monitoring metrics

mlrun/config.py
[ML-4411](https://jira.iguazeng.com/browse/ML-4411)
=> Disable explicit ack by default for v1.5.0

docs/install/kubernetes.md
The previous command doesn't work, the updated one (from Adam) does.
=> [Docs] Update CE K8s installation instructions on Apple silicon

docs/runtimes/create-and-use-functions.ipynb
[ML-2405](https://jira.iguazeng.com/browse/ML-2405)
=> [Docs] function name best practice

mlrun/datastore/redis.py
https://jira.iguazeng.com/browse/ML-4489
=> [Datastore] Fix clearing Redis when the target is specified as a datastore profile

tests/rundb/test_unit_httpdb.py
fix for: https://github.com/mlrun/mlrun/pull/4150
=> [Utils] fix line

dockerfiles/gpu/Dockerfile
part of https://jira.iguazeng.com/browse/ML-4366
=> [Dockerfiles] Fix mlrun-gpu security vulnerabilities

mlrun/runtimes/sparkjob/abstract.py, mlrun/runtimes/sparkjob/spark3job.py, tests/api/runtimes/test_spark.py
[ML-1180](https://jira.iguazeng.com/browse/ML-1180)
=> [Runtimes] Verify CPU request < limit in spark runtime

.dockerignore
include more directories that should not be included as part of deployed code
=> [Dockerfiles] Update ignoredockerfile

dockerfiles/base/Dockerfile, dockerfiles/gpu/prebaked.Dockerfile, dockerfiles/mlrun/Dockerfile
To remedy security vulnerabilities
=> [Dockerfiles] Update conda initial requirements

mlrun/datastore/sources.py
[ML-3623](https://jira.iguazeng.com/browse/ML-3623)
=> [Datastore] Fix error when using `store://` URL in data source

mlrun/model.py, mlrun/runtimes/serving.py
Ensures that the function is available to display in the UI while deploying the child functions
https://jira.iguazeng.com/browse/ML-1977
=> [Serving] Save parent function before children deployment

mlrun/api/initial_data.py
https://jira.iguazeng.com/browse/ML-3823
No need to get the full projects since we only check if there are projects in the DB.
=> [API] Reduce data version resolvement overhead

dockerfiles/jupyter/Dockerfile
Following https://github.com/mlrun/mlrun/pull/4185
=> [Images] Fix Jupyter tutorials path

mlrun/datastore/datastore_profile.py
https://jira.iguazeng.com/browse/ML-4522
=> [Datastore] Proper error handling of datastore profile reading

mlrun/runtimes/databricks_job/databricks_runtime.py, tests/runtimes/test_databricks.py
[ML-4417](https://jira.iguazeng.com/browse/ML-4417)
=> [Runtimes] Prevent running databricks runtime locally

tests/system/runtimes/test_kubejob.py
[ML-4562](https://jira.iguazeng.com/browse/ML-4562)
=> [Tests] Limit test_log_artifact_with_run_function to enterprise only.

.github/workflows/ci.yaml
to avoid spinning up runner needlessly
=> [CI] Merging lint and licensing check onto a single job

tests/api/api/test_functions.py, tests/run/test_hyper.py
retry might occur more than once
=> [Tests] Fix transient failure

docs/feature-store/end-to-end-demo/01-ingest-datasources.ipynb, mlrun/feature_store/api.py
[ML-4220](https://jira.iguazeng.com/browse/ML-4220)
=> [Feature store] Add `deploy_ingestion_service_v2`

mlrun/api/crud/model_monitoring/helpers.py, mlrun/api/crud/model_monitoring/model_endpoints.py, mlrun/common/schemas/model_monitoring/constants.py, mlrun/model_monitoring/helpers.py
[ML-4570](https://jira.iguazeng.com/browse/ML-4570)
=> [Model Monitoring] Rollback stream parquet path name

mlrun/projects/pipelines.py, mlrun/run.py, mlrun/runtimes/__init__.py, tests/api/api/test_runs.py
Adhering function dict items response by making `FunctionsDict` return `items` as list of key,value
https://jira.iguazeng.com/browse/ML-4534
=> [Pipelines] Update items function response type

mlrun/runtimes/utils.py, tests/api/api/test_utils.py
https://jira.iguazeng.com/browse/ML-4584
=> [Runtimes] Enrich function with image from task

mlrun/datastore/targets.py
[ML-4587](https://jira.iguazeng.com/browse/ML-4587),
[ML-4589](https://jira.iguazeng.com/browse/ML-4589)
=> [Model Monitoring] Fix write to single parquet target.

mlrun/model_monitoring/model_monitoring_batch.py
Until now the V3IO KV schema of the model endpoints table was generated only through the monitoring stream process. Following the implementation of `batch_infer_v2`, the user can run the batch job analysis without having any monitoring stream process. 
In this PR we use the batch drift job to infer the KV table and as a result to generate a schema file that will be used by the Grafana dashbaords. 
Related JIRA - https://jira.iguazeng.com/browse/ML-4575
=> [Model Monitoring] Infer V3IO KV schema through batch job

mlrun/datastore/targets.py, mlrun/feature_store/api.py
[ML-4588](https://jira.iguazeng.com/browse/ML-4588)
=> [Model Monitoring] save spark df to partitioned parquet not in the ingest flow 

docs/runtimes/spark-operator.ipynb
https://jira.iguazeng.com/browse/ML-4420
=> [Docs] Add code description for controlling Spark Operator memory 

dependencies.py, extras-requirements.txt, tests/test_requirements.py
=> [Requirements] Replace `azure-storage-blob` upperbound with exclusion

mlrun/api/utils/builder.py, tests/api/utils/test_builder.py
https://jira.iguazeng.com/browse/ML-4236
=> [Builder] Enrich prefixed base image

mlrun/api/utils/builder.py, tests/api/utils/test_builder.py
(cherry picked from commit 61b2e90c27b61d1d2ab5faa9784513b18de6fd2b)
=> [Builder] Enrich prefixed base image [1.5.x]

mlrun/db/httpdb.py, mlrun/launcher/remote.py, mlrun/projects/pipelines.py, mlrun/projects/project.py
https://jira.iguazeng.com/browse/ML-4593
```
> 2023-09-14 08:47:02,488 [info] Submitting remote workflow: {'workflow_engine': 'kfp', 'schedule': '0 * * * *', 'project_name': 'simple-project'}
> 2023-09-14 08:47:02,702 [info] Workflow scheduled successfully: {'workflow_response': WorkflowResponse(project='simple-project', name='main', status='scheduled', run_id=None, schedule='0 * * * *')}
```
=> [Pipelines] Add submit scheduled workflow logs [1.5.x]

mlrun/__main__.py, mlrun/api/db/sqldb/db.py, tests/api/api/test_workflows.py
Also fixed help message of project option in mlrun CLI
https://jira.iguazeng.com/browse/ML-4595
=> [SQLDB] Fix read run not found error message

mlrun/projects/project.py, tests/integration/sdk_api/projects/test_project.py, tests/projects/test_project.py
(cherry picked from commit b663888b483f85adbc7aeb7ed45acb53a3a25352)
=> [Project] Affix `set_function` tag and naming [1.5.x]

mlrun/__main__.py, mlrun/api/db/sqldb/db.py, tests/api/api/test_workflows.py
(cherry picked from commit 1c1bf01589d061dac6eb78f24007392736723ed5)
=> [SQLDB] Fix read run not found error message (#4259)

mlrun/db/httpdb.py, mlrun/launcher/remote.py, mlrun/projects/pipelines.py, mlrun/projects/project.py
(cherry picked from commit 75f4106f671aec514eb5b0cc56232e9db9555690)
=> [Pipelines] Add submit scheduled workflow logs

mlrun/config.py
[ML-4411](https://jira.iguazeng.com/browse/ML-4411)
=> [Config] Re-enable explicit ack by default

docs/cli.md, mlrun/__main__.py
(cherry picked from commit 2d8695612176a2a93de7b34db95a016f384f2fde)
=> [Docs] Fix CLI docs [1.5.x]

docs/tutorials/03-model-serving.ipynb
[ML-4366](https://jira.iguazeng.com/browse/ML-4366)
=> [Docs] add dependencies to serving classes in model serving tutorial

mlrun/model_monitoring/stores/kv_model_endpoint_store.py
=> [Model Monitoring] Encode feature statistics data (KV) [1.5.x]

mlrun/datastore/sources.py, tests/system/feature_store/test_feature_store.py
[ML-4610](https://jira.iguazeng.com/browse/ML-4610)
=> [Datastore] Remove deprecated `time_field` constructor parameter

mlrun/utils/http.py
https://github.com/mlrun/mlrun/pull/4286
=> [HTTPDB] Add retriable invalid chunks exceptions (#4286)

docs/tutorials/03-model-serving.ipynb
Backports:
https://github.com/mlrun/mlrun/pull/4297
https://github.com/mlrun/mlrun/pull/4290
=> [Tutorials] Remove ml-models [1.5.x]

docs/tutorials/03-model-serving.ipynb
=> [Tutorials] Remove warning on prediction

mlrun/api/db/sqldb/db.py
temporary, until artifacts refactor kicks in
https://jira.iguazeng.com/browse/ML-4625
=> [Artifacts] Increase retrieved iterations to 1k

tests/system/examples/basics/test_basics.py, tests/system/examples/basics/test_db.py
following https://github.com/mlrun/mlrun/pull/4294
=> [Tests] Fix system tests local label verification

tests/system/examples/basics/test_basics.py, tests/system/examples/basics/test_db.py
(cherry picked from commit 8fccbb9311da08fe8d0e34c15be6f01109170802)
=> [Tests] Fix system tests local label verification [1.5.x]

mlrun/feature_store/api.py, mlrun/feature_store/feature_set.py, mlrun/feature_store/steps.py, tests/feature-store/test_infer.py, tests/system/feature_store/test_feature_store.py
=> [Feature store] Remove parameters deprecated in 1.5.0 [1.5.x]

mlrun/api/crud/model_monitoring/deployment.py, mlrun/model_monitoring/writer.py, tests/model_monitoring/test_writer.py
=> [Model Monitoring] Implement apps writer (EE) [1.5.x]

mlrun/projects/project.py
https://jira.iguazeng.com/browse/ML-4297
=> [KFP] Warn when using image property for non-remote pipelines

docs/cheat-sheet.md, docs/install/remote.md, docs/projects/ci-integration.md
[ML-4075](https://jira.iguazeng.com/browse/ML-4075)
=> [Docs] Remove python 3.7 

mlrun/model_monitoring/api.py, tests/system/model_monitoring/test_model_monitoring.py
=> [Model Monitoring] Fix generating function_uri when calling get_or_create_model_endpoint [1.5.x]

automation/requirements.txt, dockerfiles/base/mlrun_requirements.txt, dockerfiles/gpu/Dockerfile, dockerfiles/jupyter/requirements.txt, dockerfiles/mlrun/requirements.txt, requirements.txt, tests/system/runtimes/assets/requirements.txt, tests/test_requirements.py
https://jira.iguazeng.com/browse/ML-4653
=> [Docker] Remedy security vulnerabilities

docs/cheat-sheet.md, docs/hyper-params.ipynb, docs/projects/automate-project-git-source.ipynb, docs/projects/load-project-yaml.ipynb, docs/runtimes/create-and-use-functions.ipynb, docs/runtimes/dask-mlrun.ipynb, docs/runtimes/dask-pipeline.ipynb, docs/serving/built-in-model-serving.md, docs/store/models.md, docs/training/working-with-data-and-model-artifacts.md
[ML-4368](https://jira.iguazeng.com/browse/ML-4368)
=> [Docs] Replace image name mlrun/ml-models with mlrun/mlrun

mlrun/utils/async_http.py
When method is POST or anything that has side effect, retry mechanism doen't kick in. this pr intend to loosen this restriction and do retry on methods with side effect as the chosen exception is raised when connection was not even made, meaning, the request did not went thru. making async client more robust, specifically for worker<>chief communication 
https://jira.iguazeng.com/browse/ML-3919
=> [AsyncHTTP] Do retry on connection refused error

mlrun/runtimes/function.py, mlrun/runtimes/nuclio.py
https://jira.iguazeng.com/browse/ML-104
=> [Nuclio] Allow invoking without specifying path

tests/system/model_monitoring/test_model_monitoring.py
=> [Tests] Fix test_model_monitoring_voting_ensemble system test [1.5.x]

docs/runtimes/image-build.md
Some small fixes to the docs + adding a note about project secrets being available.
=> [Docs] Improvements to image build docs

mlrun/utils/async_http.py
=> [AsyncHTTP] Do retry on connection refused error [1.5.x]

Makefile
continuing https://github.com/mlrun/mlrun/pull/2864
=> [CI] Cache jupyter builds

docs/cli.md
(cherry picked from commit a7075ca9abea835491cf64c92da5829423bb29dd)
=> [Docs] Add type hints to CLI options [1.5.x]

mlrun/feature_store/api.py, mlrun/feature_store/feature_vector.py, mlrun/feature_store/retrieval/__init__.py, mlrun/feature_store/retrieval/base.py, mlrun/feature_store/retrieval/job.py, mlrun/feature_store/retrieval/storey_merger.py
(cherry picked from commit 8a1d37960914e40905f9283363f1c53f0b30ffec)
Cherry-picked from #4340
=> [Feature Store] Update feature vector features in FeatureVectorStatus [1.5.x]

dockerfiles/jupyter/Dockerfile
backports https://github.com/mlrun/mlrun/pull/4351
=> [Dockerfiles] Jupyter dockerfile update_demos [1.5.x]

mlrun/db/httpdb.py, server/api/api/endpoints/workflows.py, server/api/crud/workflows.py
=> [Workflow] Fix running preloaded workflow

automation/requirements.txt, requirements.txt, tests/test_requirements.py
https://jira.iguazeng.com/browse/ML-2254
=> [Requirements] Bump click

mlrun/projects/pipelines.py
porting (#4376) to development
=> [RemoteRunner] Fix sanitizing workflow spec

docs/feature-store/feature-vectors.md
[ML-3784](https://jira.iguazeng.com/browse/ML-3784)
=> [Docs] Add FS FV-defined feature-set relations and join-type (per-join)

mlrun/data_types/spark.py, mlrun/data_types/to_pandas.py
[ML-4701](https://jira.iguazeng.com/browse/ML-4701)
=> [Spark] Fix datetime dtype error when pandas 2 is installed

mlrun/data_types/to_pandas.py
Fixes
```
ImportError: cannot import name 'DayTimeIntervalType' from 'pyspark.sql.types' (/spark/python/lib/pyspark.zip/pyspark/sql/types.py)
```
in `TestFeatureStoreSparkEngine.test_ingest_with_steps_mapvalues`.
=> [Spark] Fix `toPandas` to match pyspark 3.2.3

go/cmd/schemas_compiler/docker/Dockerfile, go/pkg/common/consts.go, go/pkg/services/logcollector/logcollector_test.go, go/pkg/services/logcollector/server.go, go/pkg/services/logcollector/statestore/file/client.go, go/pkg/services/logcollector/statestore/inmemory/client.go, go/pkg/services/logcollector/statestore/types.go, go/proto/log_collector.proto
=> [Log Collector] Restart log streaming when k8s API sends EOF [1.5.x]

tests/system/feature_store/test_feature_store.py, tests/system/feature_store/test_spark_engine.py
=> [Tests] Changes according to FeatureVectorStatus changes

tests/system/feature_store/test_feature_store.py, tests/system/feature_store/test_spark_engine.py
(cherry picked from commit b0739b43abb5c87c8e38fbc7e9993730f3c6e68a)
#4397
=> [Tests] Changes according to FeatureVectorStatus changes [1.5.x]

dockerfiles/mlrun-api/requirements.txt, mlrun/utils/logger.py, server/api/apiuvicorn.py, server/api/main.py
in addition, unified uvicorn logs and mlrun one
=> [API] Bump uvicorn

mlrun/projects/pipelines.py, mlrun/projects/project.py
porting (#4401) to development
=> [Workflows] Minor tweaks

mlrun/feature_store/api.py, server/api/crud/model_monitoring/helpers.py, server/api/crud/model_monitoring/model_endpoints.py, tests/system/model_monitoring/test_model_monitoring.py
Fix [ML-4635](https://jira.iguazeng.com/browse/ML-4635?focusedCommentId=115430&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-115430)
- Remove the name normalization function duplication
- Extract the `_get_features` function from the model monitoring feature set
- The name norm takes place here - it's the main logical change of this PR
- Add a system test
=> [Model Monitoring] Treat special chars properly in the inference flow 

server/api/api/endpoints/workflows.py
[ML-4730](https://jira.iguazeng.com/browse/ML-4730)
Restore to the workflow runner object's root some labels that were disable on MLRun 1.5 RCs:
- job-type
- workflow
- mlrun/client_version
- mlrun/client_python_version
=> [Workflows] Fix missing related labels

mlrun/api/api/endpoints/workflows.py
=> [Workflows] Fix missing related labels [1.5.x]

mlrun/feature_store/feature_set.py, server/api/api/endpoints/feature_store.py, server/api/crud/model_monitoring/model_endpoints.py
(cherry picked from commit f429a0c8d769659dd17515b9056234b9d9561d86)
=> [Feature-set] Inject db session from server

mlrun/feature_store/retrieval/job.py, tests/system/feature_store/test_spark_engine.py
[ML-4728](https://jira.iguazeng.com/browse/ML-4728)
=> [Feature Store] Drop columns according to the user `drop_columns` param when reading the result df with `RemoteVectorResponse` 

mlrun/api/api/endpoints/workflows.py, mlrun/config.py, mlrun/k8s_utils.py, tests/test_k8s_utils.py
=> [k8s] Sanitize label's values to ensure k8s compatibility [1.5.x]

mlrun/__main__.py, mlrun/api/api/endpoints/workflows.py, mlrun/db/httpdb.py, mlrun/projects/pipelines.py, mlrun/runtimes/base.py, mlrun/utils/helpers.py, mlrun/utils/notifications/notification/console.py, tests/integration/sdk_api/httpdb/test_exception_handling.py
In addition, some tweaks and log fixes were made as discovered during debugging
https://jira.iguazeng.com/browse/ML-4734
=> [Workflows] Fix failing silently upon execution error

requirements.txt, tests/test_requirements.py
https://jira.iguazeng.com/browse/ML-2956
=> [Storey] Make aggregations return `NaN` when there is no data except for count

server/api/utils/builder.py, tests/api/utils/test_builder.py
[ML-4741](https://jira.iguazeng.com/browse/ML-4741)
=> [Builder] Clone GitHub repository to a directory other than `/tmp`

mlrun/feature_store/retrieval/job.py, tests/system/feature_store/test_spark_engine.py
[ML-4765](https://jira.iguazeng.com/browse/ML-4765)
=> [Feature store] Fix error when dropping timestamp column [1.5.x]

docs/runtimes/create-and-use-functions.ipynb, docs/runtimes/images.md
[ML-4368](https://jira.iguazeng.com/browse/ML-4368)
replaces https://github.com/mlrun/mlrun/pull/4293
=> [Docs] Add image names and descriptions, how to build images, add/fix links 

mlrun/datastore/targets.py, mlrun/feature_store/feature_set.py, mlrun/feature_store/retrieval/job.py, tests/system/feature_store/test_spark_engine.py
Cherry pick of 1.5.x PR #4447 (0622bff) + PR #4452.
[ML-4765](https://jira.iguazeng.com/browse/ML-4765)
=> [Feature store] Fix error when dropping timestamp column

tests/system/feature_store/test_spark_engine.py
Fix `test_get_offline_features_with_filter_and_indexes` following changes in #4453.
=> [Tests] Fix spark system test

tests/system/feature_store/test_spark_engine.py
Fix `test_get_offline_features_with_filter_and_indexes` following changes in #4452.
=> [Tests] Fix spark system test [1.5.x]

mlrun/db/httpdb.py
https://jira.iguazeng.com/browse/ML-4797
=> [HTTPDB] Update `list_runs` docstring with default filter [1.5.x]

docs/change-log/index.md, docs/concepts/submitting-tasks-jobs-to-functions.md, docs/concepts/workflow-overview.md, docs/projects/automate-project-git-source.ipynb, docs/projects/load-project.md, docs/runtimes/configuring-job-resources.md
(cherry picked from commit 72a3bb2da460ebd5d38c304be92f8f8831e19683)
=> [Docs] Add 1.5.0 change log [1.5.x]

mlrun/db/httpdb.py
=> [HTTPDB] Update `list_runs` docstring with default filter

docs/cheat-sheet.md
Ports https://github.com/mlrun/mlrun/pull/4465
=> [Docs] Fix dask images

mlrun/datastore/base.py, tests/integration/aws_s3/test_aws_s3.py
https://jira.iguazeng.com/browse/ML-4796
=>  [Datastore] Fix reading csv directory when using datastore profiles

tests/system/model_monitoring/test_model_monitoring.py
Improve and fix a system test that was introduced in #4377.
The logic of the test remains the same. It now uses the standard methods of the `TestMLRunSystem` class so that it runs properly.
=> [Tests] Improve and fix TestInferenceWithSpecialChars system test

server/log-collector/cmd/logcollector/main.go, server/log-collector/pkg/common/consts.go, server/log-collector/pkg/services/logcollector/logcollector_test.go, server/log-collector/pkg/services/logcollector/server.go, server/log-collector/pkg/services/logcollector/test/logcollector_test.go
https://jira.iguazeng.com/browse/ML-4791
=> [Log collector] Update last log time every 4KB read

go/cmd/logcollector/main.go, go/pkg/common/consts.go, go/pkg/services/logcollector/logcollector_test.go, go/pkg/services/logcollector/server.go, go/pkg/services/logcollector/test/logcollector_test.go
https://github.com/mlrun/mlrun/pull/4474
=> [Log collector] Update last log time every 4KB read [1.5.x]

dockerfiles/README.md, docs/change-log/index.md, docs/cli.md, docs/install/compose.with-jupyter.yaml, docs/install/compose.yaml, docs/install/kubernetes.md, docs/projects/ci-integration.md, docs/runtimes/images.md, hack/local/README.md, hack/local/mljupy.yaml, hack/local/mlrun-local.yaml, hack/mlrun-all.yaml, hack/mlrunapi.yaml, hack/mlrunui.yaml
(cherry picked from commit 37673202ada93b3fae3cc8b509bc84b3c9a8d1bf)
=> [Docs] Bump docs version 1.5.0

docs/runtimes/dask-mlrun.ipynb
[ML-4859](https://jira.iguazeng.com/browse/[ML-4859](url))
=> [Docs] Add auto_build to handler command

mlrun/projects/project.py
Cherry picking #4504 to development.
=> [Project] Deprecate project API `build_image.skip_deployed` parameter

mlrun/datastore/datastore_profile.py, mlrun/projects/project.py
https://jira.iguazeng.com/browse/ML-4851
=> [Doc] Add docstrings to list_datastore_profiles() and register_temporary_client_datastore_profile()

mlrun/projects/project.py, tests/projects/test_project.py
(cherry picked from commit 244ffa23cf945dda1d5fe30905adea41731b236f)
https://github.com/mlrun/mlrun/pull/4509
=> [Project] Fix load project from yaml with functions [1.5.x]

README.md
Fixes [ML-4863](https://jira.iguazeng.com/browse/ML-4863) - broken images in MLRun PyPI page:
https://pypi.org/project/mlrun/1.5.0/#description
=> [Docs] Update README.md - use absolute path to images

automation/package_test/test.py, dependencies.py, extras-requirements.txt, mlrun/api/crud/client_spec.py, mlrun/common/schemas/client_spec.py, mlrun/config.py, mlrun/db/httpdb.py, mlrun/execution.py, mlrun/frameworks/_common/utils.py, mlrun/launcher/base.py, mlrun/launcher/client.py, mlrun/runtimes/local.py, mlrun/track/__init__.py, mlrun/track/tracker.py, mlrun/track/tracker_manager.py, mlrun/track/trackers/__init__.py, mlrun/track/trackers/mlflow_tracker.py, tests/common_fixtures.py, tests/track/__init__.py, tests/track/assets/simple_run_no_handler.py, tests/track/platform_trackers/__init__.py, tests/track/platform_trackers/test_mlflow_tracker.py, tests/track/test_tracker_manager.py
(cherry picked from commit 5c44b2dd9304d5158f0b8c7161e4cd7d36718e42)
=> [Track] Add MLFlow tracker (#4356)

docs/cli.md, docs/install/compose.with-jupyter.yaml, docs/install/compose.yaml, docs/projects/ci-integration.md, docs/runtimes/images.md, hack/local/README.md, hack/local/mljupy.yaml, hack/local/mlrun-local.yaml, hack/mlrun-all.yaml, hack/mlrunapi.yaml, hack/mlrunui.yaml
=> [Version] Bump 1.5.1

mlrun/model.py, mlrun/projects/project.py, mlrun/runtimes/base.py, mlrun/runtimes/kubejob.py, tests/api/runtimes/test_kubejob.py, tests/projects/test_project.py, tests/runtimes/test_base.py
=> [SDK] Remove deprecated methods and flags

mlrun/feature_store/retrieval/spark_merger.py
[ML-4854](https://jira.iguazeng.com/browse/ML-4854)
=> [Feature Store] Work around pyspark `toPandas` issue when pandas>=2

mlrun/track/tracker_manager.py, mlrun/track/trackers/mlflow_tracker.py
fixed label that was list at mlflow tracker log model
fixed error print at tracker manager post run
=> [Track] Fix log model mlflow lables

go/pkg/services/logcollector/logcollector_test.go, go/pkg/services/logcollector/server.go, mlrun/api/utils/clients/log_collector.py
porting  (#4531) to 1.5.x
https://jira.iguazeng.com/browse/ML-4841
=> [LogCollector] Fix get_log size calculation [1.5.x]

mlrun/data_types/infer.py
Fix issue introduced in #4525 (v1.6.0-rc3).
[ML-4936](https://jira.iguazeng.com/browse/ML-4936)
[ML-4939](https://jira.iguazeng.com/browse/ML-4939)
Fixes `TestInferenceWithSpecialChars::test_inference_feature_set`.
=> [Data types] Fix schema inference of df with a numeric index

mlrun/__main__.py, mlrun/launcher/client.py, mlrun/launcher/local.py, mlrun/launcher/remote.py, tests/integration/sdk_api/run/test_main.py
running function from another project should store the function in current project.
resolves: https://jira.iguazeng.com/browse/ML-2987
=> [Launcher] Pass project param to enrich_runtime for cross project execution

mlrun/utils/helpers.py
https://jira.iguazeng.com/browse/ML-4951
=> [Utils] Fix time string to seconds validation

mlrun/__main__.py, tests/integration/sdk_api/run/test_main.py
=> [CLI] Fail get runs if tag is provided, as it is not supported

go/pkg/services/logcollector/logcollector_test.go, go/pkg/services/logcollector/server.go
backports https://github.com/mlrun/mlrun/pull/4548 to 1.5.x
=> [LogCollector] Get logs fix round 2 [1.5.x]

tests/system/runtimes/assets/databricks_function_print_kwargs.py, tests/system/runtimes/test_databricks.py
fix image in test to mlrun/mlrun.
fix test_kwargs_from_file.
=> [Tests] Fix databricks tests

server/api/utils/builder.py, tests/api/utils/test_builder.py
[ML-4992](https://jira.iguazeng.com/browse/ML-4992)
=> [Server] Avoid setting workdir to target dir

mlrun/model_monitoring/batch.py, tests/system/model_monitoring/test_model_monitoring.py
Backport #4546 to 1.5.x
[ML-5011](https://jira.iguazeng.com/browse/ML-5011)
=> [Model Monitoring] Create TSDB schema for batch infer [1.5.x]

mlrun/db/httpdb.py
https://jira.iguazeng.com/browse/ML-5015
child objects replaced by related resources
=> [Docs] Improve Deletionstrategy description 

mlrun/datastore/base.py, mlrun/datastore/datastore_profile.py, mlrun/datastore/s3.py
https://jira.iguazeng.com/browse/ML-5017
Fix bugs introduced in https://github.com/mlrun/mlrun/pull/4521
=> [Datastore] Fix s3 bugs introduced in previous PR

mlrun/runtimes/base.py, server/api/runtime_handlers/base.py, server/api/runtime_handlers/mpijob/v1.py, tests/api/runtime_handlers/base.py, tests/api/runtime_handlers/test_kubejob.py, tests/api/runtime_handlers/test_mpijob.py, tests/api/runtime_handlers/test_sparkjob.py
Phase 2 of https://github.com/mlrun/mlrun/pull/4497
Adds support for mpi and spark.
https://jira.iguazeng.com/browse/ML-4997
=> [API] Add mpijob and spark state threshold monitoring

mlrun/__main__.py, tests/system/runtimes/test_kubejob.py
resolves: 
https://jira.iguazeng.com/browse/ML-1995
=> [CLI] Run - when image is not provided, use mlrun/mlrun by default

mlrun/api/main.py, mlrun/utils/helpers.py, tests/api/test_collect_runs_logs.py, tests/utils/test_helpers.py
cherrypick 897c2e5 to 1.5.x
https://github.com/mlrun/mlrun/pull/4555/files
https://jira.iguazeng.com/browse/ML-5035
=> [LogCollector] Fix big stop logs [1.5.x]

server/api/runtime_handlers/daskjob.py
https://jira.iguazeng.com/browse/ML-4996
=> [Dask] Fix dask CLI command for old mlrun clients

mlrun/config.py, mlrun/datastore/targets.py, requirements.txt, tests/test_requirements.py
[ML-4910](https://jira.iguazeng.com/browse/ML-4910)
=> [Feature Store] Fix `CSVTarget` in ingestion service, fix feature order in target with `after_step`

mlrun/runtimes/databricks_job/databricks_runtime.py, tests/runtimes/test_pod.py
Part of https://jira.iguazeng.com/browse/ML-4997
=> [Databricks] Accept `state_threshold` param

dockerfiles/mlrun/Dockerfile
Officially suggested by anaconda https://www.anaconda.com/blog/a-faster-conda-for-a-growing-community
=> [Images] Use libmamba solver for mlrun image

mlrun/datastore/targets.py
https://jira.iguazeng.com/browse/ML-5051
Fixing datastore profile target path resolution in CSV and Parquet targets
=> [Datastore] Fixing datastore profile target path resolution in CSV and Parquet targets

.github/workflows/ci.yaml, dockerfiles/test/Dockerfile
The unit test logs are so long that we 99% of the times have to read the raw logs to see the actual errors.
The color chars are making the raw logs difficult to read.
Before:
~~~
2023-11-19T10:42:10.6420809Z [31m[1m______________________ test_verify_session_success[async] ______________________[0m
2023-11-19T10:42:10.6420815Z 
2023-11-19T10:42:10.6420994Z api_url = 'http://iguazio-api-url:8080'
2023-11-19T10:42:10.6421333Z iguazio_client = <server.api.utils.clients.iguazio.AsyncClient object at 0x7f9134b38d30>
2023-11-19T10:42:10.6421565Z requests_mock = <requests_mock.mocker.Mocker object at 0x7f9134b38130>
2023-11-19T10:42:10.6421841Z aioresponses_mock = <aioresponses.core.aioresponses object at 0x7f9134b38dc0>
2023-11-19T10:42:10.6421847Z 
2023-11-19T10:42:10.6446822Z …
=> [CI] Disable github action color for unit tests job

docs/requirements.txt
https://jira.iguazeng.com/browse/ML-4861
=> [Docs] Bump sphinx and myst-nb

mlrun/datastore/targets.py
Fixes system test failures, but reopens [ML-4910](https://jira.iguazeng.com/browse/ML-4910).
=> [Datastore] Partially revert #4582

server/api/crud/workflows.py
Caused some system test failures
=> [Workflows] Fix workflow request notifications read

tests/system/feature_store/test_feature_store.py
Fix system test following changes in '[Storey] Make aggregations return NaN when there is no data except for count' pull request.
https://github.com/mlrun/mlrun/pull/4442
=> [Storey] Fix test for aggregations returning NaN

mlrun/runtimes/daskjob.py
https://jira.iguazeng.com/browse/ML-4997
=> [Dask] Do not support state thresholds

docs/runtimes/configuring-job-resources.md, mlrun/feature_store/feature_set.py
[ML-3379](https://jira.iguazeng.com/browse/ML-3379)
=> [Docs] Add "state_threshold" to monitoring

mlrun/api/main.py, mlrun/config.py, tests/api/test_collect_runs_logs.py
=> [Log Collector] Limit consecutive start log requests on failed runs [1.5.x]

mlrun/feature_store/retrieval/spark_merger.py
[ML-5022](https://jira.iguazeng.com/browse/ML-5022)
=> [Feature Store] Fix workaround for pyspark->pandas2 timestamp conversion issue

mlrun/config.py, mlrun/model_monitoring/batch_application.py
There are no logic changes (except a tiny one in [93e2df68b936c60fba69d1990770b820c4b56bcc](https://github.com/mlrun/mlrun/pull/4621/commits/93e2df68b936c60fba69d1990770b820c4b56bcc)).
Remove unused imports, code, and some other refactoring (`np.unique` -> `set`, `staticmethod` -> `classmethod`, use `mm_constants`).
I recommend going over it commit by commit.
This PR separates style changes from future changes in the interval logic.
=> [Model Monitoring] Refactor the controller code

mlrun/datastore/targets.py
* Deserialize `after_step` from target spec
* Force feature inference for side target
[ML-5039](https://jira.iguazeng.com/browse/ML-5039)
[ML-4910](https://jira.iguazeng.com/browse/ML-4910)
=> [Datastore] Fix feature inference in side target 

mlrun/datastore/sources.py, tests/system/test_aws_s3.py
https://jira.iguazeng.com/browse/ML-5083
=> [Datastore] Add support for datastore profile for CVS/Parquet sources

docs/change-log/index.md, docs/install/kubernetes.md, docs/install/remote.md
Backport of https://github.com/mlrun/mlrun/pull/4639/
=> [Docs] V1.5.2 change log  (#4639) [v1.5.x]

.gitignore, docs/conf.py, docs/feature-store/feature-vectors.md, mlrun/config.py, mlrun/db/httpdb.py, mlrun/package/__init__.py, mlrun/projects/project.py, mlrun/run.py, mlrun/runtimes/sparkjob/spark3job.py
Was raised by sphinx logs as warnings - unexpected indentation and friends
=> [Docs] Fix some docstring formatting issues

server/api/db/sqldb/db.py, tests/api/api/test_projects.py
resolves:
https://jira.iguazeng.com/browse/ML-5050
=> [API] Normalize project parameters when storing a project

mlrun/api/runtime_handlers/base.py, mlrun/config.py
https://jira.iguazeng.com/browse/ML-5148
=> [API] Reduce memory footprint of runs monitoring [1.5.x]

server/log-collector/cmd/logcollector/main.go, server/log-collector/pkg/services/logcollector/logcollector_test.go, server/log-collector/pkg/services/logcollector/server.go, server/log-collector/pkg/services/logcollector/statestore/abstract/client.go, server/log-collector/pkg/services/logcollector/statestore/factory/factory.go, server/log-collector/pkg/services/logcollector/statestore/file/client.go, server/log-collector/pkg/services/logcollector/statestore/file/file_test.go, server/log-collector/pkg/services/logcollector/statestore/inmemory/client.go, server/log-collector/pkg/services/logcollector/statestore/types.go, server/log-collector/pkg/services/logcollector/test/logcollector_test.go
For better debug-ability of the log collector.
To enable advanced log level, set the following env var to an int value >= 1:
```
MLRUN_LOG_COLLECTOR__ADVANCED_LOG_LEVEL
```
Related to https://jira.iguazeng.com/browse/ML-4843
=> [Log Collector] Add logs to adding/removing items from state

server/api/runtime_handlers/base.py, tests/api/runtime_handlers/test_kubejob.py
Following https://github.com/mlrun/mlrun/pull/4656 since we filter the run now
In case we find a runtime resource and its run was last updated over a week ago
=> [API] Search run if missing in monitoring

mlrun/datastore/utils.py, mlrun/feature_store/feature_set.py
Fixes `TestFeatureStore::test_passthrough_feature_set` as well as [ML-5145](https://jira.iguazeng.com/browse/ML-5145).
=> [Feature Store] Fix issues with default `start_time` and `end_time`

mlrun/api/runtime_handlers/base.py, tests/api/runtime_handlers/test_kubejob.py
(cherry picked from commit f300671fbd8ee4d9950cb6387c8ce04f8293a7c4)
=> [API] Search run if missing in monitoring [1.5.x]

server/api/runtime_handlers/base.py, tests/api/api/test_runs.py, tests/api/runtime_handlers/test_kubejob.py, tests/api/runtime_handlers/test_mpijob.py, tests/api/runtime_handlers/test_sparkjob.py
https://jira.iguazeng.com/browse/ML-5154
=> [API] Move automated run abortion text to `status.error`

mlrun/config.py
[ML-4895](https://jira.iguazeng.com/browse/ML-4895)
=> [Config] Enable explicit ack on nuclio 1.12.7 or newer only

server/api/runtime_handlers/daskjob.py
https://jira.iguazeng.com/browse/ML-5185
=> [Dask] Retry reconnection before bailing upon connection error

mlrun/serving/server.py
Related to [ML-4959](https://jira.iguazeng.com/browse/ML-4959).
=> [Serving] Add logs to termination callback

mlrun/datastore/targets.py
Related to [ML-5108](https://jira.iguazeng.com/browse/ML-5108).
=> [Datastore] Avoid saving function in target attributes

mlrun/runtimes/function.py
[ML-4826](https://jira.iguazeng.com/browse/ML-4826)
=> [Runtimes] Use HTTP connection pool to speed up function invocations

tests/system/feature_store/test_feature_store.py
=> [Tests] Fix `TestFeatureStore` system tests

mlrun/feature_store/steps.py
[ML-4923](https://jira.iguazeng.com/browse/ML-4923)
=> [Feature Store] Improve `OneHotEncoder` warning

mlrun/__main__.py, server/api/crud/runs.py, server/api/runtime_handlers/base.py, server/api/runtime_handlers/kubejob.py, server/api/runtime_handlers/mpijob/v1.py, server/api/runtime_handlers/mpijob/v1alpha1.py, server/api/runtime_handlers/remotesparkjob.py, server/api/runtime_handlers/sparkjob/spark3job.py, server/api/utils/singletons/k8s.py, tests/api/conftest.py, tests/api/crud/test_runs.py, tests/api/runtimes/base.py
https://jira.iguazeng.com/browse/ML-4883
=> [API] Delete runtime resources before deleting run

mlrun/datastore/sources.py, mlrun/datastore/targets.py
https://jira.iguazeng.com/browse/ML-5240
Fix passing storage options to spark session for S3
=> [Spark] Fix datastore profile bug

docs/index.md
from /tutorial/ to /tutorials/
=> [Docs] Repair other urls

mlrun/datastore/targets.py, mlrun/serving/states.py
[ML-5108](https://jira.iguazeng.com/browse/ML-5108)
=> [Serving] Fix YAML serialization error in serving and ingestion service

mlrun/projects/operations.py, mlrun/projects/project.py, mlrun/runtimes/kubejob.py, mlrun/utils/helpers.py
https://jira.iguazeng.com/browse/ML-4867
=> [SDK] Add warning for overwrite build params default change

mlrun/utils/helpers.py, tests/integration/sdk_api/httpdb/test_exception_handling.py, tests/launcher/test_local.py, tests/launcher/test_remote.py, tests/run/test_run.py
Improve readability for a few exceptions
=> [Exception] Improve readability

server/api/crud/runs.py, tests/api/crud/test_runs.py
https://jira.iguazeng.com/browse/ML-5276
=> [CRUD] Validate run state before deletion

requirements.txt, tests/test_requirements.py
[ML-5298](https://jira.iguazeng.com/browse/ML-5298)
[ML-5299](https://jira.iguazeng.com/browse/ML-5299)
=> [Requirements] Bump storey to 1.6.11

.flake8, .github/workflows/ci.yaml, .gitignore, Makefile, dev-requirements.txt, mlrun/datastore/datastore_profile.py, mlrun/datastore/targets.py, mlrun/feature_store/feature_vector.py, mlrun/feature_store/steps.py, mlrun/frameworks/_common/model_handler.py, mlrun/frameworks/lgbm/mlrun_interfaces/booster_mlrun_interface.py, mlrun/frameworks/pytorch/callbacks/tensorboard_logging_callback.py, mlrun/frameworks/sklearn/metric.py, mlrun/frameworks/tf_keras/mlrun_interface.py, mlrun/runtimes/local.py, mlrun/utils/db.py, mlrun/utils/helpers.py, pyproject.toml, tests/api/db/test_runs.py, tests/api/runtime_handlers/test_kubejob.py, tests/frameworks/lgbm/test_lgbm.py, tests/frameworks/test_ml_frameworks.py, tests/integration/sdk_api/httpdb/runs/test_runs.py, tests/rundb/test_unit_httpdb.py, tests/system/model_monitoring/test_model_monitoring.py, tests/test_config.py
The first part of [ML-5300](https://jira.iguazeng.com/browse/ML-5300).
- Move the configuration
- Adapt commands
- Adapt requirements
- Fix new reported errors
I recommend reviewing the changes commit by commit.
https://docs.astral.sh/ruff/linter/
=> [Linting] Add Ruff linter - replace isort & flake8

mlrun/feature_store/api.py
https://jira.iguazeng.com/browse/ML-4622
=> [Featurestore] Add future deprecation messages to several APIs

mlrun/__main__.py, mlrun/config.py, mlrun/db/httpdb.py, tests/rundb/test_unit_httpdb.py
Resolves:
https://jira.iguazeng.com/browse/ML-4749
=> [Logs] Refactor get_log & watch_log functions for better log retrieval

mlrun/runtimes/constants.py, server/api/crud/runs.py, tests/api/crud/test_runs.py
Change run state to aborting while it is being aborted.
=> [API] Add aborting state

mlrun/feature_store/api.py
This reverts commit 14e16377e5dfefee60c31785774ff08b2e9f7ba7.
Fixes [ML-5343](https://jira.iguazeng.com/browse/ML-5343).
=> Revert "[Featurestore] Add future deprecation messages to several APIs (#4754)"

mlrun/feature_store/retrieval/base.py
Seems to have been accidentally removed in #3672.
=> [Feature Store] Add missing annotation

mlrun/runtimes/local.py, mlrun/track/tracker_manager.py
No need for this extra commit if there are no trackers
=> [Tracker] Don't commit run if no trackers

mlrun/model.py, mlrun/runtimes/constants.py
https://jira.iguazeng.com/browse/ML-5339
Return the fields regardless of the state
=> [Run] Fix state validation in error property getter

requirements.txt, tests/system/feature_store/test_feature_store.py, tests/test_requirements.py
1) Bump storey to handle large single parquet ingest....
2) Add system test.
[ML-5119](https://jira.iguazeng.com/browse/ML-5119)
=> [Requirements] Ingest large df - bump story to 1.6.12

mlrun/common/schemas/frontend_spec.py, mlrun/config.py, server/api/api/endpoints/frontend_spec.py, tests/api/api/test_frontend_spec.py
[ML-4894](https://jira.iguazeng.com/browse/ML-4894)
=> [API] Add model monitoring dashboard URL to frontend spec 

tests/system/feature_store/test_feature_store.py
Change large df ingest test target path.
Following https://github.com/mlrun/mlrun/pull/4777
=> [Tests] Change test target path

mlrun/utils/helpers.py, server/api/db/sqldb/db.py
https://jira.iguazeng.com/browse/ML-5195
=> [Pipelines] Default workflow status to unknown if status is missing

mlrun/datastore/datastore_profile.py, mlrun/feature_store/api.py
https://jira.iguazeng.com/browse/ML-5056
=> [Datastore] Remove store type embedding in URL

mlrun/datastore/s3.py, mlrun/datastore/sources.py, mlrun/datastore/targets.py, mlrun/feature_store/api.py, tests/system/feature_store/test_spark_s3.py
https://jira.iguazeng.com/browse/ML-5292 (WIP - still does not resolve it)
=> [Datastore] Fix datastore hadoop based profiles handling in Spark (s3)

server/api/api/endpoints/functions.py
[ML-5363](https://jira.iguazeng.com/browse/ML-5363)
=> [API] Fix call to v3io stream `create()`

mlrun/datastore/azure_blob.py, tests/system/datastore/test_azure.py
[ML-5375](https://jira.iguazeng.com/browse/ML-5375)
=> [Datastore] fix purge_targets on azure datastore

mlrun/feature_store/api.py, mlrun/feature_store/feature_set.py, mlrun/feature_store/feature_vector.py, tests/feature-store/test_featureset.py, tests/feature-store/test_featurevec.py
https://jira.iguazeng.com/browse/ML-4622
=> [Featurestore] Add future deprication messages to several APIs

mlrun/datastore/datastore.py
https://jira.iguazeng.com/browse/ML-5182
=> [Datastore] Fix store manager reading datastore profile

mlrun/config.py
[ML-5392](https://jira.iguazeng.com/browse/ML-5392)
Also raises minimum nuclio version to latest for important fixes.
=> [Config] Fix nuclio version resolution for explicit ack

mlrun/db/httpdb.py
https://jira.iguazeng.com/browse/ML-4386
=> [HTTPDB] Warn list runs with notification does not include local runs

automation/patch_igz/patch_remote.py
Allow to specify tag for image in patch_remote defaulting to latest and greatest
=> [Automation] Support specific tag

mlrun/config.py, mlrun/model.py, mlrun/runtimes/base.py, mlrun/runtimes/constants.py, mlrun/runtimes/pod.py, tests/api/runtime_handlers/test_kubejob.py, tests/api/runtime_handlers/test_mpijob.py, tests/api/runtime_handlers/test_sparkjob.py, tests/api/runtimes/test_kubejob.py, tests/api/test_launcher.py
https://jira.iguazeng.com/browse/ML-5373
=> [KubeResource] Rename state threshold `running` to `executing`

dev-requirements.txt, tests/api/utils/test_scheduler.py
https://jira.iguazeng.com/browse/ML-5213
=> [Tests] Rerun flaky scheduler test

mlrun/datastore/sources.py
[ML-5350](https://jira.iguazeng.com/browse/ML-5350)
=> [Datastore] Fix key field propagation from `FeatureSet` to `OnlineSource`

.github/workflows/system-tests-enterprise-v2.yml
work is tbd, current system tests will keep on running using github runners
=> [CI] Run system test on self hosted runners

requirements.txt, tests/test_requirements.py
[ML-5351](https://jira.iguazeng.com/browse/ML-5351)
[ML-5352](https://jira.iguazeng.com/browse/ML-5352)
=> [Requirements] Bump storey to 1.6.12

mlrun/projects/project.py
https://jira.iguazeng.com/browse/ML-4784
=> [Project] Set default build base image

requirements.txt, tests/test_requirements.py
[ML-5104](https://jira.iguazeng.com/browse/ML-5104)
=> [Requirements] Bump storey to 1.6.14

server/api/runtime_handlers/base.py, server/api/utils/builder.py
https://jira.iguazeng.com/browse/ML-5198
=> [API] Fix log of runtime attribute

docs/runtimes/load-from-hub.md
[ML-3370](https://jira.iguazeng.com/browse/ML-3370)
=> [Docs] Add creating and using a custom/private hub

server/api/api/endpoints/artifacts.py, tests/api/api/test_artifacts.py, tests/api/api/test_projects.py, tests/integration/sdk_api/httpdb/test_exception_handling.py
=> [API] Remove deprecated artifacts endpoints

.github/workflows/release.yaml, Makefile, dev-requirements.txt, setup.py
https://jira.iguazeng.com/browse/ML-5435 - [https://packaging.python.org/en/latest/discussions/setup-py-deprecated/](https://packaging.python.org/en/latest/discussions/setup-py-deprecated/:)
license update - https://jira.iguazeng.com/browse/ML-5436
=> [Build] Update build command

.github/workflows/system-tests-enterprise.yml
Adding workspace to be a safe directory to allow executing git commands within dir
=> [CI] Fix system tests using git examples

server/api/crud/runs.py, tests/api/crud/test_runs.py
https://jira.iguazeng.com/browse/ML-5394
=> [API] Fix delete runs error status code

tests/system/runtimes/test_archives.py
ensure project is overwritten in case it exists
=> [CI] Fix system test existing project [1.5.x]

tests/system/runtimes/test_archives.py
=> [CI] Fix system test existing project

.github/workflows/system-tests-opensource.yml, automation/system_test/prepare.py
bumped kubernetes version as well
=> [CI] Fix open source system test missing deleted argument

dev-requirements.txt, mlrun/frameworks/parallel_coordinates.py, tests/pytest.ini
allowing to stop hanging/deadlock tests faster
=> [CI] Timeout pytest cases

tests/system/examples/basics/test_db.py
task name is now prepend to artifact key
=> [CI] Fix test artifact keys

mlrun/datastore/azure_blob.py, mlrun/datastore/sources.py, mlrun/datastore/targets.py, mlrun/datastore/utils.py, tests/system/feature_store/spark_hadoop_test_base.py, tests/system/feature_store/test_spark_azure.py, tests/system/feature_store/test_spark_s3.py
https://jira.iguazeng.com/browse/ML-5258
=> [Spark] Make spark work with azure datastore profile

mlrun/model_monitoring/writer.py, tests/system/model_monitoring/assets/application.py, tests/system/model_monitoring/test_app.py
Fixes [ML-5462](https://jira.iguazeng.com/browse/ML-5462).
Add the case to the system test.
=> [Model Monitoring] Fix saving multiple metrics in the TSDB

mlrun/projects/project.py, tests/projects/test_project.py
review made in :
https://github.com/mlrun/mlrun/pull/4835
resolves :
https://jira.iguazeng.com/browse/ML-5078
=> [Project] Enable adding git to a project after project creation

mlrun/datastore/google_cloud_storage.py, tests/integration/google_cloud_storage/test_google_cloud_storage.py, tests/system/datastore/test_google_cloud_storage.py
https://jira.iguazeng.com/browse/ML-5451
=> [Datastore] Allow passing GCS credentials as a json string

mlrun/datastore/datastore_profile.py, mlrun/datastore/google_cloud_storage.py, mlrun/datastore/utils.py, tests/system/feature_store/test_spark_gcs.py
https://jira.iguazeng.com/browse/ML-5257
=> [Spark] Add support for GCS datastore profiles

server/api/api/endpoints/artifacts_v2.py, server/api/crud/artifacts.py
following the PR which refactors the artifacts :
https://github.com/mlrun/mlrun/pull/4753
new create_artifact function was added, so we should do the artifact size calculating also there.
=> [Artifacts] calculate artifact size on create artifact

mlrun/runtimes/databricks_job/databricks_wrapper.py, tests/system/runtimes/test_databricks.py
[ML-5478](https://jira.iguazeng.com/browse/ML-5478)
=> [Datastore] Databricks artifact path - support another type of spark path.

mlrun/artifacts/base.py, mlrun/artifacts/dataset.py, mlrun/artifacts/model.py, mlrun/datastore/store_resources.py, tests/system/examples/jobs/test_jobs.py
=> [System test] Fix expected artifact URI

requirements.txt, tests/test_requirements.py
[ML-5442](https://jira.iguazeng.com/browse/ML-5442)
=> [Requirements] Bump storey to 1.6.16

mlrun/db/httpdb.py, mlrun/utils/helpers.py, server/api/utils/builder.py
https://jira.iguazeng.com/browse/ML-5471
=> [Build] Warn ECR and S3 permissions conflict

mlrun/projects/project.py
https://jira.iguazeng.com/browse/ML-5463
=> [Project] Raise error on invalid export path

mlrun/db/httpdb.py, server/api/api/endpoints/background_tasks.py, server/api/db/base.py, server/api/db/sqldb/db.py, server/api/utils/background_tasks/internal.py, server/api/utils/background_tasks/project.py, tests/api/api/test_background_tasks.py, tests/api/db/test_background_tasks.py, tests/system/runtimes/test_kubejob.py
Add list project background tasks endpoint.
Support for filters (default filter is created in the last 7 days)
And check timeouts of background tasks
https://jira.iguazeng.com/browse/ML-5515
=> [API] Support list project background tasks

requirements.txt
[ML-5509](https://jira.iguazeng.com/browse/ML-5509)
=> [Kafka] Bump v3io-frames to fix numpy compatibility issue

docs/deployment/index.md, docs/install.md, docs/install/aws-install.md, docs/install/local-docker.md, docs/monitoring/index.md, docs/projects/run-build-deploy.md, docs/serving/serving-overview.md, docs/training/working-with-data-and-model-artifacts.md
[ML-5481](https://jira.iguazeng.com/browse/ML-5481)
=> [Docs] Add example of build_image using project source

mlrun/runtimes/serving.py
[ML-5506](https://jira.iguazeng.com/browse/ML-5506)
=> [Serving] Fix setting of max_workers for v3io-stream-trigger to use maxWorkers name

mlrun/runtimes/databricks_job/databricks_runtime.py
[ML-5516](https://jira.iguazeng.com/browse/ML-5516)
=> [Runtimes] Databricks backward compatibility - wrapper usage

mlrun/datastore/sources.py
[ML-5499](https://jira.iguazeng.com/browse/ML-5499)
=> [Kafka] Force number of replicas of 1 when nuclio is too old

mlrun/model_monitoring/controller.py, mlrun/runtimes/serving.py, tests/model_monitoring/test_helpers.py
[ML-5497](https://jira.iguazeng.com/browse/ML-5497)
=> [Model Monitoring] Change default last analyzed to be the latest between first request time or last update time

mlrun/data_types/to_pandas.py
https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
=> [Core] Fix deprecated numpy type

tests/system/model_monitoring/test_model_monitoring.py
[ML-5080](https://jira.iguazeng.com/browse/ML-5080)
=> [Tests] Fix context carryover between model monitoring tests

mlrun/model_monitoring/stream_processing.py
First introduce in #4889 
[ML-5513](https://jira.iguazeng.com/browse/ML-5513)
=> [Model Monitoring] Fix (remove) redundent convert to `datetime` in stream pod

mlrun/artifacts/base.py, mlrun/artifacts/dataset.py, mlrun/artifacts/manager.py, mlrun/artifacts/model.py, mlrun/artifacts/plots.py, mlrun/db/httpdb.py, mlrun/lists.py, mlrun/projects/project.py, mlrun/serving/routers.py, mlrun/serving/server.py, mlrun/serving/utils.py, server/api/db/sqldb/db.py
https://jira.iguazeng.com/browse/ML-5525
=> [SDK] Todos and deprecations chore

mlrun/datastore/targets.py, tests/datastore/test_targets.py
[ML-5484](https://jira.iguazeng.com/browse/ML-5484)
=> [Datastore] Remove run ID from `StreamTarget` path

mlrun/datastore/azure_blob.py, mlrun/datastore/base.py, mlrun/datastore/dbfs_store.py, mlrun/datastore/filestore.py, mlrun/datastore/google_cloud_storage.py, mlrun/datastore/redis.py, mlrun/datastore/s3.py, mlrun/datastore/targets.py, mlrun/datastore/v3io.py, mlrun/model_monitoring/controller.py, tests/system/feature_store/test_feature_store.py, tests/system/feature_store/test_spark_engine.py, tests/test_datastores.py
https://jira.iguazeng.com/browse/ML-5510
Refactoring an internal get_filesystem() method
=> [Datastore] Refactor internal get_filesystem() method

mlrun/model_monitoring/controller.py, mlrun/model_monitoring/controller_handler.py, mlrun/model_monitoring/helpers.py, mlrun/utils/logger.py, tests/model_monitoring/test_helpers.py, tests/system/model_monitoring/test_app.py
Resolves [ML-5347](https://jira.iguazeng.com/browse/ML-5347).
=> [Model Monitoring] Improve the controller job's logs

server/api/db/sqldb/db.py
https://docs.sqlalchemy.org/en/14/orm/query.html#sqlalchemy.orm.Query.with_for_update
Relates to - https://github.com/mlrun/mlrun/pull/4938
Makes updating runs a transaction (locks the row in the DB). This is needed mainly for runs with workers (mpi) where the context can send concurrent update requests from different workers.
Options explanation:
- read - renders LOCK IN SHARE MODE set shared locks that permit other transactions to read the examined rows but not to update or delete them 
- nowait - renders to NOWAIT, raises an error when lockd, set to False
- of - specifies which table to lock (not supported in mysql and sqlite according to sqlalchemy 1.4 docs but is supported according to mysql in https://dev.mysql.com/doc/refman/8.0/en/select.html)
- skip_locked - gives only rows that …
=> [SQLDB] Lock run row on update

mlrun/datastore/sources.py, mlrun/datastore/targets.py
[ML-4899](https://jira.iguazeng.com/browse/ML-4899)
All TestFeatureStoreSqlDB are passed after the deletion
=> [Data Store] Delete deprecated param from `SQLTarget` & `SQLSource`.

docs/data-prep/ingest-data-fs.md
[ML-4899](https://jira.iguazeng.com/browse/ML-4899)
Following #4955.
=> [Docs] Replace deprecated SQL parameter in documentation

mlrun/launcher/base.py, mlrun/model.py, mlrun/runtimes/base.py, mlrun/runtimes/constants.py, mlrun/runtimes/local.py
https://jira.iguazeng.com/browse/ML-5517
Some changes to make sure that databricks runs do not go from aborting to error before moving to aborted
=> [Databricks] Fix abortion state transitions

automation/deployment/deployer.py, mlrun/feature_store/retrieval/job.py, mlrun/runtimes/kubejob.py, server/api/api/endpoints/functions.py, server/api/api/utils.py, tests/api/api/test_functions.py
Make the script nicer to develop and more concise instead of having to pass the parameters everywhere
=> [Automation] Nest CE deployment args under object

automation/requirements.txt, dev-requirements.txt, docs/requirements.txt, requirements.txt, tests/test_requirements.py
In addition, added some logic to filter out safe-requirements from "invalid" map of requirements, leaving less work for developers to update upon need
=> [Requirements] Remedy vulnerabilities

mlrun/datastore/targets.py, mlrun/model.py, mlrun/platforms/iguazio.py, tests/datastore/test_targets.py
[ML-5559](https://jira.iguazeng.com/browse/ML-5559)
[ML-5560](https://jira.iguazeng.com/browse/ML-5560)
=> [Datastore] Return correct path in kafka and stream targets

server/api/crud/model_monitoring/deployment.py
Enforce the base-period > `config.httpdb.scheduling.min_allowed_interval` 
[ML-5256](https://jira.iguazeng.com/browse/ML-5256)
In the system test we all ready have config map with : "MLRUN_HTTPDB__SCHEDULING__MIN_ALLOWED_INTERVAL": "0 Seconds". (automation/system_test/prepare.py)
=> [Model Monitoring] Delete controller job if the schedule submission went wrong

mlrun/common/schemas/client_spec.py, mlrun/common/schemas/frontend_spec.py, mlrun/db/httpdb.py, mlrun/render.py, server/api/api/endpoints/frontend_spec.py, server/api/api/endpoints/functions.py, server/api/crud/client_spec.py, tests/api/api/test_client_spec.py, tests/api/api/test_frontend_spec.py, tests/api/api/test_functions.py, tests/api/api/test_projects.py
=> [SDK] Remove deprecated fields

mlrun/model_monitoring/controller.py
Resolves [ML-5453](https://jira.iguazeng.com/browse/ML-5453).
Since all apps have the same policy, log the results in the format:
```
{"model-endpoint": ["window-i-start", "window-i+1-start"]}
```
When an application is triggered - the UI shows an explicit result in the run's row:
The relevant system test passed (`pytest tests/system/model_monitoring/test_app.py::TestMonitoringAppFlow`).
=> [Model Monitoring] Log windows result in the controller job

server/api/db/sqldb/db.py
https://jira.iguazeng.com/browse/ML-4991
=> [DB] Lock run db row on store run

mlrun/model_monitoring/stores/kv_model_endpoint_store.py, requirements.txt
Also:
* Bump v3io-frames
* Reduce except clause following frames fix in https://github.com/v3io/frames/pull/663
[ML-5583](https://jira.iguazeng.com/browse/ML-5583)
=> [Model Monitoring] Remove unhelpful warning

mlrun/datastore/sources.py, mlrun/datastore/spark_utils.py, mlrun/datastore/targets.py
https://jira.iguazeng.com/browse/ML-5476
=> [Spark] Make Hadoop options compatible with lazy operations

requirements.txt, tests/system/feature_store/test_feature_store.py, tests/test_requirements.py
- bump storey.
- add tests.
[ML-5576](https://jira.iguazeng.com/browse/ML-5576)
=> [Feature Store] fix Ingest data with single quotes in v3io engine

docs/serving/graph-ha-cfg.md
[ML-5545](https://jira.iguazeng.com/browse/ML-5545)
=> [Docs] Setting `min_replicas` and `max_replicas` in `KafkaSource`

mlrun/datastore/datastore_profile.py
https://jira.iguazeng.com/browse/ML-5595
=> [Datastore] Forbid unlisted parameters in datastore profile initialization

mlrun/runtimes/utils.py
https://jira.iguazeng.com/browse/ML-5417
=> [SDK] Remove no git warning when not a git repo

server/api/api/endpoints/functions.py
https://jira.iguazeng.com/browse/ML-5633
=> [API] Fix delete schedule reroute to chief

dockerfiles/mlrun/Dockerfile
Required in order to build horovod
https://jira.iguazeng.com/browse/ML-4585
=> [Images] Add CMAKE to mlrun/mlrun

dockerfiles/README.md, docs/runtimes/images.md
https://jira.iguazeng.com/browse/ML-5641
=> [Docs] Fix images description

mlrun/datastore/utils.py, tests/datastore/test_sources.py
[ML-5661](https://jira.iguazeng.com/browse/ML-5661)
=> [Datastore] Fix `ValueError` when parsing a timestamp string column with pandas 1

tests/system/projects/test_project.py
Port the fix in #4999 to 1.6.x
=> [Project] Fix load project with artifacts test [1.6.x]

mlrun/datastore/utils.py, tests/datastore/test_sources.py
[ML-5661](https://jira.iguazeng.com/browse/ML-5661)
Cherry-pick of #5053 / d978962.
=> [Datastore] Fix ValueError when parsing a timestamp string column with pandas 1 [1.6.x]

mlrun/datastore/sources.py
https://jira.iguazeng.com/browse/ML-5579
=> [Datastore] Clarify error messages when using spark to ingest unsupported sources

mlrun/datastore/datastore.py, mlrun/datastore/datastore_profile.py, server/api/api/endpoints/files.py, server/api/crud/datastore_profiles.py, server/api/rundb/sqldb.py, tests/api/api/test_files.py
https://jira.iguazeng.com/browse/ML-5638
https://jira.iguazeng.com/browse/ML-5634
=> [Datastore] Fix previewing artifacts associated with datastore profile

mlrun/model_monitoring/stream_processing.py
port from #5058 
(cherry picked from commit 376340de273675eee4d6b67d0aae43d2775256a3)
=> [Model Monitoring] Fix path filtering according to nuclio changes [1.6.x]

mlrun/artifacts/manager.py, tests/artifacts/test_artifacts.py
1)Added to `ensure_artifact_source_file_exists` artifact.df case....
2) Added tests.
[ML-5644](https://jira.iguazeng.com/browse/ML-5644)
=> [Artifacts] Fix log dataset artifact with df

server/api/crud/model_monitoring/deployment.py
[ML-5666](https://jira.iguazeng.com/browse/ML-5666)
=> [Model Monitoring] Enable explicit ack for V3IO streams

server/api/crud/model_monitoring/model_endpoints.py
[ML-5673](https://jira.iguazeng.com/browse/ML-5673)
=> [Model Monitoring] Saving feature_stats as empty dict and not as null in the model_endpoint

docs/monitoring/dashboards/model-monitoring-details.json, server/api/api/endpoints/grafana_proxy.py
=> [Grafana] Set MLRun API datasource for `Feature Analysis` chart [1.6.x]

mlrun/artifacts/manager.py, tests/artifacts/test_artifacts.py
[ML-5644](https://jira.iguazeng.com/browse/ML-5644)
=> [Artifacts] Fix log dataset artifact with df [1.6.x]

mlrun/datastore/datastore.py, mlrun/datastore/datastore_profile.py, server/api/api/endpoints/files.py, server/api/crud/datastore_profiles.py, server/api/rundb/sqldb.py, tests/api/api/test_files.py
https://jira.iguazeng.com/browse/ML-5638
https://jira.iguazeng.com/browse/ML-5634
=> [Datastore] Fix previewing artifacts associated with datastore profile [1.6.x] 

server/api/api/endpoints/workflows.py, tests/api/api/test_workflows.py
(cherry picked from commit c3daa20dedb1c78d1b512385537f38b47088a007)
=> [API] Do not enrich workflow schedule when given spec [1.6.x]

server/api/api/endpoints/jobs.py, server/api/utils/clients/chief.py
=> [Model Monitoring] Fix monitoring jobs API query permissions [1.6.x]

server/api/utils/auth/verifier.py, server/api/utils/clients/chief.py, server/api/utils/clients/iguazio.py, tests/api/utils/clients/test_chief.py, tests/api/utils/clients/test_iguazio.py
Send x-request-id within request to iguazio/chief when possible
https://jira.iguazeng.com/browse/ML-5649
=> [AsyncHTTPClient] Let it a be more traceable

server/api/crud/model_monitoring/deployment.py
[ML-5666](https://jira.iguazeng.com/browse/ML-5666)
Backport of #5071 / d407c53.
=> [Model Monitoring] Enable explicit ack for V3IO streams [1.6.x]

mlrun/serving/states.py
According to #4702.
Fix system test failure  https://github.com/mlrun/mlrun/actions/runs/7778159227
=> [Serving] Add init to `ErrorStep` class

mlrun/feature_store/api.py
https://jira.iguazeng.com/browse/ML-5642
=> [FeatureStore] Fix misleading deprecation messages [1.6.x]

server/api/crud/projects.py
=> [Project] Fix DELETE Project not returning 412 when Nuclio functions exists [1.6.x]

mlrun/datastore/google_cloud_storage.py, tests/datastore/test_google_cloud_storage.py
https://jira.iguazeng.com/browse/ML-5688
=> [Datastore] Fix GCS storage options handling

tests/system/projects/test_project.py
https://github.com/mlrun/mlrun/pull/5093 to 1.6.x
=> [SystemTest] Ensure parquet file when creating dataframe [1.6.x]

dockerfiles/jupyter/requirements.txt, requirements.txt
https://github.com/nuclio/nuclio-jupyter/releases/tag/v0.9.16
=> [Dependencies] Bump nuclio-jupyter to 0.9.16

mlrun/datastore/google_cloud_storage.py, tests/datastore/test_google_cloud_storage.py
https://jira.iguazeng.com/browse/ML-5688
=> [Datastore] Fix GCS storage options handling [1.6.x]

mlrun/config.py, server/api/api/endpoints/projects.py, server/api/api/utils.py, server/api/crud/projects.py, server/api/utils/clients/nuclio.py, server/api/utils/projects/follower.py, server/api/utils/projects/leader.py, server/api/utils/projects/remotes/follower.py, server/api/utils/projects/remotes/nop_follower.py, tests/api/utils/projects/test_leader_member.py
porting (#5096) to 1.6.x
https://jira.iguazeng.com/browse/ML-5588
=> [Project] Wait for project to be deleted in Nuclio when deleting project [1.6.x]

server/api/api/endpoints/projects.py, server/api/api/endpoints/projects_v2.py
A regression where the auth info was not passed correctly
https://jira.iguazeng.com/browse/ML-5695
=> [Projects] Fix project deletion missing auth_info [1.6.x]

server/api/api/endpoints/projects.py, server/api/api/endpoints/projects_v2.py
porting (#5102) to development
=> [Projects] Fix project deletion missing auth_info

server/api/crud/projects.py
=> [Project] Ensure nuclio function pods are deleted [1.6.x]

mlrun/datastore/sources.py, mlrun/runtimes/nuclio/function.py, mlrun/runtimes/nuclio/serving.py, server/api/crud/model_monitoring/deployment.py
[ML-5698](https://jira.iguazeng.com/browse/ML-5698)
=> [Datastore] Fix nuclio deprecation warnings

mlrun/datastore/sources.py, mlrun/runtimes/nuclio/serving.py
[ML-5693](https://jira.iguazeng.com/browse/ML-5693)
=> [Kafka] Default `max_workers` to 1 instead of 4

mlrun/datastore/sources.py, mlrun/runtimes/serving.py
[ML-5693](https://jira.iguazeng.com/browse/ML-5693)
Cherry-pick of #5111 / 06775de.
=> [Kafka] Default `max_workers` to 1 instead of 4 [1.6.x]

mlrun/feature_store/api.py, mlrun/feature_store/feature_set.py
https://jira.iguazeng.com/browse/ML-5711
=> [Documentation] Fix doc strings for several feature set APIs

mlrun/feature_store/api.py, mlrun/feature_store/feature_set.py
https://jira.iguazeng.com/browse/ML-5711
=> [Documentation] Fix doc strings for several feature set APIs [1.6.x]

mlrun/artifacts/manager.py, tests/system/api/test_artifacts.py
https://github.com/mlrun/mlrun/pull/5115
=> [Artifacts] Fix import artifact bug [1.6.x]

server/api/crud/projects.py, server/api/utils/projects/follower.py, tests/api/utils/projects/test_follower_member.py
=> [Project] Fix Project Deletion Failure due to Project Sync Race Condition [1.6.x]

mlrun/serving/routers.py
[ML-5590](https://jira.iguazeng.com/browse/ML-5590)
Backport of #5018 / 45a1cee.
=> [Serving] update api call of get_online_service [1.6.x]

mlrun/datastore/datastore.py, mlrun/datastore/datastore_profile.py
https://jira.iguazeng.com/browse/ML-5716
=> [Datastore] Correct the passing of the secret to the profile reader

docs/tutorials/01-mlrun-basics.ipynb
https://jira.iguazeng.com/browse/ML-5508
=> [Docs] Bump sklearn and numpy in tutorials [1.6.x]

docs/tutorials/01-mlrun-basics.ipynb
https://jira.iguazeng.com/browse/ML-5508
=> [Docs] Bump sklearn and numpy in tutorials

mlrun/projects/project.py, mlrun/utils/helpers.py, tests/utils/test_helpers.py
Allowing usernames with "@" and "." to be able to create projects while setting `user_project=True`.
https://jira.iguazeng.com/browse/ML-5721
=> [Projects] Support email-like username

mlrun/projects/project.py, mlrun/utils/helpers.py, tests/utils/test_helpers.py
=> [Projects] Support email-like username [1.6.x]

mlrun/datastore/datastore.py, mlrun/datastore/datastore_profile.py
https://jira.iguazeng.com/browse/ML-5716
=> [Datastore] Correct the passing of the secret to the profile reader [1.6.x]

mlrun/feature_store/api.py, mlrun/feature_store/feature_vector.py
https://jira.iguazeng.com/browse/ML-5711
=> [Documentation] Fix doc strings for several feature vector APIs

mlrun/serving/routers.py
Wrong reference was introduced in #5018.
[ML-5728](https://jira.iguazeng.com/browse/ML-5728)
=> [Serving] Fix reference to nonexistent field

mlrun/feature_store/api.py, mlrun/feature_store/feature_vector.py
https://jira.iguazeng.com/browse/ML-5711
=> [Documentation] Fix doc strings for several feature vector APIs [1.6.x]

mlrun/datastore/datastore_profile.py
https://jira.iguazeng.com/browse/ML-5736
=> [Datatstore] Fix artifact preview/download the from GUI

mlrun/datastore/datastore_profile.py
https://jira.iguazeng.com/browse/ML-5736
=> [Datatstore] Fix artifact preview/download the from GUI [1.6.x]

mlrun/model_monitoring/stream_processing.py
=> [Mode Monitoring] Fix merge issues

docs/data-prep/index.md, docs/runtimes/serving-function.md
[ML-5563](https://jira.iguazeng.com/browse/ML-5563)
=> [Doc] Update serving example

mlrun/config.py, server/api/runtime_handlers/base.py, server/api/utils/singletons/k8s.py, tests/api/runtime_handlers/base.py
https://jira.iguazeng.com/browse/ML-5756
1. Increase timeout waiting for CRD deletion to 5 mins and make configurable
2. Add force deletion if timeout passed
=> [API] Add force CRD deletion after timeout [1.6.x]

mlrun/k8s_utils.py, mlrun/projects/project.py, mlrun/utils/helpers.py, mlrun/utils/regex.py, server/api/utils/projects/follower.py, server/api/utils/projects/leader.py, server/api/utils/projects/member.py, tests/api/api/test_projects.py, tests/api/utils/projects/test_leader_member.py, tests/projects/test_project.py
Ensure projects have valid name and labels prior to creation / update to adhere k8s conventions made by mlrun co-existing friend - Nuclio
https://jira.iguazeng.com/browse/ML-5746
=> [Project] Validate project labels upon creation/update

mlrun/k8s_utils.py, mlrun/projects/project.py, mlrun/utils/helpers.py, mlrun/utils/regex.py, server/api/utils/projects/follower.py, server/api/utils/projects/leader.py, server/api/utils/projects/member.py, tests/api/api/test_projects.py, tests/api/utils/projects/test_leader_member.py, tests/projects/test_project.py
=> [Project] Validate project labels upon creation/update [1.6.x]

dockerfiles/mlrun-api/requirements.txt
mitigating https://github.com/encode/uvicorn/pull/2243
=> [API] Bump uvicorn [1.6.x]

server/api/common/runtime_handlers.py, server/api/utils/singletons/k8s.py
https://jira.iguazeng.com/browse/ML-5721
=> [K8s] Support email-like usernames

docs/data-prep/logging_datasets.md
`run_local` is not a thing anymore
=> [Docs] Update logging datasets page

docs/change-log/index.md, docs/store/datastore.md
(cherry picked from commit bf9bd39dc4c46e2f2563ee27d58ac7e6a8fa3c43)
=> [Docs] Add v1.6.0 change log

mlrun/feature_store/feature_vector.py
=> [Docs] Repair FeatureVector sample

mlrun/artifacts/manager.py, mlrun/common/constants.py, mlrun/utils/helpers.py, server/api/crud/artifacts.py, tests/api/api/test_artifacts.py, tests/artifacts/test_artifacts.py, tests/system/api/test_artifacts.py
resolves: [ML-3889](https://jira.iguazeng.com/browse/ML-3889)
=> [Artifacts] Add validation to oversized inline artifact store

server/api/initial_data.py, tests/api/db/test_artifacts.py
=> [Artifacts] Persist db key when migrating to artifact v2 table [1.6.x]

tests/system/model_monitoring/test_model_monitoring.py
=> [Tests] Skip 3 chronically failing model monitoring system tests [1.6.x]

docs/change-log/index.md
=> [Docs] Add V1.6.1 to change log [1.6.x]

automation/patch_igz/patch_remote.py, mlrun/config.py, mlrun/db/httpdb.py, mlrun/kfpops.py, mlrun/package/utils/_archiver.py, mlrun/platforms/iguazio.py, mlrun/projects/project.py, mlrun/serving/remote.py, mlrun/utils/helpers.py, server/api/utils/clients/iguazio.py, server/api/utils/clients/nuclio.py, tests/platforms/test_iguazio.py, tests/projects/test_project.py, tests/system/feature_store/test_feature_store.py, tests/test_kfp.py, tests/utils/test_helpers.py
Most issues are pretty basic with no real impact, but getting those fixes in are better for getting the report looks much better.
there should not back any non-backwards compatibility issues here
=> [Security] Static analysis issues remediation [1.6.x]
