mlrun/kfpops.py
mlrun/platforms/iguazio.py
mlrun/run.py
mlrun/runtimes/__init__.py
mlrun/runtimes/kubejob.py
mlrun/runtimes/sparkjob.py

Currently supports 2.3 only (hard-coded)

Spark app support

---

.gitignore
Dockerfile.db
Dockerfile.test
Makefile
Pipfile.lock
README.md
mlrun/__main__.py
mlrun/db/httpd.py
setup.cfg
setup.py
tests/last_log.py
tests/test_httpdb.py

`mlrun db` and a Dockerfile to run db
Fixes #8

Run HTTP db

---

Makefile
mlrun/config.py
mlrun/db/httpd.py
mlrun/db/httpdb.py
tests/test_httpdb.py

HTTP authentication

---

mlrun/db/httpd.py
mlrun/db/httpdb.py
tests/test_httpdb.py
tests/test_xdocker.py

Add perfix to HTTP API

---

mlrun/artifacts.py
mlrun/db/filedb.py
mlrun/execution.py
mlrun/k8s_utils.py
mlrun/kfpops.py
mlrun/model.py
mlrun/runtimes/__init__.py
mlrun/runtimes/base.py
mlrun/runtimes/function.py
mlrun/runtimes/generators.py
mlrun/runtimes/local.py
mlrun/runtimes/mpijob.py
mlrun/utils.py

Fixes #47 also some pep8 changes

Nuke mutable defaults

---

mlrun/__init__.py
mlrun/config.py
mlrun/datastore.py
mlrun/render.py
mlrun/runtimes/base.py
mlrun/runtimes/function.py

add ipy links to UI, verbose prints, normalize serving func name

Ui links & fixes

---

mlrun/config.py
mlrun/db/filedb.py
mlrun/db/sqldb.py
tests/last_log.py
tests/test_sqldb.py

Run unique on (uid, project, iter)

---

mlrun/db/httpd.py
mlrun/db/periodic.py
tests/test_periodic.py

Periodic tasks

---

mlrun/runtimes/__init__.py
mlrun/runtimes/function.py
mlrun/runtimes/kubejob.py
mlrun/runtimes/nuclio.py
mlrun/runtimes/serving.py
mlrun/runtimes/utils.py

* require updated nuclio-jupyter

flexible Mlrun hook + new apply()

---

mlrun/db/sqldb.py

Quell SQLAlchemy warnings

---

mlrun/runtimes/serving.py

* Raises Exception when appropriate
* Supports urls via 'data_url'
* Supports direct file send

* Raises Exception when appropriate

---

mlrun/funcdoc.py
tests/rst_cases.yml

Fix funcdoc errors

---

mlrun/db/filedb.py
mlrun/db/httpd.py
mlrun/db/sqldb.py
tests/test_filedb.py
tests/test_sqldb.py

Persist cron

---

Dockerfile.test
mlrun/funcdoc.py
tests/Dockerfile.test-nb
tests/test_funcdoc.py

Attrubute Error in find_handlers

---

mlrun/config.py

Sets default database to sqldb. Had to change from `:memory:` to file based.

Default to sqldb

---

mlrun/db/httpd.py
tests/test_httpd.py

More HTTP API methods

---

mlrun/db/sqldb.py
tests/test_httpdb.py
tests/test_sqldb.py

Honor "tag" in list_artifacts

---

mlrun/db/sqldb.py
tests/test_sqldb.py

latest tag in artifacts

---

mlrun/db/filedb.py
mlrun/db/httpd.py
mlrun/db/sqldb.py
mlrun/execution.py
mlrun/projects/project.py
mlrun/runtimes/base.py
mlrun/runtimes/daskjob.py
mlrun/utils.py

fixes to projects, use isoformat for dates, fix httpd api gaps

Fixes to v044

---

mlrun/db/base.py
mlrun/db/filedb.py
mlrun/db/sqldb.py
tests/test_filedb.py
tests/test_sqldb.py

List artrifacts "updated" filter

---

docs/requirements.txt
mlrun/runtimes/function.py
mlrun/runtimes/local.py
requirements.txt

remove nuclio sdk dependency (solve bug with nuclio version changes)

No nuclio sdk

---

mlrun/funcdoc.py
tests/info_cases.yml

Match parameters by name

---

examples/remote.md

@yaronha please review.
See the updated doc on the PR branch on my fork: https://github.com/Sharon-iguazio/mlrun/blob/doc-review/examples-remote.md/examples/remote.md.
NOTE:
1. I edited the CLI help text that's quoted in the doc. I'll submit a separate PR with similar updates (and others) to the CLI help text.
2. I changed the hardcoded use of the "admin" platform user to `$V3IO_USERMAME` and gave "admin" as an example (as we had discussed f2f).

[DOC REVIEW] examples/remote.md doc edits [IG-13721]

---

hack/local/README.md

@yaronha please review.
See the updated doc on the PR branch on my fork: https://github.com/Sharon-iguazio/mlrun/blob/doc-review/hack-local-README/hack/local/README.md

[DOC REVIEW] hack/local/README.md doc edits [IG-13721]

---

mlrun/funcdoc.py
tests/arc.txt
tests/test_funcdoc.py

Support compound annotations

---

mlrun/db/sqldb.py

Fix bug in store_function

---

README.md

I recommend reading the updated README file on the PR branch: https://github.com/Sharon-iguazio/mlrun/blob/doc-review/README-1/README.md
**NOTE:**
1. In a separate PR, **I want to move the QS tutorial section to a separate file under** **docs/** and link to it from the main README (and maybe move the RST files in the current **docs/** directory to an **rst/** or **src/** docs subdirectory). @yaronha Please approve before I make the changes.
2. The changes also include **edits to quoted help text and code comments** + some **PEP8 code fixes** (mainly to enforce 79 chars per line). I'll submit separate PRs with matching changes to the related source files.
3. In the **"Using Hyperparameters for Job Scaling"** section, I added `--out-path` to the CLI example, as it's supposed to match the …

[DOC REVIEW] README.md doc edits (#1) [IG-13721]

---

dockerfiles/models/Dockerfile

This adds a folder to the **mlrun/ml-models** image called /models loaded with auto-generated model config files.

added model_configs to models image

---

dev-requirements.txt
mlrun/__main__.py
mlrun/artifacts/__init__.py
mlrun/artifacts/base.py
mlrun/artifacts/manager.py
mlrun/artifacts/model.py
mlrun/artifacts/plots.py
mlrun/config.py
mlrun/datastore.py
mlrun/db/filedb.py
mlrun/db/httpd.py
mlrun/db/httpdb.py
mlrun/execution.py
mlrun/kfpops.py
mlrun/platforms/iguazio.py
mlrun/projects/project.py
mlrun/run.py
mlrun/runtimes/__init__.py
mlrun/runtimes/base.py
mlrun/runtimes/function.py
mlrun/runtimes/serving.py
mlrun/runtimes/utils.py
mlrun/utils.py
requirements.txt

enhance model serving and provide log_model() function and other enhancements

Model server plus

---

mlrun/__main__.py
mlrun/projects/project.py

- support inline workflow and loading project from a file
- add params and secrets support to cli

Standalone proj

---

mlrun/__init__.py

provide a simple way to set and verify basic config

Add environment setup helper function

---

mlrun/api/api/endpoints/logs.py
mlrun/api/api/endpoints/runs.py
mlrun/api/db/sqldb/db.py

* aligning SQLDB defaults to the interface defaults
* some other typos originated from the FastAPI refactor I found

Bugfix - Align SQDB defaults

---

mlrun/artifacts/dataset.py
mlrun/platforms/iguazio.py
mlrun/platforms/other.py
mlrun/runtimes/function.py
mlrun/runtimes/pod.py
mlrun/utils.py
tests/test_log_serialization.py

fix nuclio remote access and serialization + add vol/env secrets

Fix nuclio remote, add secrets, and serialization

---

.gitignore
mlrun/funcdoc.py
tests/test_funcdoc.py

Handler types like mlrun.DataItem

---

mlrun/__main__.py
mlrun/api/api/endpoints/runtimes.py
mlrun/db/httpdb.py
mlrun/runtimes/base.py
mlrun/runtimes/daskjob.py
mlrun/runtimes/kubejob.py
mlrun/runtimes/mpijob/v1.py
mlrun/runtimes/mpijob/v1alpha1.py
mlrun/runtimes/sparkjob.py

`mlrun clean` command improvements:
* improve help string
* validate `kind` is one of valid kinds (and give proper error when not)
* add option to give `grace_period`

Clean command improvements

---

mlrun/runtimes/base.py
mlrun/utils/helpers.py
mlrun/utils/regex.py
tests/test_run.py
tests/utils/test_helpers.py

Since we put the run name in the labels of the pod, its name must pass the label value regex check

Validate run name regex

---

Makefile
dockerfiles/README.md
docs/install.md
docs/quick-start.md
hack/local/README.md
hack/local/mlrun-local.yaml
hack/mlrun-all.yaml
hack/mlrunapi.yaml
hack/mlrunui.yaml

and also: 
* change makefile's default docker tag to `unstable`
* change UI images reference in docs from `quay.io/iguazio/mlrun-ui` to `mlrun/mlrun-ui`

Remove latest docker tag references in docs

---

Jenkinsfile
Makefile
dockerfiles/jupyter/Dockerfile
docs/install.md
docs/quick-start.md
hack/local/README.md
hack/local/mljupy.yaml

* change image name from `mlrun/jupy` to mlrun/jupyter`
* move dockerfile under `dockerfiles` directory
* fix references from `mlrun/jupy:latest` to `mlrun/jupyter:0.5.0`
* added makefile targets
* some fixes & changes to the dockerfile
* fixed dockerfiles cache disabling which apparently didn't work (`$(date)` in makefile returns nothing, should be `$(shell date)`

Fix jupyter image

---

Makefile

although with the list the makefile is more readable, people forget to add new commands to this list which is worse

Makefile Phony near each command instead of one list

---

mlrun/api/api/utils.py
mlrun/model.py
mlrun/utils/helpers.py

Also fix response project and name on submit schedule job

Don't default to default project unneeded-ly 

---

tests/api/api/test_files.py
tests/common_fixtures.py
tests/test_datastores.py

Added tests from client side for:
- forbidden
- not found

Adding unit tests for files API

---

mlrun/config.py

To align it to MLRun's cleanup grace period

Change default kfp ttl from 24h to 4h

---

Makefile
mlrun/__init__.py

Also fixed `bump-version` makefile target (had a bug related to string normalization)

Bump to 0.5.2-rc1

---

mlrun/api/api/utils.py
tests/api/api/test_utils.py

* The actual bug fix is the addition of `kind=function.kind` in https://github.com/mlrun/mlrun/pull/427/files#diff-96065660c4c47af26977bef5e1569648R95, without it `new_function` doesn't "know" what is the function kind so it doesn't "know" how to parse the body and the outcome function object spec is always empty
* moved some of the code to `_parse_submit_job_body` to make testing easier and better readability
* changed names and added comments
* added test

Fix function enrichment on job submission

---

mlrun/runtimes/local.py

fix log print for py files to show log progress 

---

examples/v2_model_server.ipynb
mlrun/serving/README.md

edit v2 serving README and add notebook example

Fix v2 serving readme and add example notebook

---

docs/install.md
docs/quick-start.md
hack/local/README.md

Continuing https://github.com/mlrun/mlrun/pull/477

[Docs] Fix all instances of local installation commands

---

mlrun/api/api/endpoints/schedules.py
mlrun/api/api/utils.py
mlrun/api/db/base.py
mlrun/api/db/filedb/db.py
mlrun/api/db/sqldb/db.py
mlrun/api/schemas/schedule.py
mlrun/api/utils/scheduler.py
tests/api/db/test_projects.py
tests/api/utils/test_scheduler.py

- Create
- Delete when schedule is deleted
- Added to schemas on get and insert (and update for future)
- Tested creation

Added full support to schedule labels

---

mlrun/runtimes/daskjob.py

Will add tests in a followup PR

[Dask] Fix cleanup wrong condition

---

mlrun/model.py
mlrun/serving/server.py
mlrun/serving/states.py
mlrun/utils/helpers.py

enhance and fix serving state machine to support future topologies

[Serving] Enhance and fix serving state machine to support future topologies

---

mlrun/api/initial_data.py
mlrun/api/utils/alembic.py
mlrun/api/utils/almbic.py
tests/api/conftest.py

1. If no database is present create it from scratch up to the latest revision.
2. If a database is present with an alembic revision - upgrade it to the latest revision.
3. If a database is present without an alembic revision - stamp it to the first revision and upgrade it to the latest revision.

[DB migrations] Handle all possible initialization options

---

mlrun/api/api/endpoints/schedules.py
mlrun/api/db/base.py
mlrun/api/db/filedb/db.py
mlrun/api/db/sqldb/db.py
mlrun/api/db/sqldb/models.py
mlrun/api/schemas/__init__.py
mlrun/api/schemas/schedule.py
mlrun/api/utils/scheduler.py
tests/api/utils/test_scheduler.py

Support updating schedule via api and via scheduler util

[Scheduling] Add update support

---

mlrun/config.py
mlrun/render.py

Continuing https://github.com/mlrun/mlrun/pull/506

[SDK] Make printed items background color configurable

---

mlrun/config.py

Looks nicer than https://github.com/mlrun/mlrun/pull/506:

[SDK] Change printed items background colors

---

tests/system/demos/horovod/test_horovod.py

Reverting https://github.com/mlrun/mlrun/pull/528

[System tests] Re-enable horovod demo

---

mlrun/runtimes/function.py
tests/runtimes/test_function.py

Broken by https://github.com/mlrun/mlrun/pull/559 - added test

[Nuclio] Fix volume and volume mount creation

---

mlrun/config.py
mlrun/runtimes/base.py
mlrun/runtimes/daskjob.py
mlrun/runtimes/function.py
mlrun/runtimes/pod.py
mlrun/runtimes/sparkjob.py

Backport of https://github.com/mlrun/mlrun/pull/580

[Runtimes] Set jobs dbpath from configuration instead of client [Backport 0.5.x]

---

dev-requirements.txt
hack/local/README.md
hack/local/mlrun-local.yaml
hack/mlrun-all.yaml
hack/mlrunapi.yaml
mlrun/builder.py
mlrun/config.py
mlrun/db/httpdb.py
mlrun/runtimes/base.py
mlrun/runtimes/kubejob.py
mlrun/runtimes/utils.py
mlrun/utils/helpers.py
tests/common_fixtures.py
tests/conftest.py
tests/test_config.py
tests/utils/test_helpers.py

Backport of https://github.com/mlrun/mlrun/pull/582
Required to backport some config fixes from https://github.com/mlrun/mlrun/pull/542 as well

[Builder] Change registry URL configurations [0.5.x backport]

---

dockerfiles/base/Dockerfile
dockerfiles/jupyter/Dockerfile
dockerfiles/mlrun-api/Dockerfile
dockerfiles/mlrun/Dockerfile
dockerfiles/models-gpu/Dockerfile
dockerfiles/models-gpu/py36/Dockerfile
dockerfiles/models/Dockerfile
dockerfiles/models/py36/Dockerfile
dockerfiles/test-system/Dockerfile
dockerfiles/test/Dockerfile
mlrun/db/httpdb.py

Backport of pip upgrade addition from https://github.com/mlrun/mlrun/pull/523
Plus backport of jupyter image improvement from https://github.com/mlrun/mlrun/pull/582
Plus linting and import fix caused from wrong conflict solving when cherry picking

[Build] Add pip upgrade to images [0.5.x backport]

---

mlrun/runtimes/sparkjob.py

Solving Iguazio Jira ticket IG-17472

[Sparkjob] Support cuda image

---

.github/workflows/system-tests.yml
automation/system_test/prepare.py
examples/mlrun_jobs.ipynb
mlrun/api/api/endpoints/functions.py
mlrun/builder.py
mlrun/config.py
mlrun/db/httpdb.py
mlrun/runtimes/kubejob.py
tests/system/examples/jobs/test_jobs.py

Backport of https://github.com/mlrun/mlrun/pull/589

[Builder] Install specific mlrun version [Backport 0.5.x]

---

mlrun/model.py
mlrun/platforms/iguazio.py
mlrun/run.py
mlrun/runtimes/base.py
mlrun/runtimes/funcdoc.py
mlrun/runtimes/funcref.py
mlrun/runtimes/function.py
mlrun/runtimes/function_reference.py
mlrun/runtimes/kubejob.py
mlrun/runtimes/local.py
requirements.txt

* various function nuclio runtime fixes 
* fix debug env var
* add py requierments option to code to func and fn.with_requierments()
* add function ref object
* move fn.with_code() to runtime base

[Runtimes] General fixes and adding FunciontReference

---

.github/workflows/build.yaml
.github/workflows/system-tests.yml

Backport of https://github.com/mlrun/mlrun/pull/602

[System tests] Enable to take UI from action branch name in mlrun/ui [Backport 0.5.x]

---

.github/workflows/build.yaml
.github/workflows/ci.yaml

Backport of https://github.com/mlrun/mlrun/pull/604

[CI] Create a cache tag per version for the build images workflow [Backport 0.5.x]

---

mlrun/__init__.py
mlrun/api/api/endpoints/files.py
mlrun/artifacts/base.py
mlrun/artifacts/dataset.py
mlrun/artifacts/manager.py
mlrun/artifacts/model.py
mlrun/datastore/__init__.py
mlrun/datastore/datastore.py
mlrun/db/__init__.py
mlrun/execution.py
mlrun/model.py
mlrun/projects/project.py
mlrun/runtimes/function.py
mlrun/serving/routers.py
mlrun/serving/v1_serving.py
mlrun/utils/helpers.py

* fix small bugs in serving
* add v3io stream trigger to nuclio
* small enhancments to internal methods

[Serving] Minor fixes

---

mlrun/projects/project.py
tests/projects/test_project.py

Typo fix from https://github.com/mlrun/mlrun/pull/596

[Projects] Fix functions syncing

---

mlrun/__main__.py
mlrun/api/api/endpoints/functions.py
mlrun/api/api/utils.py
mlrun/api/crud/pipelines.py
mlrun/artifacts/base.py
mlrun/artifacts/dataset.py
mlrun/artifacts/model.py
mlrun/datastore/__init__.py
mlrun/datastore/data_resources.py
mlrun/datastore/datastore.py
mlrun/datastore/store_resources.py
mlrun/datastore/v3io.py
mlrun/execution.py
mlrun/model.py
mlrun/run.py
mlrun/serving/server.py
mlrun/utils/helpers.py
tests/utils/test_helpers.py

* extend store:// prefix to other resources (feature store ..)
* get_store_resource() to get all resource types + Resource Cache for serving/storey
* central path<>resource mapping vs use of constants
* related serving context bug fix

[Artifacts] Extend store prefix

---

mlrun/runtimes/serving.py

* fix add model bug in serving (graph wasnt set properly)

[Serving] Fix graph initialization in add model

---

mlrun/serving/states.py

* fix plot bugs and missing responder and full_event fields
* add default on_error (for all states unless state has specific on_error)

[serving] fix serving state bugs and add default on_error

---

mlrun/utils/helpers.py
tests/system/base.py
tests/system/examples/jobs/test_jobs.py

[Artifacts] Fix store url generation

---

README.md
docs/index.rst

Changed documentation main page
Change readme

[Doc] Update description, benefits and key-features

---

.github/workflows/ci.yaml
Makefile
dockerfiles/base/Dockerfile
dockerfiles/jupyter/Dockerfile
dockerfiles/mlrun-api/Dockerfile
dockerfiles/mlrun/Dockerfile
dockerfiles/models-gpu/Dockerfile
dockerfiles/models-gpu/py36/Dockerfile
dockerfiles/models/Dockerfile
dockerfiles/models/py36/Dockerfile
dockerfiles/test-system/Dockerfile
dockerfiles/test/Dockerfile

Backport of most of https://github.com/mlrun/mlrun/pull/630

[Images] Pin pip version and use legacy resolver [0.5.x Backport]

---

docs/conf.py
mlrun/datastore/store_resources.py
tests/utils/test_helpers.py

* fix store schema parsing for cases such as "store:///name"

[Artifacts] Fix store schema parsing

---

mlrun/__init__.py
mlrun/run.py

* fix set_environment (when artifact_path is not set)
* add doc to set_environment and support access_key param
* add doc to code_to_function and import_function

[SDK] Fix set_environment and add doc strings

---

mlrun/runtimes/mpijob/abstract.py

Add tested defaults for better performance on AWS.

[MPIJob] Add mpi_args default value

---

mlrun/__init__.py
mlrun/projects/project.py
tests/projects/test_project.py

* add user_project option to set_environment and new_project which will add the active user name to the project name (making it unique per user)

[Projects] Add utilities to create a project per user

---

docs/tutorial/01-mlrun-basics.ipynb

fix few broken doc image links in tutorial

[Doc] fix few broken doc image links

---

docs/index.rst
docs/tutorial/01-mlrun-basics.ipynb
docs/tutorial/02-model-training.ipynb
docs/tutorial/03-model-serving.ipynb
docs/tutorial/04-pipeline.ipynb

- Add "by the end of this tutorial" sections
- Improvements to part 4

[Doc] Add minor improvements to the tutorials

---

mlrun/api/api/utils.py
mlrun/api/db/sqldb/db.py
mlrun/run.py
mlrun/utils/helpers.py
tests/api/api/test_utils.py
tests/utils/test_helpers.py

Relevant Jira ticket https://jira.iguazeng.com/browse/ML-110

[Jobs] Fix to assign task project to function from hub on job submission

---

mlrun/runtimes/mpijob/abstract.py
mlrun/runtimes/mpijob/v1.py

Backport of https://github.com/mlrun/mlrun/pull/649 and https://github.com/mlrun/mlrun/pull/655

[MPIJob] Support setting mpi args [Backport 0.5.x]

---

docs/howto/index.md
docs/tutorial/04-pipeline.ipynb

@yaronha @gilad-shaham please approve; @yaronha please merge.

[Doc] getting-started-tutorial NB #4 doc-review edits; howto/ title edit ("How-To Guides and Demos")

---

docs/tutorial/03-model-serving.ipynb

@yaronha @gilad-shaham please approve and merge.

[Doc] getting-started-tutorial NB #3: doc-review edits #2

---

docs/tutorial/01-mlrun-basics.ipynb

@yaronha @gilad-shaham please approve.
(Note: The NB currently uses both Sphinx admonition formatting and the basic Markdown blockquote note formatting. I didn't convert more MD notes to Sphinx admonitions to simplify later merging the NB changes to the demos repo + because it should be tested and I don't currently compile the MLRun docs, but I think this should be done after the merge to the demos repo.)

[Doc] getting-started-tutorial NB #1: doc-review edits #2

---

docs/tutorial/02-model-training.ipynb
docs/tutorial/index.md

Edit PR #698 doc changes following review comments
@yaronha @gilad-shaham please approve.

[Doc] getting-started-tutorial: minor title edit (hyphenate "Getting-Started") + NB #2 start/end code-markers doc edits

---

mlrun/builder.py
mlrun/config.py
mlrun/k8s_utils.py

Backport of https://github.com/mlrun/mlrun/pull/696

[Builder] Make init container image configurable, set pull policy and pin version to 3.13.1 [Backport 0.5.x]

---

mlrun/model.py
tests/api/runtimes/base.py
tests/api/runtimes/test_kubejob.py

Adding infrastructure for performing unit-tests on runtimes. Currently starting with testing the KubeJob runtime.

[Tests] Add unit-tests for runtimes

---

README.md
docs/index.rst

Doc review for PR #677 doc edits

[Doc] Review PR 677 docs/index.rst edits (add MLRun architecture & remove key features) & merge to README

---

tests/api/runtimes/base.py
tests/api/runtimes/test_kubejob.py

Signed-off-by: Yan Burman <yanburman@users.noreply.github.com>

[Tests] Add with_code test to kubejob runtime

---

mlrun/runtimes/base.py
tests/api/runtimes/base.py
tests/api/runtimes/test_kubejob.py
tests/api/runtimes/test_nuclio.py

Signed-off-by: Yan Burman <yanburman@users.noreply.github.com>

[Tests] Add more with_code tests to kubejob runtime

---

mlrun/datastore/__init__.py

fix bug of not returning stream object

[Serving] Fix model stream not returned

---

mlrun/runtimes/sparkjob.py

Resolves https://jira.iguazeng.com/browse/ML-53

[Sparkjob] Fix handling for int cpu limit

---

mlrun/datastore/datastore.py
mlrun/datastore/store_resources.py
mlrun/datastore/targets.py
mlrun/feature_store/api.py
mlrun/feature_store/retrieval/job.py
mlrun/feature_store/retrieval/local_merger.py
mlrun/model.py

* support default target path for feature vectors 
* support column drop in get offline features
* support context.get_table() for feature set/vector uris
* fix bugs

[Feature-store] Fix passing feature vector as job data item (input)

---

mlrun/runtimes/daskjob.py
mlrun/runtimes/kubejob.py
mlrun/runtimes/remotesparkjob.py
mlrun/runtimes/sparkjob.py

Also - Align `.deploy()` signatures in inheritors
This fixes the problem described here - https://github.com/mlrun/mlrun/issues/711#issuecomment-777101814

[Pipelines] Trigger deployment through API (and not directly) when in pipelines context

---

mlrun/api/api/endpoints/healthz.py
mlrun/config.py
mlrun/db/httpdb.py
mlrun/kfpops.py

This fixes the problem described here https://github.com/mlrun/mlrun/issues/711#issuecomment-778834468

[Pipelines] Enrich pods with env var with the API URL

---

mlrun/api/db/sqldb/db.py
tests/api/api/test_projects.py
tests/api/utils/test_scheduler.py

This resolves:
* https://jira.iguazeng.com/browse/ML-84
* https://jira.iguazeng.com/browse/ML-85

[API] Return conflict on already existing resource

---

mlrun/api/db/sqldb/db.py
mlrun/api/utils/scheduler.py
tests/api/utils/test_scheduler.py

* 404 on get
* 404 on update
* success on delete
This resolves:
* https://jira.iguazeng.com/browse/ML-89
* https://jira.iguazeng.com/browse/ML-62

[Scheduler] Raise correct errors when schedule not found

---

mlrun/artifacts/model.py
mlrun/execution.py
mlrun/feature_store/api.py
mlrun/feature_store/feature_vector.py
mlrun/feature_store/retrieval/local_merger.py
mlrun/feature_store/retrieval/online.py
mlrun/utils/helpers.py
tests/feature-store/test_feature_store.py

* remove indexes from vector by default
* seperate label feature, label not merged in online vector
* allow to get online vector as (ordered) list

[Feature-store] Fixes & enhancements in feature vector for removing index columns, using labels, ordering results

---

mlrun/api/db/sqldb/db.py
mlrun/artifacts/base.py
mlrun/model.py
mlrun/utils/helpers.py
tests/api/db/test_artifacts.py
tests/rundb/test_dbs.py
tests/rundb/test_sqldb.py

Added a test for each problem that I found
Unrelated changes:
* replaced `DBError` with our errors so that correct status code will be returned
* little fixes to the uri generation functions
* Fixed the `tests/rundb/test_dbs.py` to be runnable in local env - they were "counting" on stuff that happens in tests that are running before, therefore it worked in CI when running all tests, but running only tests from this file didn't work

[Artifacts] Fix several bugs related to tagging

---

mlrun/datastore/sources.py
mlrun/datastore/targets.py
mlrun/feature_store/api.py
mlrun/feature_store/feature_set.py
mlrun/feature_store/feature_vector.py
mlrun/feature_store/ingestion.py
mlrun/serving/routers.py
mlrun/serving/server.py
mlrun/serving/v2_serving.py
tests/feature-store/test_feature_store.py

* fixes in real-time ingestion flow 
* fixes in model serving and real-time vector
* add TSDB Writer and writer options

[Feature-store] Fixes and enhancements in real-time flow

---

tests/system/examples/basics/test_basics.py
tests/system/examples/dask/test_dask.py

Fixing breakage caused by https://github.com/mlrun/mlrun/pull/812

[System tests] Fix scrape metrics wrong assertions

---

mlrun/runtimes/sparkjob.py

[This PR](https://github.com/mlrun/mlrun/pull/803) mistakenly removed it - https://github.com/mlrun/mlrun/pull/803/files#diff-96399d147b4a75f8592560b1ddce759d9007ebabd02c9d77f68d393805cd1679L254

[Sparkjob] Fix not setting executor instances

---

mlrun/feature_store/retrieval/local_merger.py
tests/system/feature_store/test_feature_store.py

fixes https://jira.iguazeng.com/browse/ML-312

[Feature store] Ignore errors in drop columns in case entity is not set

---

mlrun/mlutils/models.py

skparams parameter in gen_sklearn_model was not being unpacked correctly. Errors out whenever parameters are supplied

[mlutils] Fixed unpacking error in gen_sklearn_model

---

mlrun/artifacts/base.py
mlrun/artifacts/dataset.py
mlrun/datastore/targets.py
mlrun/feature_store/feature_vector.py
mlrun/feature_store/retrieval/local_merger.py
mlrun/utils/helpers.py
tests/artifacts/test_dataset.py

[This PR](https://github.com/mlrun/mlrun/commit/80df9a45c8eae06783eee9b81b58a48eabfbd2cf) changed the behvaior and caused the hash to stop being enriched
Fixes - https://jira.iguazeng.com/browse/ML-299

[Dataset] Fix hash not being enriched

---

mlrun/feature_store/__init__.py
mlrun/feature_store/api.py
mlrun/feature_store/common.py
mlrun/feature_store/feature_vector.py

* small feature store API changes after team review

[Feature store] Small api changes + add docstrings

---

mlrun/__main__.py
mlrun/runtimes/base.py
mlrun/runtimes/local.py
mlrun/runtimes/utils.py
tests/system/feature_store/test_feature_store.py
tests/test_run.py

* improve parallelism, workers which completed move to next task
* fix print/log issues, prints are visible after each iteration, text doesn't crop

[Hyper-params] Use dask as_completed (improve parallelism) + fix logging issues

---

mlrun/api/db/sqldb/db.py
mlrun/api/schemas/__init__.py
mlrun/api/schemas/constants.py
mlrun/api/schemas/project.py
mlrun/config.py
tests/api/api/test_projects.py
tests/api/db/test_runs.py
tests/common_fixtures.py

Also: found a bug in the runs state/s filter which I'm using in this PR as well - fixed it

[Projects] Add summary format to improve projects screen performance

---

mlrun/feature_store/feature_vector.py
requirements.txt
tests/system/feature_store/test_feature_store.py

https://jira.iguazeng.com/browse/ML-303

[Feature store] In case the key does not exist return None

---

mlrun/config.py
mlrun/utils/helpers.py
tests/utils/test_helpers.py

Implements https://jira.iguazeng.com/browse/ML-337

[Runtimes] Support configuring specific images that should be enriched with registry

---

docs/store/feature-store-demo.ipynb

fix pip command
pip uninstall storey - > pip install storey

[Doc] Fix typo in feature-store-demo.ipynb

---

mlrun/api/crud/model_endpoints.py
mlrun/api/schemas/model_endpoints.py

This PR adds additional information to each model endpoint - the names of the label columns and the algorithm of the model

[Model Monitoring] Additional data to endpoint kv record

---

docs/model_monitoring/dashboards/details.json
docs/model_monitoring/dashboards/overview.json
docs/model_monitoring/dashboards/performance.json
docs/model_monitoring/model-monitoring-deployment.ipynb

This PR adds basic "how-to" tutorial for congratulating and deploying  the model monitoring

[Doc] Add how-to notebook for model monitoring deployment

---

mlrun/runtimes/serving.py

[Serving] Fix calling parentheses typo

---

mlrun/feature_store/feature_set.py

broke in https://github.com/mlrun/mlrun/pull/876

[Feature store] Fix  missing attribute initialization in feature set

---

mlrun/feature_store/feature_set.py
tests/system/feature_store/test_feature_store.py

https://jira.iguazeng.com/browse/ML-346

[Feature store] Return graph state in add_aggregation

---

mlrun/feature_store/feature_vector.py
requirements.txt
tests/system/feature_store/test_feature_store.py

https://jira.iguazeng.com/browse/ML-493?filter=-1

[Feature store] Handle empty response in service_online.get

---

mlrun/datastore/targets.py
tests/system/feature_store/test_feature_store.py

https://jira.iguazeng.com/browse/ML-516

[Feature store] Fix wrong handling of aggregated features in NoSql target

---

mlrun/feature_store/api.py

https://jira.iguazeng.com/browse/ML-503

[Feature store] Adding option to specify uid/tag in delete methods

---

mlrun/datastore/targets.py
mlrun/runtimes/serving.py
mlrun/serving/states.py

https://jira.iguazeng.com/browse/ML-522

[Feature store] Support deployment of an empty graph ingestion service

---

mlrun/feature_store/api.py
tests/system/feature_store/test_feature_store.py

https://jira.iguazeng.com/browse/ML-283

[Feature store] Fix ingest handling for a feature set provided by URI

---

mlrun/datastore/base.py
mlrun/datastore/targets.py
mlrun/feature_store/api.py
mlrun/feature_store/feature_set.py
mlrun/feature_store/retrieval/local_merger.py
tests/system/feature_store/test_feature_store.py

https://jira.iguazeng.com/browse/ML-451

[Feature store] Support filtering by time in get_offline_features

---

mlrun/feature_store/api.py
mlrun/feature_store/feature_set.py
mlrun/feature_store/ingestion.py
mlrun/runtimes/remotesparkjob.py

https://jira.iguazeng.com/browse/ML-558

[Feature store] Fix spark ingest as job

---

mlrun/run.py

Code to function is the most important function currently inside of mlrun to understand. It represents the easiest way to create an mlrun function, and as such deserves ample documentation and type completion.

[Doc] Improve code_to_function docstring

---

mlrun/feature_store/feature_vector.py

https://jira.iguazeng.com/browse/ML-584

[Feature store] Do not return None for column that is label

---

examples/mlrun_sparkk8s.ipynb
mlrun/model.py
mlrun/runtimes/base.py
mlrun/runtimes/sparkjob.py

[Sparkjob] Add `ui_url` attribute to Run status object and enrich it when running spark functions

---

mlrun/feature_store/retrieval/online.py
tests/system/feature_store/test_feature_store.py

https://jira.iguazeng.com/browse/ML-656

[Feature store] Fix bug in online features with multiple entities

---

mlrun/datastore/base.py
tests/system/feature_store/test_feature_store.py

https://jira.iguazeng.com/browse/ML-672

[Feature store] Bug fix in offline features with filtering

---

mlrun/api/utils/projects/follower.py

Fixes https://jira.iguazeng.com/browse/IG-18689

[Projects] Don't fail initialization on projects sync failure

---

mlrun/datastore/base.py
mlrun/datastore/targets.py
mlrun/datastore/v3io.py
mlrun/feature_store/feature_set.py
tests/system/env.yml
tests/system/feature_store/test_feature_store.py

[Feature store] Support purging targets

---

mlrun/api/api/endpoints/functions.py
mlrun/api/schemas/__init__.py
mlrun/api/schemas/function.py
mlrun/builder.py
mlrun/runtimes/kubejob.py

Fixes https://jira.iguazeng.com/browse/ML-654

[Runtimes] Fix built image logging + use enums for function states on building

---

mlrun/datastore/targets.py
mlrun/db/httpdb.py
mlrun/feature_store/api.py
mlrun/feature_store/feature_set.py
tests/system/base.py
tests/system/feature_store/test_feature_store.py

[Feature store] Support controlling whether to overwrite the previously ingested data in ingest()

---

mlrun/datastore/base.py
requirements.txt
tests/system/feature_store/test_feature_store.py

https://jira.iguazeng.com/browse/ML-673

[Feature Store] Partitions no longer start with "igzpart"

---

mlrun/feature_store/feature_set.py

[Feature Store] Fix missing project setting in save

---

mlrun/serving/server.py
requirements.txt

https://jira.iguazeng.com/browse/ML-717

[Serving] Change default log level to info

---

mlrun/feature_store/feature_set.py

[Feature Store] Documenting windows types

---

mlrun/datastore/sources.py
mlrun/feature_store/api.py

https://jira.iguazeng.com/browse/ML-757

[Feature Store] Enable ingest to spark from pandas df

---

mlrun/feature_store/api.py
tests/system/feature_store/test_feature_store.py

[Feature Store] Fail `delete_feature_set` if no purging was done

---

mlrun/datastore/targets.py
requirements.txt

ML-638
Depends on https://github.com/mlrun/storey/pull/253

[Feature Store] Convert string timestamps to datetime based on schema in NoSqlTarget

---

mlrun/__init__.py
mlrun/api/utils/projects/leader.py
mlrun/projects/__init__.py
mlrun/projects/project.py
tests/test_convenince_methods.py

Fixes https://jira.iguazeng.com/browse/ML-722

[SDK] Explode when setting invalid project name in `set_environment`

---

mlrun/data_types/infer.py
tests/system/feature_store/test_feature_store.py

[Feature Store] Fix disappeared index type

---

mlrun/projects/project.py
tests/projects/test_project.py

Fixes https://jira.iguazeng.com/browse/ML-526

[Projects] Ensure project dir on export

---

dockerfiles/test-system/Dockerfile

Fixing bug originated in https://github.com/mlrun/mlrun/pull/1051

[System Tests] Fix dockerfile

---

dockerfiles/test-system/Dockerfile
mlrun/feature_store/common.py
mlrun/feature_store/feature_vector.py
requirements.txt

[Feature Vector] Fix using feature from another project in `get_offline_features`

---

mlrun/datastore/targets.py
tests/system/feature_store/test_feature_store.py

[Feature Store] Set suffix for ParquetTarget in FeatureVector

---

mlrun/datastore/targets.py
tests/system/feature_store/test_feature_store.py

[Feature Store] Set suffix for ParquetTarget in FeatureVector [Backport 0.6.x]

---

mlrun/data_types/data_types.py
tests/system/feature_store/test_feature_store.py

https://jira.iguazeng.com/browse/ML-793

[Feature Store] Handling schemas with timezone in datetime

---

.github/workflows/unstable.yaml
dockerfiles/README.md
docs/feature-store/feature-sets.md
docs/feature-store/training-serving.md
docs/howto/convert-mlrun-code.ipynb
docs/howto/convert-original-code.ipynb
docs/runtimes/mlrun_jobs.ipynb
docs/serving/distributed-graph.ipynb
docs/serving/serving-graph.md
docs/store/datastore.md
docs/tutorial/01-mlrun-basics.ipynb
examples/mlrun_basics.ipynb
examples/mlrun_jobs.ipynb
examples/xgb_serving.ipynb
mlrun/api/api/endpoints/artifacts.py
mlrun/api/db/sqldb/db.py
mlrun/k8s_utils.py
mlrun/runtimes/base.py
mlrun/runtimes/function.py
mlrun/runtimes/mpijob/abstract.py
setup.py
tests/platforms/test_iguazio.py

[Docs] Fix typos

---

mlrun/feature_store/feature_vector.py

https://jira.iguazeng.com/browse/ML-791

[Feature store] Add with_indexes param to feature vector ctor

---

mlrun/datastore/base.py
tests/datastore/test_base.py

Fixes https://jira.iguazeng.com/browse/ML-726

[Datastore] Fix `as_df` from http dataitem

---

mlrun/data_types/infer.py
tests/system/feature_store/test_feature_store.py

https://jira.iguazeng.com/browse/ML-820

[Feature Store]  Fix Ingest conversion for column with type object

---

mlrun/datastore/targets.py
mlrun/feature_store/api.py
tests/system/feature_store/test_feature_store.py

[Feature Store] Overwrite specified path

---

mlrun/data_types/infer.py
tests/feature-store/test_infer.py

[Feature Store] Present entity key in the Preview tab

---

mlrun/data_types/infer.py
tests/feature-store/test_infer.py

This reverts commit a566bd8eebb31a9b6e21c8870ca41efcb8b2d126.

[Feature Store] Revert "Present entity key in the Preview tab (#1106)"

---

mlrun/feature_store/api.py
tests/system/feature_store/test_feature_store.py

Fixes https://jira.iguazeng.com/browse/ML-801

[Feature Store] The statistics tab presents 'entity' key empty row

---

mlrun/feature_store/api.py

[Feature Store] Fix misleading exception message

---

dockerfiles/jupyter/requirements.txt
mlrun/api/api/endpoints/functions.py
mlrun/api/schemas/auth.py
mlrun/runtimes/function.py
requirements.txt

depends on https://github.com/nuclio/nuclio-jupyter/pull/127

[Nuclio] Support providing auth info

---

mlrun/feature_store/feature_vector.py
tests/system/feature_store/test_feature_store.py

https://jira.iguazeng.com/browse/ML-843

[Feature Store] Check type of parameter for online service.get

---

.github/workflows/system-tests-opensource.yml

Inspired from https://github.com/nuclio/nuclio/pull/2272

[System Tests] Fix open source system tests CI

---

mlrun/api/api/endpoints/artifacts.py
mlrun/api/api/endpoints/functions.py
mlrun/api/api/endpoints/logs.py
mlrun/api/api/endpoints/runs.py

Fixing some bugs from https://github.com/mlrun/mlrun/pull/1170

[API] Run auth in threadpool

---

mlrun/datastore/store_resources.py
mlrun/feature_store/retrieval/online.py

https://jira.iguazeng.com/browse/ML-930

[Feature Store] Throw error if trying to read from online service without an online target

---

mlrun/feature_store/feature_set.py
tests/system/feature_store/test_feature_store.py

https://jira.iguazeng.com/browse/ML-926

[Feature Store] Remove emit policy from `add_aggregation`

---

mlrun/api/db/sqldb/models.py
mlrun/api/migrations/versions/d781f58f607f_tag_object_name_string.py

The Tag `obj_name` was an `Integer` while we are saving strings in it. Changed it to `String`.

[DB] Change Tag `object_name` column from Integer to String

---

mlrun/api/api/endpoints/projects.py
mlrun/api/utils/projects/remotes/nop_leader.py
tests/api/api/test_projects.py
tests/api/utils/projects/test_follower_member.py

Typo was only affecting follower mode therefore took time to discover
Enhanced projects API tests to test both leader and follower mode

[Projects] Fix typo in delete project endpoint

---

mlrun/feature_store/retrieval/local_merger.py
tests/system/feature_store/test_feature_store.py

…e only the appropriate feature set
https://jira.iguazeng.com/browse/ML-913

[Feature Store] Filter correct feature set when filtering multiple feature set by start time

---

mlrun/projects/project.py
tests/projects/test_project.py

Fixes https://jira.iguazeng.com/browse/ML-944

[Projects] Fix list attributes setters

---

mlrun/db/httpdb.py
tests/integration/sdk_api/artifacts/test_artifact_tags.py

Fixes https://jira.iguazeng.com/browse/ML-980

[SDK] Fix  list artifact tags in httpdb

---

mlrun/data_types/spark.py

https://jira.iguazeng.com/browse/ML-941

[Feature Store] Align get_stats for spark engine with storey engine

---

mlrun/feature_store/__init__.py
mlrun/feature_store/api.py
mlrun/feature_store/feature_vector.py
mlrun/feature_store/retrieval/online.py
tests/system/feature_store/test_feature_store.py

[Feature Store] Adding `FixedWindowType` argument  to `get_online_feature_service`

---

tests/system/feature_store/test_feature_store.py

[Feature Store] Fix `test_query_on_fixed_window` failure

---

mlrun/feature_store/retrieval/local_merger.py
tests/system/feature_store/test_feature_store.py

fix with_indexes parameter on vector to return the key column as index in get_offline_features.
also arranged the code to be more coherent.

[Feature Store] Get offline features fix with indexes

---

dev-requirements.txt
mlrun/api/migrations/tests/test_migrations.py

pytest_alembic version 0.4.0 changed their pytest fixtures.
Fixed our tests to work with the new fixtures.

[MigrationTests] Fix tests to support new pytest_alembic version (0.4.0)

---

mlrun/datastore/utils.py

[Feature Store] Replace s3 url scheme with s3a when engine is spark

---

mlrun/api/utils/clients/opa.py
mlrun/config.py
tests/api/utils/clients/test_opa.py

Leveraging https://github.com/iguazio/zebo/pull/5307

[OPA] Optimize resources filter to send one request to opa server

---

docs/feature-store/transformations.md

[Docs] Add documentation for Spark+S3

---

mlrun/api/api/endpoints/client_spec.py
mlrun/api/api/endpoints/functions.py
mlrun/api/api/endpoints/grafana_proxy.py
mlrun/api/api/endpoints/healthz.py
mlrun/api/api/endpoints/marketplace.py
mlrun/api/api/endpoints/model_endpoints.py
mlrun/api/api/endpoints/pipelines.py
mlrun/api/crud/__init__.py
mlrun/api/crud/model_endpoints.py
mlrun/api/crud/pipelines.py
mlrun/kfpops.py
mlrun/run.py
tests/api/api/marketplace/test_marketplace.py
tests/api/api/test_grafana_proxy.py
tests/api/api/test_model_endpoints.py
tests/api/api/test_pipelines.py
tests/api/crud/test_pipelines.py

Also:
* Fix `mlrun.api.crud` package usage throughout code

[API] Reuse formatting logic on Pipelines list and get endpoints

---

mlrun/projects/project.py
tests/projects/test_project.py

Fixing some bugs originating from https://github.com/mlrun/mlrun/pull/1151
This is a quick patch fix, more "correct" fixes might be done later by @yaronha 
Fixes:
https://jira.iguazeng.com/browse/ML-1004
https://jira.iguazeng.com/browse/ML-1005

[Projects] Fix default artifact path setting, init repo in non-existing dir and set function from notebook

---

mlrun/api/crud/pipelines.py
mlrun/kfpops.py
tests/api/api/test_pipelines.py

Fixes https://jira.iguazeng.com/browse/ML-1011

[Pipelines] Fix DAG generation

---

mlrun/api/api/endpoints/functions.py
tests/system/base.py
tests/system/projects/test_project.py
tests/system/runtimes/assets/nuclio_function.py
tests/system/runtimes/test_nuclio.py

Fixes - https://jira.iguazeng.com/browse/ML-1018

[API] Ensure project on function deployment

---

mlrun/api/api/endpoints/runtime_resources.py
mlrun/builder.py
mlrun/k8s_utils.py
mlrun/runtimes/base.py
mlrun/runtimes/kubejob.py
tests/api/api/test_runtime_resources.py
tests/api/runtime_handlers/base.py
tests/api/runtime_handlers/test_kubejob.py

Fixes https://jira.iguazeng.com/browse/ML-999

[Runtimes] Fix builder pod cleanup

---

mlrun/api/api/endpoints/feature_store.py
mlrun/api/crud/feature_store.py
mlrun/api/db/base.py
mlrun/api/db/filedb/db.py
mlrun/api/db/sqldb/db.py
mlrun/api/schemas/__init__.py
mlrun/api/schemas/feature_store.py
tests/api/api/feature_store/base.py
tests/api/api/feature_store/test_feature_sets.py
tests/api/api/feature_store/test_feature_vectors.py

Adding 2 endpoints:
1. `GET /projects/{project}/feature-sets/{name}/tags`
2. `GET /projects/{project}/feature-vectors/{name}/tags`
Both currently only supporting giving * in name

[API] Add list feature sets/vectors tags endpoints

---

mlrun/feature_store/api.py
mlrun/feature_store/ingestion.py
requirements.txt
tests/system/feature_store/test_feature_store.py

https://jira.iguazeng.com/browse/ML-1027

[Feature Store] Saving overwrite value for scheduled ingest

---

.github/workflows/system-tests-opensource.yml
automation/system_test/prepare.py
mlrun/projects/pipelines.py
mlrun/run.py
tests/system/api/test_secrets.py
tests/system/examples/basics/test_db.py
tests/system/feature_store/test_feature_store.py
tests/system/projects/test_project.py

* Secrets system tests - from the recent changes there
* Demos system tests - Breakage from mktemp change - https://github.com/mlrun/mlrun/pull/1257/files#diff-70248055cfe6255eee70163bf67189b832b6c469a72cdb6e26ec8d6f6816e856L67
* Project system tests - Breakage from disabling auto mount by default
* Examples system tests - Breakage from run local changes https://github.com/mlrun/mlrun/pull/1162/files#diff-e9b83378c14d7906bbe955feee4d4de89aea67a210758afbafd606b8e0e6eceeR157

[System Tests] Fix breakages

---

mlrun/runtimes/function.py
tests/api/runtimes/test_nuclio.py

Fixes: https://jira.iguazeng.com/browse/ML-912

[Nuclio] Fix function labels assignment

---

mlrun/projects/project.py
mlrun/utils/model_monitoring.py

[Model Monitoring] Add project and global functions for setting the model monitoring credentials

---

mlrun/api/api/utils.py
mlrun/config.py
tests/api/utils/test_scheduler.py

Fixes https://jira.iguazeng.com/browse/ML-1041

[API] Block running local runtimes in API

---

mlrun/api/api/endpoints/feature_store.py

Fixes https://jira.iguazeng.com/browse/ML-1046

[API] Fix ingest feature set endpoint OPA checks

---

mlrun/model_monitoring/stream_processing.py

[Model Monitoring] Events from `VotingEnsemble` were filtered and were not saved to targets

---

requirements.txt

 [Requirements] Bump storey to 0.7.8

---

mlrun/data_types/infer.py
tests/system/feature_store/test_feature_store.py

https://jira.iguazeng.com/browse/ML-1036

[Feature Store] Handling empty df

---

dockerfiles/jupyter/requirements.txt
requirements.txt

changes included - https://github.com/nuclio/nuclio-jupyter/releases/tag/v0.8.19

[Requirements] Bump nuclio-jupyter to 0.8.19

---

mlrun/model_monitoring/stream_processing.py

[Model Monitoring] Relieve checks to infer columns from data

---

docs/model_monitoring/initial-setup-configuration.ipynb

[Docs] Update model monitoring example

---

mlrun/api/api/endpoints/pipelines.py
mlrun/api/crud/pipelines.py
tests/api/api/test_pipelines.py

Fixes https://jira.iguazeng.com/browse/ML-1107

[API] Fix get pipeline endpoint OPA validation and project enrichment

---

mlrun/utils/regex.py

The links point to the wrong lines. Fix by anchoring to a specific revision.

[Utils] Fix unanchored github links

---

Makefile
mlrun/projects/project.py

Done by setting `MLRUN_NO_CACHE` to anything
Also:
* Remove serving image section from makefile (image not used, dockerfile was removed here https://github.com/mlrun/mlrun/pull/1323
* Change `get_or_create_project` to only save to DB (and not also to a file)

[Makefile] Add option to disable cache

---

mlrun/api/crud/model_endpoints.py
tests/system/model_monitoring/test_model_monitoring.py

[Model Monitoring] Don't explode in list endpoints endpoint on project w/o endpoints

---

mlrun/runtimes/serving.py
tests/api/runtimes/test_nuclio.py
tests/api/runtimes/test_serving.py

Bug fix, adding fields to ServingSpec.

[Serving] Fix node selectors and priority class name support

---

tests/integration/azure_blob/test_azure_blob.py

The `verify_auth_parameters_and_configure_env` function was retuning `None` for env tests that should be executed (vs. `False` if the test was not configured). However, this response was causing tests to be skipped due to the changes introduced with the `fsspec` tests. Cleared this up - now only a `None` response would cause a test to be skipped. Env tests that are properly configured return `{}` instead - this works with the `fsspec` tests which expect the function to return a dictionary with storage params in it.

[Tests] Azure blob env tests were always skipped

---

tests/system/model_monitoring/test_model_monitoring.py

…ble path to the serving function

[System Tests] Download the model to accessible path to the serving function

---

mlrun/api/api/endpoints/artifacts.py
mlrun/api/api/endpoints/functions.py
mlrun/api/api/endpoints/pipelines.py
mlrun/db/httpdb.py
mlrun/runtimes/base.py
mlrun/runtimes/daskjob.py
mlrun/runtimes/sparkjob/spark2job.py

See https://medium.com/python-features/how-to-avoid-classic-pitfall-while-passing-default-values-in-python-7002c0dc4c7c

[All] Don't default function argument to config value

---

tests/system/model_monitoring/test_model_monitoring.py

[System tests] Model monitoring test fix

---

mlrun/serving/remote.py
tests/serving/test_remote.py

* input_path was ignored in async RemoteStep, fixed and added test
* improve url/data handeling

[Serving] Fix async input_path bug in RemoteStep

---

mlrun/api/api/endpoints/model_endpoints.py
mlrun/api/crud/model_endpoints.py
tests/system/model_monitoring/test_model_monitoring.py

[Model Monitoring]  Set user access key to `delete_endpoint_record`

---

tests/system/model_monitoring/test_model_monitoring.py

[System Tests] Fix model monitoring metrics testing

---

mlrun/api/api/endpoints/projects.py
mlrun/api/db/sqldb/db.py
mlrun/api/utils/projects/follower.py
tests/api/api/test_projects.py
tests/api/db/test_projects.py
tests/api/utils/projects/test_follower_member.py

Fixes https://jira.iguazeng.com/browse/IG-19427

[API] Fix leader format in list projects endpoint

---

mlrun/api/crud/model_endpoints.py
mlrun/api/crud/projects.py
mlrun/datastore/v3io.py
mlrun/utils/model_monitoring.py
tests/system/model_monitoring/test_model_monitoring.py

[Model Monitoring] Clean project resources

---

mlrun/utils/helpers.py
tests/utils/test_helpers.py

In https://github.com/mlrun/mlrun/pull/1349 I did the change in config but forgot to use it
Fixes https://jira.iguazeng.com/browse/ML-1107

[Utils] Fix hub templating

---

requirements.txt
tests/api/api/test_docs.py

[Requirements] Change `fastapi` to `~=0.67.0` to fix docs generation bug

---

requirements.txt

[Requirements] Bump `storey` version to 0.8.2

---

mlrun/data_types/infer.py
mlrun/data_types/spark.py
mlrun/datastore/sources.py
mlrun/datastore/targets.py
mlrun/feature_store/api.py
mlrun/feature_store/ingestion.py
mlrun/model.py
tests/system/feature_store/test_feature_store.py

* support ingestion of very large datasets in chunks and writing results to multiple files
* added BigQuerySource for loading data into the feature store (support pandas and spark engine)
* chunking is supported in CSV, DataFrame, and BigQuery sources
* reduce the overhead with infer (infer on portion of the data when possible)

[Feature Store] ingestion of large files + BigQuery source (pandas + spark)

---

mlrun/builder.py
mlrun/config.py
mlrun/k8s_utils.py
tests/system/runtimes/assets/kubejob_function.py
tests/system/runtimes/test_kubejob.py

Testing:
For now I added a test that just deploys (part of it is image building) a function which doesn't really test the specific addition of this PR of supporting configuring pip ca, for that I need the ability to reconfigure the API during system tests which is complex, will add it in another PR

[Builder] Support providing pip ca file

---

mlrun/api/initial_data.py
mlrun/api/utils/db/alembic.py
mlrun/config.py
tests/api/utils/test_alembic_util.py

- Make the DB migration from sqlite to mysql configurable
- Make the use of DB backups configurable

[DB] DB Backups and DB Migrations are configurable

---

docs/runtimes/functions.md
docs/secrets.md
docs/store/datastore.md

Adding documentation on datastore processing, including details on credential handling for object-storage data stores.

[Docs] Document object-storage access and credential passing

---

mlrun/serving/states.py
tests/api/runtimes/test_serving.py

[Serving] Fix missing handler error handling

---

mlrun/data_types/spark.py

[Feature Store] Avoid collecting Spark dataframe to driver on infer

---

mlrun/datastore/targets.py
mlrun/feature_store/api.py

https://jira.iguazeng.com/browse/ML-1257

[Feature Store] Raise exception on targets that do not support overwrite=false

---

mlrun/feature_store/api.py
requirements.txt

[Feature Store] In case of scheduled ingest without new source, save filter start for next run

---

mlrun/builder.py
tests/test_builder.py

Fixes https://jira.iguazeng.com/browse/ML-1334

[Builder] Fix to enrich image only when needed

---

mlrun/datastore/sources.py
mlrun/datastore/targets.py
mlrun/feature_store/api.py

https://jira.iguazeng.com/browse/ML-1251

[Feature Store] Add support for incremental ingest with spark engine

---

mlrun/serving/remote.py
mlrun/serving/server.py
tests/serving/test_remote.py

[Serving] Fix RemoteStep

---

.github/workflows/system-tests-enterprise.yml

Bug from https://github.com/mlrun/mlrun/pull/1475

[System Tests] Fix args order

---

Jenkinsfile

ML-509 update release status

---

docs/feature-store/transformations.md

https://jira.iguazeng.com/browse/ML-674

[Docs] Additional details about name parameter

---

docs/secrets.md

https://jira.iguazeng.com/browse/ML-991

[Docs] Set env variables from k8s secrets in nuclio functions spec

---

docs/secrets.md

https://jira.iguazeng.com/browse/ML-1051

[Docs] Add section about creating secrets in project page and English editing

---

docs/model_monitoring/model-monitoring-deployment.ipynb

[Docs] Little fixes to model monitoring docs

---

mlrun/datastore/sources.py
mlrun/feature_store/api.py

https://jira.iguazeng.com/browse/ML-1529

[Feature Store] Several bug fixes in incremental spark ingest

---

docs/feature-store/transformations.md
mlrun/feature_store/feature_set.py

added count to aggregation types, and added s, h, d to the period parameter in feature_store.FeatureSet

[Docs] Add `add_aggregation` details

---

docs/feature-store/feature-sets.md

column names that start with t_ are not supported

[Docs] Limitation on column names of ingested data

---

docs/cli.md
docs/howto/remote.md
docs/install.md
docs/quick-start.ipynb
docs/store/artifacts.md
docs/tutorial/01-mlrun-basics.ipynb
docs/tutorial/04-pipeline.ipynb
docs/tutorial/index.md

replace all occurrences of Data Science Platform to MLOps Platform

[Docs] Replace all occurrences of Data Science Platform to MLOps Platform

---

mlrun/serving/states.py

[Serving] Pass context to StreamTarget

---

mlrun/api/db/sqldb/db.py
tests/api/db/test_functions.py

https://jira.iguazeng.com/browse/ML-1588

[DB] Fix list functions by non-existing tag to return empty list instead of all functions

---

mlrun/feature_store/feature_vector.py
tests/system/feature_store/test_feature_store.py

fixing get_offline_features and get_online_feature_service to take consideration of 'tag' and get the correct associated data.
[ML-1470](https://jira.iguazeng.com/browse/ML-1470)

[Feature Store] Fix issue with `get_offline` or `get_online` for tag

---

mlrun/artifacts/dataset.py
mlrun/projects/project.py
mlrun/utils/helpers.py
tests/projects/test_local_pipeline.py
tests/test_run.py

* fix bug log_dataset() without format resulted in bad target_path
* project.log_artifact() should not add the artifact to the project.spec (only to the DB)
* in project.set_artifact() verify the target_path was set, and provide short form for registering files
* fix log artifact w local_path="./x/y" (target path result was "artifact-path/./x/y")
* add/update doc strings

[Artifacts] Fix log_artifact/dataset issues

---

mlrun/artifacts/manager.py
mlrun/projects/project.py
tests/system/backward_compatiblity/assets/function.py
tests/system/backward_compatiblity/test_api_backward_compatibility.py
tests/system/backward_compatiblity/test_code_executed_in_runing_job.py
tests/system/base.py

https://jira.iguazeng.com/browse/ML-1274

[System Tests] Add API backward compatibility tests

---

mlrun/kfpops.py
mlrun/projects/pipelines.py
mlrun/utils/helpers.py

adds link to MLRun pipeline UI in the run log and in the notebook, e.g.:
Pipeline running (id=2e531881-7013-481a-ab65-7a763103dda5), `click here to view` the details in MLRun UI

[Projects] Print workflow ui hyperlink in project.run()

---

mlrun/feature_store/api.py

Fix a issue with extension of description

[Docs] Update documentation for function ingest

---

tests/system/feature_store/test_feature_store.py

https://jira.iguazeng.com/browse/ML-1351

[System Tests] Fix system tests stuck on unclosed online feature service

---

mlrun/datastore/base.py
tests/feature-store/test_infer.py
tests/system/feature_store/test_feature_store.py

[Datastore] Raise exception when `start_time`/`end_time` are passed and `time_column` is not

---

mlrun/feature_store/api.py

…s by default
https://jira.iguazeng.com/browse/ML-1606?filter=-1

[Feature Store] Fix permission check in `get_feature_vector`

---

mlrun/api/crud/model_endpoints.py

[Model Monitoring] `list_endpoints` should succeed even if batch job did not run yet

---

mlrun/feature_store/steps.py

Added int support and documentation to the Feature store's MapValues step.

[Feature Store] Add int support and documentation to the `MapValues` step

---

mlrun/api/api/endpoints/frontend_spec.py
mlrun/api/schemas/frontend_spec.py
tests/api/api/test_frontend_spec.py

https://jira.iguazeng.com/browse/ML-1663

[API] Add default artifact path to frontend spec endpoint response 

---

dockerfiles/base/requirements.txt
dockerfiles/mlrun-api/requirements.txt
extras-requirements.txt
mlrun/api/crud/pipelines.py
mlrun/runtimes/daskjob.py
requirements.txt
setup.py
tests/test_requirements.py

Backport of:
* https://github.com/mlrun/mlrun/pull/1439
* https://github.com/mlrun/mlrun/pull/1679
* https://github.com/mlrun/mlrun/pull/1677

[Requirements] Bump versions to conform to safety checks [Backport 0.9.x]

---

mlrun/api/db/sqldb/db.py
tests/api/api/test_projects.py

Leveraging https://github.com/mlrun/mlrun/pull/1622

[DB] Optimize runs counters calculation

---

mlrun/db/filedb.py
mlrun/execution.py
mlrun/feature_store/api.py
mlrun/feature_store/common.py
mlrun/feature_store/feature_set.py
mlrun/feature_store/feature_vector.py
mlrun/feature_store/steps.py
mlrun/mlutils/data.py
mlrun/model.py
mlrun/platforms/iguazio.py
mlrun/projects/operations.py
mlrun/projects/project.py
mlrun/run.py
mlrun/runtimes/base.py
mlrun/runtimes/function.py

Revision of documentation a few typos, repair a few formatting in examples, ... . Only comethic changes.

[Docs] Small revision of documentation

---

docs/feature-store/feature-sets.md

[Docs] Add that some advanced Storey functionalities are beta

---

mlrun/runtimes/sparkjob/abstract.py
tests/api/runtime_handlers/base.py
tests/api/runtime_handlers/test_sparkjob.py

Related to https://jira.iguazeng.com/browse/ML-1271

[Sparkjob] Support `code_to_function`

---

docs/howto/remote.md

[Docs] Repair `MLRUN_ARTIFACT_PATH`

---

mlrun/runtimes/sparkjob/abstract.py

Fixes https://jira.iguazeng.com/browse/ML-1732

[Sparkjob] Fix env parsing

---

mlrun/builder.py
tests/test_builder.py

https://jira.iguazeng.com/browse/ML-1730

[Builder] Fix mlrun command install

---

docs/api/index.rst
docs/api/mlrun.frameworks/index.rst
docs/api/mlrun.frameworks/mlrun.frameworks.auto_mlrun.rst
docs/api/mlrun.frameworks/mlrun.frameworks.lgbm.rst
docs/api/mlrun.frameworks/mlrun.frameworks.pytorch.rst
docs/api/mlrun.frameworks/mlrun.frameworks.sklearn.rst
docs/api/mlrun.frameworks/mlrun.frameworks.tf_keras.rst
docs/api/mlrun.frameworks/mlrun.frameworks.xgboost.rst
mlrun/frameworks/auto_mlrun/auto_mlrun.py
mlrun/frameworks/lgbm/__init__.py
mlrun/frameworks/pytorch/__init__.py
mlrun/frameworks/sklearn/__init__.py
mlrun/frameworks/tf_keras/__init__.py
mlrun/frameworks/xgboost/__init__.py

* Added the `mlrun.frameworks` module to the mlrun docs section
* Adjusted the documentation in some of the files according to sphinx's notes.

[Docs] Add `mlrun.frameworks` to the docs

---

tests/system/feature_store/test_feature_store.py

[Feature Store] Add test for two ingests

---

docs/conf.py
mlrun/api/crud/model_endpoints.py
mlrun/execution.py
mlrun/projects/operations.py
mlrun/projects/project.py
mlrun/run.py
mlrun/runtimes/base.py
mlrun/serving/states.py

A few updates of documentation (without impact do code) e.g. add missing parameters, repair mistake in example, change copyright from 2021 to 2022, etc.

[Docs] Update docstrings and copyright

---

tests/system/base.py
tests/system/demos/horovod/test_horovod.py

Plus comment out horovod test which is broken for long time until we're fixing it

[System Tests] Fix enterprise tests being skipped

---

mlrun/feature_store/feature_vector.py
tests/system/feature_store/test_feature_store.py

ML-1108
Partially based on [a branch](https://github.com/mlrun/mlrun/compare/development...katyakats:ML-1108-2) by @katyakats.

[Feature Store] Fix handling of aliases when getting online features

---

mlrun/feature_store/feature_vector.py

Fixes feature store system tests failure.

[Feature Store] Fix `None` error

---

mlrun/feature_store/api.py
mlrun/feature_store/feature_vector.py
requirements.txt
tests/system/feature_store/test_feature_store.py
tests/test_requirements.py

[Feature Store] Fix alias handling

---

Makefile

Mistakenly merged test code in https://github.com/mlrun/mlrun/pull/1774

[Makefile] Remove mistakenly merged test code

---

mlrun/api/main.py

Fixes https://jira.iguazeng.com/browse/ML-1787

[API] Set default thread pool max workers to 64

---

mlrun/config.py
tests/test_config.py

https://jira.iguazeng.com/browse/IG-20283
Related to  https://github.com/iguazio/provazio/pull/2338

[Config] Add default preemptible configuration

---

mlrun/api/api/endpoints/frontend_spec.py
mlrun/api/schemas/frontend_spec.py
mlrun/builder.py
mlrun/config.py
mlrun/runtimes/utils.py
tests/api/api/test_frontend_spec.py
tests/platforms/test_iguazio.py
tests/test_builder.py

Backport of https://github.com/mlrun/mlrun/pull/1755

[Builder] Support configuring image name prefix template to enforce [Backport 0.10.x]

---

mlrun/builder.py
mlrun/k8s_utils.py
mlrun/kfpops.py
mlrun/platforms/iguazio.py
tests/test_builder.py

Backport of https://github.com/mlrun/mlrun/pull/1782

[Runtimes] Fix to enrich KFP and Kaniko pods with the default function node selector [Backport 0.10.x]

---

mlrun/config.py
tests/test_config.py

Backport of https://github.com/mlrun/mlrun/pull/1793

[Config] Ignore null base64 string [Backport 0.10.x]

---

mlrun/api/db/sqldb/db.py
tests/api/api/test_functions.py

https://github.com/mlrun/mlrun/pull/1797 was merged in a rush, this PR addressing some comments brought up by @theSaarco offline on it

[DB] Add conflict message to retry on + improve testing

---

mlrun/runtimes/daskjob.py
mlrun/runtimes/utils.py
tests/system/examples/dask/test_dask.py

https://jira.iguazeng.com/browse/ML-1817

[Dask] Add shutdown dask cluster as part of the function's `close()` method

---

docs/feature-store/transformations.md

[Docs] Add doc about spark operator ingestion

---

mlrun/feature_store/api.py

[Feature Store] Support spark dataframe ingestion

---

mlrun/runtimes/sparkjob/abstract.py

fix issue with naming of method submit_job

[Sparkjob] Fix submit job method collision

---

mlrun/runtimes/function.py

fix failure when the Git URL has no branch

[Nuclio] Fix git URL resolution

---

mlrun/artifacts/base.py
mlrun/artifacts/model.py

When I tried to log DataArtifact with extra_data, I had an Exception

[Artifacts] Fix bug for log extra data in all kinds of artifacts

---

mlrun/config.py

[Feature Store] Re-enable `flush_interval` by default

---

docs/feature-store/end-to-end-demo/01-ingest-datasources.ipynb

[Docs] Reduce demo input size to reduce demo runtime

---

mlrun/builder.py
mlrun/k8s_utils.py
tests/test_builder.py

Part of https://jira.iguazeng.com/browse/ML-1880
- Enable support for passing of function spec attributes to kaniko

[Build] Assign more function spec attributes to kaniko pod

---

mlrun/feature_store/feature_set.py
tests/system/feature_store/test_spark_engine.py

[Feature Store] Preserve all columns in Spark aggregation step

---

docs/serving/model-serving-get-started.ipynb

while x variable that used to test the serving function was not defined - added my_data (just as in demo's getting started model serving)
using mock to server while echo.py functions wasn't present, added from echo.py import *

[Docs] Fix model serving example

---

docs/howto/remote.md
docs/install.md

two topics are identical
fixed numbering

[Docs] Fix set environment variables numbering

---

mlrun/api/api/deps.py
mlrun/api/api/endpoints/operations.py
mlrun/api/initial_data.py
mlrun/api/main.py
mlrun/api/utils/db/mysql.py
mlrun/db/httpdb.py
mlrun/runtimes/base.py
tests/api/api/test_functions.py
tests/api/test_api_states.py
tests/integration/sdk_api/httpdb/test_operations.py
tests/system/examples/dask/test_dask.py

Backport of https://github.com/mlrun/mlrun/pull/1830

[DB] Fix backup and migrations not to happen before unwanted-ly [Backport 0.10.x]

---

mlrun/feature_store/feature_set.py

Add examples for add_feature, add_entity and repair description for fullname (old version render doc visible issue)

[Docs] Add examples and repair description

---

mlrun/datastore/s3.py

[Datastore] Do not silence import error

---

extras-requirements.txt
setup.py
tests/test_requirements.py

[Requirements] Fix s3fs import error

---

mlrun/feature_store/api.py

[Feature Store] Only stop spark context if we created it

---

mlrun/datastore/sources.py

[Datastore] Add Iguazio application partner attribute

---

mlrun/k8s_utils.py
mlrun/runtimes/pod.py
tests/api/runtimes/test_kubejob.py

https://jira.iguazeng.com/browse/ML-1981

[Runtimes] Fix failing build as a result of wrong affinity type

---

docs/install-kubernetes.md

[Docs] Improve K8s installation guide

---

mlrun/runtimes/serving.py
mlrun/serving/states.py
tests/serving/test_flow.py

fixes https://jira.iguazeng.com/browse/ML-1785

[Serving] Verify that functions referenced in steps are added as children

---

mlrun/runtimes/utils.py
tests/api/api/test_utils.py

https://jira.iguazeng.com/browse/ML-1754

[API] Enable override of preemption mode on submit job

---

mlrun/db/httpdb.py

https://jira.iguazeng.com/browse/ML-2052

[KFP] Fix default function pod resources not being applied to KFP main container 

---

mlrun/datastore/sources.py
tests/system/feature_store/test_spark_engine.py

[Datastore] Parse time fields in CSVSource when engine is spark

---

mlrun/config.py
mlrun/k8s_utils.py

Fixes https://jira.iguazeng.com/browse/ML-2086

[Secrets] Move username from auth secret name to label

---

mlrun/runtimes/function.py
tests/api/runtimes/test_nuclio.py

https://jira.iguazeng.com/browse/ML-1968

[Nuclio] Fix base image pull secret assignment

---

mlrun/runtimes/sparkjob/abstract.py

Added default for sparkjob pods, default for driver and executor limits and requests
Support for ticket [ML-1722](https://jira.iguazeng.com/browse/ML-1722)

[Spark] Enrich default limits and requests

---

docs/feature-store/using-spark-engine.md

New validations were introduced here https://github.com/mlrun/mlrun/pull/1833

[Documentation] Fix documentation following new validations

---

mlrun/datastore/sources.py

[Datastore] Fix remote ingestion with `SnowflakeSource`

---

mlrun/feature_store/api.py
tests/system/feature_store/test_spark_engine.py

[Feature Store] Fix mix-up of transient time columns between multiple spark targets

---

automation/package_test/test.py
extras-requirements.txt
mlrun/datastore/sources.py
setup.py

[Datastore] Fix remote execution of `BigQuerySource`

---

extras-requirements.txt
setup.py
tests/test_requirements.py

[Requirements] Fix `ImportError` on ingest to Azure

---

mlrun/datastore/sources.py

[Datastore] Greatly improve BigQuery iterator performance

---

mlrun/config.py
mlrun/runtimes/base.py
mlrun/runtimes/constants.py
tests/api/runtime_handlers/test_kubejob.py
tests/conftest.py

https://github.com/mlrun/mlrun/pull/1944

[Runtimes] Fix jobs stuck in non-terminal state after node drain/preemption [Backport 1.0.x]

---

mlrun/api/api/utils.py
tests/api/api/test_utils.py
tests/integration/sdk_api/httpdb/test_exception_handling.py

Implements https://jira.iguazeng.com/browse/ML-2151 and https://jira.iguazeng.com/browse/ML-2150

[API] Block unauthorized paths on files endpoints

---

mlrun/runtimes/sparkjob/spark3job.py
tests/api/runtimes/test_spark.py

[Runtimes] Add java options spark job parameters [Backport 1.0.x]

---

mlrun/runtimes/base.py
mlrun/runtimes/constants.py
mlrun/runtimes/daskjob.py
mlrun/runtimes/kubejob.py
mlrun/runtimes/mpijob/v1.py
mlrun/runtimes/mpijob/v1alpha1.py
mlrun/runtimes/remotesparkjob.py
mlrun/runtimes/sparkjob/abstract.py
tests/api/runtime_handlers/base.py
tests/api/runtime_handlers/test_daskjob.py
tests/api/runtime_handlers/test_kubejob.py
tests/api/runtime_handlers/test_mpijob.py
tests/api/runtime_handlers/test_remotespark.py
tests/api/runtime_handlers/test_sparkjob.py

https://jira.iguazeng.com/browse/ML-2202

[Runtimes] Fix looping over all runtimes when monitoring for stuck runs 

---

mlrun/datastore/sources.py

[Datastore] Get Snowflake password from env or secret

---

mlrun/api/utils/projects/follower.py
mlrun/api/utils/projects/member.py
tests/api/api/feature_store/test_feature_sets.py
tests/api/api/feature_store/test_feature_vectors.py
tests/api/api/test_functions.py
tests/api/api/test_submit.py
tests/api/api/test_utils.py
tests/api/api/utils.py
tests/api/runtimes/test_serving.py
tests/api/utils/projects/test_leader_member.py
tests/integration/sdk_api/artifacts/test_artifacts.py
tests/integration/sdk_api/httpdb/test_exception_handling.py
tests/integration/sdk_api/httpdb/test_runs.py
tests/integration/sdk_api/run/test_run.py
tests/rundb/test_httpdb.py
tests/system/runtimes/test_archives.py
tests/system/runtimes/test_nuclio.py

Part of https://jira.iguazeng.com/browse/ML-2200

[API] Remove auto project creation when project doesn't exist

---

.github/workflows/unstable.yaml

[ML-2210](https://jira.iguazeng.com/browse/ML-2210) update unstable.yaml

[CI] Fix unstable action to not create duplicate releases

---

mlrun/feature_store/api.py
tests/system/feature_store/test_spark_engine.py

[Feature Store] Spark: Avoid writing empty output files

---

.flake8
mlrun/datastore/targets.py
mlrun/feature_store/api.py
tests/common_fixtures.py
tests/feature-store/test_ingest.py
tests/system/feature_store/test_feature_store.py

[Feature Store] Remove bad characters from source dataframe columns

---

docs/projects/ci-integration.md

@jillnogold added the periods on the last 2 sentences.

[Docs] Add period to the end of the sentences in `ci-integration.md`

---

Jenkinsfile

ML-2210 fixed pipeline by triggering each step in separated pod

[CI] Fix Jenkins release pipeline by triggering each step in separated pod

---

mlrun/runtimes/sparkjob/abstract.py
mlrun/runtimes/sparkjob/spark3job.py
tests/api/runtimes/test_spark.py

development equivalent of #2017
ML-2255

[Spark] Allow mounting v3io on driver but not executors

---

automation/package_test/test.py
requirements.txt
tests/automation/package_test/assets/ignored_vulnerabilities.json
tests/automation/package_test/test_package_test.py
tests/test_requirements.py

Backport of https://github.com/mlrun/mlrun/pull/2016 and https://github.com/mlrun/mlrun/pull/2024

[Requirements] Add vulnerability check to CI and fix vulnerabilities [Backport 1.0.x]

---

requirements.txt
tests/test_requirements.py

See comment in code for explanations
Fixes https://jira.iguazeng.com/browse/ML-2276

[Requirements] Add typing-extensions explictly

---

extras-requirements.txt
setup.py

ML-2278
See https://github.com/Azure/azure-sdk-for-python/issues/24765#issuecomment-1150310498

[Requirements] Limit Azure transitive dependency to avoid new bug

---

requirements.txt
tests/test_requirements.py

[Requirements] Bump storey to 1.0.6 [1.0.x]

---

mlrun/config.py
mlrun/runtimes/pod.py
tests/common_fixtures.py
tests/runtimes/test_base.py

Adding an `s3` auto-mount option that will use the `mount_s3` modifier.

[Runtimes] Adding s3 auto-mount option

---

mlrun/runtimes/sparkjob/abstract.py
tests/api/runtimes/test_spark.py

[Runtimes] Fix case where `with_igz_spark()` is called more than once

---

tests/system/feature_store/test_feature_store.py

[Feature Store] Add test for alias change

---

mlrun/artifacts/model.py
tests/test_datastores.py

`Artifact` --> `LegacyArtifact`
🤦

[Artifacts] Fix wrong inheritance in `LegacyModelArtifact`

---

mlrun/api/api/endpoints/functions.py
mlrun/api/crud/model_endpoints.py
mlrun/datastore/sources.py
mlrun/model_monitoring/model_monitoring_batch.py

Fixes https://github.com/mlrun/mlrun/pull/1941.

[Model Endpoints] Fix overriding of the v3io import

---

mlrun/datastore/sources.py

[Datastore] Fix `KafkaSource`

---

.github/workflows/ci.yaml

See comment in yaml for explanations

[CI] Run CI on push to backport release branches

---

mlrun/datastore/sources.py

[Datastore] Change Snowflake application to Iguazio_Platform

---

mlrun/datastore/targets.py
mlrun/feature_store/feature_vector.py
tests/system/feature_store/test_feature_store.py

[ML-2331](https://jira.iguazeng.com/browse/ML-2331)

[Datastore] Fix `OfflineVectorResponse.to_csv`

---

mlrun/feature_store/api.py
mlrun/feature_store/feature_vector.py
tests/system/feature_store/test_feature_store.py

[ML-2338](https://jira.iguazeng.com/browse/ML-2338)

[Feature Store] Fix alias handling in `OnlineVectorService`

---

dockerfiles/jupyter/requirements.txt
tests/test_requirements.py

Add `nbclassic>=0.2.8` to jupyter requirements

[Jupyter Image] Set `nbclassic>=0.2.8` to fix the image

---

mlrun/datastore/sources.py
tests/feature-store/test_model.py

[ML-2340](https://jira.iguazeng.com/browse/ML-2340)

[Datastore] Fix failure on empty string time parameter

---

mlrun/datastore/sources.py

[Datastore] Iguazio_Platform -> iguazio_platform

---

mlrun/datastore/utils.py
tests/system/runtimes/test_nuclio.py

[ML-2350](https://jira.iguazeng.com/browse/ML-2350)

[Datastore] Fix kafka URL parsing

---

requirements.txt
tests/test_requirements.py

[Requirements] Raise PyArrow upper limit to 6.x

---

mlrun/runtimes/sparkjob/abstract.py
mlrun/utils/regex.py
tests/utils/test_helpers.py

https://jira.iguazeng.com/browse/ML-2062

[Spark] Add DNS-1035 validation

---

automation/release_notes/generate.py
mlrun/__main__.py
mlrun/api/utils/projects/follower.py
mlrun/api/utils/projects/leader.py
mlrun/api/utils/projects/member.py
mlrun/projects/project.py
tests/integration/sdk_api/projects/test_project.py
tests/projects/test_project.py
tests/run/test_main.py

Contains fixes of:
https://github.com/mlrun/mlrun/pull/2092#pullrequestreview-1023166433
https://github.com/mlrun/mlrun/pull/2063#pullrequestreview-1023170144
Also added fix for release-notes generation to use `git log old_branch..new_branch` instead of `git log old_branch..HEAD`.

[Projects] Add `ensure_project` to CLI commands 

---

mlrun/api/crud/client_spec.py
mlrun/api/schemas/client_spec.py
mlrun/api/schemas/function.py
mlrun/builder.py
mlrun/config.py
mlrun/db/httpdb.py
mlrun/k8s_utils.py
mlrun/runtimes/pod.py
tests/runtimes/test_run.py
tests/test_builder.py

[Builder] Support pushing images to ECR [1.0.x]

---

mlrun/api/api/endpoints/functions.py
mlrun/api/crud/model_endpoints.py
mlrun/api/schemas/model_endpoints.py
mlrun/data_types/infer.py
mlrun/model_monitoring/helpers.py
mlrun/model_monitoring/model_monitoring_batch.py
mlrun/model_monitoring/stream_processing_fs.py
mlrun/serving/routers.py
mlrun/serving/v2_serving.py
tests/system/model_monitoring/test_model_monitoring.py

Revert "[Model Monitoring]: Create model monitoring feature set per model endpoint"

---

dockerfiles/jupyter/requirements.txt
tests/test_requirements.py

(cherry picked from commit 558591e66228343569eab43a87301202198620f4)

[Jupyter] Backport `nbclassic>=0.2.8` to fix the image [1.0.x]

---

.github/workflows/build-workflow-matrix.json
.github/workflows/build.yaml
.github/workflows/release.yaml

Backport of https://github.com/mlrun/mlrun/pull/2126 and  https://github.com/mlrun/mlrun/pull/2127

[CI] Enable to skip steps in the build & release workflows [Backport 1.0.x]

---

mlrun/serving/states.py

Fixes `TestNuclioRuntimeWithStream.test_serving_with_child_function`
ML-2388

[Serving] Fix `QueueStep`

---

LICENSE

https://jira.iguazeng.com/browse/ML-2363

[License] Update license to be detected in github

---

mlrun/builder.py
tests/test_builder.py

Builder - fix resolve repo with no tag

---

mlrun/data_types/spark.py
mlrun/feature_store/api.py
tests/system/feature_store/spark_ingest_remote_test_code.py
tests/system/feature_store/test_spark_engine.py

[ML-2403](https://jira.iguazeng.com/browse/ML-2403)

[Feature Store] Fix ingest failure when a feature is named "summary"

---

mlrun/builder.py
tests/test_builder.py

bp https://github.com/mlrun/mlrun/pull/2154

[Builder] create ECR cache repo [1.0.x]

---

mlrun/__main__.py
mlrun/projects/project.py

(cherry picked from commit a93abbfc93f2925fcf797c60170b1cbf86ff7744)
(cherry picked from commit da424ca13f01207f42b1e3ab5af3c118922aa0e0)

[Projects] Backport timeout for run workflow [1.0.x]

---

.github/workflows/build.yaml

(cherry picked from commit 2c02fdf1495b5f833d93cb797a98414ff9a4b90d)
(cherry picked from commit 19d2bcd54bb9ae1cf014b87117ef426f8b70c29b)
(cherry picked from commit 769b79c8660f0db760d9b9a86b396799154f30c6)

[CI] Add option to disable cache in build workflow [1.0.x]

---

mlrun/model_monitoring/features_drift_table.py
mlrun/model_monitoring/model_monitoring_batch.py
tests/model_monitoring/test_features_drift_table.py

* Added features drift table plot to later be produced during the batch monitoring job and in the `predict` handler of auto trainer.
* Adjusted the batch job code to be nicer.
* Moved the `check_for_drift` method to the `VirtualDrift` class and added per feature method to it as well.

[Model Monitoring] Added drift table plot and per feature detection

---

mlrun/runtimes/sparkjob/abstract.py
tests/api/runtimes/test_spark.py

https://jira.iguazeng.com/browse/ML-2429

[Spark] Enrich image pull secrets

---

mlrun/runtimes/sparkjob/abstract.py
tests/api/runtimes/test_spark.py

[Spark] Enrich image pull secrets [1.0.x]

---

docs/runtimes/spark-operator.ipynb

[ML-2325](https://jira.iguazeng.com/browse/ML-2325)

[Docs] Fix spark-operator documentation

---

mlrun/builder.py
mlrun/runtimes/base.py
mlrun/runtimes/sparkjob/abstract.py
tests/test_builder.py

Back ports https://github.com/mlrun/mlrun/pull/2132

[Builder] BackPort Fix pushing images to configured registry with a specific repository [1.0.x]

---

mlrun/builder.py
tests/test_builder.py

registry may end with repository after the `.amazonaws.com`
https://jira.iguazeng.com/browse/ML-2428

[Builder] Fix ECR URL inference

---

dockerfiles/mlrun-api/Dockerfile

https://jira.iguazeng.com/browse/ML-2447

[API] Fix unable to deploy dask cluster as a result of unresolved username in container

---

mlrun/api/api/utils.py
mlrun/api/schemas/__init__.py
mlrun/api/schemas/auth.py
mlrun/api/schemas/function.py
mlrun/api/utils/auth/verifier.py
mlrun/api/utils/clients/iguazio.py
mlrun/config.py
mlrun/runtimes/pod.py
tests/api/api/test_frontend_spec.py
tests/api/api/test_grafana_proxy.py
tests/api/api/test_utils.py
tests/api/api/utils.py
tests/api/runtimes/test_kubejob.py

[API] - Security context enrichment modes [1.0.x]

---

mlrun/api/api/utils.py
mlrun/api/schemas/auth.py
mlrun/api/utils/auth/verifier.py
mlrun/api/utils/clients/iguazio.py
tests/api/api/test_utils.py

https://jira.iguazeng.com/browse/ML-2451
1. move getting user unix id only on submit run
2. verify control plane session

[API] Fix get user unix id

---

mlrun/api/api/utils.py
mlrun/api/schemas/auth.py
mlrun/api/utils/auth/verifier.py
mlrun/api/utils/clients/iguazio.py
tests/api/api/test_utils.py

backports https://github.com/mlrun/mlrun/pull/2187

[API] Fix get user unix id [1.0.x]

---

.github/ISSUE_TEMPLATE/bug_report.yaml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/documentation_improvement.yaml
.github/ISSUE_TEMPLATE/feature_request.yaml
.github/ISSUE_TEMPLATE/installation_issue.yaml

Added templates for submitting GitHub issues. Includes Installation Issue, Bug Report, Documentation Improvement, Feature Request, and Question/Help/Support (Links to MLOps Live)

Added GitHub Issue Templates

---

mlrun/feature_store/api.py
tests/system/feature_store/test_spark_engine.py

[ML-2326](https://jira.iguazeng.com/browse/ML-2326)

[Feature Store] Fix spark ingest when `overwrite=False`

---

docs/concepts/jobs-overview.md
docs/concepts/model-training.md
docs/concepts/scheduled-jobs.md
docs/training/working-with-data-and-model-artifacts.md

Added docs for Jobs Overview, Scheduled Jobs, Model Training, Create a Basic Training Job, and Working with Data and Model Artifacts

[Docs] Added docs for concepts and training

---

dockerfiles/base/Dockerfile
dockerfiles/mlrun/Dockerfile
dockerfiles/models-gpu/Dockerfile

BP for https://github.com/mlrun/mlrun/pull/2199

[Runtimes] Allow runtime images to run with a non-root user [1.0.x]

---

docs/runtimes/mlrun_code_annotations.ipynb
docs/runtimes/mlrun_jobs.ipynb

https://jira.iguazeng.com/browse/ML-105

[Docs] Save notebook before running code_to_function note

---

mlrun/api/api/endpoints/functions.py
tests/api/runtimes/test_dask.py
tests/api/runtimes/test_nuclio.py

Fixes:
https://jira.iguazeng.com/browse/ML-2482
https://jira.iguazeng.com/browse/ML-2481

[Runtimes] Fix security context enrichment for dask and nuclio

---

mlrun/api/api/endpoints/functions.py
tests/api/runtimes/test_dask.py
tests/api/runtimes/test_nuclio.py

(cherry picked from commit abb15658f58e227572a8e993f27f82108b2f9851)

[Runtimes] Backport Fix security context enrichment for dask and nuclio [1.0.x]

---

mlrun/api/api/endpoints/functions.py
mlrun/api/api/utils.py
mlrun/api/schemas/project.py
mlrun/api/utils/clients/iguazio.py
mlrun/api/utils/projects/remotes/nop_leader.py
mlrun/api/utils/scheduler.py
tests/api/api/test_utils.py
tests/api/utils/clients/test_iguazio.py
tests/api/utils/projects/test_follower_member.py
tests/api/utils/test_scheduler.py

[Scheduler] Backport Fix failing schedules with security context enrichment [1.0.x]

---

mlrun/api/api/utils.py
mlrun/api/schemas/function.py
mlrun/config.py
mlrun/kfpops.py
mlrun/projects/pipelines.py
tests/projects/test_remote_pipeline.py

[Pipelines] Kubeflow pipeline pod security context [1.0.x] (#2207)

---

mlrun/config.py
mlrun/db/httpdb.py
tests/rundb/test_unit_httpdb.py

Fix for https://jira.iguazeng.com/browse/ML-2479 
BP for https://github.com/mlrun/mlrun/pull/2219

[SDK] Fix fail to send request to MLRun API with `ConnectionResetError` [1.0.x]

---

mlrun/config.py
tests/test_config.py

Allow enabling security context enrichment only for iguazio >= 3.5.1

[API] Verify security context enrichment mode is allowed

---

mlrun/config.py
tests/test_config.py

[API] Verify security context enrichment mode is allowed [1.0.x]

---

mlrun/api/api/endpoints/feature_store.py
mlrun/feature_store/api.py
mlrun/feature_store/common.py
mlrun/feature_store/ingestion.py

1. Fixed https://jira.iguazeng.com/browse/ML-2158. 
2. Fixed security context enrichments.

[Feature Store] Add enrichments and validation to functions created through ingest endpoint

---

mlrun/api/api/endpoints/feature_store.py
mlrun/api/api/endpoints/functions.py
mlrun/api/api/utils.py
mlrun/feature_store/api.py
mlrun/feature_store/common.py
mlrun/feature_store/ingestion.py
tests/api/runtimes/test_nuclio.py
tests/api/runtimes/test_serving.py

Backport - https://github.com/mlrun/mlrun/pull/2250
Backport - https://github.com/mlrun/mlrun/pull/2231

[API] Enrich functions in endpoints [1.0.x]

---

mlrun/db/httpdb.py
mlrun/serving/remote.py

Fix using mlrun config with proper imports

[SDK] Fix import errors with HTTP retry mechanism

---

docs/concepts/scheduled-jobs.md
docs/feature-store/feature-sets.md
docs/feature-store/retrieve-offline-data.md
docs/install.md
docs/install/local-docker.md
docs/runtimes/configuring-job-resources.md
docs/secrets.md

[Docs] Typo changes

---

mlrun/feature_store/api.py
tests/feature-store/test_ingest.py

[ML-1488](https://jira.iguazeng.com/browse/ML-1488)
- Updated both in `ingest()` and in `_ingest_with_spark()`
- Added test

[Feature Store] Update `return_df` behaviour in ingest

---

automation/scripts/github_workflow_free_space.sh

Signed-off-by: eliyahu77 <root@linux-eliyahun.iguaz.io>

[MLRun] Fix shebang with copyright

---

.github/workflows/ci.yaml
automation/test.py

If the copyright checker finds a problematic file, it will print out the copyright message to add to the file

[CI] Add Copyright Instructions To Copyright Checker

---

mlrun/feature_store/feature_set.py
tests/system/feature_store/test_feature_store.py

Fixes an issue introduced in #2237.
[ML-2536](https://jira.iguazeng.com/browse/ML-2536)

[Feature Store] Fix drop of partitioning columns

---

mlrun/api/api/endpoints/runs.py
tests/api/api/test_runs.py

Fixes: 
- https://jira.iguazeng.com/browse/ML-2544
- https://jira.iguazeng.com/browse/ML-2540
- https://jira.iguazeng.com/browse/ML-2541

[API] Fix not raising error when deleting runs with unprivileged user

---

requirements.txt
tests/test_requirements.py

https://github.com/mlrun/storey/releases/tag/v1.1.9

[Requirements] Bump storey to 1.1.9

---

mlrun/datastore/targets.py

[Datastore] fix NoSqlBaseTarget non-instantiate check

---

tests/system/base.py
tests/system/feature_store/test_spark_engine.py

By deploying the image only once.

[Spark] Reduce runtime of spark system tests

---

mlrun/api/api/utils.py
mlrun/builder.py
mlrun/runtimes/base.py
mlrun/runtimes/pod.py
tests/test_builder.py

[Builder] Add service account to kaniko pod [1.1.x]

---

requirements.txt

[Requirements] Backport Bump v3io and v3iofs versions [1.1.x]

---

mlrun/run.py

fix system issue caused by https://github.com/mlrun/mlrun/pull/2329

[Nuclio] Fix bug in system tests with nuclio jobs

---

docs/api/mlrun.feature_store.rst
mlrun/feature_store/feature_set.py
mlrun/feature_store/feature_vector.py

Fixing issues #2312 and #2313.

[Docs] Add docs for feature-set spec and status

---

requirements.txt
tests/test_requirements.py

(cherry picked from commit a50e6f4c4de6fab9afafd43ff064d6624b28856e)

[Requirements] Blacklist protobuf 3.20.2 [1.1.x]

---

mlrun/runtimes/mpijob/v1.py

Fixes https://jira.iguazeng.com/browse/ML-2590

[Runtimes] Enrich MPI with service account

---

mlrun/api/utils/db/backup.py
mlrun/config.py
tests/api/utils/test_db_backup.py

(cherry picked from commit c036e3e833a0abb7fc1c11c3fef9f6fb533bb990)

[Migrations] Fix failure in backup as a result of a big blob [1.1.x]

---

docs/store/datastore.md
mlrun/datastore/s3.py
tests/integration/aws_s3/test-aws-s3.yml
tests/integration/aws_s3/test_aws_s3.py

[Datastore] Support S3 authentication using local profile or assuming an IAM role [1.1.x]

---

mlrun/datastore/v3io.py
tests/system/datastore/test_v3io.py

[V3IO] Add support for upload of >5GB files

---

mlrun/datastore/v3io.py
tests/system/datastore/test_v3io.py

[V3IO] Add support for upload of >5GB files (#2379)

---

docs/model_monitoring/model-monitoring-deployment.ipynb

This makes the wording on the configuration more clear based on feedback from customers

[Docs] Update wording on grafana configuration for model monitoring

---

mlrun/datastore/s3.py
tests/integration/aws_s3/test_aws_s3.py

Completes the implementation done in #2395 - it uses the profile or assume-role parameters when using `fsspec` to access the storage (in `as_df()` for example).

[Datastore] S3 - support profile and assume-role when using `fsspec`

---

mlrun/datastore/s3.py
tests/integration/aws_s3/test_aws_s3.py

[Datastore] S3 - support profile and assume-role when using `fsspec` [1.1.x]

---

mlrun/__main__.py

[CLI] Add option to run the API/DB in background process

---

mlrun/api/db/sqldb/db.py
tests/api/db/test_artifacts.py

Fixing ml-2638.
Back-porting #2433

[Artifacts] Fix `del_artifact` to properly support providing a tag [1.1.x]

---

mlrun/runtimes/utils.py
mlrun/utils/clones.py

Remove username and password from git repo URL so that we don't display sensitive information in functions spec (code origin)

[Utils] Redact username and password from git repo URL

---

mlrun/utils/clones.py

bp https://github.com/mlrun/mlrun/pull/2444

[Utils] Redact username and password from git repo URL [1.1.x]

---

mlrun/api/utils/projects/follower.py

We've seen a bug where the `updated_at` field returned from the projects leader as `0001-01-01 00:00:00` which is an unsupported timestamp in iguazio's database and causes the next query to return a `500` status code.
Added some defensive programming:
- If for any reason we fail GETing the projects from the project's leader, we'll try again without the `update_at` filter.
- If for any reason the returned latest update at is older than the epoch (`1970-01-01 00:00:00`), we set it to the epoch.

[Projects] Fix Sync Mechanism Using Wrong `updated_at` Filter

---

.github/workflows/ci.yaml
dev-requirements.txt

(cherry picked from commit ce1c92d5a2614782374da737fa35b4d38c93256a)

[CI] Add lint step for python 3.9 and fix linting failure [1.1.x]

---

docs/install/local-docker.md

Only note for port reconfiguration

[Docs] Note for port reconfiguration

---

mlrun/__main__.py

[CLI] Support schedule param to be passed as bool [1.1.x]

---

mlrun/api/utils/projects/follower.py

Backports - https://github.com/mlrun/mlrun/pull/2458 & https://github.com/mlrun/mlrun/pull/2470

[Projects] Fix Sync Mechanism Using Wrong `updated_at` Filter [1.1.x]

---

extras-requirements.txt
requirements.txt

[Requirements] Add Jinja2 explictly [1.1.x]

---

mlrun/run.py

Pushed the maps into the ContextHandler so they will be created on demand and not on import.

[Run] Move maps initialization into the ContextHandler

---

requirements.txt
tests/test_requirements.py

ticket - https://jira.iguazeng.com/browse/ML-2653
reverts https://github.com/mlrun/mlrun/pull/2472

[Requirements] Explicitly require importlib-metadata >= 3.6

---

mlrun/serving/states.py
requirements.txt
tests/system/runtimes/test_nuclio.py
tests/test_requirements.py

[ML-2672](https://jira.iguazeng.com/browse/ML-2672)

[Requirements] Bump storey, expand testing of `QueueStep`

---

mlrun/runtimes/sparkjob/spark3job.py
tests/api/runtimes/test_spark.py

[ML-1557](https://jira.iguazeng.com/browse/ML-1557)

[Runtimes] Job set executor SA only

---

mlrun/datastore/sources.py

[ML-2685](https://jira.iguazeng.com/browse/ML-2685)

[Datastore] Fix SASL bug in `KafkaSource`

---

requirements.txt
tests/test_requirements.py

https://github.com/mlrun/mlrun/pull/2488

[Requirements] Bump min requirements for few packages 

---

mlrun/datastore/v3io.py

[ML-2691](https://jira.iguazeng.com/browse/ML-2691)

[DataStore] V3io: Fix put large strings

---

mlrun/api/db/sqldb/db.py
mlrun/db/httpdb.py
tests/api/db/test_feature_sets.py
tests/integration/sdk_api/feature_store/test_feature_store.py
tests/rundb/test_httpdb.py

https://jira.iguazeng.com/browse/ML-1639

[Feature Store] Update feature set and vector fix

---

mlrun/datastore/redis.py
tests/system/datastore/test_redis.py

[ML-2706](https://jira.iguazeng.com/browse/ML-2706)

[FeatureStore] Fix redis purge after storey redis key change

---

mlrun/api/db/sqldb/db.py
mlrun/db/httpdb.py
tests/api/api/test_artifacts.py

https://jira.iguazeng.com/browse/ML-2664

[Artifacts] Fix list artifact with multiple tags returns multiple times with the same tag

---

mlrun/datastore/redis.py
tests/system/datastore/test_redis.py
tests/system/feature_store/test_feature_store.py

[ML-2706](https://jira.iguazeng.com/browse/ML-2706)

[DataStore] Redis: fix rm() for non-default target, build redis key with hashtags and fix tests

---

mlrun/api/api/endpoints/internal/memory_reports.py
mlrun/api/utils/memory_reports.py

because this feature is enabled by a flag there is no reason to import it until used, moved to a class.

[Memory Report] Fix objgraph import

---

mlrun/data_types/spark.py
tests/system/feature_store/test_spark_engine.py

[ML-1272](https://jira.iguazeng.com/browse/ML-1272)

[Feature Store] Remove id from spark_stats

---

mlrun/feature_store/api.py

[ML-2632](https://jira.iguazeng.com/browse/ML-2632)

[FeatureStore] Block preview with spark

---

mlrun/api/db/sqldb/db.py
tests/api/db/test_feature_sets.py

https://jira.iguazeng.com/browse/ML-2710
handle special cases where a feature set with the same uid exists but has a different tag - just re-tag the old object

[FeatureStore] Update feature set / vector fix

---

mlrun/datastore/targets.py
mlrun/feature_store/steps.py
tests/feature-store/test_steps.py

This pr address to [ML-2719](https://jira.iguazeng.com/browse/ML-2719).
Also copy data before saving to nosql target, because when saving df to nosql target it's changed unexpectedly.

[Feature Store] Check if mapping is unique and copy data before saving to nosql target

---

mlrun/runtimes/function.py
mlrun/runtimes/pod.py
tests/api/runtimes/test_kubejob.py
tests/api/runtimes/test_nuclio.py

Add with_annotations function so users will be able to set an annotations for the different runtimes:
image
https://jira.iguazeng.com/browse/ML-1495

[Runtimes] Add with annotations method for runtimes

---

mlrun/feature_store/feature_set.py
mlrun/serving/states.py
tests/serving/test_flow.py

Fix bug https://jira.iguazeng.com/browse/ML-2346

[Serving] Use before param in add_aggregate function as expected.

---

mlrun/api/utils/clients/chief.py
mlrun/config.py

Fixes https://jira.iguazeng.com/browse/ML-2759

[API] Add timeouts for requests which are getting rerouted to chief

---

mlrun/feature_store/retrieval/base.py
mlrun/feature_store/retrieval/dask_merger.py
mlrun/feature_store/retrieval/local_merger.py
mlrun/feature_store/retrieval/spark_merger.py

[ML-2773](https://jira.iguazeng.com/browse/ML-2773)

[Feature Store] Reduce merger peak memory consumption

---

mlrun/artifacts/manager.py
mlrun/artifacts/model.py
mlrun/projects/project.py
tests/projects/test_project.py

[Artifacts] Fix legacy artifacts load when loading project [1.1.x]

---

mlrun/utils/http.py
tests/rundb/test_unit_httpdb.py

BP for - https://github.com/mlrun/mlrun/pull/2576, https://github.com/mlrun/mlrun/pull/2586

[API] Make the HTTP retry mechanism more generic [1.1.x]

---

mlrun/datastore/v3io.py
tests/system/datastore/test_v3io.py

[ML-2796](https://jira.iguazeng.com/browse/ML-2796)

 [DataStore] Fix v3io listdir: fix logic error and move to httpclient transport

---

mlrun/api/db/sqldb/db.py

Fixes https://jira.iguazeng.com/browse/ML-2746.

[Artifacts] List Artifacts enrich with tag for all tags 

---

tests/system/feature_store/test_feature_store.py

Fix CI failure in test_sync_pipeline_chunks()

[Tests] Adopt test_sync_pipeline_chunks to entities set to df index

---

mlrun/feature_store/api.py
tests/system/feature_store/test_spark_engine.py

Fixes transient failure and speeds up the test.

[Tests] Fix `test_schedule_on_filtered_by_time`

---

mlrun/feature_store/retrieval/spark_merger.py

[ML-2798](https://jira.iguazeng.com/browse/ML-2798)

[Feature Store] Fix target path in spark merger

---

mlrun/projects/operations.py
mlrun/projects/project.py
mlrun/runtimes/base.py
mlrun/runtimes/kubejob.py
tests/api/runtimes/test_kubejob.py

Introduced new param to the `build_function` method which allows users to overwrite pre-existing build commands
https://jira.iguazeng.com/browse/ML-2702

[Build] Add `overwrite_build_params` for `build_function`

---

mlrun/builder.py
tests/system/runtimes/test_archives.py

1. need to check if security context is enabled before `chown` on workdir.
2. need to get the security context because it’s not always given depending on the flow.
3. rewrite `src_dir` and `source` logic to make it simpler and easy to understand.
4. when using source from git or remote we need to copy the context.

[Builder] Build function from source fixes

---

mlrun/api/crud/logs.py
mlrun/api/crud/secrets.py

when not in k8s the check fails, fixed

[API] fix check for k8s in get logs

---

docs/conf.py

Added mock imports to sphinx documentation

[Docs] Fix docs generating of frameworks

---

mlrun/projects/operations.py
mlrun/projects/project.py
mlrun/runtimes/kubejob.py
tests/system/projects/assets/handler.py
tests/system/projects/test_project.py

Fixes https://jira.iguazeng.com/browse/ML-2849

[Projects] Fix project doesn't persist changes on a function when using `project.build/run_function`

---

mlrun/api/db/sqldb/db.py
tests/api/db/test_artifacts.py

https://jira.iguazeng.com/browse/ML-2853

[Artifacts] Fix list artifacts when having multiple hyper params runs

---

mlrun/api/db/sqldb/db.py
tests/api/db/test_artifacts.py

https://jira.iguazeng.com/browse/ML-2854

[Artifacts] Fix querying artifacts with tag name while link artifact is not tagged

---

mlrun/__main__.py
tests/system/projects/test_project.py

https://jira.iguazeng.com/browse/ML-2865
Pass timeout param forward for waiting on pod status

[CLI] Waiting for pod status with timeout fix when running project

---

mlrun/__main__.py
tests/system/projects/test_project.py

backports https://github.com/mlrun/mlrun/pull/2635

[CLI] Waiting for pod status with timeout fix when running project [1.1.x]

---

tests/system/feature_store/test_feature_store.py

Including a fix mirroring #2598.

[Tests] Fix failing feature store system tests

---

mlrun/datastore/sources.py
tests/system/feature_store/test_feature_store.py

Improves the error described in #2648.
Relates to [ML-2800](https://jira.iguazeng.com/browse/ML-2800).

Raise error on `ingest` with `KafkaSource`

---

mlrun/__init__.py
mlrun/api/api/endpoints/files.py
mlrun/api/crud/marketplace.py
mlrun/datastore/azure_blob.py
mlrun/datastore/base.py
mlrun/datastore/datastore.py
mlrun/datastore/filestore.py
mlrun/datastore/google_cloud_storage.py
mlrun/datastore/inmem.py
mlrun/datastore/redis.py
mlrun/datastore/s3.py
mlrun/datastore/store_resources.py
mlrun/datastore/v3io.py
mlrun/execution.py
mlrun/secrets.py
mlrun/utils/clones.py
mlrun/utils/notifications/notification/git.py
tests/test_datastores.py
tests/utils/test_get_secrets.py

Backport 
- https://github.com/mlrun/mlrun/pull/2661
- https://github.com/mlrun/mlrun/pull/2659 
- https://github.com/mlrun/mlrun/pull/2633

[Secrets] Backport secrets fixes [1.2.x]

---

mlrun/model.py

(cherry picked from commit 09c3e9aecf94aed0c4bffe89c87d5d2859572699)

[Run] Fix outputs wait for completion [1.2.x]

---

dev-requirements.txt
mlrun/serving/server.py
tests/system/runtimes/assets/map_avro.py
tests/system/runtimes/test_nuclio.py

backporting [ML-2836](https://jira.iguazeng.com/browse/ML-2836)

[FeatureStore] Fix serving to support AVRO encoded kafka (#2658)

---

mlrun/execution.py
mlrun/secrets.py
tests/utils/test_get_secrets.py

[Secrets] Fix `get_secret_or_env` [1.2.x]

---

mlrun/__init__.py
mlrun/__main__.py
mlrun/datastore/datastore.py
mlrun/db/filedb.py
mlrun/runtimes/local.py
tests/api/conftest.py
tests/common_fixtures.py
tests/test_datastores.py

(cherry picked from commit 671247a77711f47d1cbe7974456fee66e6285de3)

[DataStore] Fix how we resolve if running as API [1.2.x]

---

mlrun/__main__.py

https://github.com/mlrun/mlrun/pull/2665

[CLI] Do not ignore unknown options

---

mlrun/projects/pipelines.py

[ML-2953](https://jira.iguazeng.com/browse/ML-2953)

[Projects] Add missing `overwrite` field to `WorkflowSpec` [1.2.x]

---

mlrun/projects/pipelines.py
mlrun/projects/project.py
tests/system/projects/test_project.py

[ML-2931](https://jira.iguazeng.com/browse/ML-2931)

[Projects] Raise error for workflow scheduling with non-remote project [1.2.x]

---

mlrun/__main__.py

Revert "[CLI] Do not ignore unknown options [1.2.x]"

---

mlrun/__main__.py

Revert "[CLI] Do not ignore unknown options"

---

mlrun/api/api/endpoints/schedules.py
mlrun/api/crud/secrets.py
mlrun/api/utils/scheduler.py
mlrun/k8s_utils.py
tests/api/conftest.py
tests/api/utils/test_scheduler.py

[Schedules] Scheduled tasks access-key usage refactor (#2695) [1.2.x]

---

mlrun/projects/pipelines.py
mlrun/projects/project.py
tests/system/projects/test_project.py

[ML-2931](https://jira.iguazeng.com/browse/ML-2931)

[Projects] Raise error for workflow scheduling with non-remote project [1.1.x]

---

mlrun/projects/pipelines.py
mlrun/projects/project.py
tests/system/projects/test_project.py

[ML-2931](https://jira.iguazeng.com/browse/ML-2931)

[Projects] Raise error for workflow scheduling with non-remote project

---

mlrun/__init__.py
mlrun/__main__.py
mlrun/config.py
mlrun/datastore/datastore.py
tests/api/conftest.py
tests/common_fixtures.py
tests/test_convenince_methods.py
tests/test_datastores.py

[CLI] Merge fixes for get runtime command and config set environment [1.2.x]

---

docs/install/aws-install.md

…s sent to AWS console to get the recommended parameters

[Docs] Edit wording to make AWS Documentation more clear

---

mlrun/utils/helpers.py

[Utils] - Remove spammy logs

---

mlrun/projects/project.py

* curently function cache is ignored and local changes are ovewritten, this fixes that

[Project]  Set default sync=True in project.get_function()

---

docs/contents.rst
docs/data-prep/ingest-data-fs.md
docs/ecosystem.md
docs/feature-store/feature-sets.md
docs/feature-store/feature-store-overview.md
docs/feature-store/transformations.md
docs/index.md
docs/install/aws-install.md
docs/serving/available-steps.md
docs/serving/getting-started.ipynb
docs/tutorial/index.md

[Docs] Add ecosystem, bug fixes

---

mlrun/api/api/endpoints/files.py
tests/api/api/test_files.py

[API] Add project-scope `files`/`filestat` API that work with project secrets [1.2.x]

---

mlrun/api/utils/scheduler.py
tests/api/utils/test_scheduler.py

[Schedules] Fix label handling when reloading schedules [1.2.x]

---

mlrun/artifacts/manager.py
tests/artifacts/test_artifacts.py
tests/artifacts/test_model.py

https://jira.iguazeng.com/browse/ML-2905

[Artifacts] Don't resolve artifact `target_path` if explicitly request `upload=False` [1.2.x]

---

mlrun/runtimes/base.py

Log the tracking information for when running locally / client
https://jira.iguazeng.com/browse/ML-3011

[API] Remove print from api [1.2.x]

---

mlrun/runtimes/base.py

[API] Remove print from api

---

mlrun/projects/pipelines.py
mlrun/projects/project.py
tests/system/projects/test_project.py

Revert "[Projects] Raise error for workflow scheduling with non-remote project [1.2.x]"

---

mlrun/__main__.py
tests/run/assets/sleep.py
tests/run/test_main.py
tests/system/runtimes/assets/sleep.py
tests/system/runtimes/test_kubejob.py

https://jira.iguazeng.com/browse/ML-3010

[CLI] Fix watch when running function through CLI

---

mlrun/k8s_utils.py
mlrun/runtimes/base.py
tests/api/runtime_handlers/base.py

Cleanup some lines from runtime to a more appropriate place

[Runtime] Move some k8s logic to k8s helpers

---

mlrun/__main__.py
tests/run/assets/sleep.py
tests/run/test_main.py
tests/system/runtimes/assets/sleep.py
tests/system/runtimes/test_kubejob.py

(cherry picked from commit 1e6278826d90a6c219aeab25951969da6da7cbf4)

[CLI] Backport - Fix watch when running function through CLI [1.2.x]

---

mlrun/runtimes/sparkjob/abstract.py

backports #2738 from development

[Runtime] Fix resolving completion time [1.2.x]

---

mlrun/projects/project.py

Reduce friction for users working with sdk from current working directory

[Projects] Set default context path to working directory

---

mlrun/feature_store/api.py

Reverts #2694.
This reverts commit 05eb0dafdbad7350ee5e03f88cfbfc5b24987edd.

Revert "[Spark] Shut local spark context down when `ingest` completes [1.2.x]

---

mlrun/runtimes/local.py
tests/run/assets/fail.py
tests/run/test_run.py

Fixes https://jira.iguazeng.com/browse/ML-2986

[Run] Fix not updating the run state when running local fails on pre-loading of the function [1.2.x]

---

mlrun/api/main.py
mlrun/config.py

BP for https://github.com/mlrun/mlrun/pull/2613

[API] Configure Uvicorn Keep Alive Timeout [1.1.x]

---

mlrun/execution.py
mlrun/runtimes/base.py
tests/api/api/test_submit.py
tests/projects/test_project.py

BP for https://github.com/mlrun/mlrun/pull/2671

[API] Fix run paramaters larger than int64 corrupting projects [1.2.x]

---

mlrun/__main__.py
tests/run/test_main.py

(cherry picked from commit 11f31303c5f217be18a44a154ce04516f6f71b4f)
backports #2745

[CLI] Validate base arguments (#2745) [1.2.x]

---

mlrun/model_monitoring/helpers.py
tests/system/model_monitoring/test_model_monitoring.py

…nction (#2688)
(cherry picked from commit e8902c4e5381e4ab30bf2184efb5c076271f869e)

[Model Monitoring] Ensure auth info for model monitoring batch job function [1.2.x]

---

mlrun/runtimes/local.py
tests/run/assets/fail.py
tests/run/test_run.py

(cherry picked from commit ac41d7d2a5ac96f375d57bcc24513461753fb07b)

[Run] Fix not updating the run state when running local fails on pre-loading of the function 

---

mlrun/api/utils/clients/chief.py
mlrun/config.py

(cherry picked from commit 588e04c3b2fe7fda8abfe54d786831c4cf728090)

[API] Add timeouts for requests which are getting rerouted to chief [1.1.x]

---

docs/install/kubernetes.md
mlrun/runtimes/mpijob/abstract.py

- Some improvements to make the install docs clearer.
- Now there is only a full installation with options to opt out of some features

[Docs] Update MLRun CE Kubernetes Installation Docs for new "only full" Deployment

---

mlrun/__main__.py
mlrun/model.py
mlrun/runtimes/base.py
mlrun/runtimes/local.py
tests/api/runtimes/base.py
tests/api/runtimes/test_kubejob.py
tests/run/test_main.py
tests/system/runtimes/assets/function_with_args.py
tests/system/runtimes/test_kubejob.py

(cherry picked from commit c08f2d106b6aad4e3a2022df6029bfdac8d1f9d2)
bp (#2765)

[CLI][Runtimes] URL placeholder for using run args without URL [1.2.x]

---

mlrun/api/crud/pipelines.py

[Pipelines] Support `list_pipelines` with pagination & predicates (#2784) [1.2.x]

---

mlrun/config.py
mlrun/datastore/datastore.py
mlrun/datastore/filestore.py
tests/test_datastores.py

[Datastore] Backport fix handling of DataItem path in windows

[Datastore] Backport fix handling of DataItem path in windows [1.2.x]

---

mlrun/feature_store/retrieval/local_merger.py
tests/system/feature_store/test_spark_engine.py

Development version of #2790.
[ML-3092](https://jira.iguazeng.com/browse/ML-3092)

[Feature Store] Fix: set index before write to target in local merger

---

mlrun/feature_store/retrieval/local_merger.py
tests/system/feature_store/test_spark_engine.py

[ML-3092](https://jira.iguazeng.com/browse/ML-3092)

[Feature Store] Fix: set index before write to target in local merger [1.2.x]

---

mlrun/datastore/sources.py

[ML-3102](https://jira.iguazeng.com/browse/ML-3102)

[Datastore] Fix `CSVSource` parsing of `timestamp_key`

---

mlrun/api/api/endpoints/frontend_spec.py
mlrun/api/api/endpoints/marketplace.py
mlrun/platforms/__init__.py
mlrun/platforms/iguazio.py
tests/api/api/test_frontend_spec.py
tests/platforms/test_iguazio.py

[API] verify cookie session is iguazio-like sessions [1.2.x]

---

mlrun/projects/pipelines.py
mlrun/utils/notifications/notification/base.py
mlrun/utils/notifications/notification/slack.py
mlrun/utils/notifications/notification_pusher.py

[Projects] Slack notify remote workflow [1.2.x]

---

mlrun/serving/routers.py
mlrun/serving/server.py
mlrun/serving/v2_serving.py
tests/serving/test_serving.py

Fixing 2 bugs : 
1. Using GET method of router serving - https://jira.iguazeng.com/browse/ML-2918
2. Using inexplicit GET method in test mode (mock)

[Serving] GET with router & inexplicit GET in test mode  

---

.github/workflows/system-tests-enterprise.yml
automation/system_test/prepare.py
tests/system/conftest.py
tests/system/env-template.yml

Added the option to send slack notification using webhook for failing system tests

[CI] Send slack notifications for failing system tests

---

mlrun/serving/routers.py
mlrun/serving/server.py
tests/serving/test_serving.py

(cherry picked from pr #2783 )

[Serving] GET with router & inexplicit GET in test mode [1.2.x]

---

CONTRIBUTING.md

It nows explains how to use `mlrun-ce` in order to run system tests easily. Thanks to @quaark for crafting this piece. I'm just pasting it

[Docs] Update contributing

---

docs/data-prep/ingest-data-fs.md
mlrun/datastore/base.py
mlrun/datastore/targets.py
mlrun/datastore/v3io.py
mlrun/feature_store/api.py
mlrun/feature_store/feature_vector.py
mlrun/feature_store/steps.py
mlrun/model_monitoring/helpers.py
tests/api/api/feature_store/test_feature_sets.py
tests/api/api/feature_store/test_feature_vectors.py
tests/feature-store/test_infer.py
tests/feature-store/test_ingest.py
tests/feature-store/test_steps.py
tests/integration/azure_blob/test_dask_dataitem_to_azure_blob.py
tests/integration/sdk_api/feature_store/test_feature_store.py
tests/system/feature_store/test_feature_store.py
tests/system/feature_store/test_google_big_query.py
tests/system/feature_store/test_spark_engine.py
tests/test_datastores.py

to `fstore` and `file_system` (didn't find any cases in the code base where `fs` is used to mean feature set).

[Development] Disambiguate `fs`

---

requirements.txt
tests/system/feature_store/test_feature_store.py
tests/system/feature_store/test_spark_engine.py
tests/test_requirements.py

[ML-1167](https://jira.iguazeng.com/browse/ML-1167)

[Feature Store] Bump storey to 1.3.2, with regression test

---

mlrun/projects/project.py

(cherry picked from commit aba8bcc865b5d1a680eb8c3a667aaa84095aeae7)

[Project] Fix `load_project` log message (#2825) [1.2.x]

---

mlrun/api/api/endpoints/frontend_spec.py
mlrun/api/crud/client_spec.py
mlrun/api/schemas/client_spec.py
mlrun/api/schemas/frontend_spec.py
mlrun/config.py
mlrun/db/httpdb.py
tests/api/api/test_client_spec.py
tests/api/api/test_frontend_spec.py

Backport https://github.com/mlrun/mlrun/pull/2800

[API] Add Fields to Client Spec for Use in UI [1.2.x]

---

pyproject.toml

(cherry picked from commit 4976ae4e950be14de5a5cc9fbcaa0a6db3b5a3ac)

[Makefile] Isort ignore venvs [1.2.x]

---

mlrun/db/httpdb.py
mlrun/feature_store/api.py
mlrun/mlutils/data.py
mlrun/model_monitoring/helpers.py
mlrun/run.py
mlrun/runtimes/sparkjob/abstract.py
tests/system/demos/horovod/assets/utils_functions.py

[Docs] Update docstrings

---

mlrun/feature_store/api.py
tests/system/feature_store/test_feature_store.py

As discussed with @assaf758 and @theSaarco.
[ML-3099](https://jira.iguazeng.com/browse/ML-3099)

[Feature Store] Fix and deprecate `preview`'s `timestamp_key` parameter

---

mlrun/api/api/utils.py
mlrun/execution.py
mlrun/runtimes/base.py
mlrun/runtimes/generators.py
tests/api/api/test_submit.py

Back-porting #2823
(cherry picked from commit c12346de332e9d37045fe35ab0f5ea3c2900a078)

[Runtimes] Fix submitting job with hyper-params config param to use correct credentials [1.2.x]

---

mlrun/__main__.py
mlrun/projects/pipelines.py
mlrun/projects/project.py
tests/system/projects/test_project.py

Contains the changes that were inserted into `1.1.3`.
Followed by #2651 and the fix that was added by #2818.
Also reverts #2711 which was reverted only on `1.1.x` and `1.2.x`.
Will be back-ported to `1.2.x` as well.

[CLI][Projects] Add overwrite scheduled workflow

---

mlrun/api/api/utils.py
mlrun/k8s_utils.py
mlrun/projects/project.py
tests/projects/test_project.py

(cherry picked from commit 3217e30e16894680d0ec8276a453f8421b20fcd1)

[Project] Mask credentials when `project.set_function` [1.2.x]

---

mlrun/feature_store/api.py
requirements.txt
tests/system/feature_store/test_feature_store.py
tests/test_requirements.py

and related test (`test_schedule_on_filtered_by_time`).

[Feature Store] Fix time filtering in scheduled jobs

---

mlrun/api/api/endpoints/frontend_spec.py
mlrun/api/crud/client_spec.py
mlrun/api/schemas/client_spec.py
mlrun/api/schemas/frontend_spec.py
mlrun/db/httpdb.py
tests/api/api/test_client_spec.py
tests/api/api/test_frontend_spec.py

For - https://jira.iguazeng.com/browse/CEML-86

[API] Include the whole CE section in frontend-spec and client-spec

---

mlrun/api/api/endpoints/frontend_spec.py
mlrun/api/crud/client_spec.py
mlrun/api/schemas/client_spec.py
mlrun/api/schemas/frontend_spec.py
mlrun/db/httpdb.py
tests/api/api/test_client_spec.py
tests/api/api/test_frontend_spec.py

BP - https://github.com/mlrun/mlrun/pull/2834

[API] Include the whole CE section in frontend-spec and client-spec [1.2.x]

---

mlrun/db/__init__.py

(cherry picked from commit 20d68e3ecd6923fa1db9ad852283770bb637bec5)

[FileDB] Add warning message when initializing FileRunDB [1.2.x]

---

tests/system/api/test_secrets.py

Leftover from - https://github.com/mlrun/mlrun/pull/2855

[CI] Remove Failing Test

---

mlrun/serving/routers.py

https://jira.iguazeng.com/browse/ML-3151

[Serving] Revert to db.create_or_patch_model_endpoint [1.2.x]

---

mlrun/datastore/sources.py
mlrun/feature_store/api.py
mlrun/feature_store/retrieval/spark_merger.py
tests/system/feature_store/test_spark_engine.py

Fixes `test_basic_remote_spark_ingest_csv`

[Spark] Parse timestamp column if needed in `CSVSource`

---

mlrun/api/db/sqldb/db.py
mlrun/api/utils/scheduler.py
tests/api/utils/test_scheduler.py

(cherry picked from commit ae8e7d7f3b86ed18e966279e6e59a965e4d8d5dc)

[Scheduler] Update next run time after skipping run

---

tests/system/conftest.py

[CI] Make system test session report concise

---

tests/system/projects/test_project.py

Follow up to https://github.com/mlrun/mlrun/pull/2849

[Project] System tests fixes

---

mlrun/feature_store/api.py

[ML-3194](https://jira.iguazeng.com/browse/ML-3194)
Fixes a regression introduced in #2845.

[Feature Store] Fix scheduled ingest

---

mlrun/api/api/utils.py
mlrun/api/crud/model_monitoring/model_endpoints.py
mlrun/api/utils/asyncio.py
mlrun/api/utils/scheduler.py
tests/api/utils/clients/test_iguazio.py

Putting a sync/blocking calls on async function isn't a good idea, wrapping in thread for now

[Scheduler] Fix submit not being true-async

---

mlrun/datastore/sources.py

[ML-3263](https://jira.iguazeng.com/browse/ML-3263)

[Datastore] Fix error in `CSVSource` on unsupported parameters

---

tests/api/utils/test_scheduler.py

[Scheduler] Fix transient test take 4

---

mlrun/datastore/redis.py
mlrun/datastore/targets.py
mlrun/datastore/utils.py
mlrun/feature_store/api.py
tests/system/feature_store/test_spark_engine.py

[ML-3008](https://jira.iguazeng.com/browse/ML-3008)

[Spark] Add redis support

---

mlrun/api/utils/auth/providers/opa.py

Requests were closed prior to clients reading the request due to a bug. This PR adds async context manager that allows using the response before it is closed and release it once out of async context.

[OPA] Fix asynchronous requests

---

go/cmd/logcollector/main.go
go/pkg/common/utils.go
go/pkg/services/logcollector/logcollector_test.go
go/pkg/services/logcollector/server.go
go/pkg/services/logcollector/statestore/file/client.go
go/pkg/services/logcollector/statestore/types.go
go/pkg/services/logcollector/test/logcollector_test.go

Fix unit and integration tests following the previous changes.

[Log Collector] Fix GO tests

---

mlrun/feature_store/feature_set.py
mlrun/serving/states.py

Add missing documentation for FeatureSet.plot

[Docs] Add documentation for FeatureSet.plot

---

mlrun/datastore/targets.py
mlrun/secrets.py

[ML-2957](https://jira.iguazeng.com/browse/ML-2957)

[Config] Use prefixed secrets as credentials

---

docs/data-prep/ingest-data-fs.md
docs/feature-store/feature-sets.md
docs/feature-store/feature-vectors.md
docs/runtimes/create-and-use-functions.ipynb

[Docs] Add: register offline data as a feature set; feature store spark using Redis; SQL source, target and driver

---

go/cmd/logcollector/main.go
go/pkg/common/k8s/k8s.go
go/pkg/common/utils.go
go/pkg/framework/server.go
go/pkg/services/logcollector/server.go
go/pkg/services/logcollector/statestore/file/client.go
mlrun/api/utils/clients/log_collector.py
mlrun/api/utils/clients/protocols/grpc.py
mlrun/config.py

Some refinements for logs, error handling and etc

[LogCollector] Code updates 

---

dockerfiles/jupyter/requirements.txt
requirements.txt

Important bug fix https://github.com/nuclio/nuclio-jupyter/pull/161

[Requirements] Bump nuclio-jupyter to 0.9.7

---

docs/install/remote.md

updated installation/remote section documentation

[Docs] Update mlrun-config command explanation

---

mlrun/runtimes/base.py
tests/system/projects/test_project.py

Also added function information for the updates log so we will know which function is in context

[Tests] Fix project system tests

---

tests/projects/test_project.py

updating repo https://github.com/mlrun/project-demo/pull/13 to have 5 method caused the tests to fail

[CI] Fix project demo git repo related tests

---

tests/system/feature_store/test_feature_store.py

Fix tests/system/feature_store/test_feature_store.py::TestFeatureStore::test_overwrite

[Tests] Fix FeatureStore test_overwrite

---

docs/change-log/index.md
mlrun/feature_store/steps.py

Typo in sample, add info about support spark also (based on source code)

[Docs] Update info about DropFeatures

---

.github/workflows/release.yaml
.github/workflows/system-tests-enterprise.yml
.github/workflows/system-tests-opensource.yml
automation/system_test/prepare.py

In addition, updated python version on ci

[CI] Update prepare.py to getch provctl from specific endpoint

---

mlrun/feature_store/retrieval/base.py
mlrun/feature_store/retrieval/dask_merger.py
mlrun/feature_store/retrieval/local_merger.py
tests/system/feature_store/test_feature_store.py

[ML-3327](https://jira.iguazeng.com/browse/ML-3327)

[Feature Store] Fix outer-join when user pass `entity_rows` to `get_offline_feature`

---

Makefile
mlrun/db/httpdb.py
mlrun/projects/project.py
mlrun/run.py
mlrun/utils/helpers.py
tests/projects/test_project.py

https://jira.iguazeng.com/browse/ML-3293

[Build] Normalize function name fixes

---

mlrun/datastore/targets.py
mlrun/feature_store/ingestion.py
tests/system/feature_store/test_feature_store.py

Fix [ML-3301 ](https://jira.iguazeng.com/browse/ML-3301)

[Datastore] Fix pandas write_dataframe de-duplication logic

---

mlrun/artifacts/base.py
mlrun/artifacts/dataset.py
mlrun/artifacts/model.py

https://jira.iguazeng.com/browse/ML-3104

[Artifacts] Remove pending deprecation warnings from spec and meta fields

---

automation/release_notes/generate.py
mlrun/api/db/base.py
mlrun/api/db/filedb/db.py
mlrun/api/db/sqldb/db.py
mlrun/db/sqldb.py
tests/api/api/test_artifacts.py
tests/api/db/test_artifacts.py
tests/integration/sdk_api/projects/test_project.py

https://jira.iguazeng.com/browse/ML-3234

[Artifacts] List artifacts with all tags if not given

---

mlrun/feature_store/retrieval/base.py
mlrun/feature_store/retrieval/job.py
tests/api/runtimes/test_spark.py

[ML-3277](https://jira.iguazeng.com/browse/ML-3277)
Also fixes a dask warning when running with `get_offline_features` with spark engine.

[Feature Store] Fix `get_offline_features` with spark operator

---

mlrun/serving/routers.py

https://jira.iguazeng.com/browse/ML-3337

[Serving] Fix default type for `EnrichmentVotingEnsemble.executor_type` to be thread

---

mlrun/feature_store/ingestion.py
mlrun/feature_store/steps.py

[ML-3223](https://jira.iguazeng.com/browse/ML-3223)

[Feature Store] raise an error when FeaturesetValidator or SetEventMetadata are in graph of spark featureset (engine=spark)

---

mlrun/runtimes/remotesparkjob.py
mlrun/runtimes/sparkjob/abstract.py

https://jira.iguazeng.com/browse/ML-3384

[Spark] Fix call to deprecated method `mount_v3io_extended`

---

mlrun/api/api/endpoints/pipelines.py
mlrun/api/api/endpoints/runtime_resources.py
mlrun/api/api/utils.py
mlrun/api/main.py
mlrun/projects/project.py
mlrun/runtimes/remotesparkjob.py
tests/api/api/test_docs.py
tests/api/api/test_pipelines.py
tests/api/api/test_runtime_resources.py
tests/api/api/test_schedules.py
tests/api/api/test_submit.py
tests/integration/sdk_api/httpdb/test_exception_handling.py

https://jira.iguazeng.com/browse/ML-3104

[API] Remove deprecated older than 0.7.0

---

mlrun/feature_store/api.py

[ML-3298](https://jira.iguazeng.com/browse/ML-3298)

[Feature Store] Fix `_ingest_with_spark` does not raise proper errors

---

mlrun/feature_store/feature_set.py
tests/system/feature_store/test_spark_engine.py

[ML-2896](https://jira.iguazeng.com/browse/ML-2896)

[Feature store] Fix sum of square and variance aggregations in spark engine

---

examples/mlrun_basics.ipynb
mlrun/__init__.py
mlrun/api/main.py
mlrun/datastore/targets.py
mlrun/db/httpdb.py
mlrun/model.py
mlrun/projects/project.py
tests/api/api/test_runs.py
tests/utils/test_vault.py

https://jira.iguazeng.com/browse/ML-3104

[MLRun] Remove deprecated methods and parameters

---

dockerfiles/models-gpu/Dockerfile

https://jira.iguazeng.com/browse/ML-1362

[Models-GPU] Install opencv dependencies

---

mlrun/projects/project.py
tests/projects/test_project.py

Fix for https://jira.iguazeng.com/browse/ML-3168

[SDK] Fix `project.set_artifact` not validating artifact exists

---

dockerfiles/models-gpu/Dockerfile
dockerfiles/models-gpu/prebaked.Dockerfile
dockerfiles/models-gpu/py37/prebaked.Dockerfile

fixes - https://github.com/mlrun/mlrun/pull/3085

[Models-GPU] Move opencv dependencies installation to prebaked images

---

mlrun/runtimes/function.py

In addition, updated documentation
https://jira.iguazeng.com/browse/ML-1848

[Nuclio] Set default workers to 8 in case `None` was given

---

mlrun/api/db/sqldb/db.py
mlrun/runtimes/function.py

internal ticket https://jira.iguazeng.com/browse/ML-3409

[Nuclio] Ensure byte string are decoded to string on old python runtimes

---

docs/cheat-sheet.md
docs/concepts/functions-overview.md
docs/feature-store/basic-demo.ipynb
docs/monitoring/index.md
docs/runtimes/dask-mlrun.ipynb
docs/runtimes/dask-pipeline.ipynb
docs/runtimes/mlrun_jobs.ipynb
docs/serving/distributed-graph.ipynb
docs/store/artifacts.md

[Docs] Remove deprecated methods and classes

---

automation/system_test/cleanup.py

Before it failed when there was a tag without digest, now it will skip and move on. this is probably due to a bug on docker api where there is a tag without digest and deleting is also possible on a specific digest.

[CI] Best effort clean stale docker images on system tests
